import { test, expect, type Page, type APIRequestContext } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { blankContent, blankRequirement } from '@/domain/tasks/types';
import type { TaskDetail } from '@/server/tasks/service';
import type { ScheduleContent, ScheduleDetail, ScheduleList } from '@/server/scheduling/contracts';
export const ctx = 'ctx-jp-a-luna';
export async function login(page: Page, email = 'admin@example.test') { await page.context().clearCookies(); await page.goto('/login'); await page.getByRole('textbox', { name: '이메일', exact: true }).fill(email); await page.getByLabel('비밀번호', { exact: true }).fill('Demo-Hale-2026!'); await page.getByRole('button', { name: '로그인', exact: true }).click(); await expect(page).toHaveURL(/\/$/); }
export async function mutation(r: APIRequestContext, url: string, data: unknown, method = 'POST') { const token = await (await r.get('/api/auth/csrf')).json(); return r.fetch(url, { method, data, headers: { Origin: `http://127.0.0.1:${process.env.E2E_PORT}`, 'X-CSRF-Token': token.csrfToken } }); }
export async function json<T>(r: APIRequestContext, url: string): Promise<T> { const response = await r.get(url); expect(response.status(), await response.text()).toBe(200); return response.json(); }
export async function setup(page: Page) { await login(page); const content = { ...blankContent(), title: '합성 일정 UI ' + randomUUID().slice(0, 5), description: '일정·알림 실제 업무 원본', internalMemo: 'G13_PRIVATE_CANARY', deadline: { ...blankContent().deadline, value: '2099-10-01', certainty: 'confirmed' as const, responsibleUserId: 'user-gsg' }, requirements: [{ ...blankRequirement('answer', 'short_text'), label: '필수 답변' }] }; const r = await mutation(page.request, '/api/tasks', { category: 'spot', content, targets: [{ contextId: ctx, ownerId: 'user-gsg', assigneeId: 'user-luna', coAssigneeIds: ['user-co'], productIds: [] }], idempotencyKey: randomUUID() }); expect(r.status(), await r.text()).toBe(201); const taskId = (await r.json()).ids[0] as string, d = await json<TaskDetail>(page.request, `/api/tasks/${taskId}?context=${ctx}`); const pub = await mutation(page.request, `/api/tasks/${taskId}`, { command: 'publish', expectedRevision: d.task.revision, idempotencyKey: randomUUID() }); expect(pub.status(), await pub.text()).toBe(200); return { taskId, content }; }
export function content(taskId: string, title = '합성 배송 확인'): ScheduleContent { return { taskId, title, kind: 'shipping', visibility: 'public', deadline: { value: '2099-10-02', precision: 'date', timezone: 'Asia/Tokyo', certainty: 'expected', source: '합성 거래처', sourceVersion: 'v1', responsibleUserId: 'user-luna', raw: '  原文 10月2日 예정  ' }, statements: [], conflicts: [] }; }
export async function schedule(page: Page, taskId: string, patch: Partial<ScheduleContent> = {}) { const r = await mutation(page.request, '/api/schedule', { command: 'save', contextId: ctx, scheduleId: null, expectedRevision: 0, content: { ...content(taskId), ...patch }, reason: '합성 최초 기록', idempotencyKey: randomUUID() }); expect(r.status(), await r.text()).toBe(200); return (await r.json()).ids[0] as string; }
export async function revise(page: Page, id: string, patch: Partial<ScheduleContent>) { const d = await json<ScheduleDetail>(page.request, `/api/schedule/${id}`), r = await mutation(page.request, '/api/schedule', { command: 'save', contextId: ctx, scheduleId: id, expectedRevision: d.revision, content: { ...d.current.content, ...patch }, reason: '다른 작성자의 기록', idempotencyKey: randomUUID() }); expect(r.status(), await r.text()).toBe(200); return json<ScheduleDetail>(page.request, `/api/schedule/${id}`); }
export async function open(page: Page, id?: string, taskId?: string) { await page.goto(`/schedule${id ? '/' + id : ''}?context=${ctx}${taskId ? '&task=' + taskId : ''}`); await expect(page.getByText('현재 권한과 일정을 확인하고 있습니다.', { exact: true })).toHaveCount(0); }
export async function saved(page: Page) { await expect(page.getByRole('status').filter({ hasText: '저장 결과를 확인했습니다.' })).toBeVisible(); }
export async function fillNew(page: Page, taskId: string, title: string) { await open(page, undefined, taskId); await page.getByRole('button', { name: '새 일정 기록', exact: true }).click(); await page.getByRole('textbox', { name: '일정 제목', exact: true }).fill(title); await page.getByRole('combobox', { name: '연결 업무', exact: true }).selectOption(taskId); await page.getByRole('combobox', { name: '일정 종류', exact: true }).selectOption('shipping'); await page.getByRole('combobox', { name: '확인·다음 행동 책임자', exact: true }).selectOption('user-luna'); }
export async function find(page: Page, title: string) { const list = await json<ScheduleList>(page.request, `/api/schedule?context=${ctx}`); const row = list.items.find(i => i.title === title)!; expect(row).toBeTruthy(); return row.source.targetId; }
export function journeys() { test.beforeEach(async ({ page }) => { await page.context().tracing.start({ screenshots: true, snapshots: true, sources: true }); }); test.afterEach(async ({ page }, info) => { await writeFile(info.outputPath('final.html'), await page.content()); await page.screenshot({ path: info.outputPath('final.png'), fullPage: true }); await page.context().tracing.stop({ path: info.outputPath('trace.zip') }); }); }
