"use client";
import {useEffect,useRef,useState} from 'react';
import {CompletionError as ReviewError,isDenied,request} from '@/features/completion/client';
import type {AiReviewDetail,AiReviewWorkspace,HumanReviewCommand} from '@/server/ai-review/contracts';
import {endpoint,pathname,purgeRecovery,readRecovery,recoveryKey,storeRecovery,type Pending,type Recovery,type Selection,type View} from './model';
export function useReview(initial:View,actorId:string,selection:Selection){
 const scope=recoveryKey(actorId,selection);
 const [state,setState]=useState({view:initial as View|null,ready:false,busy:false,denied:false,error:'',code:'',message:'',conflict:false,recovery:{actorId,scope,at:0,reviews:{},opinions:{},pending:null} as Recovery});
 const current=useRef(state),life=useRef({alive:false,halted:false,generation:0,reads:0,locked:false});
 function active(g=life.current.generation){if(!life.current.alive||life.current.halted||g!==life.current.generation)return false;const q=new URLSearchParams(window.location.search);return window.location.pathname===pathname(selection)&&(!q.has('context')||q.get('context')===selection.contextId)&&q.getAll('context').length<=1&&(q.get('versionId')??undefined)===selection.versionId&&(q.get('releaseId')??undefined)===selection.releaseId;}
 function update(p:Partial<typeof state>){const next={...current.current,...p};current.current=next;setState(next);if(next.ready&&!next.denied)storeRecovery(next.recovery);}
 function purge(){life.current.halted=true;life.current.generation++;life.current.reads++;purgeRecovery();update({view:null,ready:false,busy:false,denied:true,error:'현재 접근 권한이 없어 보호된 결과와 작성값을 지웠습니다.',code:'DENIED',message:'',conflict:false,recovery:{actorId,scope,at:Date.now(),reviews:{},opinions:{},pending:null}});}
 function failure(e:unknown){if(isDenied(e)){purge();return;}if(active())update({error:e instanceof Error?e.message:'연결을 확인해 주세요. 작성값은 유지됩니다.',code:e instanceof ReviewError?e.code:'NETWORK'});}
 async function load(){const me=await request<{user:{id:string}}>('/api/auth/me');if(me.user.id!==actorId)throw new ReviewError('로그인 계정이 변경되었습니다.',403,'ACTOR_CHANGED');const data=await request<View['data']>(endpoint(selection));if('contextId' in data&&data.contextId!==selection.contextId)throw new ReviewError('선택한 컨텍스트의 자료가 아닙니다.',404,'NOT_FOUND');return {kind:selection.kind,data} as View;}
 function accept(view:View){return {view,ready:true,recovery:current.current.ready?current.current.recovery:readRecovery(scope,actorId)??current.current.recovery};}
 async function refresh(){const g=life.current.generation,r=++life.current.reads;try{const view=await load();if(active(g)&&r===life.current.reads)update({...accept(view),message:'현재 권한과 저장본을 다시 확인했습니다. 작성값은 유지됩니다.'});}catch(e){if(active(g)&&(isDenied(e)||r===life.current.reads))failure(e);}}
 useEffect(()=>{const l=life.current;l.alive=true;l.halted=false;const g=++l.generation,r=++l.reads;void load().then(view=>{if(active(g)&&r===l.reads)update(accept(view));}).catch(e=>{if(active(g)&&(isDenied(e)||r===l.reads))failure(e);});const focus=()=>{if(active())void refresh();};const logout=(e:MouseEvent)=>{if(e.target instanceof Element&&e.target.closest('button')?.textContent?.trim()==='로그아웃')purge();};window.addEventListener('focus',focus);document.addEventListener('click',logout,true);const timer=setInterval(focus,20000);return()=>{l.alive=false;l.generation++;l.reads++;clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('click',logout,true);};
 // Actor/context/selection are immutable for the keyed surface. Read tickets also guard initial reads.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 function editReview(command:HumanReviewCommand){if(active()&&current.current.ready&&!current.current.recovery.pending)update({recovery:{...current.current.recovery,reviews:{...current.current.recovery.reviews,[command.findingId]:command}}});}
 function editOpinion(id:string,value:{targetIndex:number;text:string}){if(active()&&current.current.ready&&!current.current.recovery.pending)update({recovery:{...current.current.recovery,opinions:{...current.current.recovery.opinions,[id]:value}}});}
 async function execute(proposed?:Pending){if(!active()||!current.current.ready||life.current.locked)return;life.current.locked=true;const g=life.current.generation;++life.current.reads;update({busy:true,error:'',code:'',message:''});try{let pending=current.current.recovery.pending;if(!pending){if(!proposed)return;pending=proposed;update({recovery:{...current.current.recovery,pending}});}if(!pending.receipt){const response=await request<{runId?:string;actionId?:string;ids?:string[]}>(pending.url,pending.body,()=>active(g));if(!active(g))return;const receipt=response.runId??response.actionId??response.ids?.[0];if(!receipt)throw Error('저장 응답을 확인하지 못했습니다. 같은 요청으로 다시 확인해 주세요.');pending={...pending,receipt};update({recovery:{...current.current.recovery,pending}});}const r=++life.current.reads,view=await load();if(!active(g)||r!==life.current.reads)return;const reviews={...current.current.recovery.reviews};if(pending.kind==='review')delete reviews[pending.body.findingId];const keepQueued=pending.kind==='start'&&view.kind==='input'&&view.data.runs.find(v=>v.id===pending.receipt)?.state==='queued';update({view,ready:true,conflict:false,recovery:{...current.current.recovery,reviews,pending:keepQueued?{...pending,receipt:null}:null},message:pending.kind==='start'?(keepQueued?'분석이 대기 중입니다. 같은 요청으로 대기 분석을 이어갈 수 있습니다.':'분석 실행 기록을 확인했습니다.'):pending.kind==='review'?'사람 검토 기록을 저장했습니다. 원문과 공개 상태는 변경하지 않았습니다.':pending.kind==='settings'?'외부 AI 설정을 저장했습니다.':pending.kind==='retry'?'같은 실행의 명시적 재시도 기록을 확인했습니다.':'내부 의견을 저장했습니다. 브랜드 공개는 수정 취합 화면에서 별도로 진행합니다.'});}catch(e){if(active(g)){if(e instanceof ReviewError&&[409,422].includes(e.status))update({recovery:{...current.current.recovery,pending:null},conflict:e.status===409});failure(e);}}finally{life.current.locked=false;if(active(g))update({busy:false});}}
 function start(w:AiReviewWorkspace,extractionRunId:string,engine:'synthetic_demo'|'provider'='synthetic_demo'){void execute({kind:'start',url:`/api/ai-review/inputs/${w.inputId}/start`,body:{inputVersionId:w.inputVersionId,extractionRunId,expectedRunId:w.runs[0]?.id??null,corpusReleaseId:w.corpus.id,corpusManifestHash:w.corpus.manifestHash,engine,idempotencyKey:crypto.randomUUID()},receipt:null});}
 function review(d:AiReviewDetail,command:HumanReviewCommand){void execute({kind:'review',url:`/api/ai-review/runs/${d.id}/review`,body:{...command,idempotencyKey:crypto.randomUUID()},receipt:null});}
 function settings(w:AiReviewWorkspace,enabled:boolean){void execute({kind:'settings',url:'/api/ai-review/settings',body:{contextId:w.contextId,enabled,expectedRevision:w.providerSettings.revision,idempotencyKey:crypto.randomUUID()},receipt:null});}
 function retry(d:AiReviewDetail,acknowledgeUnknown=false,restartConfiguration=false){void execute({kind:'retry',url:`/api/ai-review/runs/${d.id}/retry`,body:{expectedRevision:d.revision,acknowledgeUnknown,restartConfiguration,idempotencyKey:crypto.randomUUID()},receipt:null});}
 return {settings,retry,state,refresh,editReview,editOpinion,execute,start,review,active,purge,locked:state.busy||!state.ready||state.denied||!!state.recovery.pending};
}
export type ReviewController=ReturnType<typeof useReview>;
