import type { Clock, UnitOfWork } from '@/domain/records';
import { attemptData, outcomeData, planData, settingData } from '@/domain/ai-provider/parse';
import { PROVIDER_LIMITS } from '@/domain/ai-provider/types';
import { corrupt, safely } from '@/server/ai-review/stored';
import { providerConfig } from './config';
import { issueMessages, transient } from './errors';
export function providerSetting(s:UnitOfWork,contextId:string) {const row=s.list('aiProviderSetting',contextId)[0];return {revision:row?.revision??0,enabled:row?safely(()=>settingData(row.data)).enabled:true};}
export function settingsView(s:UnitOfWork,contextId:string) {const setting=providerSetting(s,contextId),c=providerConfig(),issue=!setting.enabled?'DISABLED':c.issue;return {contextId,...setting,configured:!c.issue,model:c.config?.model??null,baseURL:c.config?.baseURL??null,keyPresent:!!c.config?.apiKey,issue,message:issue?issueMessages[issue]:null,limits:PROVIDER_LIMITS,priceCap:null,externalTransmission:'registered_exact_hash_only' as const};}
export function providerHistory(s:UnitOfWork,runId:string,clock:Clock) {
 const row=s.get('aiProviderPlan',runId);if(!row)return null;const plan=safely(()=>planData(row.data));const run=s.get('aiAnalysisRun',runId);if(!run||run.contextId!==row.contextId||run.data.modelId!==plan.model||run.data.promptVersion!==plan.promptVersion||run.data.engine!=='provider')corrupt();
 const attempts=s.list('aiProviderAttempt',row.contextId!).filter(a=>a.data.runId===runId).map(a=>{const d=safely(()=>attemptData(a.data));const outcome=d.outcomeId?s.get('aiProviderOutcome',d.outcomeId):null;const o=outcome?safely(()=>outcomeData(outcome.data,plan.model)):null;const interrupted=!o&&d.leaseUntil<=clock();return {id:a.id,sequence:d.sequence,intentAt:d.intentAt,dispatchedAt:d.dispatchedAt,phase:interrupted?'interrupted' as const:d.phase,requestHash:d.requestHash,inputBytes:d.inputBytes,approximateInputTokens:d.approximateInputTokens,tokenEstimateMethod:'UTF8 byte upper estimate; not model tokenizer',issue:o?.issue??(interrupted?'RESPONSE_UNKNOWN':null),message:o?.issue?issueMessages[o.issue]:interrupted?issueMessages.RESPONSE_UNKNOWN:null,responseId:o?.responseId??null,requestId:o?.requestId??null,responseModel:o?.responseModel??null,serviceTier:o?.serviceTier??null,providerStatus:o?.providerStatus??null,responseHash:o?.responseHash??null,endedAt:o?.endedAt??null,usage:o?.usage??null,cost:o?.cost??null,remoteOutcomeUnknown:o?.remoteOutcomeUnknown??interrupted,schemaValid:o?.schemaValid??false,grounding:o?.grounding??'not_judged',requiresUnknownAcknowledgment:interrupted||!!o?.remoteOutcomeUnknown,retryable:(interrupted||!!o&&transient(o.issue))&&d.sequence<PROVIDER_LIMITS.attempts};}).sort((a,b)=>a.sequence-b.sequence);
 return {model:plan.model,promptVersion:plan.promptVersion,settingRevision:plan.settingRevision,pricingVersion:plan.pricingVersion,attempts,retryable:attempts.at(-1)?.retryable??false,remoteExactlyOnceGuaranteed:false as const};
}
