import type { Clock, UnitOfWork } from '@/domain/records';
import type { Principal } from '@/server/auth/service';
import { decide } from '@/server/policy/policy';
import { taskScope } from '@/server/policy/projection';
import { userLabel } from '@/server/submissions/access';
import { readProductUse } from '@/server/products/capture';
import { completionTask, mayComplete } from './access';
import { collectBasis, available } from './collect';
import { authorizedFile } from './sources';
import { snapshotDTO, externalDTO, followupDTO, reopenDTO } from './projection';
import { readCompletionSummary } from './summary';
import * as safe from './stored';
export function completionWorkspace(s: UnitOfWork, p: Principal, taskId: string, clock: Clock) {
    const task = completionTask(s, p, taskId, clock), staff = mayComplete(s, p, task, clock), contextId = task.contextId!;
    const snapshots = s.list('completionSnapshot', contextId).filter(x => x.data.taskId === task.id).sort((a, b) => safe.count(b.data.sequence, 1) - safe.count(a.data.sequence, 1));
    const history = snapshots.map(x => snapshotDTO(s, p, x, clock));
    const externalActions = s.list('completionExternalAction', contextId).filter(x => x.data.taskId === task.id && (staff || x.data.visibility === 'public')).flatMap(x => { const projected = available(() => externalDTO(s, p, x, clock)); return projected.state === 'available' ? [projected.value] : []; }).sort((a, b) => b.sequence - a.sequence);
    const sourceOptions = staff ? s.list('requestVersion', contextId).filter(r => r.data.taskId === task.id).sort((a, b) => b.data.sequence - a.data.sequence).map(r => ({ requestId: r.id, sequence: safe.count(r.data.sequence, 1), isCurrent: r.id === task.data.currentRequestId, files: r.data.content.referenceFileIds.flatMap(id => { const v = available(() => authorizedFile(s, p, task, id, clock, true)); return v.state === 'available' ? [v.value] : []; }), submissions: s.list('submission', contextId).filter(v => v.data.taskId === task.id && v.data.requestId === r.id).map(v => ({ id: v.id, sequence: safe.count(v.data.sequence, 1), contentHash: safe.hash(v.data.contentHash), submittedAt: safe.time(v.data.submittedAt), files: v.data.fileVersionIds.flatMap(id => { const x = available(() => authorizedFile(s, p, task, id, clock, true)); return x.state === 'available' ? [x.value] : []; }), products: v.data.productUseIds.flatMap(id => { const x = available(() => readProductUse(s, p, id, clock)); return x.state === 'available' ? [x.value] : []; }) })) })) : null;
    return { taskId: task.id, contextId, taskTitle: safe.text(task.data.title, 200), taskStatus: safe.taskStatus(task.data.status), taskRevision: safe.count(task.revision, 1), summary: readCompletionSummary(s, p, task.id, clock), capabilities: { complete: staff && task.data.status !== 'completed', reopen: staff && task.data.status === 'completed' && history.length > 0, recordExternal: staff, linkFollowup: staff && history.length > 0 }, preview: staff ? collectBasis(s, p, task, clock) : null, history, externalActions, reopenHistory: s.list('completionReopen', contextId).filter(r => r.data.taskId === task.id).map(r => reopenDTO(s, p, r, clock)), followups: s.list('completionFollowup', contextId).filter(r => r.data.taskId === task.id).flatMap(r => { const v = followupDTO(s, p, r, clock); return v ? [v] : []; }), sourceOptions, actors: staff ? s.list('user').filter(u => u.data.status === 'active' && s.list('membership', contextId).some(m => m.data.userId === u.id && m.data.status === 'active')).map(u => ({ id: u.id, label: safe.text(userLabel(s, p, contextId, u.id), 200) })) : null, evidenceOptions: staff ? s.list('fileVersion', contextId).flatMap(f => { const v = available(() => authorizedFile(s, p, task, f.id, clock)); return v.state === 'available' ? [v.value] : []; }) : null, followupOptions: staff ? s.list('task', contextId).filter(t => t.id !== task.id && decide(s, p, 'task.manage', taskScope(t), clock).allowed).map(t => ({ id: t.id, title: safe.text(t.data.title, 200), revision: safe.count(t.revision, 1), status: safe.taskStatus(t.data.status) })) : null, connections: { inquiries: true, corrections: true, submission: true, productUse: true, campaign: true, ai: false, notificationDelivery: false } };
}
