import { asyncFilter, asyncFlatMap, asyncMap } from "@/domain/async-collections";
import type { Clock, UnitOfWork } from '@/domain/records';
import type { Principal } from '@/server/auth/service';
import { decide } from '@/server/policy/policy';
import { taskScope } from '@/server/policy/projection';
import { userLabel } from '@/server/submissions/access';
import { readProductUse } from '@/server/products/capture';
import { completionTask, mayComplete } from './access';
import { collectBasis, available } from './collect';
import { authorizedFile } from './sources';
import { snapshotDTO, externalDTO, followupDTO, reopenDTO } from './projection';
import { readCompletionSummary } from './summary';
import * as safe from './stored';
export async function completionWorkspace(s: UnitOfWork, p: Principal, taskId: string, clock: Clock) {
    const task = (await completionTask(s, p, taskId, clock)), staff = (await mayComplete(s, p, task, clock)), contextId = task.contextId!;
    const snapshots = (await s.list('completionSnapshot', contextId)).filter(x => x.data.taskId === task.id).sort((a, b) => safe.count(b.data.sequence, 1) - safe.count(a.data.sequence, 1));
    const history = (await asyncMap(snapshots, async (x) => (await snapshotDTO(s, p, x, clock))));
    const externalActions = (await asyncFlatMap((await s.list('completionExternalAction', contextId)).filter(x => x.data.taskId === task.id && (staff || x.data.visibility === 'public')), async (x) => { const projected = (await available(async () => (await externalDTO(s, p, x, clock)))); return projected.state === 'available' ? [projected.value] : []; })).sort((a, b) => b.sequence - a.sequence);
    const sourceOptions = staff ? (await asyncMap((await s.list('requestVersion', contextId)).filter(r => r.data.taskId === task.id).sort((a, b) => b.data.sequence - a.data.sequence), async (r) => ({ requestId: r.id, sequence: safe.count(r.data.sequence, 1), isCurrent: r.id === task.data.currentRequestId, files: (await asyncFlatMap(r.data.content.referenceFileIds, async (id) => { const v = (await available(async () => (await authorizedFile(s, p, task, id, clock, true)))); return v.state === 'available' ? [v.value] : []; })), submissions: (await asyncMap((await s.list('submission', contextId)).filter(v => v.data.taskId === task.id && v.data.requestId === r.id), async (v) => ({ id: v.id, sequence: safe.count(v.data.sequence, 1), contentHash: safe.hash(v.data.contentHash), submittedAt: safe.time(v.data.submittedAt), files: (await asyncFlatMap(v.data.fileVersionIds, async (id) => { const x = (await available(async () => (await authorizedFile(s, p, task, id, clock, true)))); return x.state === 'available' ? [x.value] : []; })), products: (await asyncFlatMap(v.data.productUseIds, async (id) => { const x = (await available(async () => (await readProductUse(s, p, id, clock)))); return x.state === 'available' ? [x.value] : []; })) }))) }))) : null;
    return { taskId: task.id, contextId, taskTitle: safe.text(task.data.title, 200), taskStatus: safe.taskStatus(task.data.status), taskRevision: safe.count(task.revision, 1), summary: (await readCompletionSummary(s, p, task.id, clock)), capabilities: { complete: staff && task.data.status !== 'completed', reopen: staff && task.data.status === 'completed' && history.length > 0, recordExternal: staff, linkFollowup: staff && history.length > 0 }, preview: staff ? (await collectBasis(s, p, task, clock)) : null, history, externalActions, reopenHistory: (await asyncMap((await s.list('completionReopen', contextId)).filter(r => r.data.taskId === task.id), async (r) => (await reopenDTO(s, p, r, clock)))), followups: (await asyncFlatMap((await s.list('completionFollowup', contextId)).filter(r => r.data.taskId === task.id), async (r) => { const v = (await followupDTO(s, p, r, clock)); return v ? [v] : []; })), sourceOptions, actors: staff ? (await asyncMap((await asyncFilter((await s.list('user')), async (u) => u.data.status === 'active' && (await s.list('membership', contextId)).some(m => m.data.userId === u.id && m.data.status === 'active'))), async (u) => ({ id: u.id, label: safe.text((await userLabel(s, p, contextId, u.id)), 200) }))) : null, evidenceOptions: staff ? (await asyncFlatMap((await s.list('fileVersion', contextId)), async (f) => { const v = (await available(async () => (await authorizedFile(s, p, task, f.id, clock)))); return v.state === 'available' ? [v.value] : []; })) : null, followupOptions: staff ? (await asyncFilter((await s.list('task', contextId)), async (t) => t.id !== task.id && (await decide(s, p, 'task.manage', taskScope(t), clock)).allowed)).map(t => ({ id: t.id, title: safe.text(t.data.title, 200), revision: safe.count(t.revision, 1), status: safe.taskStatus(t.data.status) })) : null, connections: { inquiries: true, corrections: true, submission: true, productUse: true, campaign: true, ai: true, notificationDelivery: true } };
}
