import { jsonContentEqual } from '@/domain/json-content';
import { object, id, integer, text, oneOf, hash, invalid } from '@/domain/ai-review/validate';
import { estimateCost } from './usage';
import { PROVIDER_ISSUES, type ProviderRecords, type Usage } from './types';
const nullable = <T>(v: unknown, read: (v: unknown) => T) => v === null ? null : read(v);
const bool = (v: unknown) => typeof v === 'boolean' ? v : invalid();
const date = (v: unknown) => { const d = text(v, 40); if (!Number.isFinite(Date.parse(d))) invalid(); return d; };
export function settingData(raw: unknown): ProviderRecords['aiProviderSetting'] { const v=object(raw);return { enabled:bool(v.enabled),changedBy:id(v.changedBy) }; }
export function planData(raw: unknown): ProviderRecords['aiProviderPlan'] { const v=object(raw);const baseURL=text(v.baseURL,100);if(baseURL!=='https://api.openai.com/v1'&&baseURL!=='https://api.openai.com/v1/')invalid();return {runId:id(v.runId),settingRevision:integer(v.settingRevision,0),model:text(v.model,160),baseURL,promptVersion:text(v.promptVersion,160),settingsEnabled:bool(v.settingsEnabled),maxOutputTokens:integer(v.maxOutputTokens,1),timeoutMs:integer(v.timeoutMs,1),pricingVersion:text(v.pricingVersion,160)}; }
export function attemptData(raw: unknown): ProviderRecords['aiProviderAttempt'] { const v=object(raw);return {runId:id(v.runId),sequence:integer(v.sequence,1),actorId:id(v.actorId),claimId:id(v.claimId),phase:oneOf(v.phase,['intent','dispatched','settled']),intentAt:date(v.intentAt),dispatchedAt:nullable(v.dispatchedAt,date),leaseUntil:date(v.leaseUntil),requestHash:nullable(v.requestHash,hash),inputBytes:nullable(v.inputBytes,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),approximateInputTokens:nullable(v.approximateInputTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),outcomeId:nullable(v.outcomeId,id)}; }
export function usageData(raw:unknown):Usage {const v=object(raw);return {inputTokens:nullable(v.inputTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),cachedTokens:nullable(v.cachedTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),cacheWriteTokens:nullable(v.cacheWriteTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),outputTokens:nullable(v.outputTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),reasoningTokens:nullable(v.reasoningTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER)),totalTokens:nullable(v.totalTokens,n=>integer(n,0,Number.MAX_SAFE_INTEGER))};}
export function outcomeData(raw:unknown,requestedModel:string):ProviderRecords['aiProviderOutcome'] {const v=object(raw),usage=usageData(v.usage),responseModel=nullable(v.responseModel,n=>text(n,160)),serviceTier=nullable(v.serviceTier,n=>text(n,40));const cost=estimateCost(usage,requestedModel,responseModel,serviceTier);if(!jsonContentEqual(v.cost, cost))invalid();return {attemptId:id(v.attemptId),runId:id(v.runId),endedAt:date(v.endedAt),issue:nullable(v.issue,n=>oneOf(n,PROVIDER_ISSUES)),responseId:nullable(v.responseId,id),requestId:nullable(v.requestId,id),responseModel,serviceTier,providerStatus:nullable(v.providerStatus,n=>text(n,40)),responseHash:nullable(v.responseHash,hash),rawCandidate:nullable(v.rawCandidate,n=>text(n,262144)),usage,cost,remoteOutcomeUnknown:bool(v.remoteOutcomeUnknown),schemaValid:bool(v.schemaValid),grounding:oneOf(v.grounding,['confirmed','insufficient','not_judged'])};}
