import Link from 'next/link';
import type {Available,CompletionBasis,EvaluationFact} from '@/domain/completion/types';
import {statusLabels,purposeLabels,taskHref} from './model';
import s from './ui.module.css';
function Evaluation({title,value}:{title:string;value:Available<EvaluationFact>}){return <article className={s.sub}><h3>{title}</h3>{value.state==='unavailable'?<p>자료를 확인할 수 없습니다. 0건이나 검토 완료로 처리하지 않습니다.</p>:<><p>필수 {value.value.required} · 충족 {value.value.satisfied} · 누락 {value.value.missing} · 형식 확인 {value.value.invalid}</p>{value.value.humanReviewPending&&<p className={s.notice}>사람의 규격 확인이 남아 있습니다.</p>}</>}</article>;}
export function BasisView({basis:b,taskId,contextId,historical=false}:{basis:CompletionBasis & {submittedSourceState?:string};taskId:string;contextId:string;historical?:boolean}){
 const base=taskHref(taskId,contextId);
 return <div className={s.stack}>
 <section className={s.sub}><h3>{historical?'완료 당시 요청·제출 기준':'현재 요청과 최근 제출의 기준'}</h3><p>{b.currentRequestUnavailable?'현재 요청을 확인할 수 없습니다.':b.currentRequest?`요청 v${b.currentRequest.sequence}`:'공개 요청 없음'}</p>{b.submittedSourceState==='unavailable'?<p>당시 제출 자료에 현재 접근할 수 없습니다. 다른 제출로 대체하지 않습니다.</p>:b.latestSubmission?<><p>제출 v{b.latestSubmission.sequence} · {b.latestSubmission.mode==='full'?'전체 제출':'부분 제출'} · {b.latestSubmission.submittedAt}</p>{b.latestMatchesCurrentRequest===false&&<p className={s.notice}>이 제출은 현재 요청과 다른 요청 버전의 자료입니다.</p>}<Link href={base}>업무의 제출 이력 확인 ↗</Link><p>당시 상품 사용본 {b.latestSubmission.products.state==='available'?`${b.latestSubmission.products.value.length}건`:'확인 불가'}</p><details><summary>정확한 제출 기준</summary><p>{b.latestSubmission.contentHash}</p>{b.latestSubmission.products.state==='available'&&b.latestSubmission.products.value.map(p=><p key={p.id}>상품 사용본 {p.id} · 상품 버전 {p.productVersionId} · 컨텍스트 버전 {p.contextProductVersionId}</p>)}</details></>:<p>실제 제출 없음</p>}<p>{b.currentProducts.state==='available'?`현재 상품 기준 ${b.currentProducts.value.length}건 · 제출 당시 사용본과 별도`:'현재 상품 기준을 확인할 수 없습니다.'}</p></section>
 <div className={s.grid}><Evaluation title={historical?'완료 당시 요청에 대한 평가':'현재 요청에 대한 평가'} value={b.currentEvaluation}/><Evaluation title="제출 원래 요청의 평가" value={b.originalSubmittedEvaluation}/></div>
 <section className={s.sub}><h3>문의·외부 확인</h3>{b.inquiries.state==='unavailable'?<p>문의 자료 확인 불가</p>:<><p>미해결 {b.inquiries.value.unresolved} · 외부 대기 {b.inquiries.value.externalWaiting}</p>{b.inquiries.value.items.length?<ul>{b.inquiries.value.items.map(i=><li key={i.questionId}><Link href={`/inquiries/${i.conversationId}?context=${contextId}`}>{i.text||'첨부 질문'} ↗</Link> · {statusLabels[i.state]??i.state}{i.externalWait&&<p>외부 확인 담당 {i.externalWait.responsibleLabel}</p>}</li>)}</ul>:<p>접근 가능한 문의 없음</p>}</>}</section>
 <section className={s.sub}><h3>수정 취합·검토</h3>{b.corrections.state==='unavailable'?<p>수정 자료 확인 불가</p>:<><p>미해결 {b.corrections.value.unresolved}</p><p>반영 기록은 해결 판정과 별개입니다.</p>{b.corrections.value.items.map((x,i)=><p key={x.batchVersionId+x.itemKey}>항목 {i+1} · {statusLabels[x.status]??x.status}</p>)}{b.corrections.value.pendingScopes.map((x,i)=><p key={x.batchVersionId+i}>{x.agency} · {x.scope} · {x.expectedOn??'회신 예정일 미정'}</p>)}</>}<Link href={`/tasks/${taskId}/corrections?context=${contextId}`}>수정·검토 원문 확인 ↗</Link></section>
 <section className={s.sub}><h3>PR·행사와 실물</h3>{b.campaign.state==='not_connected'?<p>이 기록 시점에는 행사 상태가 연결되지 않았습니다.</p>:b.campaign.state==='unavailable'?<p>행사 원본을 확인할 수 없습니다. 미확인을 0건으로 바꾸지 않습니다.</p>:<>{b.campaign.value.requestSource?.noMaterials&&<p className={s.notice}>이 요청 버전의 자동 제출 대상 항목 없음</p>}{!b.campaign.value.campaigns.length&&<p>연결 가능한 행사 없음</p>}{b.campaign.value.campaigns.map(c=><article className={s.sub} key={c.campaignVersionId}>{c.menus.map(m=><section key={m.menu.catalogVersionId+m.menu.menuKey}><h4>{m.menu.menuNumber} · {m.menu.menuName}</h4><p>{m.active?'현재 선택된 자료 대상':'현재 자동 제출 대상 아님'}{m.retainedForCancellationReview?' · 취소 협의 보류 범위':''}</p><p>현재 필수 누락 {m.missingRequired} · 후속 자료 누락 {m.missingFollowup} · 수령 확인 누락 {m.missingReceiptObservation}</p><dl className={s.facts}>{Object.entries(m.state).map(([k,v])=><div key={k}><dt>{({response:'참여 회신',application:'신청',selection:'선정',preparation:'준비',execution:'진행',resultReceipt:'결과 수령',cancellation:'취소 협의'} as Record<string,string>)[k]}</dt><dd>{statusLabels[v]??v}</dd></div>)}</dl><p>자동 제출 독촉 {m.reminderEligible?'대상':'중지'}</p>{m.physical.map(p=><article key={p.physicalKey}><h5>실물 · {p.purpose}</h5><p>{p.destination} · 요청 {p.requestedQuantity??'수량 미정'} {p.unit}</p><p>발송 기록 {p.dispatchFacts} · 수령 기록 {p.receiptFacts} · {p.receipt==='unconfirmed'?'수령 미확인':'명시 수령 기록 있음'}</p><p>기록 유무만으로 요청 수량의 이행을 판정하지 않습니다.</p></article>)}{m.followups.map(f=><p key={f.followupKey}>후속 자료 · {({publication_url:'게시 URL',execution_photo:'실행 사진',performance_report:'성과 보고',custom:'별도 자료'})[f.kind]} · {f.status==='pending'?'수령 대기':'수령 기록'}</p>)}</section>)}<Link href={`/tasks/${taskId}/campaigns?context=${contextId}&campaign=${c.campaignId}&version=${c.campaignVersionId}`}>당시 행사 버전 확인 ↗</Link></article>)}</>}</section>
 <section className={s.sub} aria-label="AI 잔여 상태"><h3>AI 검토</h3>{b.ai.state==='not_connected'?<p>이 기록 시점에는 AI 결과가 연결되지 않았습니다.</p>:b.ai.state==='unavailable'?<p>AI 자료를 확인할 수 없습니다. 비공개 또는 접근 불가 상태를 0건으로 표시하지 않습니다.</p>:<><p>실패·중단 {b.ai.value.failed}건 · 대기·실행 중 {b.ai.value.pending}건 · 사람 미검토 후보 {b.ai.value.unreviewedFindings}건</p><p>AI 실패나 미검토는 잔여 정보이며 GSG의 수동 완료를 차단하지 않습니다.</p>{!b.ai.value.items.length&&<p>이 기준에서 연결 가능한 분석 실행 없음</p>}{b.ai.value.items.map(run=><article className={s.sub} key={run.runId}><p><Link href={`/ai-review/runs/${run.runId}?context=${contextId}`}>정확한 분석 실행 확인</Link> · {({queued:'분석 대기',running:'분석 중',finished:'분석 결과 저장됨',failed:'분석 실패',interrupted:'분석 중단'})[run.state]}</p><p>사람 미검토 후보 {run.unreviewedFindings===null?'확인 불가':`${run.unreviewedFindings}건`}{run.staleCorpus?' · 과거 근거 버전':''}</p>{run.issue&&<p>실행 사유 {run.issue}</p>}</article>)}</>}</section>
 <section className={s.sub}><h3>외부 진행 기록</h3>{b.externalActions.length?b.externalActions.map(x=><p key={x.id}>{purposeLabels[x.purpose]} · {x.latestProgress||'진행 설명 없음'} · {x.waitingExternal?'외부 대기':'외부 대기 아님'} · 기록 {x.recordedAt}</p>):<p>외부 진행 기록 없음</p>}</section>
 </div>;
}
