import Link from 'next/link';
import type {ExternalActionInput} from '@/domain/completion/types';
import type {Controller} from './controller';
import {purposeLabels} from './model';
import {Field,ActorField} from './fields';
import s from './ui.module.css';
export function ExternalForm({c}:{c:Controller}){const d=c.state.data!;const fallback:ExternalActionInput={purpose:'review_request',destination:'',requester:{kind:'user',userId:''},performer:{kind:'user',userId:''},source:{requestId:'',submissionId:null,submissionContentHash:null,fileVersionIds:[],productUseIds:[]},observedAt:null,evidenceFileVersionIds:[],latestProgress:'',waitingExternal:false,visibility:'public'};const value=c.state.recovery.forms.external??fallback,set=(patch:Partial<ExternalActionInput>)=>c.edit({external:{...value,...patch}}),request=d.sourceOptions?.find(r=>r.requestId===value.source.requestId),submission=request?.submissions.find(x=>x.id===value.source.submissionId);const files=[...(submission?.files??request?.files??[]),...(submission?.products.filter(p=>value.source.productUseIds.includes(p.id)).flatMap(p=>p.files.flatMap(f=>d.evidenceOptions?.filter(x=>x.id===f.fileVersionId)??[]))??[])].filter((f,i,a)=>a.findIndex(x=>x.id===f.id)===i);
 return <form className={s.panel} onSubmit={e=>{e.preventDefault();void c.execute({command:'record_external',taskId:d.taskId,expectedTaskRevision:d.taskRevision,idempotencyKey:crypto.randomUUID(),action:value});}}><h2>외부 전달·진행 사실 기록</h2><p>확인한 사실을 저장합니다. 실제 발송·신청·승인·납품을 실행하거나 완료 처리하지 않습니다.</p><fieldset disabled={c.locked} className={s.bare}><div className={s.grid}><Field label="전달 목적"><select aria-label="전달 목적" value={value.purpose} onChange={e=>set({purpose:e.target.value as ExternalActionInput['purpose']})}>{Object.entries(purposeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="전달 대상"><input aria-label="전달 대상" required maxLength={1000} value={value.destination} onChange={e=>set({destination:e.target.value})}/></Field></div><div className={s.grid}><ActorField name="요청자" actors={d.actors??[]} value={value.requester} onChange={requester=>set({requester})}/><ActorField name="실제 수행자" actors={d.actors??[]} value={value.performer} onChange={performer=>set({performer})}/></div>
 <fieldset className={s.sub}><legend>정확한 전달 자료</legend><Field label="요청 버전"><select aria-label="요청 버전" required value={value.source.requestId} onChange={e=>set({source:{requestId:e.target.value,submissionId:null,submissionContentHash:null,fileVersionIds:[],productUseIds:[]}})}><option value="">요청 선택</option>{d.sourceOptions?.map(r=><option key={r.requestId} value={r.requestId}>요청 v{r.sequence}{r.isCurrent?' · 현재':' · 과거'}</option>)}</select></Field><Field label="제출 버전"><select aria-label="제출 버전" value={value.source.submissionId??''} onChange={e=>{const sub=request?.submissions.find(x=>x.id===e.target.value);set({source:{...value.source,submissionId:sub?.id??null,submissionContentHash:sub?.contentHash??null,fileVersionIds:[],productUseIds:[]}});}}><option value="">요청의 참고자료만</option>{request?.submissions.map(v=><option key={v.id} value={v.id}>제출 v{v.sequence} · {v.submittedAt}</option>)}</select></Field><fieldset className={s.bare}><legend>당시 상품 사용본</legend>{submission?.products.length?submission.products.map(p=><label className={s.check} key={p.id}><input type="checkbox" checked={value.source.productUseIds.includes(p.id)} onChange={e=>{const ids=e.target.checked?[...value.source.productUseIds,p.id]:value.source.productUseIds.filter(x=>x!==p.id);set({source:{...value.source,productUseIds:ids,fileVersionIds:value.source.fileVersionIds.filter(id=>submission.files.some(f=>f.id===id)||submission.products.filter(q=>ids.includes(q.id)).some(q=>q.files.some(f=>f.fileVersionId===id)))}});}}/>{p.common.name} · {p.capturedAt}에 고정</label>):<p>선택한 제출의 상품 사용본 없음</p>}</fieldset><fieldset className={s.bare}><legend>전달 파일</legend>{files.length?files.map(f=><label className={s.check} key={f.id}><input type="checkbox" checked={value.source.fileVersionIds.includes(f.id)} onChange={e=>set({source:{...value.source,fileVersionIds:e.target.checked?[...value.source.fileVersionIds,f.id]:value.source.fileVersionIds.filter(x=>x!==f.id)}})}/>{f.name}</label>):<p>선택 범위에서 전달 가능한 파일 없음</p>}</fieldset><p>과거 버전을 선택해도 최신 제출·상품으로 바꾸지 않습니다.</p></fieldset>
 <fieldset className={s.sub}><legend>관측 시각과 출처</legend><Field label="관측 시각 정밀도"><select aria-label="관측 시각 정밀도" value={value.observedAt?.precision??'none'} onChange={e=>set({observedAt:e.target.value==='none'?null:{value:'',precision:e.target.value as 'date'|'datetime',timezone:'Asia/Seoul',source:''}})}><option value="none">시각 미확인</option><option value="date">날짜만 확인</option><option value="datetime">일시·시간대 확인</option></select></Field>{value.observedAt&&<><Field label="관측 날짜 또는 일시"><input aria-label="관측 날짜 또는 일시" type={value.observedAt.precision==='date'?'date':'text'} placeholder="2026-09-22T09:00:00+09:00" required value={value.observedAt.value} onChange={e=>set({observedAt:{...value.observedAt!,value:e.target.value}})}/></Field><Field label="관측 시간대"><input aria-label="관측 시간대" required value={value.observedAt.timezone} onChange={e=>set({observedAt:{...value.observedAt!,timezone:e.target.value}})}/></Field><Field label="관측 출처"><textarea aria-label="관측 출처" maxLength={1000} value={value.observedAt.source} onChange={e=>set({observedAt:{...value.observedAt!,source:e.target.value}})}/></Field><p>일시는 UTC 오프셋을, 시간대는 Asia/Seoul 같은 지역 이름을 입력합니다.</p></>}</fieldset>
 <fieldset className={s.sub}><legend>확인 증빙 파일</legend>{d.evidenceOptions?.filter(f=>value.visibility==='internal'||f.visibility==='public').map(f=><label className={s.check} key={f.id}><input type="checkbox" checked={value.evidenceFileVersionIds.includes(f.id)} onChange={e=>set({evidenceFileVersionIds:e.target.checked?[...value.evidenceFileVersionIds,f.id]:value.evidenceFileVersionIds.filter(x=>x!==f.id)})}/>{f.name} · {f.visibility==='public'?'공개':'내부'}</label>)}<p>새 증빙은 <Link href={`/tasks/${d.taskId}?context=${d.contextId}`}>업무의 자료 업로드</Link>에서 등록한 뒤 현재 저장본을 다시 확인해 선택하세요.</p></fieldset>
 <Field label="최신 진행 설명"><textarea aria-label="최신 진행 설명" maxLength={4000} value={value.latestProgress} onChange={e=>set({latestProgress:e.target.value})}/></Field><label className={s.check}><input type="checkbox" checked={value.waitingExternal} onChange={e=>set({waitingExternal:e.target.checked})}/>외부 확인 대기</label><Field label="기록 공개 범위"><select aria-label="기록 공개 범위" value={value.visibility} onChange={e=>{const visibility=e.target.value as 'public'|'internal';set({visibility,evidenceFileVersionIds:value.evidenceFileVersionIds.filter(id=>visibility==='internal'||d.evidenceOptions?.some(f=>f.id===id&&f.visibility==='public'))});}}><option value="public">브랜드에 공개</option><option value="internal">GSG 내부</option></select></Field><button className="button" type="submit">전달·진행 기록 저장</button></fieldset></form>;
}
