import Link from 'next/link';
import {useState} from 'react';
import type {Controller} from './controller';
import {BasisView} from './basis';
import {purposeLabels,statusLabels,taskHref} from './model';
import s from './ui.module.css';
function Download({url,name,c}:{url:string;name:string;c:Controller}){const[busy,setBusy]=useState(false);return <button type="button" className="button subtle" disabled={busy||c.locked} onClick={async()=>{setBusy(true);try{const r=await fetch(url,{cache:'no-store'});if([401,403,404].includes(r.status)){c.purge();return;}if(!r.ok)throw Error('파일을 내려받지 못했습니다. 다시 시도해 주세요.');const blob=await r.blob();if(!c.active())return;const object=URL.createObjectURL(blob),a=document.createElement('a');a.href=object;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(object),1000);}catch(e){c.failure(e);}finally{setBusy(false);}}}>{name} 내려받기</button>;}
export function History({c}:{c:Controller}){const d=c.state.data!;return <div className={s.stack}><section className={s.panel}><h2>완료 당시 기록</h2><p>완료 뒤 요청·제출·외부 진행이 바뀌어도 이 기준은 바뀌지 않습니다. 현재 접근할 수 없는 원본은 확인 불가로 표시합니다.</p>{!d.history.length?<p>아직 완료 기록이 없습니다.</p>:d.history.map(h=><article className={s.sub} key={h.id}><h3>완료 v{h.sequence} · {h.completedAt}</h3><p>{h.completedByLabel} · 이전 상태 {statusLabels[h.statusBefore]}</p><p>{h.memo||'완료 메모 없음'}</p><details><summary>완료 v{h.sequence}의 잔여 상태</summary><BasisView historical basis={h.basis} taskId={d.taskId} contextId={d.contextId}/></details><details><summary>기록 정보</summary><p>완료 기록 {h.id}</p>{'basisHash' in h&&<p>기준 {h.basisHash}</p>}</details></article>)}</section><section className={s.panel}><h2>재개 이력</h2>{d.reopenHistory.length?d.reopenHistory.map(r=><article key={r.id}><h3>{r.reopenedAt} · {r.reopenedByLabel}</h3><p>{r.reason} · 재개 상태 {statusLabels[r.resumedStatus]}</p></article>):<p>재개 기록 없음</p>}</section><section className={s.panel}><h2>연결된 후속 업무</h2>{d.followups.length?d.followups.map(f=><article key={f.id}><h3><Link href={taskHref(f.taskId,d.contextId)}>{f.title} ↗</Link></h3><p>{f.reason||'연결 사유 없음'} · {f.linkedByLabel} · {f.linkedAt}</p></article>):<p>후속 업무 연결 없음</p>}</section></div>;}
export function ExternalHistory({c}:{c:Controller}){const d=c.state.data!;return <section className={s.panel}><h2>저장된 전달·진행 기록</h2>{d.externalActions.length?d.externalActions.map(a=><article className={s.sub} key={a.id}><h3>{purposeLabels[a.purpose]} · {a.destination}</h3><p>{a.visibility==='internal'?'GSG 내부':'브랜드 공개'} · 사실 기록만 저장</p><dl className={s.facts}><div><dt>요청자</dt><dd>{a.requester.label}</dd></div><div><dt>실제 수행자</dt><dd>{a.performer.label}</dd></div><div><dt>플랫폼 기록자</dt><dd>{a.recordedByLabel} · {a.recordedAt}</dd></div><div><dt>관측 시각</dt><dd>{a.observedAt?`${a.observedAt.value} · ${a.observedAt.timezone} · ${a.observedAt.source||'출처 설명 없음'}`:'미확인'}</dd></div></dl><p>요청 v{a.source.requestSequence} · {a.source.submissionSequence?`제출 v${a.source.submissionSequence}`:'요청 참고자료'}</p><p>{a.latestProgress||'진행 설명 없음'} · {a.waitingExternal?'외부 확인 대기':'외부 대기 아님'}</p><div className={s.actions}>{a.source.files.map(f=><Download key={f.id} c={c} url={f.downloadUrl} name={f.name}/>)}{a.evidenceFiles.map(f=><Download key={'e'+f.id} c={c} url={f.downloadUrl} name={f.name}/>)}</div>{a.source.products.map(p=><p key={p.id}>당시 상품 · {p.common.name} · 고정 {p.capturedAt}</p>)}<details><summary>기록 정보</summary><p>전달 기록 {a.id} · 요청 {a.source.requestId}</p>{a.source.submissionId&&<p>제출 {a.source.submissionId} · {a.source.submissionContentHash}</p>}{[...a.source.files,...a.evidenceFiles].map((f,i)=><p key={f.id+i}>{f.name} · {f.sha256}</p>)}</details><p>이 기록 자체가 실제 발송·외부 승인·수령의 실행 결과는 아닙니다.</p></article>):<p>아직 전달·진행 기록이 없습니다.</p>}</section>;}
