'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useCompletion} from './controller';
import type {CompletionWorkspace} from './model';
import {statusLabels,taskHref} from './model';
import {BasisView} from './basis';
import {ExternalForm} from './external';
import {ExternalHistory,History} from './history';
import {Followup} from './followup';
import {Field} from './fields';
import s from './ui.module.css';
export function CompletionSurface({initial,actorId}:{initial:CompletionWorkspace;actorId:string}){const c=useCompletion(initial,actorId),{state}=c,d=state.data,[tab,setTab]=useState('current');if(state.denied||!d)return <section className={s.panel} role="alert"><h1>완료·외부 진행 기록을 열 수 없습니다</h1><p>{state.error}</p><Link href="/login">로그인 확인</Link></section>;
 return <div className={s.stack}><Link className="back-link" href={taskHref(d.taskId,d.contextId)}>← 업무 상세</Link><header className={s.hero}><p className="eyebrow">GS HALE · 외부 진행과 업무 완료</p><h1>{d.taskTitle}</h1><p><span className="badge">{statusLabels[d.taskStatus]}</span> · {statusLabels[d.summary.status]}</p><p>자료와 잔여 사항을 확인하고, GSG가 업무의 완료 여부를 기록합니다. 프로젝트 전체 완료와는 별개입니다.</p></header>
 {state.error&&<section className={s.error} role="alert"><p>{state.error}</p><p>입력은 유지했습니다. 현재 기준과 비교한 뒤 다시 진행하세요.</p></section>}{state.message&&<p className={s.success} role="status">{state.message}</p>}{!state.ready&&<p role="status">현재 권한과 저장본을 확인하는 중입니다.</p>}
 {state.recovery.pending&&<section className={s.notice}><h2>{state.recovery.pending.ids?'저장은 완료됐습니다':'처리 결과 확인이 필요합니다'}</h2><p>{state.recovery.pending.ids?'완료된 기록을 보존했습니다. 다시 저장하지 않고 조회만 재시도합니다.':'같은 입력과 같은 요청 키로 결과를 확인합니다. 중복된 새 기록을 만들지 않습니다.'}</p>{state.recovery.pending.ids&&<details><summary>기록 정보</summary><p>{state.recovery.pending.ids.join(' · ')}</p></details>}<button className="button" disabled={state.busy} onClick={()=>void c.execute()}>{state.recovery.pending.ids?'저장된 결과 다시 조회':'동일 요청으로 결과 확인'}</button></section>}
 <div className={s.actions}><button className="button subtle" disabled={state.busy} onClick={()=>void c.refresh()}>현재 저장본 다시 확인</button></div><nav className={s.tabs} aria-label="완료·외부 진행 화면">{[['current','현재 잔여 상태'],['external','외부 전달·진행'],['history','완료·재개 이력'],...(d.capabilities.linkFollowup?[['followup','후속 업무']]:[])].map(([v,l])=><button type="button" key={v} className="button subtle" aria-pressed={tab===v} onClick={()=>setTab(v)}>{l}</button>)}</nav>
 {tab==='current'&&<><section className={s.panel}><h2>현재 잔여 상태</h2>{d.preview?<BasisView basis={d.preview.basis} taskId={d.taskId} contextId={d.contextId}/>:<p>브랜드는 공개된 완료 이력을 확인할 수 있습니다. 잔여 상태 검토와 완료 변경은 GSG가 진행합니다.</p>}</section>{d.capabilities.complete&&d.preview&&<form className={s.panel} onSubmit={e=>{e.preventDefault();if(state.recheck)return;void c.execute({command:'complete',taskId:d.taskId,expectedTaskRevision:d.taskRevision,expectedBasisHash:d.preview!.basisHash,memo:state.recovery.forms.memo,idempotencyKey:crypto.randomUUID()});}}><h2>GSG 수동 완료</h2><p>미해결 문의·외부 대기·취소 협의가 남아 있어도 완료할 수 있습니다. 현재 잔여 상태를 당시 기록으로 고정합니다.</p><Field label="완료 메모 (선택)"><textarea aria-label="완료 메모 (선택)" disabled={c.locked} maxLength={4000} value={state.recovery.forms.memo} onChange={e=>c.edit({memo:e.target.value})}/></Field>{state.recheck&&<div className={s.notice}><p>저장 기준이 변경됐습니다. 최신 잔여 상태를 확인한 다음 명시적으로 다시 완료하세요.</p><button className="button subtle" type="button" disabled={state.busy} onClick={()=>void c.refresh(true)}>최신 완료 기준 다시 확인</button></div>}<button className="button" disabled={c.locked||state.recheck}>현재 기준으로 업무 완료</button></form>}{d.capabilities.reopen&&<form className={s.panel} onSubmit={e=>{e.preventDefault();void c.execute({command:'reopen',taskId:d.taskId,expectedTaskRevision:d.taskRevision,completionId:d.history[0].id,reason:state.recovery.forms.reopenReason,idempotencyKey:crypto.randomUUID()});}}><h2>업무 재개</h2><p>기존 완료 시각과 당시 잔여 상태는 보존됩니다.</p><Field label="재개 사유"><textarea aria-label="재개 사유" required disabled={c.locked} maxLength={2000} value={state.recovery.forms.reopenReason} onChange={e=>c.edit({reopenReason:e.target.value})}/></Field><button className="button" disabled={c.locked}>사유를 기록하고 재개</button></form>}</>}
 {tab==='external'&&<>{d.capabilities.recordExternal&&<ExternalForm c={c}/>}<ExternalHistory c={c}/></>}{tab==='history'&&<History c={c}/>} {tab==='followup'&&d.capabilities.linkFollowup&&<Followup c={c}/>}
 </div>;
}
