import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {api,post,get,login,ctx,content,create,detail,picker,save,open,tracing,screenshot} from '../fixtures/ai-input-ui';
import {createTask,taskCommand,partial} from '../fixtures/notices';
import type {SubmissionWorkspace} from '@/server/submissions/contracts';
tracing();
test('G15-U11 A21 exact actual G05 S1 file ProductUse and G06 version remain after S2; task entry',async({page},info)=>{
 const admin=await api(),brand=await api('luna@example.test'),task=await createTask(admin,'AI 실제 제출 연결',['product-serum']);await taskCommand(admin,task,'publish');const s1=await partial(brand,task),sources=await picker(brand),first=sources.submissions.find(v=>v.id===s1.latest!.id)!;expect(first.files).toHaveLength(1);expect(first.products).toHaveLength(1);await login(page,'luna@example.test');await page.goto(`/tasks/${task}?context=${ctx}`);await page.getByRole('link',{name:'이 업무의 AI 입력 작성 ↗',exact:true}).click();await page.getByRole('textbox',{name:'입력 제목',exact:true}).fill('정확한 제출 S1');await page.getByRole('combobox',{name:'제품 분류',exact:true}).selectOption('general_cosmetic');await page.getByRole('textbox',{name:'사용처',exact:true}).fill('합성 POP');await page.getByRole('combobox',{name:'제출 버전',exact:true}).selectOption(first.id);await page.getByRole('checkbox',{name:/이 제출의 상품 사용본/}).check();const product=page.getByRole('group',{name:'독립적으로 연결할 상품 버전'});await product.getByRole('checkbox',{name:sources.products.find(p=>p.productId==='product-serum')!.name,exact:true}).check();await page.getByRole('combobox',{name:'입력 형식',exact:true}).selectOption('images');await page.getByRole('group',{name:'실제로 읽을 자료 선택'}).getByRole('checkbox',{name:/제출 v1 원본/}).check();const id=await save(page),before=await detail(brand,id);expect(before.version.content.submission!.submissionId).toBe(first.id);expect(before.version.content.submission!.productUseIds).toEqual([first.products[0].id]);expect(before.sources[0].sourceId).toBe(first.files[0].id);expect(before.version.content.products[0].productVersionId).toBe(sources.products.find(p=>p.productId==='product-serum')!.currentProductVersionId);
 let w=await get<SubmissionWorkspace>(brand,`/api/tasks/${task}/submissions`);await post(brand,`/api/tasks/${task}/submission-draft`,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,content:{...w.draft!.content,narrative:'후속 S2'},idempotencyKey:randomUUID()});w=await get<SubmissionWorkspace>(brand,`/api/tasks/${task}/submissions`);await post(brand,`/api/tasks/${task}/submissions`,{baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,expectedTaskRevision:w.taskRevision,mode:'partial',idempotencyKey:randomUUID()},201);await page.reload();await expect(page.getByRole('region',{name:'저장된 입력'})).toContainText('요청 v1 / 제출 v1');expect((await detail(brand,id)).version).toEqual(before.version);await screenshot(page,info,'exact-s1-product');await page.goto(`/ai-input/new?context=${ctx}&task=${task}&request=${first.requestId}&submission=missing`);await expect(page.locator('main').getByRole('alert')).toContainText('최신 제출로 대신 선택하지 않습니다');await expect(page.getByRole('textbox',{name:'입력 제목',exact:true})).toHaveCount(0);await admin.dispose();await brand.dispose();
});
test('G15-U12 A19/AC15-04 private inputs and read-only teammate have no hidden prices or edit capability',async({page},info)=>{
 const admin=await api(),brand=await api('luna@example.test');const internal=await create(admin,content('G15_STAFF_PRIVATE_CANARY'),'staff'),shared=await create(brand,content('브랜드 작성 공유 원문'));await login(page,'team@example.test');await open(page,shared.id);await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveCount(0);await expect(page.getByText('다른 작성자의 입력입니다. 읽기 실행과 조회만 할 수 있습니다.')).toBeVisible();await page.goto(`/ai-input/${internal.id}?context=${ctx}`);await expect(page.locator('main').getByRole('alert')).toBeVisible();expect(await page.content()).not.toContain('G15_STAFF_PRIVATE_CANARY');expect((await page.request.get(`/api/ai-input/${internal.id}`)).status()).toBe(404);const source=await picker(page.request);expect(JSON.stringify(source)).not.toMatch(/internalPrice|purchasePrice|supplyPrice/);await screenshot(page,info,'private-denied');await admin.dispose();await brand.dispose();
});
