import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {api,login,newInput,save,tracing,screenshot,suspend,synthetic} from '../fixtures/ai-input-ui';
tracing();
test('G15-U07 A22 save response loss same intent plus committed POST failed GET uses GET-only recovery',async({page},info)=>{
 await login(page,'luna@example.test');await newInput(page,'응답 유실 합성');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill(synthetic);const bodies:string[]=[],ids:string[]=[];let abortFirst=true;await page.route('**/api/ai-input',async route=>{if(route.request().method()!=='POST')return route.continue();bodies.push(route.request().postData()!);const response=await route.fetch();ids.push((await response.json()).id);if(abortFirst){abortFirst=false;return route.abort('failed');}await route.fulfill({response});});await page.getByRole('button',{name:'입력 저장',exact:true}).click();await expect(page.getByRole('button',{name:'같은 저장 요청 다시 확인'})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'같은 저장 요청 다시 확인'})).toBeVisible();await page.getByRole('button',{name:'같은 저장 요청 다시 확인'}).click();await expect(page.getByRole('heading',{name:'저장된 입력 v1',exact:true})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);expect(ids[0]).toBe(ids[1]);await page.unroute('**/api/ai-input');
 await newInput(page,'저장 후 조회 실패');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('두 번째 합성');let posts=0,failed=false;await page.route('**/api/ai-input**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/api/ai-input'&&route.request().method()==='POST'){posts++;return route.continue();}if(posts===1&&!failed&&/^\/api\/ai-input\/[^/]+$/.test(url.pathname)&&!url.pathname.endsWith('/sources')&&route.request().method()==='GET'){failed=true;return route.fulfill({status:503,json:{error:{code:'STORAGE_UNAVAILABLE',message:'합성 조회 장애'}}});}await route.continue();});await page.getByRole('button',{name:'입력 저장',exact:true}).click();await expect(page.getByRole('button',{name:'저장 결과 다시 읽기'})).toBeVisible();await expect(page.getByRole('button',{name:'입력 저장',exact:true})).toBeDisabled();await page.getByRole('button',{name:'저장 결과 다시 읽기'}).click();await expect(page.getByRole('heading',{name:'저장된 입력 v1',exact:true})).toBeVisible();expect(posts).toBe(1);await screenshot(page,info,'confirmed-get-only');
});
test('G15-U08 A19/AC15-04 actual uploaded asset late response after revocation cannot restore UI or recovery',async({page},info)=>{
 await login(page,'luna@example.test');const admin=await api();await newInput(page,'늦은 업로드 보호','images');
 await page.evaluate(()=>{const original=window.fetch.bind(window),w=window as unknown as {heldUpload?:{status:number;id:string};releaseUpload?:()=>void;uploadDelivered?:boolean;lateLeaks?:string[]};window.fetch=async(input,init)=>{const response=await original(input,init);const url=input instanceof Request?input.url:String(input);if(url.includes('/api/ai-input/assets?')&&init?.method==='POST'){const body=await response.clone().json();w.heldUpload={status:response.status,id:body.id};await new Promise<void>(resolve=>{w.releaseUpload=resolve;});w.uploadDelivered=true;}return response;};});
 await page.getByLabel('새 원본 파일',{exact:true}).setInputFiles('tests/fixtures/ai-input/japanese.png');await expect.poll(()=>page.evaluate(()=>(window as unknown as {heldUpload?:{status:number}}).heldUpload?.status)).toBe(200);await suspend(admin,'suspended');await page.getByRole('button',{name:'서버에서 새로 확인',exact:true}).click();await expect(page.locator('main').getByRole('alert')).toBeVisible();await expect(page.getByRole('textbox',{name:'입력 제목',exact:true})).toHaveCount(0);
 await page.evaluate(()=>{const w=window as unknown as {releaseUpload?:()=>void;lateLeaks:string[]};w.lateLeaks=[];new MutationObserver(()=>{const text=document.querySelector('main')?.textContent??'';if(text.includes('japanese.png')||text.includes('파일을 업로드했습니다.'))w.lateLeaks.push(text);}).observe(document.querySelector('main')!,{subtree:true,childList:true,characterData:true});w.releaseUpload!();});await expect.poll(()=>page.evaluate(()=>(window as unknown as {uploadDelivered:boolean}).uploadDelivered)).toBe(true);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
 const observed=await page.evaluate(()=>({held:(window as unknown as {heldUpload:unknown}).heldUpload,leaks:(window as unknown as {lateLeaks:string[]}).lateLeaks,recovery:Object.keys(sessionStorage).filter(k=>k.startsWith('gs-hale.ai-input.v1:'))}));await writeFile(info.outputPath('actual-late-upload-response-private.json'),JSON.stringify(observed,null,2));expect(observed.leaks).toEqual([]);expect(observed.recovery).toEqual([]);await expect(page.getByText('japanese.png',{exact:true})).toHaveCount(0);await screenshot(page,info,'revoked-late-upload');await suspend(admin,'active');await admin.dispose();
});
test('G15-U09 A19 actual saved version late response after current auth denial cannot restore protected input',async({page},info)=>{
 await login(page,'luna@example.test');await newInput(page,'늦은 저장 보호');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('실제 저장 원문');const id=await save(page),admin=await api();await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('늦은 응답 비공개 원문');let release!:()=>void,arrived!:()=>void;const hold=new Promise<void>(r=>release=r),done=new Promise<void>(r=>arrived=r);await page.route(`**/api/ai-input/${id}/versions`,async route=>{const response=await route.fetch();expect(response.status()).toBe(200);arrived();await hold;await route.fulfill({response});});await page.getByRole('button',{name:'새 버전 저장',exact:true}).click();await done;await suspend(admin,'suspended');await page.getByRole('button',{name:'서버에서 새로 확인',exact:true}).click();await expect(page.getByRole('region',{name:'저장된 입력'})).toHaveCount(0);const delivered=page.waitForResponse(response=>response.url().endsWith(`/api/ai-input/${id}/versions`)&&response.request().method()==='POST');release();await delivered;await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('gs-hale.ai-input.v1:')).length)).toBe(0);await screenshot(page,info,'revoked-late-save');await suspend(admin,'active');await admin.dispose();
});
