import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {api,post,login,content,create,extract,open,tracing,screenshot} from '../fixtures/ai-input-ui';
tracing();
test('G15-U14 AC15-04 readiness belongs to selected version across back forward and late actual response',async({page},info)=>{
 const r=await api('luna@example.test'),v1=await create(r);await extract(r,v1);const v2=await post(r,`/api/ai-input/${v1.id}/versions`,{expectedRevision:v1.revision,content:content('미등록 합성 원문 v2'),idempotencyKey:randomUUID()});await extract(r,v2);await login(page,'luna@example.test');await open(page,v1.id);const history=page.getByRole('navigation',{name:'입력 버전'}),allowed=page.getByRole('status').filter({hasText:'등록된 합성 자료임을 확인했습니다'}),denied=page.getByRole('status').filter({hasText:'외부 전송 대상이 아닙니다'});await history.getByRole('link',{name:'v1',exact:true}).click();await page.getByRole('button',{name:'외부 전송 대상 여부 확인'}).click();await expect(allowed).toBeVisible();await page.goBack();await expect(page.getByRole('heading',{name:'저장된 입력 v2',exact:true})).toBeVisible();await expect(allowed).toHaveCount(0);await page.getByRole('button',{name:'외부 전송 대상 여부 확인'}).click();await expect(denied).toBeVisible();await page.goForward();await expect(page.getByRole('heading',{name:'저장된 입력 v1',exact:true})).toBeVisible();await expect(denied).toHaveCount(0);
 let release!:()=>void,arrived!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),ready=new Promise<void>(resolve=>arrived=resolve);let held:unknown;await page.route(`**/api/ai-input/${v1.id}/transfer-readiness`,async route=>{const response=await route.fetch();expect(response.status()).toBe(200);held=await response.json();arrived();await gate;await route.fulfill({response});});await page.getByRole('button',{name:'외부 전송 대상 여부 확인'}).click();await ready;await page.goBack();await expect(page.getByRole('heading',{name:'저장된 입력 v2',exact:true})).toBeVisible();const delivered=page.waitForResponse(response=>response.url().endsWith('/transfer-readiness'));release();await delivered;await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(allowed).toHaveCount(0);await expect(denied).toHaveCount(0);expect(held).toMatchObject({allowed:true,providerCalled:false,analysisConnected:false});await writeFile(info.outputPath('actual-old-version-readiness-private.json'),JSON.stringify({held,currentVersion:2},null,2));await screenshot(page,info,'version-readiness');await r.dispose();
});
