import {test,expect} from '@playwright/test';
import {api,login,content,create,upload,newInput,save,open,read,chooseUpload,tracing,screenshot} from '../fixtures/ai-input-ui';
tracing();
test('G15-U04 AC15-02 native PDF exact selected pages actual upload and download',async({page},info)=>{
 await login(page,'luna@example.test');await newInput(page,'12쪽 중 두 페이지','pdf');await chooseUpload(page,'native-12.pdf');await page.getByRole('textbox',{name:'읽을 PDF 페이지',exact:true}).fill('1-11');await page.getByRole('button',{name:'입력 저장',exact:true}).click();await expect(page.locator('main').getByRole('alert')).toContainText('최대 10');await expect(page.getByRole('textbox',{name:'읽을 PDF 페이지',exact:true})).toHaveValue('1-11');await page.getByRole('textbox',{name:'읽을 PDF 페이지',exact:true}).fill('2, 10');await save(page);await read(page);const result=page.getByRole('region',{name:'읽기 결과'});await expect(result).toContainText('선택 제외 10');await expect(result).toContainText('PAGE_02_SYNTHETIC');await expect(result).toContainText('PAGE_10_SYNTHETIC');await expect(result).not.toContainText('PAGE_01_SYNTHETIC');const dl=page.waitForEvent('download');await page.getByRole('link',{name:/저장한 원본 내려받기/}).click();expect((await dl).suggestedFilename()).toBe('native-12.pdf');await screenshot(page,info,'pdf-selected');
});
test('G15-U05 AC15-02/03 scanned PDF and image OCR uncertainty persisted',async({page},info)=>{
 test.setTimeout(120000);await login(page,'luna@example.test');await newInput(page,'스캔 PDF 일부','pdf');await chooseUpload(page,'mixed-3.pdf');await page.getByRole('textbox',{name:'읽을 PDF 페이지',exact:true}).fill('1,2');await save(page);await read(page);let result=page.getByRole('region',{name:'읽기 결과'});await expect(result.getByRole('heading',{name:'일부만 읽음 · 사람 확인 필요'})).toBeVisible();await expect(result).toContainText('선택 제외 1');await expect(result).not.toContainText('UNSELECTED_PRIVATE_SENTINEL');await screenshot(page,info,'scanned-pdf');await newInput(page,'이미지 인식','images');await chooseUpload(page,'japanese.png');await save(page);await read(page);result=page.getByRole('region',{name:'읽기 결과'});await expect(result.getByRole('heading',{name:'일부만 읽음 · 사람 확인 필요'})).toBeVisible();await expect(result).toContainText('인식 신뢰도');await expect(result).toContainText('모든 문자를 읽었는지 확인할 수 없습니다');await page.reload();await expect(page.getByRole('region',{name:'읽기 결과'})).toContainText('사람 확인 필요');await screenshot(page,info,'image-ocr');
});
test('G15-U06 AC15-03 locked corrupt empty and low contrast remain explicitly unread',async({page},info)=>{
 test.setTimeout(120000);await login(page,'luna@example.test');const r=await api('luna@example.test');for(const [name,expected]of [['locked.pdf','잠긴 PDF'],['corrupt.pdf','손상된 PDF'],['blank.pdf','텍스트를 찾지 못했습니다'],['low-contrast.png','대비가 낮아']]){const a=await upload(r,name),d=await create(r,{...content(),kind:name.endsWith('.pdf')?'pdf':'images',text:null,sources:[{kind:'upload',assetId:a.id}],selectedPages:name.endsWith('.pdf')?[1]:[]});await open(page,d.id);await read(page);const result=page.getByRole('region',{name:'읽기 결과'});await expect(result).toContainText(expected);await expect(result.getByRole('heading',{name:'선택 범위 읽음 · 사람 확인 필요'})).toHaveCount(0);}await screenshot(page,info,'unread');await r.dispose();
});
