import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {api,post,login,content,create,detail,newInput,save,open,read,synthetic,tracing,screenshot} from '../fixtures/ai-input-ui';
tracing();
test('G15-U01 AC15-01/04 ordinary navigation empty text scope and external boundary',async({page},info)=>{
 await login(page,'luna@example.test');await page.getByRole('navigation',{name:'주 메뉴'}).getByRole('link',{name:'AI 입력·읽기'}).click();await expect(page.getByRole('heading',{name:'저장된 입력이 없습니다'})).toBeVisible();await newInput(page,'브라우저 합성 텍스트');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill(synthetic);const id=await save(page);await read(page);await expect(page.getByRole('heading',{name:'선택 범위 읽음 · 사람 확인 필요'})).toBeVisible();await page.getByRole('button',{name:'외부 전송 대상 여부 확인'}).click();await expect(page.getByRole('status').filter({hasText:'외부 모델 호출은 실행하지 않았습니다.'})).toBeVisible();
 await newInput(page,'미확인 분류');await page.getByRole('combobox',{name:'제품 분류',exact:true}).selectOption('unknown');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('미등록 현업 아닌 합성');await save(page);await read(page);await expect(page.getByRole('region',{name:'읽기 결과'}).getByText('지원 범위 밖 · 1번째 시도')).toBeVisible();await expect(page.getByRole('button',{name:'외부 전송 대상 여부 확인'})).toHaveCount(0);await screenshot(page,info,'scope-unknown');await open(page,id);
});
test('G15-U02 AC15-03 versions immutable CAS explicit reapply and draft survives history',async({page},info)=>{
 await login(page,'luna@example.test');await newInput(page,'버전·충돌 확인');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('원문 v1');const id=await save(page),r=await api('luna@example.test'),d=await detail(r,id);await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('내 작성값 유지');await post(r,`/api/ai-input/${id}/versions`,{expectedRevision:d.revision,content:{...d.version.content,text:'다른 창 v2'},idempotencyKey:randomUUID()});await page.getByRole('button',{name:'새 버전 저장',exact:true}).click();await expect(page.getByRole('alert')).toContainText('입력은 유지했습니다');await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveValue('내 작성값 유지');await page.getByRole('button',{name:'최신 버전 비교 · 작성값 유지'}).click();await expect(page.getByRole('heading',{name:'현재 서버 버전 v2'})).toBeVisible();await page.getByRole('button',{name:'현재 버전 기준으로 내 입력 유지'}).click();await page.getByRole('button',{name:'새 버전 저장',exact:true}).click();await expect(page.getByRole('heading',{name:'저장된 입력 v3',exact:true})).toBeVisible();await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('미저장 v4');await page.getByRole('navigation',{name:'입력 버전'}).getByRole('link',{name:'v1',exact:true}).click();await expect(page.getByRole('region',{name:'저장된 입력'})).toContainText('원문 v1');await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveCount(0);await page.getByRole('navigation',{name:'입력 버전'}).getByRole('link',{name:'v3 · 현재',exact:true}).click();await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveValue('미저장 v4');await page.reload();await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveValue('미저장 v4');await screenshot(page,info,'version-recovery');await r.dispose();
});
test('G15-U03 AC15-01/03 scope variants exact 10000 and excess input retained',async({page},info)=>{
 await login(page,'luna@example.test');await newInput(page,'한도 확인');await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('肌'.repeat(10001));await page.getByRole('button',{name:'입력 저장',exact:true}).click();await expect(page.getByRole('alert')).toContainText('10,000자');await expect(page.getByRole('textbox',{name:'입력 문안',exact:true})).toHaveValue('肌'.repeat(10001));await page.getByRole('textbox',{name:'입력 문안',exact:true}).fill('肌'.repeat(10000));await save(page);await read(page);await expect(page.getByRole('heading',{name:'선택 범위 읽음 · 사람 확인 필요'})).toBeVisible();const r=await api('luna@example.test');for(const scope of [{classification:'medicated'},{media:'sds'},{language:'ko'}]){const c=content(),d=await create(r,{...c,scope:{...c.scope,...scope}});await open(page,d.id);await read(page);await expect(page.getByRole('region',{name:'읽기 결과'})).toContainText('지원 범위 밖');}await screenshot(page,info,'unsupported');await r.dispose();
});
