import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {seeded,chooseOne,login,ctx,json,open as campaignOpen,tab,saved} from '../fixtures/campaigns-ui';
import {seedBatch} from '../fixtures/corrections-ui';
import {campaignPdfSubmission} from '../fixtures/ai-input-union';
import {tracing,picker,save,read,detail} from '../fixtures/ai-input-ui';
import type {SubmissionSnapshot,SubmissionWorkspace} from '@/server/submissions/contracts';
tracing();
test('G15-UNION A21 exact campaign selected-menu PDF/G06 use/G10 review survives no-material request; all task entries and mobile geometry',async({page},info)=>{
 test.setTimeout(120000);const x=await seeded(page);await chooseOne(page,x.taskId,x.id);const original=await campaignPdfSubmission(page,x.taskId);
 await login(page);const batch=await seedBatch(page,original.snapshot,1);await login(page,'luna@example.test');
 for(const taskId of [x.taskId,'task-onboarding']){await page.goto(`/tasks/${taskId}?context=${ctx}`);await expect(page.getByRole('region',{name:'업무 연결 문의',exact:true})).toBeVisible();for(const name of ['수정 취합·검토 기록 ↗','PR·행사 참여와 실물 ↗','이 업무의 AI 입력 작성 ↗'])await expect(page.getByRole('link',{name,exact:true})).toBeVisible();}
 await page.goto(`/tasks/${x.taskId}?context=${ctx}`);await page.getByRole('link',{name:'수정 취합·검토 기록 ↗',exact:true}).click();await expect(page.getByRole('navigation',{name:'수정 검토 화면',exact:true})).toBeVisible();await expect(page.getByText('PUBLIC_G10_UI_SELECTED',{exact:true}).first()).toBeVisible();
 await page.goto(`/tasks/${x.taskId}?context=${ctx}`);await page.getByRole('link',{name:'이 업무의 AI 입력 작성 ↗',exact:true}).click();const sources=await picker(page.request),s1=sources.submissions.find(s=>s.id===original.snapshot.id)!;expect(s1.products.map(p=>p.productId)).toEqual(['product-serum']);expect(s1.files[0].sha256).toBe(original.sha256);
 const title='G15_LONG_LATIN_'+('A'.repeat(176));await page.getByRole('textbox',{name:'입력 제목',exact:true}).fill(title);await page.getByRole('combobox',{name:'제품 분류',exact:true}).selectOption('general_cosmetic');await page.getByRole('textbox',{name:'사용처',exact:true}).fill('합성 행사 POP');await page.getByRole('combobox',{name:'제출 버전',exact:true}).selectOption(s1.id);await page.getByRole('checkbox',{name:/이 제출의 상품 사용본/}).check();await page.getByRole('combobox',{name:'입력 형식',exact:true}).selectOption('pdf');await page.getByRole('group',{name:'실제로 읽을 자료 선택',exact:true}).getByRole('radio',{name:'native-12.pdf · 제출 v1 원본',exact:true}).check();await page.getByRole('textbox',{name:'읽을 PDF 페이지',exact:true}).fill('2, 10');
 const id=await save(page);await read(page);const before=await detail(page.request,id);expect(before.version.content.submission).toEqual({taskId:x.taskId,requestId:s1.requestId,submissionId:s1.id,productUseIds:[s1.products[0].id]});expect(before.runs[0].snapshot!.text).toContain('PAGE_02');expect(before.runs[0].snapshot!.text).toContain('PAGE_10');expect(before.runs[0].snapshot!.units.filter(u=>u.status==='unselected')).toHaveLength(10);const source=await page.request.get(before.sources[0].url!);expect(source.status()).toBe(200);expect(createHash('sha256').update(await source.body()).digest('hex')).toBe(original.sha256);
 await page.evaluate(()=>scrollTo(0,0));const configured=page.viewportSize()!,metrics=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,dpr:devicePixelRatio,controls:[...document.querySelectorAll('main h1,main button,main input,main select,main textarea')].filter(e=>e.getClientRects().length).map(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right}))})),viewport=await page.screenshot({path:info.outputPath('union-viewport-private.png')}),full=await page.screenshot({path:info.outputPath('union-full-private.png'),fullPage:true});await writeFile(info.outputPath('union-geometry.json'),JSON.stringify({configured,metrics,titleLength:title.length,png:{viewport:viewport.readUInt32BE(16),full:full.readUInt32BE(16)}},null,2));expect(metrics.innerWidth).toBe(configured.width);expect(metrics.scrollWidth).toBeLessThanOrEqual(configured.width);expect(metrics.controls.every(c=>c.left>=-1&&c.right<=configured.width+1)).toBe(true);expect(viewport.readUInt32BE(16)).toBe(configured.width*metrics.dpr);expect(full.readUInt32BE(16)).toBe(configured.width*metrics.dpr);
 await campaignOpen(page,x.taskId,x.id);await tab(page,'참여·사실 기록');await page.getByRole('combobox',{name:'참여 회신',exact:true}).selectOption('decline');await page.getByRole('button',{name:'참여 회신 저장',exact:true}).click();await saved(page);const current=await json<SubmissionWorkspace>(page.request,`/api/tasks/${x.taskId}/submissions`);expect(current.request.source?.noMaterials).toBe(true);expect(current.submittedEvaluation!.evaluation.required).toBe(0);
 const old=await json<SubmissionSnapshot>(page.request,`/api/submissions/${original.snapshot.id}`);expect(old.contentHash).toBe(original.snapshot.contentHash);expect(old.review.unresolved).toBe(1);expect(old.review.batchVersionIds).toContain(batch.id);await page.goto(`/ai-input/${id}?context=${ctx}`);await expect(page.getByRole('region',{name:'저장된 입력',exact:true})).toBeVisible();const after=await detail(page.request,id);expect(after.version).toEqual(before.version);expect(after.runs).toEqual(before.runs);expect(after.submission?.products[0].productVersionId).toBe(original.snapshot.products[0].productVersionId);expect(after.analysis).toEqual({connected:true,status:'RESTRICTED',url:null,providerCalled:false});await writeFile(info.outputPath('actual-union-identities-private.json'),JSON.stringify({task:x.taskId,campaign:x.id,original,correction:batch.id,currentRequest:current.request,input:after},null,2));
});
