import {test,expect} from '@playwright/test';
import {login,ready,start,open,form,tracing,api,membership,record,ctx} from '../../scripts/ai-review-ui-support';
tracing();
test('G16-U06 actual successful POST held then current membership denied purges and late release stays empty',async({page},info)=>{
 test.setTimeout(60000);await login(page,'operator@example.test');const input=await ready(page.request),run=await start(page.request,input.id),id=run.detail.result!.findings[0].id;await open(page,run.runId);const admin=await api();let release!:()=>void,reached!:()=>void,settled=false;const gate=new Promise<void>(r=>release=r),hit=new Promise<void>(r=>reached=r);await page.route('**/api/ai-review/runs/*/review',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);reached();await gate;await route.fulfill({response});settled=true;});try{const f=form(page,id);await f.getByRole('textbox',{name:'판단 사유 (필수)',exact:true}).fill('G16_REVOKED_DRAFT');await f.getByRole('button',{name:'사람 검토 기록',exact:true}).click();await hit;await membership(admin,'suspended');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('main').getByRole('alert')).toContainText('보호된 결과와 작성값을 지웠습니다');expect((await page.request.get(`/api/ai-review/runs/${run.runId}`)).status()).toBe(404);release();await expect.poll(()=>settled).toBe(true);await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(page.getByRole('region',{name:'분석 결과 요약'})).toHaveCount(0);expect(await page.locator('main').textContent()).not.toContain('G16_REVOKED_DRAFT');expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('gs-hale.ai-review.v1:')))).toEqual([]);await record(info,'late-authorized-post',{commit:200,currentDenied:404,settled,protectedDOMAbsent:true});}finally{release?.();await membership(admin,'active');await admin.dispose();}
});
test('G16-U07 brand direct API SSR cannot expose analysis and G15 link remains absent',async({page},info)=>{
 const staff=await api();try{const input=await ready(staff),run=await start(staff,input.id);await login(page,'luna@example.test');for(const path of [`/api/ai-review?contextId=${ctx}`,`/api/ai-review/inputs/${input.id}`,`/api/ai-review/runs/${run.runId}`,`/api/ai-review/runs/${run.runId}/raw`,`/api/ai-review/corpus?contextId=${ctx}`]){const r=await page.request.get(path);expect([403,404]).toContain(r.status());expect(await r.text()).not.toContain(run.detail.result!.rawHash);}const r=await page.goto(`/ai-review/runs/${run.runId}?context=${ctx}`);expect(r!.status()).toBe(404);expect(await page.content()).not.toContain(run.detail.result!.rawHash);await page.goto(`/ai-input/${input.id}?context=${ctx}`);await expect(page.getByRole('region',{name:'저장된 입력',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'이 입력 버전의 근거 분석·사람 검토',exact:true})).toHaveCount(0);await record(info,'brand-boundary',{routes:5,SSR:404,analysisEntryAbsent:true});}finally{await staff.dispose();}
});
