import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {login,ready,start,open,runDetail,form,tracing,post,api,record,ctx} from '../../scripts/ai-review-ui-support';
tracing();
test('G16-U03 committed human review lost response survives refresh with exact same intent once',async({page},info)=>{
 await login(page);const input=await ready(page.request),run=await start(page.request,input.id);await open(page,run.runId);const id=run.detail.result!.findings[0].id;let once=true;const requests:unknown[]=[];await page.route('**/api/ai-review/runs/*/review',async route=>{requests.push(route.request().postDataJSON());const response=await route.fetch();expect(response.status()).toBe(200);if(once){once=false;await route.abort('failed');}else await route.fulfill({response});});const f=form(page,id);await f.getByRole('textbox',{name:'판단 사유 (필수)',exact:true}).fill('복구 합성 사유');await f.getByRole('button',{name:'사람 검토 기록',exact:true}).click();await expect(page.locator('main').getByRole('alert')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'같은 요청으로 다시 확인',exact:true})).toBeEnabled();await page.getByRole('button',{name:'같은 요청으로 다시 확인',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'사람 검토 기록을 저장했습니다.'})).toBeVisible();expect(requests).toHaveLength(2);expect(requests[0]).toEqual(requests[1]);const d=await runDetail(page.request,run.runId);expect(d.result!.findings[0].review.history).toHaveLength(1);await record(info,'same-intent',{requests,history:d.result!.findings[0].review});
});
test('G16-U04 different GSG account CAS preserves draft and requires explicit latest revision',async({page},info)=>{
 await login(page,'operator@example.test');const input=await ready(page.request),run=await start(page.request,input.id),id=run.detail.result!.findings[0].id;await open(page,run.runId);const f=form(page,id);await f.getByRole('textbox',{name:'판단 사유 (필수)',exact:true}).fill('내 작성 사유 유지');const other=await api();try{await post(other,`/api/ai-review/runs/${run.runId}/review`,{findingId:id,expectedRevision:0,decision:'reject',reason:'다른 GSG 계정 판정',editedSuggestion:null,idempotencyKey:randomUUID()});await f.getByRole('button',{name:'사람 검토 기록',exact:true}).click();await expect(page.locator('main').getByRole('alert')).toBeVisible();await expect(f.getByRole('textbox',{name:'판단 사유 (필수)',exact:true})).toHaveValue('내 작성 사유 유지');await page.getByRole('button',{name:'현재 저장본 새로 확인',exact:true}).click();await page.getByRole('button',{name:'최신 검토 기준으로 작성값 유지',exact:true}).click();await f.getByRole('button',{name:'사람 검토 기록',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'사람 검토 기록을 저장했습니다.'})).toBeVisible();const d=await runDetail(page.request,run.runId);expect(d.result!.findings[0].review.history.map(h=>h.reason)).toEqual(['다른 GSG 계정 판정','내 작성 사유 유지']);await record(info,'different-actors-cas',d.result!.findings[0].review);}finally{await other.dispose();}
});
test('G16-U05 delayed initial read cannot overwrite newer actual review and readiness',async({page},info)=>{
 await login(page);const input=await ready(page.request),run=await start(page.request,input.id),id=run.detail.result!.findings[0].id;let release!:()=>void,reached!:()=>void,first=true,settled=false;const gate=new Promise<void>(r=>release=r),hit=new Promise<void>(r=>reached=r);await page.route(`**/api/ai-review/runs/${run.runId}`,async route=>{if(!first){await route.continue();return;}first=false;const response=await route.fetch();expect(response.status()).toBe(200);reached();await gate;await route.fulfill({response});settled=true;});try{await page.goto(`/ai-review/runs/${run.runId}?context=${ctx}`);await hit;await post(page.request,`/api/ai-review/runs/${run.runId}/review`,{findingId:id,expectedRevision:0,decision:'accept',reason:'새 조회에만 보이는 실제 판단',editedSuggestion:null,idempotencyKey:randomUUID()});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByText('사람 검토 이력 1건',{exact:true})).toBeVisible();release();await expect.poll(()=>settled).toBe(true);await expect(form(page,id).getByRole('textbox',{name:'판단 사유 (필수)',exact:true})).toBeEnabled();await expect(page.getByText('사람 검토 이력 1건',{exact:true})).toBeVisible();await record(info,'initial-read-causal',{settled,latestHistory:1,oldHistory:0});}finally{release?.();}
});
