import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {login,ready,start,open,review,runDetail,form,tracing,ctx,geometry,captureRSC,record,post} from '../../scripts/ai-review-ui-support';
tracing();
test('G16-U01 actual G15 entry -> synthetic candidate -> accept edit reject history + clicked RSC and390',async({page},info)=>{
 test.setTimeout(90000);await login(page);const input=await ready(page.request,undefined,{title:'G16_LONG_TITLE_'+('A'.repeat(150))});await page.goto(`/ai-input/${input.id}?context=${ctx}`);const channels=await captureRSC(page,info);await page.getByRole('link',{name:'이 입력 버전의 근거 분석·사람 검토',exact:true}).click();await expect(page.getByRole('button',{name:'합성 데모 분석 실행',exact:true})).toBeEnabled();await page.getByRole('button',{name:'합성 데모 분석 실행',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'분석 실행 기록을 확인했습니다.'})).toBeVisible();await page.getByRole('link',{name:'1차 분석 · 분석 결과 저장됨',exact:true}).click();await expect(page.getByRole('region',{name:'분석 결과 요약'})).toContainText('적법 확인이 아닙니다');const d=(await page.request.get(new URL(page.url()).pathname.replace('/ai-review/','/api/ai-review/')));expect(d.status()).toBe(200);const data=await d.json(),f=data.result.findings[0];await expect(page.getByRole('article',{name:`후보 ${f.id}`,exact:true})).toContainText('위험 수준');await expect(page.getByText('한국어 비공식 번역',{exact:true}).first()).toBeVisible();await review(page,f.id,'accept','합성 원문과 근거 확인');await review(page,f.id,'edit','수정 사유 기록');await review(page,f.id,'reject','기각 사유 기록');const after=await runDetail(page.request,data.id);expect(after.result!.findings[0].review.history.map(v=>v.decision)).toEqual(['accept','edit','reject']);expect(after.snapshot.snapshotHash).toBe(data.snapshot.snapshotHash);expect(after.result!.rawHash).toBe(data.result.rawHash);await page.getByText('사람 검토 이력 3건',{exact:true}).click();await expect(page.getByText('기각 사유 기록',{exact:true})).toBeVisible();await form(page,f.id).getByRole('textbox',{name:'판단 사유 (필수)',exact:true}).focus();await page.keyboard.press('Tab');await geometry(page,info,'flow');expect(channels.some(v=>v.status===200&&v.contentType.includes('text/x-component'))).toBe(true);const payloads=await Promise.all(channels.map(v=>readFile(v.path,'utf8')));expect(payloads.join('\n')).toContain(input.id);await record(info,'actual-clicked-rsc',{mode:'Browser navigation; exact route.fetch response bytes, fulfilled without rewriting',channels});
});
test('G16-U02 no candidates, unsupported input, read-only corpus and old input version remain distinct',async({page},info)=>{
 await login(page);const input=await ready(page.request,'合成テスト。肌を清潔に保ちます。'),run=await start(page.request,input.id);await open(page,run.runId);await expect(page.getByRole('heading',{name:'확인된 문제 후보 없음',exact:true})).toBeVisible();await expect(page.getByText('후보가 0개여도 적법 확인이 아닙니다.',{exact:false})).toBeVisible();await post(page.request,`/api/ai-input/${input.id}/versions`,{expectedRevision:input.revision,content:{...input.version.content,text:'새 합성 원문'},idempotencyKey:randomUUID()});await page.getByRole('button',{name:'현재 저장본 새로 확인',exact:true}).click();await expect(page.getByRole('region',{name:'분석 실행',exact:true})).toContainText('과거 입력');await page.getByRole('link',{name:'실행 당시 근거 자료',exact:true}).click();await expect(page.getByRole('region',{name:'근거 자료 공개 버전'})).toContainText('읽기 전용');await expect(page.getByText('기계 번역 · 사람 검수 전',{exact:true}).first()).toBeVisible();await geometry(page,info,'corpus');
});
