import { test, expect, type Page, type APIRequestContext } from "@playwright/test";
const password = "Demo-Hale-2026!";
async function login(page: Page, email = "admin@example.test") { await page.goto("/login"); await page.getByLabel("이메일", { exact: true }).fill(email); await page.getByLabel("비밀번호", { exact: true }).fill(password); await page.getByRole("button", { name: "로그인", exact: true }).click(); await expect(page).toHaveURL(/\/$/); }
async function mutation(request: APIRequestContext, url: string, method: string, data: unknown) { const csrf = await (await request.get("/api/auth/csrf")).json(); return request.fetch(url, { method, data, headers: { Origin: new URL(process.env.APP_ORIGIN || `http://127.0.0.1:${process.env.E2E_PORT || "4111"}`).origin, "X-CSRF-Token": csrf.csrfToken } }); }
test("UI creates event, invites/accepts new account, suspends existing session and preserves errors", async ({ page, browser }, info) => {
    const suffix = `${info.project.name}-${Date.now()}`;
    const email = `ui-${suffix}@example.test`;
    await login(page);
    await page.getByRole("link", { name: /컨텍스트·회원/ }).click();
    const create = page.getByRole("heading", { name: "컨텍스트 생성", exact: true }).locator("..");
    await create.getByLabel("유형").selectOption("event");
    await create.getByRole("combobox", { name: "국가", exact: true }).selectOption("JP");
    await create.getByRole("combobox", { name: "브랜드", exact: true }).selectOption("brand-luna");
    await create.getByLabel("행사명").fill(`시연 행사 ${suffix}`);
    await create.getByRole("button", { name: "컨텍스트 생성", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "컨텍스트를 생성했습니다" })).toBeVisible();
    await expect(page.getByText("아직 연결된 회원이 없습니다.")).toBeVisible();
    const contextId = await page.getByLabel("관리할 컨텍스트").inputValue();
    const invite = page.getByRole("heading", { name: "사용자 초대", exact: true }).locator("..");
    await invite.getByLabel("이름", { exact: true }).fill(`새 사용자 ${suffix}`);
    await invite.getByLabel("이메일", { exact: true }).fill(email);
    await invite.getByLabel("담당 범위", { exact: true }).fill("행사 회신");
    await invite.getByRole("button", { name: "초대 링크 생성" }).click();
    await expect(page.getByText("초대 링크를 만들었습니다. 실제 이메일은 발송하지 않았습니다.")).toBeVisible();
    let link = await page.getByLabel("새 초대 링크").inputValue();
    await invite.getByLabel("이름", { exact: true }).fill(`새 사용자 ${suffix}`);
    await invite.getByLabel("이메일", { exact: true }).fill(email);
    await invite.getByRole("button", { name: "초대 링크 생성" }).click();
    await expect(page.getByRole("alert").filter({ hasText: "이미 생성된 초대" })).toBeVisible();
    await expect(invite.getByLabel("이메일", { exact: true })).toHaveValue(email);
    await page.getByRole("button", { name: "초대 재발급", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "이전 링크를 철회" })).toBeVisible();
    link = await page.getByLabel("새 초대 링크").inputValue();
    const brandContext = await browser.newContext({ viewport: info.project.name === "mobile" ? { width: 390, height: 844 } : { width: 1280, height: 800 } });
    const brand = await brandContext.newPage();
    await brand.goto(link);
    await brand.getByLabel("새 계정 비밀번호", { exact: false }).fill(password);
    await brand.getByRole("button", { name: "초대 수락", exact: true }).click();
    await expect(brand.getByRole("heading", { name: "초대 수락 완료" })).toBeVisible();
    await login(brand, email);
    await expect(brand.getByLabel("컨텍스트 선택")).toHaveValue(contextId);
    await brand.screenshot({ path: info.outputPath("new-member-home.png"), fullPage: true });
    await page.getByRole("button", { name: "회원 새로고침" }).click();
    const member = page.locator("article.member-row").filter({ hasText: email });
    await expect(member).toContainText("멤버십: 활성");
    await member.getByRole("button", { name: "멤버십 중지", exact: true }).click();
    await expect(member).toContainText("멤버십: 중지");
    const meAfter = await brandContext.request.get("/api/auth/me");
    expect((await meAfter.json()).contexts).toHaveLength(0);
    await brand.goto(`/?context=${contextId}`);
    await expect(brand.getByRole("heading", { name: "자료를 찾을 수 없습니다" })).toBeVisible();
    await member.getByRole("button", { name: "계정 전체 중지" }).click();
    await expect(member).toContainText("계정: 중지");
    expect((await brandContext.request.get("/api/auth/me")).status()).toBe(401);
    // No invitation-token input or authentication network trace enters the shared evidence.
    await page.getByLabel("관리할 컨텍스트").selectOption("ctx-empty");
    await expect(page.getByText("아직 연결된 회원이 없습니다.")).toBeVisible();
    await page.screenshot({ path: info.outputPath("empty-members.png"), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await brandContext.close();
});
test("HTTP checks CSRF, forged roles, cross-context and reissue without leaking credentials", async ({ page, browser }, info) => {
    await login(page);
    const request = page.context().request;
    const blocked = await request.post("/api/contexts", { data: { type: "event", countryId: "JP", brandId: "brand-luna", eventName: "CSRF should not save" } });
    expect(blocked.status()).toBe(403);
    const forged = await mutation(request, "/api/contexts", "POST", { type: "event", countryId: "JP", brandId: "brand-luna", eventName: "forged", role: "admin" });
    expect(forged.status()).toBe(422);
    const email = `reissue-${info.project.name}-${Date.now()}@example.test`;
    const result = await mutation(request, "/api/contexts/ctx-jp-a-luna/invitations", "POST", { email, name: "재발급 합성", role: "brand" });
    expect(result.status()).toBe(201);
    const inv = await result.json();
    const repeat = await mutation(request, "/api/contexts/ctx-jp-a-luna/invitations", "POST", { email, name: "재발급 합성", role: "brand" });
    expect(repeat.status()).toBe(409);
    const renewed = await mutation(request, `/api/invitations/${inv.id}/reissue`, "POST", { expectedRevision: inv.revision });
    expect(renewed.status()).toBe(200);
    const next = await renewed.json();
    const expired = await mutation(request, "/api/invitations/accept", "POST", { token: inv.token, password });
    expect(expired.status()).toBe(410);
    const mismatch = await mutation(request, "/api/invitations/accept", "POST", { token: next.token, password, contextId: "ctx-jp-a-wave" });
    expect(mismatch.status()).toBe(422);
    const accepted = await mutation(request, "/api/invitations/accept", "POST", { token: next.token, password });
    expect(accepted.status()).toBe(200);
    const brandContext = await browser.newContext();
    const brand = await brandContext.newPage();
    await login(brand, email);
    const allowed = await brandContext.request.get("/api/auth/me");
    expect((await allowed.json()).contexts).toHaveLength(1);
    expect((await brandContext.request.get("/api/contexts/ctx-jp-a-wave/members")).status()).toBe(404);
    await brand.goto("/products/product-balm?context=ctx-jp-a-wave");
    await expect(brand.getByRole("heading", { name: "자료를 찾을 수 없습니다" })).toBeVisible();
    expect(await brand.content()).not.toContain("웨이브 립밤");
    const denied = await mutation(brandContext.request, "/api/contexts/ctx-jp-a-luna/invitations", "POST", { email: "should-not-exist@example.test", name: "bad", role: "brand" });
    expect(denied.status()).toBe(403);
    const members = await request.get("/api/contexts/ctx-jp-a-luna/members");
    const safe = JSON.stringify(await members.json());
    expect(safe.includes(next.token)).toBe(false);
    expect(safe.includes("tokenHash")).toBe(false);
    expect(safe.includes("digest")).toBe(false);
    await brandContext.close();
});
test("UI reassigns brand and GSG responsibility while preserving original author", async ({ page }, info) => {
    await login(page);
    await page.goto("/contexts");
    await expect(page.getByRole("heading", { name: "진행 업무 재배정" })).toBeVisible();
    const form = page.locator("form.member-row").filter({ hasText: "신규 입점 상품 기본자료 준비" });
    await form.getByLabel("새 담당자").selectOption("user-co");
    await form.getByRole("button", { name: "재배정", exact: true }).click();
    await expect(form).toContainText("현재 브랜드 담당: 공동 담당자");
    await expect(form).toContainText("최초 작성자: 가상 루나 담당");
    await form.getByLabel("배정 역할").selectOption("gsg");
    await form.getByLabel("새 담당자").selectOption("user-price");
    await form.getByRole("button", { name: "재배정", exact: true }).click();
    await expect(form).toContainText("GSG 책임자: 가격 담당자");
    await expect(page.getByRole("heading", { name: "변경 이력" }).locator("..")).toContainText("업무 재배정");
    await page.screenshot({ path: info.outputPath("assignment-history.png"), fullPage: true });
    // Restore only this test's current assignment; immutable event history remains.
    await form.getByLabel("배정 역할").selectOption("brand");
    await form.getByLabel("새 담당자").selectOption("user-luna");
    await form.getByRole("button", { name: "재배정", exact: true }).click();
    await expect(form).toContainText("현재 브랜드 담당: 가상 루나 담당");
    await form.getByLabel("배정 역할").selectOption("gsg");
    await form.getByLabel("새 담당자").selectOption("user-gsg");
    await form.getByRole("button", { name: "재배정", exact: true }).click();
    await expect(form).toContainText("GSG 책임자: 가상 운영자");
});
