import {test,expect,type Page,type Locator,type APIRequestContext} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import type {ProductDetail} from '@/server/products/service';
const ctx='ctx-jp-a-luna',other='ctx-jp-b-luna';
test.use({actionTimeout:10000});
async function login(page:Page,email='admin@example.test'){await page.context().clearCookies();await page.goto('/login');await page.getByRole('textbox',{name:'이메일',exact:true}).fill(email);await page.getByLabel('비밀번호',{exact:true}).fill('Demo-Hale-2026!');await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page).toHaveURL(/\/$/);}
async function mutation(r:APIRequestContext,url:string,data:unknown){const token=await(await r.get('/api/auth/csrf')).json();return r.post(url,{data,headers:{Origin:`http://127.0.0.1:${process.env.E2E_PORT}`,'X-CSRF-Token':token.csrfToken}});}
async function dto(page:Page,id:string,context=ctx):Promise<ProductDetail>{const r=await page.request.get(`/api/products/${id}?context=${context}`);expect(r.status()).toBe(200);return r.json();}
async function create(page:Page,name:string){await page.goto(`/products/new?context=${ctx}`);await page.getByRole('textbox',{name:'상품명 *',exact:true}).fill(name);await page.getByRole('textbox',{name:'제품 코드 *',exact:true}).fill(`001-${randomUUID().slice(0,8)}`);await page.getByLabel('임시 제품 코드',{exact:true}).check();await page.getByRole('button',{name:'상품 등록하기',exact:true}).click();await expect(page).toHaveURL(/\/products\/[a-f0-9-]+\?context=/);return new URL(page.url()).pathname.split('/').at(-1)!;}
async function fill(root:Page|Locator,name:string,value:string){await root.getByRole('textbox',{name,exact:true}).fill(value);}
async function saved(root:Locator,name:string){await root.getByRole('button',{name:`${name} 저장`,exact:true}).click();await expect(root.getByRole('status').filter({hasText:`${name}를 저장했습니다.`})).toBeVisible();}
const png=()=>Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a+ZkAAAAASUVORK5CYII=','base64');
function pdf(){const stream="BT /F1 16 Tf 20 80 Td (Synthetic G06 ingredient original) Tj ET";const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 140] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let body="%PDF-1.4\n";const offsets:number[]=[];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(body));body+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(body);body+=`xref\n0 6\n0000000000 65535 f \n${offsets.map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(body);}
test.beforeEach(async({page})=>{await page.context().tracing.start({screenshots:true,snapshots:true,sources:true});});
test.afterEach(async({page},info)=>{await writeFile(info.outputPath('final-dom-private.html'),await page.content());await page.screenshot({path:info.outputPath(info.status===info.expectedStatus?'final-private.png':'failure-private.png'),fullPage:true});await page.context().tracing.stop({path:info.outputPath('journey-private-trace.zip')});});

test('G06 UI06-A/G/I AC-06-01 SA23/24/27/28 brand nonassignee full fields real files null and metadata',async({page},info)=>{
 test.setTimeout(90000);await login(page,'team@example.test');const id=await create(page,`상품 전체필드 ${info.project.name}`),common=page.locator('#common');
 await common.getByRole('button',{name:'현지명 추가',exact:true}).click();for(const [n,v]of [['현지명 1 언어','ja'],['현지명 1 이름','合成商品'],['카테고리','일반 화장품'],['용량값','30.50'],['용량 단위','mL'],['용량 원문','30.50 mL 원문'],['색상','투명'],['향','무향'],['기타 변형','소형'],['제품 설명','설명 합성 원문'],['사용 방법','합성 사용 방법'],['원산지','한국'],['제조사','합성 제조사'],['제조 정보','제조 정보 원문'],['전성분 원문','물, 합성 성분'],['성분 표기 언어','한국어'],['용기','병'],['패키지','상자'],['라벨','일문'],['박스','6입'],['ITF','00001234']])await fill(common,n,v);await common.getByLabel('성분 제출일',{exact:true}).fill('2026-09-21');await common.getByRole('button',{name:'공통 변경 영향 확인',exact:true}).click();await expect(common.getByRole('heading',{name:'변경 영향 미리보기'})).toBeVisible();await saved(common,'브랜드 공통 정보');
 const local=page.locator('#local');await fill(local,'현지 SKU','000-SKU');await fill(local,'JAN 바코드','0000012345');await local.getByRole('combobox',{name:'등록 상태',exact:true}).selectOption('registered');await local.getByRole('combobox',{name:'판매 상태',exact:true}).selectOption('planned');await local.getByLabel('출시일',{exact:true}).fill('2026-11-01');await local.getByRole('combobox',{name:'출시일 확정 수준'}).selectOption('expected');await fill(local,'출시 시간대','Asia/Tokyo');await fill(local,'출시 정보 출처','합성 일정 원문');await fill(local,'출시일 원문','11월 예정');await saved(local,'컨텍스트 정보');
 const price=page.locator('#retail');await fill(price,'소비자가','0');await fill(price,'통화','JPY');await price.getByRole('combobox',{name:'세금 포함 여부'}).selectOption('yes');await price.getByLabel('가격 적용 시작일').fill('2026-09-21');await fill(price,'가격 출처','공개 가격표');await saved(price,'소비자가');
 const files=page.locator('#files');await files.getByLabel('상품 자료 파일 선택').setInputFiles({name:'bad.exe',mimeType:'application/octet-stream',buffer:Buffer.from('bad')});await files.getByRole('button',{name:'선택 자료 업로드'}).click();await expect(files.getByRole('alert')).toBeVisible();await files.getByLabel('상품 자료 파일 선택').setInputFiles([{name:'합성-이미지.png',mimeType:'image/png',buffer:png()},{name:'합성-성분.pdf',mimeType:'application/pdf',buffer:pdf()}]);await files.getByRole('button',{name:'선택 자료 업로드'}).click();await expect(files.getByRole('status').filter({hasText:'파일을 업로드했습니다'})).toBeVisible();const image=files.getByRole('group',{name:/^자료 1 ·/}),ingredient=files.getByRole('group',{name:/^자료 2 ·/});await image.getByRole('combobox',{name:'자료 용도'}).selectOption('image');await ingredient.getByRole('combobox',{name:'자료 용도'}).selectOption('ingredients');for(const[n,v]of[['자료 제목','합성 성분 자료'],['문서 유형','SDS'],['발행자','합성 시험기관'],['유효기간 원문','기간 명시 없음'],['자료 언어','한국어'],['사용 매체','서류'],['사용처','입점'],['자료 출처','합성 원문']])await fill(ingredient,n,v);await ingredient.getByLabel('발행일',{exact:true}).fill('2026-09-20');await saved(files,'자료 연결');
 const data=await dto(page,id);expect(data.common.capacity).toEqual({amount:'30.5',unit:'mL',raw:'30.50 mL 원문'});expect(data.common.ingredients.classification).toBeNull();expect(data.local.jan).toBe('0000012345');expect(data.files).toHaveLength(2);expect(data.files[1].statedValidTo).toBeNull();expect(data.files[1].language).toBe('한국어');expect(data.retail.current!.fields.amount).toBe('0');expect(data).not.toHaveProperty('internal');await expect(page.getByRole('button',{name:'이 상품으로 새 업무 만들기'})).toHaveCount(0);await expect(page.getByRole('link',{name:'이 상품으로 새 업무 만들기'})).toHaveCount(0);await expect(page.getByText('Excel 가져오기·내보내기는 G07 연결 예정입니다.',{exact:false})).toBeVisible();
 expect((await page.request.get(data.files[0].file.originalUrl)).status()).toBe(200);expect((await page.request.get(data.files[1].file.downloadUrl)).status()).toBe(200);await page.reload();await expect(page.getByRole('img',{name:`상품 전체필드 ${info.project.name} 상품 이미지`})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('G06 UI06-B/H AC-06-02/03/05 two retailer versions prices archive and old snapshot',async({page},info)=>{
 test.setTimeout(60000);await login(page);const id=await create(page,`컨텍스트 독립 ${info.project.name}`);await page.getByRole('combobox',{name:'추가 연결 컨텍스트'}).selectOption(other);await page.getByRole('button',{name:'컨텍스트 연결',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'컨텍스트를 연결했습니다'})).toBeVisible();const a=page.locator('#local');await fill(a,'현지 SKU','A-001');await saved(a,'컨텍스트 정보');const retail=page.locator('#retail');await fill(retail,'소비자가','1000.25');await fill(retail,'통화','JPY');await saved(retail,'소비자가');const internal=page.locator('#internal');await fill(internal,'내부 공급가','300.5');await fill(internal,'통화','JPY');await fill(internal,'내부 공급률','40');await internal.getByRole('combobox',{name:'공급률 단위'}).selectOption('percent');await fill(internal,'공급률 기준','소비자가 기준');await saved(internal,'내부 공급 조건');const before=await dto(page,id);
 await page.goto(`/products/${id}?context=${other}`);await fill(page.locator('#local'),'현지 SKU','B-009');await page.locator('#local').getByRole('combobox',{name:'판매 상태'}).selectOption('stopped');await saved(page.locator('#local'),'컨텍스트 정보');await fill(page.locator('#retail'),'소비자가','20000');await fill(page.locator('#retail'),'통화','KRW');await saved(page.locator('#retail'),'소비자가');await fill(page.locator('#common'),'상품명 *',`공통 최신 ${info.project.name}`);await saved(page.locator('#common'),'브랜드 공통 정보');const afterA=await dto(page,id);expect(afterA.local).toEqual(before.local);expect(afterA.retail).toEqual(before.retail);expect(afterA.internal).toEqual(before.internal);expect(afterA.common.name).toBe(`공통 최신 ${info.project.name}`);expect((await dto(page,id,other)).local.salesStatus).toBe('stopped');
 await page.getByRole('button',{name:'상품 보관',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'상품을 보관했습니다'})).toBeVisible();expect((await dto(page,id)).archived).toBe(true);await page.reload();await expect(page.getByRole('button',{name:'상품 복원',exact:true})).toBeVisible();await page.locator('#history').getByText(/공통 v1 ·/).click();await expect(page.locator('#history').getByText(`컨텍스트 독립 ${info.project.name}`,{exact:true})).toBeVisible();await page.getByRole('button',{name:'상품 복원',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'상품을 복원했습니다'})).toBeVisible();
 await page.goto(`/products/product-serum?context=${ctx}`);const original=await dto(page,'product-serum');expect(original.uses.length).toBeGreaterThan(0);await fill(page.locator('#common'),'제품 설명','현재만 수정한 합성 문구');await saved(page.locator('#common'),'브랜드 공통 정보');expect((await dto(page,'product-serum')).uses).toEqual(original.uses);await expect(page.getByText(/합성 사용본 계약 예시/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('G06 UI06-C/G AC-06-01/03 conflict and HTTP failure retain input and successful upload IDs',async({page},info)=>{
 test.setTimeout(60000);await login(page,'luna@example.test');const id=await create(page,`충돌 입력 ${info.project.name}`),common=page.locator('#common'),original=await dto(page,id);await fill(common,'상품명 *','저장 전 내 입력');const conflict=await mutation(page.request,`/api/products/${id}`,{contextId:ctx,command:'save_common',common:{...original.common,name:'다른 편집 최신값'},expectedCommonRevision:original.commonRevision,idempotencyKey:randomUUID()});expect(conflict.status()).toBe(200);await common.getByRole('button',{name:'브랜드 공통 정보 저장',exact:true}).click();await expect(common.getByRole('alert')).toBeVisible();await expect(common.getByRole('textbox',{name:'상품명 *',exact:true})).toHaveValue('저장 전 내 입력');await common.getByRole('button',{name:'최신 저장값 확인',exact:true}).click();await expect(common.getByRole('heading',{name:'최신 저장값 · 비교 후 선택'})).toBeVisible();await common.getByRole('button',{name:'입력 유지하고 최신 버전 기준 사용'}).click();await saved(common,'브랜드 공통 정보');expect((await dto(page,id)).common.name).toBe('저장 전 내 입력');
 await fill(common,'제품 설명','500 뒤에도 유지');await page.route(`**/api/products/${id}`,route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:{code:'STORAGE',message:'합성 저장 실패'}})}):route.continue(),{times:1});await common.getByRole('button',{name:'브랜드 공통 정보 저장',exact:true}).click();await expect(common.getByRole('alert')).toContainText('합성 저장 실패');await expect(common.getByRole('textbox',{name:'제품 설명',exact:true})).toHaveValue('500 뒤에도 유지');await saved(common,'브랜드 공통 정보');
 const files=page.locator('#files');await page.route(`**/api/products/${id}?context=${ctx}`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'STORAGE',message:'합성 목록 실패'}})}),{times:1});await files.getByLabel('상품 자료 파일 선택').setInputFiles({name:'성공-ID-유지.pdf',mimeType:'application/pdf',buffer:pdf()});await files.getByRole('button',{name:'선택 자료 업로드'}).click();await expect(files.getByRole('alert')).toContainText('파일 업로드는 완료');await expect(files.getByRole('group',{name:/^자료 1 · 성공-ID-유지/})).toBeVisible();await saved(files,'자료 연결');expect((await dto(page,id)).files[0].file.name).toBe('성공-ID-유지.pdf');
});

test('G06 UI06-F AC-06-01 SA28 actual product task create preselection existing link and archive history',async({page},info)=>{
 test.setTimeout(60000);await login(page);const id=await create(page,`업무 연결 ${info.project.name}`);await page.getByRole('combobox',{name:'연결할 기존 업무'}).selectOption('task-pop');await page.getByRole('button',{name:'기존 업무에 연결',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'기존 업무에 상품을 연결했습니다'})).toBeVisible();expect((await dto(page,id)).linkedTasks.some(t=>t.id==='task-pop')).toBe(true);await page.getByRole('link',{name:'이 상품으로 새 업무 만들기',exact:true}).click();await expect(page.getByRole('checkbox',{name:`업무 연결 ${info.project.name}`,exact:true})).toBeChecked();await fill(page,'업무 제목',`상품에서 만든 업무 ${info.project.name}`);await page.getByRole('button',{name:'초안 만들기',exact:true}).click();await expect(page).toHaveURL(/\/tasks\/[a-f0-9-]+/);const taskId=new URL(page.url()).pathname.split('/').at(-1)!;const task=await(await page.request.get(`/api/tasks/${taskId}`)).json();expect(task.task.data.productIds).toContain(id);await page.goto(`/products/${id}?context=${ctx}`);await expect(page.getByRole('link',{name:`상품에서 만든 업무 ${info.project.name} ↗`,exact:true})).toBeVisible();await page.getByRole('button',{name:'상품 보관',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'상품을 보관했습니다'})).toBeVisible();await page.reload();await expect(page.getByRole('link',{name:/매장 POP 문안 업데이트/})).toBeVisible();await expect(page.getByRole('link',{name:`상품에서 만든 업무 ${info.project.name} ↗`,exact:true})).toBeVisible();
});

test('G06 UI06-D/E/I AC-06-04 SA22 real list filters empty roles API HTML and RSC no private fields',async({page,browser},info)=>{
 await login(page,'operator@example.test');await page.goto(`/products/product-serum?context=${ctx}`);await expect(page.locator('#internal')).toHaveCount(0);expect(await dto(page,'product-serum')).not.toHaveProperty('internal');await page.goto('/products');await fill(page,'상품명·제품 코드 검색','NO_MATCH_G06_SYNTHETIC');await page.getByRole('button',{name:'검색·필터 적용'}).click();await expect(page.getByRole('heading',{name:'조건에 맞는 상품이 없습니다'})).toBeVisible();await page.getByRole('link',{name:'필터 해제',exact:true}).click();await expect(page.getByRole('link',{name:/루나 데일리 세럼|product-serum|공통 최신/}).first()).toBeVisible();await login(page);await page.goto('/products?context=ctx-empty');await expect(page.getByRole('heading',{name:'아직 등록된 상품이 없습니다'})).toBeVisible();
 const bc=await browser.newContext({viewport:info.project.name==='mobile'?{width:390,height:844}:{width:1280,height:900}});await bc.tracing.start({screenshots:true,snapshots:true,sources:true});try{const brand=await bc.newPage();await login(brand,'luna@example.test');await brand.goto(`/products/product-serum?context=${ctx}`);expect(await dto(brand,'product-serum')).not.toHaveProperty('internal');await expect(brand.locator('#internal')).toHaveCount(0);const html=await(await brand.request.get(`/products/product-serum?context=${ctx}`)).text();expect(html).not.toContain('supplyAmount');expect(html).not.toContain('supplyRate');expect((await brand.request.get('/api/products/product-balm?context=ctx-jp-a-wave')).status()).toBe(404);await brand.getByRole('link',{name:'← 상품 목록',exact:true}).click();const rsc=await brand.request.get(`/products/product-serum?context=${ctx}`,{headers:{RSC:'1'}});expect(rsc.status()).toBe(200);const body=await rsc.text();expect(body).not.toContain('supplyAmount');expect(body).not.toContain('supplyRate');await writeFile(info.outputPath('brand-product-rsc-private.txt'),body);expect(await brand.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await brand.screenshot({path:info.outputPath('brand-product-private.png'),fullPage:true});}finally{await bc.tracing.stop({path:info.outputPath('brand-private-trace.zip')});await bc.close();}
});

test('G06 CR04 home product link retains authorized view context',async({page})=>{await login(page);await page.goto(`/?context=${ctx}`);const link=page.locator('.product-card').getByRole('link').filter({hasText:'루나 데일리 세럼'});await expect(link).toHaveAttribute('href',`/products/product-serum?context=${ctx}`);await link.click();await expect(page.getByRole('heading',{level:1})).toBeVisible();});
