import {test,expect,type Page,type Locator,type APIRequestContext,type BrowserContext} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {blankContent,blankRequirement,requirementTypes,type RequestContent} from '@/domain/tasks/types';
import type {SubmissionWorkspace} from '@/server/submissions/contracts';
import type {TaskDetail} from '@/server/tasks/service';
const ctx='ctx-jp-a-luna';
test.use({actionTimeout:10000});
async function login(page:Page,email='admin@example.test'){await page.context().clearCookies();await page.goto('/login');await page.getByRole('textbox',{name:'이메일',exact:true}).fill(email);await page.getByLabel('비밀번호',{exact:true}).fill('Demo-Hale-2026!');await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page).toHaveURL(/\/$/);}
async function mutation(r:APIRequestContext,url:string,data:unknown){const token=await(await r.get('/api/auth/csrf')).json();return r.post(url,{data,headers:{Origin:`http://127.0.0.1:${process.env.E2E_PORT}`,'X-CSRF-Token':token.csrfToken}});}
async function workspace(page:Page,id:string):Promise<SubmissionWorkspace>{const r=await page.request.get(`/api/tasks/${id}/submissions`);expect(r.status()).toBe(200);return r.json();}
async function taskCommand(page:Page,id:string,command:string,extra:Record<string,unknown>={}){const t:TaskDetail=await(await page.request.get(`/api/tasks/${id}`)).json();const r=await mutation(page.request,`/api/tasks/${id}`,{command,expectedRevision:t.task.revision,idempotencyKey:randomUUID(),...extra});expect(r.status()).toBe(200);return r.json();}
function content(all=false):RequestContent{const c=blankContent();c.title=`답변 합성 ${randomUUID().slice(0,8)}`;c.description='실제 제출 검사를 위한 합성 공개 요청';c.deadline.responsibleUserId='user-gsg';c.requirements=all?requirementTypes.map(type=>({...blankRequirement(type,type),label:`검사 ${type}`,options:type==='choice'?['예','아니요']:[],productIds:type==='short_text'?['product-serum']:[]})):[{...blankRequirement('answer','long_text'),label:'공통 답변'},{...blankRequirement('number','number'),label:'필수 수량'}];return c;}
async function create(page:Page,c=content(),products:string[]=[]){await login(page);const r=await mutation(page.request,'/api/tasks',{category:'spot',content:c,targets:[{contextId:ctx,ownerId:'user-gsg',assigneeId:'user-luna',coAssigneeIds:['user-co'],productIds:products}],idempotencyKey:randomUUID()});expect(r.status()).toBe(201);const id=(await r.json()).ids[0];await taskCommand(page,id,'publish');return id as string;}
async function open(page:Page,id:string){await page.goto(`/tasks/${id}?context=${ctx}`);await expect(page.getByRole('region',{name:'답변 편집',exact:true})).toBeVisible();}
const edit=(p:Page)=>p.getByRole('region',{name:'답변 편집',exact:true});
const field=(p:Page|Locator,name:string)=>p.getByRole('textbox',{name,exact:true});
async function saved(page:Page){await edit(page).getByRole('button',{name:'답변 임시 저장',exact:true}).click();await expect(edit(page).getByRole('status').filter({hasText:'답변을 임시 저장했습니다.'})).toBeVisible();}
async function submit(page:Page,mode:'부분'|'전체',version:number){await edit(page).getByRole('button',{name:`${mode} 제출`,exact:true}).click();await expect(edit(page).getByRole('status').filter({hasText:`제출 v${version}을 ${mode} 제출했습니다.`})).toBeVisible();}
function png(){return Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a+ZkAAAAASUVORK5CYII=','base64');}
async function upload(page:Page,name='최종-합성.png'){await edit(page).getByLabel('제출 파일 선택',{exact:true}).setInputFiles({name,mimeType:'image/png',buffer:png()});await edit(page).getByRole('button',{name:'대기 파일 업로드',exact:true}).click();await expect(edit(page).getByRole('status').filter({hasText:'업로드 완료 1개.'})).toBeVisible();return(await workspace(page,new URL(page.url()).pathname.split('/').at(-1)!)).availableFiles.find(f=>f.name===name)!;}
async function extraContext(page:Page,info:{project:{name:string}}):Promise<BrowserContext>{const c=await page.context().browser()!.newContext({viewport:info.project.name==='mobile'?{width:390,height:844}:{width:1280,height:900},baseURL:`http://127.0.0.1:${process.env.E2E_PORT}`});await c.tracing.start({screenshots:true,snapshots:true,sources:true});return c;}
test.beforeEach(async({page})=>{await page.context().tracing.start({screenshots:true,snapshots:true,sources:true});});
test.afterEach(async({page},info)=>{await writeFile(info.outputPath('final-dom-private.html'),await page.content());await page.screenshot({path:info.outputPath(info.status===info.expectedStatus?'final-private.png':'failure-private.png'),fullPage:true});await page.context().tracing.stop({path:info.outputPath('journey-private-trace.zip')});});

test('G05 UI-A AC-05-01/02/05 SA15/16/18 eight typed inputs draft partial full immutable files products and actual team view',async({page},info)=>{
 test.setTimeout(100000);const id=await create(page,content(true),['product-serum']);await login(page,'luna@example.test');await open(page,id);await expect(page.getByRole('region',{name:'제출 이력',exact:true})).toContainText('아직 제출된 답변이 없습니다.');
 const file=await upload(page);expect(file).toBeTruthy();expect((await workspace(page,id)).history).toHaveLength(0);expect((await workspace(page,id)).taskStatus).toBe('requested');
 const e=edit(page);await field(e,'검사 long_text').fill('원문 v1');await field(e,'검사 short_text').fill('상품별 짧은 답변');await e.getByRole('group',{name:'검사 file',exact:true}).getByRole('checkbox',{name:'최종-합성.png',exact:true}).check();await e.getByRole('group',{name:'검사 choice',exact:true}).getByRole('checkbox',{name:'예',exact:true}).check();await field(e,'검사 number').fill('-');const date=e.getByRole('group',{name:'검사 date · 필수',exact:true});await date.getByLabel('날짜',{exact:true}).fill('2026-09-21');await field(date,'시간대').fill('Asia/Tokyo');const link=e.getByRole('group',{name:'검사 link · 필수',exact:true});await field(link,'링크 URL').fill('https://example.test/source');await field(link,'링크 설명').fill('합성 외부 원문');await link.getByRole('combobox',{name:'고정 참조',exact:true}).selectOption('file');await link.getByRole('combobox',{name:'보관 파일 버전',exact:true}).selectOption(file.id);
 const phys=e.getByRole('group',{name:'검사 physical_record · 필수',exact:true});await field(phys,'실물 관련 제공 사실').fill('보내기 위한 합성 샘플 준비');await field(phys,'실물 기록 출처').fill('브랜드 제공 기록');await phys.getByRole('button',{name:'실물 항목 추가',exact:true}).click();await field(phys,'수량').fill('2');await field(phys,'단위').fill('개');const prod=e.getByRole('group',{name:/상품정보 선택$/});await prod.getByRole('button',{name:'이 상품의 현재 버전 선택',exact:true}).click();await prod.getByLabel('상품정보 사용 기준일',{exact:true}).fill('2026-09-21');await e.getByRole('group',{name:/^연결 자료 1/}).getByRole('combobox',{name:'자료 역할',exact:true}).selectOption('editable_original');await saved(page);expect((await workspace(page,id)).draftEvaluation!.invalid).toBe(1);await page.reload();await expect(field(edit(page),'검사 number')).toHaveValue('-');await field(edit(page),'검사 number').fill('');await submit(page,'부분',1);
 const v1=(await workspace(page,id)).latest!;expect(v1.evaluation.missing).toBe(1);expect(v1.mode).toBe('partial');expect(v1.products).toHaveLength(1);expect(v1.content.artifacts[0].role).toBe('editable_original');const original=await page.request.get(v1.files[0].originalUrl);expect(original.status()).toBe(200);expect(createHash('sha256').update(await original.body()).digest('hex')).toBe(v1.files[0].sha256);await expect(edit(page).getByRole('button',{name:'부분 제출',exact:true})).toBeDisabled();
 await field(edit(page),'검사 number').fill('0');await field(edit(page),'검사 long_text').fill('수정 원문 v2');await upload(page,'확인본-v2.png');await edit(page).getByRole('group',{name:/^연결 자료 2/}).getByRole('combobox',{name:'자료 역할',exact:true}).selectOption('review_copy');await submit(page,'전체',2);const v2=(await workspace(page,id)).latest!;expect(v2.mode).toBe('full');expect(v2.evaluation.missing).toBe(0);expect(v2.content.artifacts).toHaveLength(2);expect(await(await page.request.get(`/api/submissions/${v1.id}`)).json()).toEqual(v1);await page.getByRole('button',{name:'제출 v1 보기 · 부분',exact:true}).click();await expect(page.getByRole('region',{name:'제출 v1 상세',exact:true})).toContainText('원문 v1');await expect(page.getByRole('region',{name:'제출 v1 상세',exact:true})).not.toContainText('수정 원문 v2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('typed-inputs-history-private.png'),fullPage:true});await page.goto(`/products/product-serum?context=${ctx}`);await expect(page.getByText(/실제 제출 당시 사용본/)).toHaveCount(2);
 await login(page,'team@example.test');await page.goto(`/tasks/${id}?context=${ctx}`);await expect(page.getByRole('region',{name:'답변 편집',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'실제 제출 진행',exact:true})).toContainText('남은 항목 0개');await expect(page.getByRole('region',{name:'제출 v2 상세',exact:true})).toContainText('수정 원문 v2');const team=await workspace(page,id);expect(team.draft).toBeNull();expect(team.draftEvaluation).toBeNull();expect(team).not.toHaveProperty('internal');for(const headers of [{},{RSC:'1'}] as Record<string,string>[]){const text=await(await page.request.get(`/tasks/${id}?context=${ctx}`,{headers})).text();expect(text).not.toContain('supplyAmount');expect(text).not.toContain('supplyRate');}await page.goto(`/tasks?context=${ctx}`);await expect(page.getByRole('link',{name:new RegExp(v2.request.content.title)})).toContainText('제출 v2 · 전체 제출');await page.goto(`/?context=${ctx}`);await expect(page.locator('article.task-row').filter({has:page.getByRole('link',{name:new RegExp(v2.request.content.title)})})).toContainText('제출 v2 · 전체 제출');
});

test('G05 UI-B AC-05-03/04/05 SA19/20 mixed file retry failed save refresh recovery and account cleanup',async({page},info)=>{
 test.setTimeout(80000);const id=await create(page);await login(page,'luna@example.test');await open(page,id);const e=edit(page);await field(e,'공통 답변').fill('실패 뒤 새로고침 복구 원문');await e.getByLabel('제출 파일 선택',{exact:true}).setInputFiles([{name:'성공-최종.png',mimeType:'image/png',buffer:png()},{name:'금지.exe',mimeType:'application/octet-stream',buffer:Buffer.from('bad')}]);await e.getByRole('button',{name:'대기 파일 업로드',exact:true}).click();await expect(e.getByRole('group',{name:'업로드 · 금지.exe',exact:true})).toContainText('업로드 실패');await expect(e.getByRole('group',{name:'업로드 · 성공-최종.png',exact:true})).toContainText('파일 저장 완료');const readyBefore=(await workspace(page,id)).availableFiles;const file=readyBefore.find(f=>f.name==='성공-최종.png')!;await e.getByRole('button',{name:'실패 파일만 재시도',exact:true}).click();await expect(e.getByRole('status').filter({hasText:'업로드 완료 0개.'})).toBeVisible();expect((await workspace(page,id)).availableFiles.map(f=>f.id).sort()).toEqual(readyBefore.map(f=>f.id).sort());
 await page.route(`**/api/tasks/${id}/submission-draft`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'SYNTHETIC_FAILURE',message:'합성 저장 실패'}})}),{times:1});await e.getByRole('button',{name:'답변 임시 저장',exact:true}).click();await expect(e.getByRole('alert').filter({hasText:'합성 저장 실패'})).toBeVisible();await expect(field(e,'공통 답변')).toHaveValue('실패 뒤 새로고침 복구 원문');await page.reload();await page.getByRole('button',{name:'작성값 복구하기',exact:true}).click();await expect(field(edit(page),'공통 답변')).toHaveValue('실패 뒤 새로고침 복구 원문');await expect(edit(page).getByRole('group',{name:'업로드 · 금지.exe',exact:true})).toContainText('파일 재선택 필요');await edit(page).getByRole('group',{name:'업로드 · 금지.exe',exact:true}).getByLabel('이 파일 다시 선택',{exact:true}).setInputFiles({name:'교체.png',mimeType:'image/png',buffer:png()});await edit(page).getByRole('button',{name:'대기 파일 업로드',exact:true}).click();await expect(edit(page).getByRole('status').filter({hasText:'업로드 완료 1개.'})).toBeVisible();await edit(page).getByRole('button',{name:'업로드 목록에서 제외 · 교체.png',exact:true}).click();await saved(page);const w=await workspace(page,id);expect(w.draft!.content.artifacts.map(a=>a.fileVersionId)).toContain(file.id);expect(w.draft!.content.artifacts).toHaveLength(2);expect(w.history).toHaveLength(0);await page.screenshot({path:info.outputPath('recovered-files-private.png'),fullPage:true});await field(edit(page),'공통 답변').fill('계정 변경 뒤 보이면 안 되는 로컬 입력');await page.getByRole('button',{name:'로그아웃',exact:true}).click();await expect(page).toHaveURL(/\/login/);expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('gs-hale:submission-recovery:')))).toEqual([]);await login(page,'team@example.test');await page.goto(`/tasks/${id}?context=${ctx}`);await expect(page.getByRole('region',{name:'답변 편집',exact:true})).toHaveCount(0);await expect(page.getByText('계정 변경 뒤 보이면 안 되는 로컬 입력',{exact:true})).toHaveCount(0);
});

test('G05 UI-C AC-05-03 SA17 D06 shared draft CAS compare and request rebase preserve local input',async({page},info)=>{
 test.setTimeout(80000);const c=content(),id=await create(page,c);await login(page,'luna@example.test');await open(page,id);await field(edit(page),'공통 답변').fill('처음 저장');await field(edit(page),'필수 수량').fill('3');await saved(page);const other=await extraContext(page,info);try{const co=await other.newPage();await login(co,'co@example.test');await open(co,id);await field(edit(page),'공통 답변').fill('내 충돌 입력');await field(edit(co),'공통 답변').fill('공동담당 먼저 저장');await saved(co);const coDraft=(await workspace(co,id)).draft!;expect(coDraft.providedBy).toMatchObject({kind:'user',userId:'user-co'});expect(coDraft.answers.find(a=>a.requirementKey==='answer')!.provenance.recordedBy).toBe('user-co');expect(coDraft.answers.find(a=>a.requirementKey==='number')!.provenance.recordedBy).toBe('user-luna');await edit(page).getByRole('button',{name:'답변 임시 저장',exact:true}).click();await expect(edit(page).getByRole('alert')).toBeVisible();await expect(field(edit(page),'공통 답변')).toHaveValue('내 충돌 입력');await edit(page).getByRole('button',{name:'최신 초안 비교 · 작성값 유지',exact:true}).click();await expect(page.getByRole('region',{name:'서버 초안 비교',exact:true})).toContainText('공동담당 먼저 저장');await page.getByRole('button',{name:'입력 유지 · 최신 저장 기준 선택',exact:true}).click();await saved(page);expect((await workspace(page,id)).draft!.content.answers.find(a=>a.requirementKey==='answer')!.input).toEqual({text:'내 충돌 입력'});
 await login(co);c.requirements.push({...blankRequirement('added','short_text'),label:'새 요청 필수'});await taskCommand(co,id,'save',{content:c});await taskCommand(co,id,'publish');await field(edit(page),'제출할 때 전할 말').fill('요청변경 전 미저장 메모');await edit(page).getByRole('button',{name:'최신 초안 비교 · 작성값 유지',exact:true}).click();await edit(page).getByRole('button',{name:'변경된 요청과 비교',exact:true}).click();await page.getByRole('region',{name:'요청 변경 비교',exact:true}).getByRole('checkbox',{name:'공통 답변 · 가져오기 가능',exact:true}).check();await page.getByRole('button',{name:'선택한 답변으로 새 요청 적용',exact:true}).click();await expect(edit(page).getByRole('status').filter({hasText:'새 요청 기준으로 초안을 바꿨습니다.'})).toBeVisible();await expect(field(edit(page),'공통 답변')).toHaveValue('내 충돌 입력');await field(edit(page),'새 요청 필수').fill('추가된 답변');await page.getByText('요청 변경 전 작성값 보관',{exact:true}).click();await expect(page.getByText('요청변경 전 미저장 메모',{exact:true})).toBeVisible();await saved(page);expect((await workspace(page,id)).requiresRebase).toBe(false);await page.reload();await page.getByText('요청 변경 전 작성값 보관',{exact:true}).click();await expect(page.getByText('요청변경 전 미저장 메모',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('cas-rebase-private.png'),fullPage:true});}finally{await writeFile(info.outputPath('co-final-dom-private.html'),await other.pages()[0].content());await other.tracing.stop({path:info.outputPath('co-private-trace.zip')});await other.close();}
});

test('G05 UI-D AC-05-03 duplicate response loss consumes one submission and versions reopen',async({page})=>{
 test.setTimeout(60000);const id=await create(page);await login(page,'luna@example.test');await open(page,id);await field(edit(page),'공통 답변').fill('응답 유실에도 제출 하나');await saved(page);let lost=false;await page.route(`**/api/tasks/${id}/submissions`,async route=>{if(route.request().method()==='POST'&&!lost){lost=true;const r=await route.fetch();expect(r.status()).toBe(201);await route.abort('failed');}else await route.continue();});await edit(page).getByRole('button',{name:'부분 제출',exact:true}).click();await expect(edit(page).getByRole('alert')).toBeVisible();await expect(field(edit(page),'공통 답변')).toHaveValue('응답 유실에도 제출 하나');await submit(page,'부분',1);const w=await workspace(page,id);expect(w.history).toHaveLength(1);await page.reload();await expect(page.getByRole('region',{name:'제출 v1 상세',exact:true})).toContainText('응답 유실에도 제출 하나');await page.getByRole('button',{name:'제출 v1을 새 답변 초안으로 가져오기',exact:true}).click();await expect(edit(page).getByRole('status').filter({hasText:'선택한 제출본을 새 답변 초안으로 가져왔습니다.'})).toBeVisible();await field(edit(page),'필수 수량').fill('0');await saved(page);let failRead=false;await page.route(`**/api/tasks/${id}/submissions`,async route=>{if(route.request().method()==='POST'&&!failRead){const response=await route.fetch();expect(response.status()).toBe(201);failRead=true;await route.fulfill({response});}else if(route.request().method()==='GET'&&failRead){failRead=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'SYNTHETIC_FAILURE',message:'확정 뒤 합성 조회 실패'}})});}else await route.fallback();});await edit(page).getByRole('button',{name:'전체 제출',exact:true}).click();await expect(edit(page).getByRole('alert')).toContainText('확정 뒤 합성 조회 실패');await expect(field(edit(page),'공통 답변')).toHaveValue('응답 유실에도 제출 하나');await page.unroute(`**/api/tasks/${id}/submissions`);await submit(page,'전체',2);expect((await workspace(page,id)).history).toHaveLength(2);
});

test('G05 UI-E AC-05-01/03 SA15 held draft resume and GSG proxy provider recorder remain separate',async({page})=>{
 test.setTimeout(60000);const id=await create(page);await taskCommand(page,id,'hold',{reason:'합성 보류'});await open(page,id);await expect(edit(page).getByRole('button',{name:'부분 제출',exact:true})).toBeDisabled();await edit(page).getByRole('combobox',{name:'실제 자료 제공자',exact:true}).selectOption('external');await field(edit(page),'외부 제공자 이름').fill('합성 제조사');await field(edit(page),'자료 제공 출처').fill('합성 메일 원문');await field(edit(page),'공통 답변').fill('보류 중 대행 기록');await saved(page);expect((await workspace(page,id)).taskStatus).toBe('on_hold');await taskCommand(page,id,'resume',{reason:'답변 재개'});await page.reload();await submit(page,'부분',1);const v=(await workspace(page,id)).latest!;expect(v.providedBy).toMatchObject({kind:'external_source',label:'합성 제조사',source:'합성 메일 원문'});expect(v.recordedBy).toBe('user-admin');await expect(page.getByRole('region',{name:'제출 v1 상세',exact:true})).toContainText('합성 제조사');expect(v.review.connected).toBe(false);expect(v.completion.connected).toBe(false);
});

test('G05 UI-F AC-05-03 current product change requires reselection while draft input survives',async({page},info)=>{
 test.setTimeout(70000);const id=await create(page,content(),['product-serum']);await login(page,'luna@example.test');await open(page,id);await field(edit(page),'공통 답변').fill('상품 충돌 뒤에도 보존');const prod=edit(page).getByRole('group',{name:/상품정보 선택$/});await prod.getByRole('button',{name:'이 상품의 현재 버전 선택',exact:true}).click();await prod.getByLabel('상품정보 사용 기준일',{exact:true}).fill('2026-09-21');await saved(page);const other=await extraContext(page,info);try{const admin=await other.newPage();await login(admin);const p=await(await admin.request.get(`/api/products/product-serum?context=${ctx}`)).json();const r=await mutation(admin.request,'/api/products/product-serum',{command:'save_common',contextId:ctx,expectedCommonRevision:p.commonRevision,common:{...p.common,description:'선택 후 변경 '+randomUUID()},idempotencyKey:randomUUID()});expect(r.status()).toBe(200);await edit(page).getByRole('button',{name:'부분 제출',exact:true}).click();await expect(edit(page).getByRole('alert')).toBeVisible();await expect(field(edit(page),'공통 답변')).toHaveValue('상품 충돌 뒤에도 보존');await edit(page).getByRole('button',{name:'최신 상품정보 확인 · 답변 유지',exact:true}).click();await expect(prod).toContainText('변경됨, 다시 선택 필요');await prod.getByRole('button',{name:'이 상품의 현재 버전으로 다시 선택',exact:true}).click();await submit(page,'부분',1);expect((await workspace(page,id)).latest!.products[0].common.description).toContain('선택 후 변경');}finally{await other.tracing.stop({path:info.outputPath('product-editor-private-trace.zip')});await other.close();}
});

test('G05 UI-G AC-05-04 SA21 open editor loses current assignment and cannot publish temporary files',async({page},info)=>{
 test.setTimeout(60000);const id=await create(page);await login(page,'luna@example.test');await open(page,id);const f=await upload(page,'미제출-비공개.png');await field(edit(page),'공통 답변').fill('권한 철회 전 로컬 초안');const other=await extraContext(page,info);try{const admin=await other.newPage();await login(admin);await taskCommand(admin,id,'assign',{assignment:{ownerId:'user-gsg',assigneeId:'user-co',coAssigneeIds:[]}});await edit(page).getByRole('button',{name:'답변 임시 저장',exact:true}).click();await expect(page.locator('#submissions').getByRole('alert')).toContainText('현재 답변 접근 권한');await expect(page.getByRole('region',{name:'답변 편집',exact:true})).toHaveCount(0);expect((await page.request.get(f.originalUrl)).status()).toBe(404);expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('gs-hale:submission-recovery:')))).toEqual([]);}finally{await other.tracing.stop({path:info.outputPath('reassignment-private-trace.zip')});await other.close();}
});
