import { test, expect, type Page, type APIRequestContext } from "@playwright/test";
import { writeFile } from "node:fs/promises";
import { blankContent, blankRequirement, requirementTypes } from "@/domain/tasks/types";
import type { TaskDetail } from "@/server/tasks/service";
const ctx = "ctx-jp-a-luna", password = "Demo-Hale-2026!";
test.use({ actionTimeout: 10000 });
function referencePdf() {
    const stream = "BT /F1 16 Tf 20 80 Td (Synthetic UI original) Tj ET";
    const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 140] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];
    let pdf = "%PDF-1.4\n"; const offsets = [0];
    objects.forEach((object,i)=>{ offsets.push(Buffer.byteLength(pdf)); pdf += `${i+1} 0 obj\n${object}\nendobj\n`; });
    const xref = Buffer.byteLength(pdf); pdf += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,"0")+" 00000 n \n").join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`; return Buffer.from(pdf);
}
async function login(page: Page, email = "admin@example.test") { await page.goto("/login"); await page.getByLabel("이메일", { exact: true }).fill(email); await page.getByLabel("비밀번호", { exact: true }).fill(password); await page.getByRole("button", { name: "로그인", exact: true }).click(); await expect(page).toHaveURL(/\/$/); }
async function mutation(request: APIRequestContext, url: string, data: unknown) { const csrf = await (await request.get("/api/auth/csrf")).json(); return request.post(url, { data, headers: { Origin: `http://127.0.0.1:${process.env.E2E_PORT || "4111"}`, "X-CSRF-Token": csrf.csrfToken } }); }
async function makePublished(page: Page, title: string) { const content = { ...blankContent(), title, description: "합성 개정 시험", deadline: { ...blankContent().deadline, responsibleUserId: "user-gsg" }, requirements: [{ ...blankRequirement("base"), label: "기존 항목" }] }; const r = await mutation(page.request, "/api/tasks", { targets: [{ contextId: ctx, ownerId: "user-gsg", assigneeId: "user-luna", coAssigneeIds: [], productIds: [] }], content, category: "spot", idempotencyKey: crypto.randomUUID() }); expect(r.status()).toBe(201); const id = (await r.json()).ids[0]; const row = await (await page.request.get(`/api/tasks/${id}`)).json(); expect((await mutation(page.request, `/api/tasks/${id}`, { command: "publish", expectedRevision: row.task.revision, idempotencyKey: crypto.randomUUID() })).status()).toBe(200); return id as string; }
test.afterEach(async ({ page }, info) => { if (info.status !== info.expectedStatus) { await writeFile(info.outputPath("failure-dom-private.html"), await page.content()); await page.screenshot({ path: info.outputPath("failure-private.png"), fullPage: true }); } });
test("G04 AC01/02/05 SA09/10/11/12 actual create-eight-types upload preview brand accept and date-only decision", async ({ page, browser }, info) => {
    test.setTimeout(90000); const title = `G04 여정 ${info.project.name}-${Date.now()}`; await login(page);
    await page.context().tracing.start({ screenshots: true, snapshots: true, sources: true });
    let brandContext;
    try {
        await page.goto(`/tasks/new?context=${ctx}`); await page.getByRole("combobox", { name: "GSG 책임자", exact: true }).selectOption("user-gsg"); await page.getByRole("combobox", { name: "브랜드 주담당", exact: true }).selectOption("user-luna");
        await page.getByLabel("업무 제목", { exact: true }).fill(title); await page.getByRole("textbox", { name: "공개 설명", exact: true }).fill("공개 요청 v1 · 제작 조건"); await page.getByLabel("목적", { exact: true }).fill("원문과 자료를 모아 입점 준비"); await page.getByLabel("제작 주체", { exact: true }).fill("브랜드 제작 / GSG 확인"); await page.getByLabel("자막 제작 책임").fill("브랜드"); await page.getByLabel("편집 원본 제공 책임").fill("GSG 확인"); await page.getByLabel("사용 장소").fill("매장 영상"); await page.getByRole("textbox", { name: "내부 원문", exact: true }).fill("PRIVATE_G04_UI_SOURCE");
        const due = page.getByRole("group", { name: "제출 기한", exact: true }); await due.getByLabel("기한 미정").uncheck(); await due.getByLabel("날짜", { exact: true }).fill("2026-10-01"); await due.getByRole("combobox",{name:"확인 책임자",exact:true}).selectOption("user-gsg");
        await page.getByRole("button", { name: "외부 일정 추가" }).click(); const external = page.getByRole("group", { name: "외부 일정 1", exact: true }); await external.getByRole("combobox",{name:"일정 종류",exact:true}).selectOption("printing_delivery"); await external.getByLabel("외부 확인 상대").fill("합성 인쇄소"); await external.getByLabel("기한 미정").uncheck(); await external.getByLabel("날짜", { exact: true }).fill("2026-10-20"); await external.getByRole("combobox",{name:"확정 수준",exact:true}).selectOption("needs_confirmation"); await external.getByLabel("원문 날짜·미확인 내용").fill("10/20 수요일 (요일 충돌 원문)");
        for (const [i,type] of requirementTypes.entries()) { await page.getByRole("button", { name: "요청 항목 추가", exact: true }).click(); const q = page.getByRole("group", { name: new RegExp(`^항목 ${i+1} ·`) }); await q.getByLabel("항목 제목", { exact: true }).fill(`UI ${type}`); await q.getByRole("combobox",{name:"응답 유형",exact:true}).selectOption(type); if(type==="choice") await q.getByRole("textbox",{name:"선택지 (한 줄에 하나)",exact:true}).fill("yes\nno"); if(type==="number") await q.getByLabel("단위",{exact:true}).fill("개"); if(type==="file") { await q.getByRole("button",{name:"규격 추가"}).click(); await q.getByLabel("규격 내용").fill("합성 원본 형식"); await q.getByLabel("규격 출처").fill("합성 안내"); await q.getByLabel("출처 버전").fill("v1"); await q.getByRole("combobox",{name:"규격 강도",exact:true}).selectOption("recommended"); await q.getByRole("combobox",{name:"확인 방법",exact:true}).selectOption("human"); } }
        await page.route("**/api/tasks", route => route.request().method()==="POST" ? route.fulfill({ status:503, contentType:"application/json", body:JSON.stringify({error:{code:"STORAGE_UNAVAILABLE",message:"합성 저장 실패 · 입력을 유지합니다"}}) }) : route.continue());
        await page.getByRole("button", {name:"초안 만들기",exact:true}).click(); await expect(page.locator('main [role="alert"]')).toContainText("합성 저장 실패"); await expect(page.getByLabel("업무 제목",{exact:true})).toHaveValue(title); await page.screenshot({path:info.outputPath("draft-failure-input-retained.png")}); await page.unroute("**/api/tasks");
        await page.getByRole("button",{name:"초안 만들기",exact:true}).click(); await expect(page).toHaveURL(/\/tasks\/[a-f0-9-]+\?context=/); const taskId = new URL(page.url()).pathname.split("/").at(-1)!;
        await page.getByLabel("참고파일 선택").setInputFiles({name:"unsafe.exe",mimeType:"application/octet-stream",buffer:Buffer.from("fake")}); await page.getByRole("button",{name:"선택 파일 업로드"}).click(); await expect(page.locator('main [role="alert"]')).toBeVisible();
        await page.getByLabel("참고파일 선택").setInputFiles({name:"합성-참고.pdf",mimeType:"application/pdf",buffer:referencePdf()}); await page.getByRole("button",{name:"선택 파일 업로드"}).click(); await expect(page.getByLabel("합성-참고.pdf을 참고자료로 연결")).toBeChecked(); await page.getByRole("button",{name:"초안 저장",exact:true}).click(); await expect(page.getByRole("status")).toContainText("초안을 저장했습니다");
        await page.getByRole("button",{name:"브랜드 보기 미리보기",exact:true}).click(); await expect(page.getByRole("heading",{name:"브랜드 보기 미리보기",exact:true})).toBeVisible(); await expect(page.getByText("PRIVATE_G04_UI_SOURCE",{exact:true})).toHaveCount(0); await page.screenshot({path:info.outputPath("public-preview.png"),fullPage:true}); await page.getByRole("button",{name:"이 요청 공개하기"}).click(); await expect(page.getByRole("status")).toContainText("요청을 공개했습니다");
        const publicData:TaskDetail = await (await page.request.get(`/api/tasks/${taskId}`)).json(); expect(publicData.request!.requirements).toHaveLength(8); expect(publicData.request!.milestones[0].deadline.value).toBe("2026-10-20");
        await page.getByRole("button",{name:"내부 초안 편집",exact:true}).click(); await page.getByRole("textbox",{name:"공개 설명",exact:true}).fill("UNPUBLISHED_UI_DRAFT"); await page.getByRole("button",{name:"초안 저장",exact:true}).click(); await expect(page.getByRole("status")).toContainText("초안을 저장했습니다");
        brandContext = await browser.newContext({viewport:info.project.name==="mobile"?{width:390,height:844}:{width:1280,height:900}}); const brand = await brandContext.newPage(); await login(brand,"luna@example.test"); await brand.goto(`/tasks/${taskId}?context=${ctx}`); await expect(brand.getByText("공개 요청 v1 · 제작 조건",{exact:true})).toBeVisible(); await expect(brand.getByText("UNPUBLISHED_UI_DRAFT")).toHaveCount(0); await expect(brand.getByRole("button",{name:"내부 초안 편집"})).toHaveCount(0);
        await brand.getByRole("button",{name:"읽음 기록",exact:true}).click(); await expect(brand.getByRole("status")).toContainText("읽음을 기록했습니다"); await brand.getByRole("button",{name:"작업 수락",exact:true}).click(); await expect(brand.getByRole("status")).toContainText("작업 수락을 기록했습니다"); await brand.getByText("일정 조정 요청",{exact:true}).click(); const proposed = brand.getByRole("group",{name:"제안 기한",exact:true}); await proposed.getByLabel("날짜",{exact:true}).fill("2026-11-05"); await brand.getByRole("textbox",{name:"조정 사유",exact:true}).fill("합성 일정 협의"); await brand.getByRole("button",{name:"조정 요청 보내기"}).click(); await expect(brand.getByRole("status")).toContainText("기존 마감은 유지");
        expect((await (await brand.request.get(`/api/tasks/${taskId}`)).json()).request.deadline.value).toBe("2026-10-01"); await page.reload(); await page.getByRole("button",{name:"요청 버전·활동 이력"}).click(); await page.getByRole("button",{name:"제안 기한 반영",exact:true}).click(); await expect(page.getByRole("status")).toContainText("저장했습니다"); await expect(page.getByText("제안 기한 반영 · 결과 요청 v2",{exact:false})).toBeVisible();
        await brand.reload(); await expect(brand.getByText("공개 요청 v1 · 제작 조건",{exact:true})).toBeVisible(); await expect(brand.getByText(/2026-11-05 · 요청/)).toBeVisible(); expect(await brand.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await brand.screenshot({path:info.outputPath("brand-published-request.png"),fullPage:true}); await page.screenshot({path:info.outputPath("schedule-decision-history.png"),fullPage:true});
        const previewResponse=brandContext.waitForEvent("response",r=>r.url().includes("/api/files/")&&r.url().includes("mode=preview")); const popupPromise=brandContext.waitForEvent("page"); await brand.getByRole("link",{name:"미리보기 ↗",exact:true}).click(); const popup=await popupPromise; expect((await previewResponse).status()).toBe(200); await popup.close(); const dto:TaskDetail=await(await brand.request.get(`/api/tasks/${taskId}`)).json(); expect(dto.request!.description).toBe("공개 요청 v1 · 제작 조건"); const download=await brand.request.get(`/api/files/${dto.files[0].id}?taskId=${taskId}&mode=original`); expect(download.status()).toBe(200); expect((await download.body()).toString()).toContain("Synthetic UI original");
    } finally { await brandContext?.close(); await page.context().tracing.stop({path:info.outputPath("journey-private-trace.zip")}); }
});
test("G04 AC01/04/06 SA07/08/14 projects dependency failure template selective revision and manual cycle", async ({ page },info)=>{
    test.setTimeout(90000); await login(page); const title=`G04 프로젝트 ${info.project.name}-${Date.now()}`; await page.context().tracing.start({screenshots:true,snapshots:true,sources:true});
    try {
        await page.goto(`/projects?context=${ctx}`); await page.getByLabel("프로젝트 이름").fill(title); await page.getByRole("combobox",{name:"GSG 책임자",exact:true}).selectOption("user-gsg"); await page.getByRole("combobox",{name:"브랜드 주담당",exact:true}).selectOption("user-luna"); for(const name of ["상품 등록/서류 · v1","POP·리플렛 · v1","영상/교육 · v1"]) await page.getByLabel(name,{exact:true}).check(); await page.getByRole("button",{name:"선택한 업무로 프로젝트 만들기"}).click(); await expect(page).toHaveURL(/\/projects\/[a-f0-9-]+/); const pid=new URL(page.url()).pathname.split("/").at(-1)!; const p=await(await page.request.get(`/api/projects/${pid}`)).json(); expect(p.tasks).toHaveLength(3); expect(p.data.dependencies).toEqual([]);
        await page.getByRole("combobox",{name:"먼저 진행할 업무",exact:true}).selectOption(p.tasks[0].id); await page.getByRole("combobox",{name:"다음 업무",exact:true}).selectOption(p.tasks[1].id); await page.getByRole("button",{name:"관계 추가",exact:true}).click(); await page.getByRole("button",{name:"선행 관계 저장"}).click(); await expect(page.getByRole("status")).toContainText("선행 관계를 저장했습니다"); await page.getByRole("combobox",{name:"먼저 진행할 업무",exact:true}).selectOption(p.tasks[1].id); await page.getByRole("combobox",{name:"다음 업무",exact:true}).selectOption(p.tasks[0].id); await page.getByRole("button",{name:"관계 추가",exact:true}).click(); await page.getByRole("button",{name:"선행 관계 저장"}).click(); await expect(page.locator('main [role="alert"]')).toContainText("순환"); expect((await(await page.request.get(`/api/projects/${pid}`)).json()).data.dependencies).toHaveLength(1); await page.screenshot({path:info.outputPath("dependency-cycle-rejected.png"),fullPage:true});
        const selected = await makePublished(page,`${title} 선택 업무`), untouched=await makePublished(page,`${title} 유지 업무`); const before=await(await page.request.get(`/api/tasks/${untouched}`)).json();
        await page.goto(`/tasks/templates?context=${ctx}`); await page.getByRole("combobox",{name:"기준 템플릿",exact:true}).selectOption("builtin-documents-v1"); await page.getByLabel("템플릿 이름",{exact:true}).fill(`${title} 개정양식`); await page.getByRole("textbox",{name:"공개 설명",exact:true}).fill("템플릿 개정 설명"); await page.getByRole("button",{name:"요청 항목 추가",exact:true}).click(); const added=page.getByRole("group",{name:/^항목 2 ·/}); await added.getByLabel("항목 제목").fill("SDS 추가 필수"); await added.getByRole("combobox",{name:"응답 유형",exact:true}).selectOption("file"); await page.getByRole("button",{name:"템플릿 버전 저장",exact:true}).click(); await expect(page.getByRole("status")).toContainText("기존 업무는 자동 변경되지 않습니다");
        await page.getByLabel(new RegExp(`${title} 선택 업무 · 저장 버전`)).check(); await page.getByRole("button",{name:"선택 업무 변경 영향 확인"}).click(); await expect(page.getByText(/추가 항목:.*SDS 추가 필수/)).toBeVisible(); await page.getByRole("button",{name:"선택 1개 업무에 변경 적용·공개"}).click(); await expect(page.getByRole("status")).toContainText("선택한 업무만"); expect(await(await page.request.get(`/api/tasks/${untouched}`)).json()).toEqual(before);
        await page.goto(`/tasks/${selected}?context=${ctx}`); await expect(page.getByText("SDS 추가 필수",{exact:true}).first()).toBeVisible(); await page.getByText("수동 회차 복제 · 추가 SKU 업무",{exact:true}).click(); await page.getByLabel("회차 또는 추가 SKU 이름").fill("11월 회차"); await page.getByLabel("대상 기간 시작").fill("2026-11-01"); await page.getByLabel("대상 기간 종료").fill("2026-11-30"); await page.getByRole("button",{name:"새 회차 초안 만들기"}).click(); await expect(page).not.toHaveURL(new RegExp(selected)); await expect(page.getByRole("heading",{level:1})).toContainText("11월 회차"); expect((await(await page.request.get(`/api/tasks/${selected}`)).json()).versions).toHaveLength(2); await page.screenshot({path:info.outputPath("new-manual-cycle.png")});
        await page.goto("/tasks?context=ctx-empty"); await expect(page.getByRole("heading",{name:"아직 등록된 업무가 없습니다",exact:true})).toBeVisible(); await page.screenshot({path:info.outputPath("empty-task-list.png")}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    } finally { await page.context().tracing.stop({path:info.outputPath("project-template-private-trace.zip")}); }
});
