import Link from 'next/link';
import { BRAND } from '@/domain/brand';
import { certaintyLabels, typeLabels } from '@/domain/tasks/types';
import { taskLabels, categoryLabels } from '@/components/workspace';
import type { HomeDTO, HomeTask } from '@/server/home/contracts';
import { homeScopeLabels } from '@/server/home/contracts';
import styles from './ui.module.css';
const stateLabels = { gsg_waiting: 'GSG 답변 대기', brand_supplement_waiting: '브랜드 보완 대기', external_waiting: '외부 확인 대기', resolved: '해결' };
const dateLabels = { overdue: '기한 초과', today: '오늘', near: '2일 이내', later: '예정', confirmation: '기한·담당 확인 필요' };
export function HomeFilters({ data, action = '/', view = 'list' }: { data: HomeDTO; action?: string; view?: string }) {
  return <form action={action} className={styles.filters} aria-label="홈 조회 범위"><label>조회 범위<select name="scope" defaultValue={data.scope}>{Object.entries(homeScopeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>국가 · 리테일러 · 브랜드<select name="context" defaultValue={data.selectedContext ?? ''}><option value="">연결된 첫 컨텍스트</option>{data.contexts.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label><input type="hidden" name="view" value={view}/><button className="button">범위 적용</button><p>내 업무는 모든 허용 컨텍스트의 본인 담당·공동담당 업무입니다. 공지는 현재 수신 권한을 기준으로 표시합니다.</p></form>;
}
function TaskCard({ task }: { task: HomeTask }) {
  return <article className={styles.card} data-home-task={task.id}><div className={styles.row}><span className="badge">{categoryLabels[task.category]}</span><span className="badge">{taskLabels[task.status]}</span></div><h3><Link href={task.url}>{task.title} ↗</Link></h3><p>{task.contextLabel}</p><p>{task.nextAction}</p><dl className={styles.facts}><div><dt>브랜드 담당</dt><dd>{task.assignees.map(u => u.label).join(', ')}</dd></div><div><dt>GSG 담당</dt><dd>{task.owner.label}</dd></div><div><dt>요청 기한</dt><dd>{task.deadline?.value ?? '기한 미정'}{task.deadline && ` · ${task.deadline.timezone} · ${certaintyLabels[task.deadline.certainty]}`}</dd></div><div><dt>제출 자료</dt><dd>{task.submission ? `${task.submission.mode === 'full' ? '전체' : '부분'} 제출 · ${task.submission.current ? '현재 요청' : '이전 요청'} · ${task.submission.at}` : '제출 기록 없음'}<br/>{task.remaining === null ? '요청 항목 확인 필요' : `남은 필수 항목 ${task.remaining}개`}</dd></div></dl>{task.corrections > 0 && <p className={styles.attention}>공개된 미해결 보완 {task.corrections}개 · 완료 상태와 별도</p>}{task.completedAt && <p>GSG 수동 완료: {task.completedAt} · 당시 잔여 상태는 완료 이력에서 확인</p>}{task.products.length > 0 && <div className={styles.row} aria-label="관련 상품">{task.products.map(p => <Link key={p.id} href={p.url}>상품: {p.name} ↗</Link>)}</div>}{task.project && <p><Link href={task.project.url}>입점 프로젝트: {task.project.title} ↗</Link></p>}{task.requirements.length > 0 && <details><summary>요청 항목 {task.requirements.length}개</summary><ul>{task.requirements.map(q => <li key={q.key}>{q.required ? '필수' : '선택'} · {q.label} · {typeLabels[q.type]}</li>)}</ul></details>}<div className={styles.row}><Link href={task.url}>요청·답변·첨부</Link><Link href={`/tasks/${encodeURIComponent(task.id)}/corrections?context=${encodeURIComponent(task.contextId)}`}>검토·보완</Link><Link href={`/tasks/${encodeURIComponent(task.id)}/completion?context=${encodeURIComponent(task.contextId)}`}>완료·외부 전달 기록</Link></div></article>;
}
export function HomeSurface({ data, view }: { data: HomeDTO; view: 'list' | 'kanban' | 'timeline' }) {
  const c = data.counts, query = new URLSearchParams({ scope: data.scope, ...(data.selectedContext ? { context: data.selectedContext } : {}) });
  const groups = [...new Map(data.tasks.map(t => [t.owner.id, t.owner])).values()];
  return <div className={styles.stack}><header className={styles.hero}><p className="eyebrow">{BRAND.name} · {data.role === 'gsg' ? 'GSG 운영 홈' : '브랜드 업무 홈'}</p><h1>{BRAND.slogan}</h1><p>{BRAND.definition}</p><div className={styles.row}><Link className="button" href={`/tasks?${query}`}>신규 입점·스팟 업무</Link><Link className="button subtle" href={`/products${data.selectedContext ? `?context=${encodeURIComponent(data.selectedContext)}` : ''}`}>상품정보 · 등록·수정</Link></div></header><HomeFilters data={data} view={view}/>{!data.contexts.length ? <section className={styles.panel}><h2>연결된 컨텍스트가 없습니다</h2><p>GSG 담당자에게 국가·리테일러·브랜드 연결을 요청해 주세요.</p></section> : <><section className={styles.metrics} aria-label="현재 업무 집계">{[
    ['업무', c.tasks, '#home-tasks'], ['미답변 질문', c.unresolved, '#home-questions'], ['오늘 기한', c.today, '#home-dates'], ['2일 이내', c.near, '#home-dates'], ['기한 초과', c.overdue, '#home-dates'], ['기한·담당 확인', c.confirmation, '#home-dates'], ...(data.role === 'gsg' ? [['외부 확인 예정', c.externalChecks, '#home-dates'], ['새 제출 · 검토 미기록', c.newSubmissions, '#home-submissions'], ['전달 필요 확인', c.handoffChecks, '#home-handoff']] : [['미해결 보완', c.corrections, '#home-tasks']]), ['읽지 않은 공지', c.unreadNotices, '#home-notices'],
  ].map(([label, count, href]) => <a key={label} href={String(href)} className={styles.metric}><span>{label}</span><strong>{count}</strong></a>)}</section>
  <section className={styles.panel} id="home-questions"><h2>남은 질문 · {c.unresolved}개</h2><p>질문별로 집계합니다. 답변·보완·외부 확인은 각각의 진행 상태입니다.</p>{data.questions.length ? <ul className={styles.actionList}>{data.questions.map(q => <li key={q.id}><Link href={q.url}>{q.title} · 질문 {q.number} ↗</Link><span>{stateLabels[q.state]} · GSG {q.owner?.label ?? '담당 확인 필요'}</span></li>)}</ul> : <p>이 범위에 남은 질문이 없습니다.</p>}</section>
  <section className={styles.panel} id="home-dates"><h2>기한과 외부 확인 일정</h2><p>원본 시간대의 날짜 기준으로 오늘·1~2일 이내·초과를 구분합니다. 기한 미정·충돌, 외부 대기와 이미 충족된 요청은 마감 초과 미제출로 합산하지 않습니다.</p>{data.dates.some(d => d.pending) ? <ul className={styles.actionList}>{data.dates.filter(d => d.pending).map(d => <li key={d.key}><Link href={d.url}>{d.title} · {d.external ? '외부 확인' : dateLabels[d.bucket]} ↗</Link><span>{d.deadline.value ?? '기한 미정'} · {d.deadline.timezone} · {certaintyLabels[d.deadline.certainty]} · {d.owners.map(o => o.label).join(', ') || '담당 확인 필요'}</span></li>)}</ul> : <p>현재 진행이 필요한 일정이 없습니다.</p>}</section>
  {data.role === 'gsg' && <><section className={styles.panel} id="home-submissions"><h2>새 제출 · 검토 미기록 {c.newSubmissions}건</h2><p>최신 제출본에 검토 기록이 없는 진행 업무입니다. 제출은 검토·승인·완료를 뜻하지 않습니다.</p>{data.tasks.filter(t => t.reviewPending).map(t => <p key={t.id}><Link href={t.url}>{t.title}</Link> · {t.owner.label} · {t.submission?.at}</p>)}{!c.newSubmissions && <p>현재 범위에 검토 미기록 제출이 없습니다.</p>}</section><section className={styles.panel} id="home-handoff"><h2>전달 필요 확인 {c.handoffChecks}건</h2><p>현재 전체 제출본에 변경 요청 없음 검토가 있고 미해결 보완은 없지만, 그 제출본의 외부 전달 기록은 없는 업무입니다. 전달 의무·적법·승인으로 판정하지 않습니다.</p>{data.tasks.filter(t => t.handoffCheck).map(t => <p key={t.id}><Link href={`/tasks/${t.id}/completion?context=${t.contextId}`}>{t.title}</Link> · {t.owner.label}</p>)}{!c.handoffChecks && <p>현재 조건에 해당하는 업무가 없습니다.</p>}</section></>}
  <section id="home-tasks" className={styles.stack}><div className={styles.row}><h2>{data.role === 'gsg' ? 'GSG 담당별 업무' : '요청과 제출 업무'} · {c.tasks}개</h2>{(['list', 'kanban', 'timeline'] as const).map(v => <Link className="button subtle" key={v} aria-current={view === v ? 'page' : undefined} href={`/?${query}&view=${v}`}>{v === 'list' ? '목록' : v === 'kanban' ? '칸반' : '프로젝트 타임라인'}</Link>)}</div>{!c.tasks ? <p className={styles.panel}>이 조회 범위에 업무가 없습니다. 다른 조회 범위를 선택해 보세요.</p> : view === 'kanban' ? <div className={styles.kanban}>{Object.entries(taskLabels).map(([key, label]) => <section key={key} className={styles.lane}><h3>{label} · {data.tasks.filter(t => t.status === key).length}</h3>{data.tasks.filter(t => t.status === key).map(t => <TaskCard key={t.id} task={t}/>)}</section>)}</div> : view === 'timeline' ? <div className={styles.stack}>{[...new Set(data.tasks.map(t => t.project?.id ?? 'spot'))].map(id => <section className={styles.stack} key={id}><h3>{data.tasks.find(t => t.project?.id === id)?.project?.title ?? '프로젝트 없는 독립 업무'}</h3>{data.tasks.filter(t => (t.project?.id ?? 'spot') === id).map(t => <TaskCard key={t.id} task={t}/>)}</section>)}</div> : data.role === 'gsg' ? groups.map(owner => <section className={styles.stack} key={owner.id}><h3>{owner.label} · {data.tasks.filter(t => t.owner.id === owner.id).length}개</h3><div className={styles.grid}>{data.tasks.filter(t => t.owner.id === owner.id).map(t => <TaskCard key={t.id} task={t}/>)}</div></section>) : <div className={styles.grid}>{data.tasks.map(t => <TaskCard key={t.id} task={t}/>)}</div>}</section>
  <section className={styles.panel} id="home-notices"><h2>공지·가이드</h2>{data.notices.length ? <ul className={styles.actionList}>{data.notices.map(n => <li key={n.id}><Link href={n.url}>{n.title} ↗</Link><span>{n.unread ? '현재 버전 읽기 전' : '현재 버전 읽음'}</span></li>)}</ul> : <p>현재 수신할 수 있는 공개 공지가 없습니다.</p>}</section></>}
  <aside className={styles.panel}><h2>{BRAND.campaign}</h2><p>{BRAND.opening}</p><p className={styles.muted}>{data.mode === 'supabase' ? 'Supabase 영속 저장' : data.mode === 'sqlite' ? 'SQLite 영속 저장' : 'Mock 세션 저장'} · {data.generatedAt} 기준 · 홈 조회는 읽음·알림·완료 기록을 만들지 않습니다.</p></aside></div>;
}
