"use client";
import type { RequestContent, Milestone } from "@/domain/tasks/types";
import type { TaskCatalog } from "@/server/tasks/service";
import { DeadlineEditor } from "./deadline-editor";
import { RequirementEditor } from "./requirement-editor";
import s from "./ui.module.css";
export const milestoneLabels: Record<Milestone["kind"],string> = { application:"신청", review:"검토 회신", printing_delivery:"인쇄·납품", publication_use:"게시·사용" };
export function ContentEditor({ value, onChange, members, products, includeInternal=true }: { value:RequestContent; onChange:(c:RequestContent)=>void; members:TaskCatalog["members"]; products:TaskCatalog["products"]; includeInternal?:boolean }) {
    const set = <K extends keyof RequestContent>(key:K,v:RequestContent[K])=>onChange({...value,[key]:v});
    return <div className={s.stack}><section className={s.panel}><h2>요청 내용</h2><div className={s.grid}>
        <label className={`${s.field} ${s.wide}`}>업무 제목<input required value={value.title} maxLength={200} onChange={e=>set("title",e.target.value)}/></label>
        <label className={`${s.field} ${s.wide}`}>공개 설명<textarea value={value.description} maxLength={20000} rows={5} onChange={e=>set("description",e.target.value)}/></label>
        {([['purpose','목적'],['output','필요한 산출물'],['productionResponsibility','제작 주체'],['subtitleResponsibility','자막 제작 책임'],['originalResponsibility','편집 원본 제공 책임'],['usePlace','사용 장소'],['nextAction','다음 행동']] as const).map(([key,label])=><label className={s.field} key={key}>{label}<input required={key==="nextAction"} value={value[key]} maxLength={key==="purpose"||key==="output"?2000:1000} onChange={e=>set(key,e.target.value)}/></label>)}
    </div></section><section className={s.panel}><h2>기한과 외부 일정</h2><div className={s.stack}><DeadlineEditor value={value.deadline} onChange={d=>set("deadline",d)} members={members}/>
    {value.milestones.map((m,i)=><fieldset className={s.sub} key={m.id}><legend>외부 일정 {i+1}</legend><div className={s.grid}>
        <label className={s.field}>일정 종류<select value={m.kind} onChange={e=>set("milestones",value.milestones.map((x,n)=>n===i?{...x,kind:e.target.value as Milestone["kind"]}:x))}>{Object.entries(milestoneLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
        <label className={s.field}>일정 공개 범위<select value={m.visibility} onChange={e=>set("milestones",value.milestones.map((x,n)=>n===i?{...x,visibility:e.target.value as "public"|"internal"}:x))}><option value="public">브랜드 공개</option><option value="internal">GSG 내부</option></select></label>
        <label className={`${s.field} ${s.wide}`}>외부 확인 상대<input required value={m.counterpart} maxLength={500} onChange={e=>set("milestones",value.milestones.map((x,n)=>n===i?{...x,counterpart:e.target.value}:x))}/><span className={s.hint}>연락·업무 기록입니다. 계정이나 자동 발송이 생성되지 않습니다.</span></label>
    </div><DeadlineEditor label="외부 확인일" value={m.deadline} onChange={d=>set("milestones",value.milestones.map((x,n)=>n===i?{...x,deadline:d}:x))} members={members}/><div className={s.actions}><button type="button" className="button subtle" onClick={()=>set("milestones",value.milestones.filter((_,n)=>n!==i))}>외부 일정 삭제</button></div></fieldset>)}
    <button type="button" className="button subtle" onClick={()=>set("milestones",[...value.milestones,{id:`date-${crypto.randomUUID()}`,kind:"review",deadline:{...value.deadline,value:null},counterpart:"",visibility:"public"}])}>외부 일정 추가</button></div></section>
    <section className={s.panel}><RequirementEditor value={value.requirements} onChange={r=>set("requirements",r)} products={products}/></section>
    <section className={s.panel}><h2>참고 링크</h2><p className={s.hint}>외부 링크의 내용은 고정되지 않습니다. 등록 시 외부 자료를 자동 수집하지 않습니다.</p><div className={s.stack}>{value.links.map((l,i)=><div className={s.sub} key={i}><div className={s.grid}><label className={s.field}>링크 주소<input required type="url" value={l.url} onChange={e=>set("links",value.links.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/></label><label className={s.field}>링크 설명<input required value={l.description} onChange={e=>set("links",value.links.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/></label></div><div className={s.actions}><button type="button" className="button subtle" onClick={()=>set("links",value.links.filter((_,n)=>n!==i))}>링크 삭제</button></div></div>)}<button type="button" className="button subtle" onClick={()=>set("links",[...value.links,{url:"",description:"",contentFixed:false}])}>참고 링크 추가</button></div></section>
    {includeInternal&&<section className={s.panel}><h2>GSG 내부 기록</h2><p className={s.hint}>브랜드 공개 설명과 분리됩니다.</p><div className={s.grid}><label className={s.field}>내부 원문<textarea value={value.internalOriginal} maxLength={20000} onChange={e=>set("internalOriginal",e.target.value)}/></label><label className={s.field}>내부 메모<textarea value={value.internalMemo} maxLength={10000} onChange={e=>set("internalMemo",e.target.value)}/></label></div></section>}</div>;
}
