"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { blankContent, type RequestContent } from "@/domain/tasks/types";
import type { TaskCatalog } from "@/server/tasks/service";
import { ContentEditor } from "./content-editor";
import { TargetEditor,initialTarget,type Target } from "./target-editor";
import { request,useCommand } from "./client";
import s from "./ui.module.css";
export function CreateTask({ catalog,contextId,initialProjectId="",initialProductIds=[] }: {catalog:TaskCatalog;contextId:string;initialProjectId?:string;initialProductIds?:string[]}) {
    const router=useRouter(),command=useCommand();const [targets,setTargets]=useState<Target[]>([{...initialTarget(contextId,catalog),productIds:initialProductIds.filter(id=>catalog.products.some(p=>p.id===id))}]),[catalogs,setCatalogs]=useState<Record<string,TaskCatalog>>({[contextId]:catalog});
    const [content,setContent]=useState<RequestContent>(()=>({...blankContent(),deadline:{...blankContent().deadline,responsibleUserId:initialTarget(contextId,catalog).ownerId}}));
    const [category,setCategory]=useState<"spot"|"onboarding">(initialProjectId?"onboarding":"spot"),[projectId,setProjectId]=useState(initialProjectId),[templateId,setTemplateId]=useState(""),[subtype,setSubtype]=useState("직접 작성"),[adding,setAdding]=useState(false);
    async function addContext(id:string){if(!id)return;setAdding(true);command.setError("");try{const other=await request<TaskCatalog>(`/api/tasks?context=${encodeURIComponent(id)}`);if(!other.canManage)throw new Error("이 컨텍스트의 업무 생성 권한이 없습니다.");setCatalogs(v=>({...v,[id]:other}));setTargets(v=>[...v,initialTarget(id,other)]);}catch(e){command.setError(e instanceof Error?e.message:"대상을 불러오지 못했습니다.");}finally{setAdding(false);}}
    if(!catalog.canManage)return <div className={s.empty}>업무 생성은 GSG 담당자가 진행합니다.</div>;
    return <div className={s.stack}><Link className="back-link" href={`/tasks?context=${contextId}`}>← 업무 목록</Link><header><p className="eyebrow">CREATE REQUEST</p><h1>업무 만들기</h1><p>초안을 저장한 뒤 참고파일을 추가하고 브랜드 보기로 확인해 공개합니다.</p></header>
    <form className={s.stack} onSubmit={e=>{e.preventDefault();void command.run<{ids:string[]}>("/api/tasks",{targets,content,category,projectId:projectId||null,templateVersionId:templateId||null,subtype},r=>router.push(`/tasks/${r.ids[0]}?context=${contextId}`),"초안을 만들었습니다.");}}>
    <fieldset disabled={command.busy} className={s.stack} style={{border:0,padding:0,margin:0}}><section className={s.panel}><h2>분류와 시작 양식</h2><div className={s.grid}><label className={s.field}>업무 분류<select value={category} onChange={e=>{setCategory(e.target.value as "spot"|"onboarding");setProjectId("");setTargets(v=>v.slice(0,1));}}><option value="spot">스팟 업무 · 독립 요청</option><option value="onboarding">신규 입점 · 기존 프로젝트에 추가</option></select></label>
    {category==="onboarding"&&<label className={s.field}>신규 입점 프로젝트<select required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">프로젝트 선택</option>{catalog.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><Link className={s.link} href={`/projects?context=${contextId}`}>새 프로젝트 만들기 ↗</Link></label>}
    <label className={s.field}>시작 템플릿<select value={templateId} onChange={e=>{const t=catalog.templates.find(x=>x.id===e.target.value);setTemplateId(e.target.value);setSubtype(t?.name??"직접 작성");if(t)setContent({...structuredClone(t.content),deadline:{...t.content.deadline,responsibleUserId:targets[0].ownerId}});}}><option value="">직접 작성</option>{catalog.templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.sequence}{t.builtin?" · 기본":""}</option>)}</select><span className={s.hint}>템플릿 선택 시 현재 작성 내용을 선택한 양식으로 바꿉니다.</span></label><label className={s.field}>세부 유형<input value={subtype} maxLength={200} onChange={e=>setSubtype(e.target.value)}/></label></div></section>
    {targets.map((t,i)=><section className={s.panel} key={t.contextId}><h2>대상 {i+1} · {catalog.contexts.find(c=>c.id===t.contextId)?.data.retailer} / {catalog.contexts.find(c=>c.id===t.contextId)?.data.brand}</h2><TargetEditor value={t} catalog={catalogs[t.contextId]} onChange={next=>setTargets(v=>v.map((x,n)=>n===i?next:x))}/>{i>0&&<div className={s.actions}><button type="button" className="button subtle" onClick={()=>setTargets(v=>v.filter((_,n)=>n!==i))}>이 대상 제외</button></div>}</section>)}
    {category==="spot"&&<section className={s.panel}><label className={s.field}>다른 컨텍스트에도 독립 업무 만들기<select value="" disabled={adding} onChange={e=>void addContext(e.target.value)}><option value="">{adding?"불러오는 중…":"추가 대상 선택"}</option>{catalog.contexts.filter(c=>!targets.some(t=>t.contextId===c.id)).map(c=><option key={c.id} value={c.id}>{c.data.country} / {c.data.retailer} / {c.data.brand}</option>)}</select></label><p className={s.hint}>각 대상의 담당·상품을 따로 선택합니다. 요청과 마감은 최초 내용으로 복사되며, 생성 후 서로 독립적으로 수정됩니다. 여러 대상에 복제할 때 기한·외부 일정의 확인 책임자는 각 대상의 GSG 책임자, 제품별 항목은 각 대상에서 선택한 상품으로 맞춰집니다. 개별 초안에서 확인 후 공개하세요.</p></section>}
    <ContentEditor value={content} onChange={setContent} members={catalog.members} products={catalog.products.filter(p=>targets[0].productIds.includes(p.id))}/>
    <div className={s.notice}>참고파일은 초안을 만든 뒤 업무 상세에서 업로드할 수 있습니다.</div><div className={s.actions}><button className="button" type="submit">{command.busy?"저장 중…":targets.length>1?`${targets.length}개 독립 초안 만들기`:"초안 만들기"}</button></div></fieldset>{command.error&&<p role="alert" className={s.error}>{command.error}</p>}</form></div>;
}
