"use client";
import Link from "next/link";
import {RequestSourceNotice} from "@/features/submissions/views";
import {SubmissionSurface} from "@/features/submissions/surface";
import {parseSubmissionReference} from "@/features/submissions/reference";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { TaskDetail,TaskCatalog } from "@/server/tasks/service";
import type { RequestContent,Deadline } from "@/domain/tasks/types";
import { taskLabels,categoryLabels } from "@/components/workspace";
import { ContentEditor } from "./content-editor";
import { RequestView,type PublicContent } from "./request-view";
import { ReferenceEditor } from "./reference-editor";
import { TargetEditor,Checks,type Target } from "./target-editor";
import { DeadlineEditor,DeadlineView } from "./deadline-editor";
import { request,useCommand } from "./client";
import s from "./ui.module.css";
const activityLabels={read:"읽음",accept:"수락",schedule:"일정 조정 요청",schedule_resolved:"일정 조정 결정"};
const auditLabels:Record<string,string>={"task.created":"업무 생성","task.draft":"초안 저장","task.published":"요청 공개","task.reassigned":"담당자 변경","task.state":"진행 상태 변경","task.read":"읽음 기록","task.accept":"작업 수락","task.schedule":"기한 조정 요청","task.schedule_decide":"기한 조정 결정"};
const statusLabels:Record<string,string>={received:"실제 제출에서 충족",invalid:"입력 확인 필요",missing:"추가 제출 필요",prior_received:"이전 제출에서 충족",needs_reconfirmation:"재확인 필요",not_applicable:"해당 없음",optional:"선택 항목"};
const deadlineFields = ["value", "precision", "timezone", "certainty", "source", "sourceVersion", "responsibleUserId", "raw"] as const satisfies readonly (keyof Deadline)[];
function DeadlineChangeNotice({ published, draft }: { published?: Deadline; draft: Deadline }) {
    if (!published || !deadlineFields.some(field => published[field] !== draft[field])) return null;
    return <p role="status" className={s.notice}>공개된 요청과 초안의 기한 정보가 다릅니다. 초안을 공개하기 전에 기한을 다시 확인하세요.</p>;
}
export function TaskDetailView({ initial,catalog }: {initial:TaskDetail;catalog:TaskCatalog}) {
    const router=useRouter(),search=useSearchParams(),command=useCommand();const reference=parseSubmissionReference(initial.task.id,search);const [detail,setDetail]=useState(initial),[draft,setDraft]=useState<RequestContent|null>(initial.draft),[tab,setTab]=useState(initial.request?"request":"edit"),[preview,setPreview]=useState<PublicContent|null>(null),[fetching,setFetching]=useState(false),[conflict,setConflict]=useState(false);
    const t=detail.task, contextId=t.contextId!, base=`/api/tasks/${t.id}`;const name=(id:string)=>catalog.members.find(m=>m.id===id)?.name??"이전 담당자";
    const [assignment,setAssignment]=useState<Target>({contextId,ownerId:t.data.ownerId,assigneeId:t.data.assigneeId,coAssigneeIds:t.data.coAssigneeIds,productIds:t.data.productIds});
    const [proposed,setProposed]=useState<Deadline>(initial.request?.deadline??initial.draft!.deadline),[reason,setReason]=useState(""),[stateReason,setStateReason]=useState(""),[cycle,setCycle]=useState({label:"",start:"",end:""}),[cycleProducts,setCycleProducts]=useState(t.data.productIds);
    const selectedCatalog={...catalog,products:catalog.products.filter(p=>t.data.productIds.includes(p.id))};
    async function refresh(preserve=true){const fresh=await request<TaskDetail>(base+`?context=${contextId}`);setDetail(fresh);if(!preserve)setDraft(fresh.draft);return fresh;}
    function perform(cmd:string,extra:Record<string,unknown>={},success="저장했습니다."){void command.run<{ids:string[]}>(base,{command:cmd,expectedRevision:detail.task.revision,...extra},async r=>{if(cmd==="duplicate"){router.push(`/tasks/${r.ids[0]}?context=${contextId}`);return;}await refresh(cmd!=="save");setConflict(false);if(cmd==="publish")setTab("request");},success);}
    async function loadLatest(){setFetching(true);command.setError("");try{await refresh(true);setConflict(true);command.setMessage("최신 저장 버전을 불러왔습니다. 작성 중인 입력은 유지했습니다. 내용을 비교한 뒤 다시 저장하세요.");}catch(e){command.setError(e instanceof Error?e.message:"불러오지 못했습니다.");}finally{setFetching(false);}}
    async function loadPreview(){setFetching(true);command.setError("");try{const result=await request<{content:PublicContent}>(base+"?preview=1");if(!result.content)throw new Error("공개 미리보기 응답을 확인하지 못했습니다. 다시 시도해 주세요.");setPreview(result.content);setTab("preview");}catch(e){command.setError(e instanceof Error?e.message:"미리보기를 불러오지 못했습니다.");}finally{setFetching(false);}}
    const changed=draft!==null&&JSON.stringify(draft)!==JSON.stringify(detail.draft);const closed=["completed","cancelled","on_hold"].includes(t.data.status);
    return <div className={s.stack}><Link className="back-link" href={`/tasks?context=${contextId}`}>← 업무 목록</Link><header className={s.heading}><div><p className="eyebrow">{categoryLabels[t.data.category]} · {t.data.subtype}</p><h1>{t.data.title}</h1><div className={s.row}><span className="badge">{taskLabels[t.data.status]}</span>{t.data.assignmentNeedsAttention&&<span className={s.required}>활성 담당자로 재배정이 필요합니다</span>}<span className={s.small}>저장 버전 {t.revision}</span></div></div>{t.data.projectId&&<Link className="button subtle" href={`/projects/${t.data.projectId}?context=${contextId}`}>입점 프로젝트 ↗</Link>}</header>
    {command.error&&<div role="alert" className={s.error}>{command.error}<div className={s.actions}><button type="button" className="button subtle" disabled={fetching} onClick={loadLatest}>최신 버전 확인 · 작성값 유지</button></div></div>}{command.message&&<p role="status" className={s.success}>{command.message}</p>}
    <section className={s.panel}><dl className={s.meta}><dt>GSG 책임자</dt><dd>{name(t.data.ownerId)}</dd><dt>브랜드 주담당</dt><dd>{name(t.data.assigneeId)}</dd><dt>공동담당</dt><dd>{t.data.coAssigneeIds.length?t.data.coAssigneeIds.map(name).join(", "):"없음"}</dd><dt>다음 행동</dt><dd>{t.data.nextAction}</dd>{t.data.cycle&&<><dt>회차·대상 기간</dt><dd>{t.data.cycle.label} · {t.data.cycle.start} ~ {t.data.cycle.end}</dd></>}</dl></section>
    <section className={s.panel}><Link className="button subtle" href={`/tasks/${t.id}/campaigns?context=${contextId}`}>PR·행사 참여와 실물 ↗</Link><RequestSourceNotice source={detail.versions.find(v=>v.id===t.data.currentRequestId)?.source??null}/></section>
    <div className={s.tabs}><button className="button subtle" aria-pressed={tab==="request"} onClick={()=>setTab("request")}>공개 요청</button>{detail.canManage&&<><button className="button subtle" aria-pressed={tab==="edit"} onClick={()=>setTab("edit")}>내부 초안 편집</button><button className="button subtle" disabled={fetching||command.busy||changed} onClick={loadPreview}>{fetching?"불러오는 중…":"브랜드 보기 미리보기"}</button></>}<button className="button subtle" aria-pressed={tab==="history"} onClick={()=>setTab("history")}>요청 버전·활동 이력</button></div>
    {tab==="request"&&<>{detail.request?<RequestView content={detail.request} catalog={selectedCatalog} files={detail.files} taskId={t.id}/>:<div className={s.empty}>아직 공개하지 않은 초안입니다.</div>}
    {detail.requirementStatus.length>0&&<section className={s.panel}><h2>현재 요청의 남은 항목</h2><div className={s.list}>{detail.requirementStatus.map((r,i)=><div className={s.sub} key={i}><strong>{r.label}</strong> · {statusLabels[r.status]??r.status}{r.productId&&<span> · {catalog.products.find(p=>p.id===r.productId)?.name??"상품 확인"}</span>}{r.humanReviewPending&&<p className={s.small}>사람 확인이 필요한 규격입니다.</p>}{r.sourceRequestId&&<p className={s.small}>이전 요청의 답변을 참조합니다.</p>}</div>)}</div></section>}
    {detail.request&&!closed&&!detail.canManage&&<section className={s.panel}><h2>요청 확인</h2><p className={s.hint}>읽음·수락·일정 조정은 서로 다른 기록입니다.</p><div className={s.actions}><button type="button" disabled={command.busy} className="button subtle" onClick={()=>perform("read",{},"읽음을 기록했습니다.")}>읽음 기록</button>{detail.canRespond&&<button type="button" disabled={command.busy} className="button" onClick={()=>perform("accept",{},"작업 수락을 기록했습니다.")}>작업 수락</button>}</div>{detail.canRespond&&<details className={s.details}><summary>일정 조정 요청</summary><form className={s.stack} onSubmit={e=>{e.preventDefault();perform("schedule",{deadline:proposed,reason},"일정 조정을 요청했습니다. 기존 마감은 유지됩니다.");}}><DeadlineEditor label="제안 기한" value={proposed} onChange={setProposed} members={catalog.members}/><label className={s.field}>조정 사유<textarea required value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label><button className="button" disabled={command.busy}>조정 요청 보내기</button></form></details>}</section>}
    <p className={s.quiet}>수동 완료·알림 센터는 아직 연결되지 않았습니다. 요청 변경은 버전 이력에서 확인할 수 있습니다.</p></>}
    {detail.request&&<div hidden={tab!=="request"&&reference.kind==="none"}><SubmissionSurface taskId={t.id} contextId={contextId} reference={reference} refreshKey={t.revision} onChanged={()=>refresh(true)}/></div>}
    {tab==="edit"&&detail.canManage&&draft&&<form className={s.stack} onSubmit={e=>{e.preventDefault();perform("save",{content:draft},"초안을 저장했습니다. 브랜드 공개본은 공개하기 전까지 유지됩니다.");}}><fieldset disabled={command.busy} className={s.stack} style={{border:0,padding:0,margin:0}}><DeadlineChangeNotice published={detail.request?.deadline} draft={draft.deadline}/><ContentEditor value={draft} onChange={setDraft} members={catalog.members} products={selectedCatalog.products}/><ReferenceEditor taskId={t.id} files={detail.files} selected={draft.referenceFileIds} onSelect={ids=>setDraft(d=>d?{...d,referenceFileIds:ids}:d)} onUploaded={files=>setDetail(d=>({...d,files:[...d.files,...files.filter(f=>!d.files.some(x=>x.id===f.id))]}))}/>{conflict&&<details className={s.details}><summary>서버에 저장된 최신 초안과 비교</summary>{detail.draft&&<RequestView content={detail.draft} catalog={selectedCatalog} files={detail.files} taskId={t.id}/>}</details>}<div className={s.actions}><button className="button" type="submit">{command.busy?"저장 중…":"초안 저장"}</button><button type="button" className="button subtle" onClick={loadPreview} disabled={changed||fetching}>저장한 초안 미리보기</button><span className={s.small}>{changed?"작성한 변경을 저장한 뒤 미리보기할 수 있습니다.":"현재 저장된 초안입니다."}</span></div></fieldset></form>}
    {tab==="preview"&&preview&&detail.canManage&&<section className={`${s.stack} ${s.preview} ${s.panel}`}><h2>브랜드 보기 미리보기</h2><p className={s.hint}>서버가 반환한 공개 내용입니다. 미리보기만으로 공개·읽음·알림이 생성되지 않습니다.</p><DeadlineChangeNotice published={detail.request?.deadline} draft={preview.deadline}/><RequestView content={preview} catalog={selectedCatalog} files={detail.files.filter(f=>preview.referenceFileIds.includes(f.id))} taskId={t.id}/><div className={s.actions}><button className="button" disabled={command.busy||changed} onClick={()=>perform("publish",{},"요청을 공개했습니다.")}>{command.busy?"공개 중…":"이 요청 공개하기"}</button><button className="button subtle" onClick={()=>setTab("edit")}>초안으로 돌아가기</button></div></section>}
    {tab==="history"&&<div className={s.stack}><section className={s.panel}><h2>요청 공개 버전</h2>{detail.versions.length?detail.versions.map(v=><details key={v.id} className={s.details}><summary>v{v.sequence} · {v.publishedAt} · {name(v.publishedBy)}{v.id===t.data.currentRequestId?" · 현재 공개본":""}</summary><p className={s.small}>변경 항목: {v.changedKeys.map(k=>v.content.requirements.find(r=>r.key===k)?.label??k).join(", ")||"기본 내용·기한 변경"}</p><RequestView content={v.content} catalog={selectedCatalog} files={detail.files} taskId={t.id}/></details>):<p>공개 이력이 없습니다.</p>}</section><section className={s.panel}><h2>읽음·수락·일정 활동</h2>{detail.activities.length?detail.activities.map(a=>{const x=a.data as typeof a.data & {decision?:"apply"|"keep"|null;resultingRequestId?:string|null};return <article className={s.sub} key={a.id}><strong>{activityLabels[x.kind]} · {name(x.userId)}</strong><p className={s.small}>{x.at} · 요청 v{detail.versions.find(v=>v.id===x.requestId)?.sequence??"이전"}</p>{x.reason&&<p className={s.prose}>{x.reason}</p>}{x.proposedDeadline&&<DeadlineView value={x.proposedDeadline} name={name}/>} {x.decision&&<p>{x.decision==="apply"?"제안 기한 반영":"기존 기한 유지"} {x.resultingRequestId?`· 결과 요청 v${detail.versions.find(v=>v.id===x.resultingRequestId)?.sequence??"확인"}`:""}</p>}{detail.canManage&&x.kind==="schedule"&&!detail.activities.some(y=>y.data.respondsTo===a.id)&&<div className={s.actions}><button className="button" disabled={command.busy} onClick={()=>perform("schedule_decide",{activityId:a.id,decision:"apply",reason:"제안 기한 반영"})}>제안 기한 반영</button><button className="button subtle" disabled={command.busy} onClick={()=>perform("schedule_decide",{activityId:a.id,decision:"keep",reason:"기존 기한 유지"})}>기존 기한 유지</button></div>}</article>;}):<p>아직 활동 기록이 없습니다.</p>}</section><section className={s.panel}><h2>변경 이력</h2><ol className={s.history}>{detail.history.map(h=><li key={h.id}>{auditLabels[h.data.action]??"업무 변경"} · {name(h.data.actorId)} · {h.data.at}</li>)}</ol></section></div>}
    {detail.canManage&&<section className={s.panel}><h2>업무 관리</h2><details className={s.details}><summary>담당자 변경</summary><form onSubmit={e=>{e.preventDefault();perform("assign",{assignment:{ownerId:assignment.ownerId,assigneeId:assignment.assigneeId,coAssigneeIds:assignment.coAssigneeIds}},"담당자를 변경했습니다. 이전 작성자는 유지됩니다.");}}><TargetEditor value={assignment} onChange={setAssignment} catalog={catalog} products={false}/><div className={s.actions}><button className="button" disabled={command.busy}>담당자 저장</button></div></form></details>
    <details className={s.details}><summary>수동 회차 복제 · 추가 SKU 업무</summary><form className={s.stack} onSubmit={e=>{e.preventDefault();perform("duplicate",{cycle,productIds:cycleProducts});}}><p className={s.hint}>새 독립 스팟 초안을 만듭니다. 기존 진행·답변은 유지됩니다. 제품별 항목은 새 대상 상품으로 복제되고 새 초안의 담당·기한은 생성 후 수정할 수 있습니다.</p><div className={s.grid}><label className={s.field}>회차 또는 추가 SKU 이름<input required value={cycle.label} onChange={e=>setCycle({...cycle,label:e.target.value})}/></label><label className={s.field}>대상 기간 시작<input required type="date" value={cycle.start} onChange={e=>setCycle({...cycle,start:e.target.value})}/></label><label className={s.field}>대상 기간 종료<input required type="date" value={cycle.end} onChange={e=>setCycle({...cycle,end:e.target.value})}/></label></div><Checks label="새 업무 대상 상품" options={catalog.products} value={cycleProducts} onChange={setCycleProducts}/><button className="button" disabled={command.busy}>새 회차 초안 만들기</button><Link className={s.link} href={`/tasks/new?context=${contextId}${t.data.projectId?`&project=${t.data.projectId}`:""}`}>기존 입점 프로젝트에 추가 SKU 업무 만들기 ↗</Link></form></details>
    {!['draft','completed'].includes(t.data.status)&&<details className={s.details}><summary>보류·취소·재개</summary><label className={s.field}>상태 변경 사유<textarea value={stateReason} onChange={e=>setStateReason(e.target.value)} maxLength={2000}/></label><div className={s.actions}>{(['hold','cancel','resume'] as const).map((c,i)=><button className="button subtle" key={c} disabled={command.busy||!stateReason.trim()} onClick={()=>perform(c,{reason:stateReason})}>{['보류','취소','재개'][i]}</button>)}</div></details>}</section>}</div>;
}
