"use client";
import Link from "next/link";
import {SubmissionProgress} from "@/features/submissions/views";
import { useState } from "react";
import type { TaskCatalog } from "@/server/tasks/service";
import { categoryLabels,taskLabels } from "@/components/workspace";
import s from "./ui.module.css";
export function TaskCatalogView({ catalog, contextId }: {catalog:TaskCatalog;contextId:string}) {
    const [category,setCategory]=useState("all"),[mine,setMine]=useState(false),[keyword,setKeyword]=useState(""),[view,setView]=useState("list"),[status,setStatus]=useState("all");
    const tasks=catalog.tasks.filter(t=>(category==="all"||t.data.category===category)&&(!mine||t.data.assigneeId===catalog.userId||t.data.ownerId===catalog.userId||t.data.coAssigneeIds.includes(catalog.userId))&&(status==="all"||t.data.status===status)&&`${t.data.title} ${t.data.description}`.toLocaleLowerCase().includes(keyword.toLocaleLowerCase()));
    const cards=(items:typeof tasks)=>items.map(t=><Link key={t.id} className={s.card} href={`/tasks/${t.id}?context=${contextId}`}><div className={s.row}><span className={s.badge}>{categoryLabels[t.data.category]}</span><span className="badge">{taskLabels[t.data.status]}</span>{t.data.assignmentNeedsAttention&&<span className={s.required}>재배정 필요</span>}</div><h3>{t.data.title} ↗</h3><SubmissionProgress value={t.data.submissionSummary}/><p>{t.data.nextAction}</p>{t.data.notes.length>0&&<ul>{t.data.notes.map((note,index)=><li key={index}>{note}</li>)}</ul>}<div className={s.small}>브랜드 {catalog.members.find(m=>m.id===t.data.assigneeId)?.name??"담당자 확인 필요"}{t.data.coAssigneeIds.map(id=>` · 공동 ${catalog.members.find(m=>m.id===id)?.name??"담당자 확인 필요"}`).join("")} · GSG {catalog.members.find(m=>m.id===t.data.ownerId)?.name??"담당자 확인 필요"} · {t.data.deadline??"기한 미정"}</div><p className={s.small}>관련 상품: {t.data.productIds.map(id=>catalog.products.find(p=>p.id===id)?.name??"현재 열람 가능 상품 확인 필요").join(", ")||"연결 없음"}</p>{t.data.schemaVersion!==2&&<span className={s.small}>기존 합성 미리보기 · 읽기 전용</span>}</Link>);
    return <div className={s.stack}><header className={s.heading}><div><p className="eyebrow">WORK, CONNECTED</p><h1>업무</h1><p>요청, 담당자, 기한과 다음 행동을 함께 확인하세요.</p></div>{catalog.canManage&&<div className={s.row}><Link className="button" href={`/tasks/new?context=${contextId}`}>업무 만들기</Link><Link className="button subtle" href={`/projects?context=${contextId}`}>신규 입점 프로젝트</Link><Link className="button subtle" href={`/tasks/templates?context=${contextId}`}>요청 템플릿</Link></div>}</header>
    <section className={s.panel} aria-label="업무 필터"><div className={s.toolbar}><label className={s.field}>업무 검색<input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="제목 또는 요청 내용"/></label><label className={s.field}>최상위 분류<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">전체</option><option value="onboarding">신규 입점</option><option value="spot">스팟 업무</option></select></label><label className={s.field}>진행 상태<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">전체 상태</option>{Object.entries(taskLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className={s.check}><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/>내 업무만</label></div></section>
    <div className={s.row}><span className={s.small}>{tasks.length}개 업무</span><button className="button subtle" aria-pressed={view==="list"} onClick={()=>setView("list")}>목록</button><button className="button subtle" aria-pressed={view==="kanban"} onClick={()=>setView("kanban")}>칸반</button></div>
    {!tasks.length?<div className={s.empty}>{catalog.tasks.length?<p>조건에 맞는 업무가 없습니다. 필터를 변경해 보세요.</p>:<><h2>아직 등록된 업무가 없습니다</h2><p>{catalog.canManage?"첫 업무를 만들어 요청과 담당자를 연결하세요.":"공개된 업무가 생기면 이곳에서 요청과 기한을 확인할 수 있습니다."}</p>{catalog.canManage&&<Link className="button" href={`/tasks/new?context=${contextId}`}>첫 업무 만들기</Link>}</>}</div>:view==="list"?<div className={s.list}>{cards(tasks)}</div>:<div className={s.kanban}>{Object.entries(taskLabels).map(([k,l])=><section className={s.column} key={k}><h2>{l} · {tasks.filter(t=>t.data.status===k).length}</h2><div className={s.list}>{cards(tasks.filter(t=>t.data.status===k))}</div></section>)}</div>}</div>;
}
