"use client";
import Link from "next/link";
import { useState } from "react";
import type { TaskCatalog } from "@/server/tasks/service";
import { blankContent } from "@/domain/tasks/types";
import { ContentEditor } from "./content-editor";
import { request,useCommand } from "./client";
import s from "./ui.module.css";
type Impact={targets:{id:string;title:string;currentVersionId:string|null;addedKeys:string[];changedKeys:string[]}[]};
export function Templates({initial,contextId}:{initial:TaskCatalog;contextId:string}) {
    const [catalog,setCatalog]=useState(initial),[previousId,setPreviousId]=useState(""),[name,setName]=useState(""),[content,setContent]=useState(()=>({...blankContent(),deadline:{...blankContent().deadline,responsibleUserId:initial.members.find(m=>m.role==="gsg")?.id??""}}));
    const [versionId,setVersionId]=useState(""),[selected,setSelected]=useState<string[]>([]),[impact,setImpact]=useState<Impact|null>(null),[previewing,setPreviewing]=useState(false);const command=useCommand();
    async function refresh(){setCatalog(await request<TaskCatalog>(`/api/tasks?context=${contextId}`));}
    const targets=catalog.tasks.filter(t=>selected.includes(t.id)).map(t=>({id:t.id,expectedRevision:t.revision}));
    async function preview(){setPreviewing(true);command.setError("");try{setImpact(await request<Impact>("/api/templates",{command:"preview_apply",contextId,versionId,targets}));}catch(e){command.setError(e instanceof Error?e.message:"변경 영향을 확인하지 못했습니다.");}finally{setPreviewing(false);}}
    if(!catalog.canManage)return <div className={s.empty}>템플릿 관리는 GSG 담당자에게 문의해 주세요.</div>;
    return <div className={s.stack}><Link className="back-link" href={`/tasks?context=${contextId}`}>← 업무 목록</Link><header><p className="eyebrow">REQUEST LIBRARY</p><h1>요청 템플릿</h1><p>양식을 버전으로 보존하고, 적용할 업무를 직접 선택합니다.</p></header>{command.error&&<p role="alert" className={s.error}>{command.error}</p>}{command.message&&<p role="status" className={s.success}>{command.message}</p>}
    <details className={`${s.panel} ${s.details}`} open><summary>템플릿 새 버전 작성</summary><form className={s.stack} onSubmit={e=>{e.preventDefault();void command.run<{ids:string[]}>("/api/templates",{command:"save",contextId,name,previousId:previousId||null,content},async r=>{await refresh();setPreviousId(r.ids[0]);setVersionId(r.ids[0]);setImpact(null);},"템플릿 버전을 저장했습니다. 기존 업무는 자동 변경되지 않습니다.");}}><fieldset disabled={command.busy} className={s.stack} style={{border:0,padding:0,margin:0}}><div className={s.grid}><label className={s.field}>기준 템플릿<select value={previousId} onChange={e=>{setPreviousId(e.target.value);const t=catalog.templates.find(x=>x.id===e.target.value);if(t){setName(t.name);setContent({...structuredClone(t.content),deadline:{...t.content.deadline,responsibleUserId:t.content.deadline.responsibleUserId||catalog.members.find(m=>m.role==="gsg")?.id||""}});}}}><option value="">새 양식</option>{catalog.templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.sequence}{t.builtin?" · 기본":""}</option>)}</select></label><label className={s.field}>템플릿 이름<input required value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label></div><p className={s.hint}>공용 템플릿은 파일·특정 상품을 지정하지 않습니다. 각 업무 초안에서 연결할 수 있습니다.</p><ContentEditor value={content} onChange={setContent} members={catalog.members} products={[]}/><button className="button" disabled={command.busy}>{command.busy?"저장 중…":"템플릿 버전 저장"}</button></fieldset></form></details>
    <section className={s.panel}><h2>기존 업무에 선택 적용</h2><p className={s.hint}>선택한 템플릿의 요청 내용·기한을 새 공개 버전으로 적용합니다. 기존 답변과 이전 요청은 보존됩니다. 선택하지 않은 업무는 바뀌지 않습니다.</p><div className={s.stack}><label className={s.field}>적용할 템플릿 버전<select value={versionId} onChange={e=>{setVersionId(e.target.value);setImpact(null);}}><option value="">선택</option>{catalog.templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.sequence}</option>)}</select></label><fieldset className={s.sub}><legend>변경할 공개 업무</legend>{catalog.tasks.filter(t=>t.data.schemaVersion===2&&t.data.currentRequestId&&!['completed','cancelled'].includes(t.data.status)).map(t=><label className={s.check} key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>{setSelected(v=>e.target.checked?[...v,t.id]:v.filter(id=>id!==t.id));setImpact(null);}}/>{t.data.title} · 저장 버전 {t.revision}</label>)}</fieldset><button type="button" className="button subtle" disabled={!versionId||!selected.length||previewing||command.busy} onClick={preview}>{previewing?"확인 중…":"선택 업무 변경 영향 확인"}</button>
    {impact&&<div className={s.stack}>{impact.targets.map(t=><article className={s.sub} key={t.id}><h3>{t.title}</h3><p>추가 항목: {t.addedKeys.map(k=>catalog.templates.find(x=>x.id===versionId)?.content.requirements.find(q=>q.key===k)?.label??k).join(", ")||"없음"}</p><p>변경 항목: {t.changedKeys.map(k=>catalog.templates.find(x=>x.id===versionId)?.content.requirements.find(q=>q.key===k)?.label??k).join(", ")||"없음"}</p></article>)}<button className="button" disabled={command.busy} onClick={()=>void command.run("/api/templates",{command:"apply",contextId,versionId,targets},async()=>{await refresh();setImpact(null);setSelected([]);},"선택한 업무만 새 요청 버전으로 공개했습니다.")}>선택 {impact.targets.length}개 업무에 변경 적용·공개</button></div>}</div></section></div>;
}
