import { storedId,storedCount,storedDate } from './stored';
import type { Clock, UnitOfWork, StoredRecord } from '@/domain/records';
import type { Principal } from '@/server/auth/service';
import { AuthError, fail } from '@/server/auth/errors';
import { userLabel } from '@/server/submissions/access';
import { resolveInput,resolveVersion } from './access';
import { sourceIdentities } from './sources';
import { readSnapshot } from './snapshot';
import { commonDTO,contextDTO } from '@/server/products/projection';
import { readProductUse } from '@/server/products/capture';
import { provenance } from './provenance';
export const runLimits={concurrent:2,queued:16,attempts:3,leaseMs:90000} as const;
export const transientIssues=new Set(['WORKER_TIMEOUT','WORKER_MEMORY','WORKER_UNAVAILABLE','WORKER_FAILED','STORAGE_UNAVAILABLE','INTERRUPTED']);
const runIssues=new Set(['SCOPE_UNKNOWN','OUT_OF_SCOPE','INVALID_INPUT','EMPTY_INPUT','SIZE_LIMIT','PAGE_LIMIT','IMAGE_LIMIT','TYPE_MISMATCH','SOURCE_CHANGED','PDF_LOCKED','PDF_CORRUPT','INVALID_SELECTION','IMAGE_CORRUPT','RESOLUTION_LIMIT','NO_TEXT','LOW_CONTRAST','LOW_CONFIDENCE','OCR_COVERAGE_UNKNOWN','TEXT_LAYER_UNCERTAIN','WORKER_TIMEOUT','WORKER_MEMORY','WORKER_UNAVAILABLE','WORKER_FAILED','TOKEN_LIMIT','STORAGE_UNAVAILABLE','INTERRUPTED','ACCESS_CHANGED']);
export function runDTO(s:UnitOfWork,row:StoredRecord<'aiRun'>,clock:Clock){const d=row.data;storedId(d.versionId);storedCount(d.attempt);if(d.startedAt!==null)storedDate(d.startedAt);if(d.endedAt!==null)storedDate(d.endedAt);if(d.leaseUntil!==null)storedDate(d.leaseUntil);if(d.issue!==null&&!runIssues.has(d.issue))fail('STORAGE_UNAVAILABLE',503,'추출 실행 상태를 확인할 수 없습니다.');if(!['queued','reading','finished','unread','rejected','out_of_scope','failed'].includes(d.state))fail('STORAGE_UNAVAILABLE',503,'추출 실행 상태를 확인할 수 없습니다.');const interrupted=d.state==='reading'&&!!d.leaseUntil&&d.leaseUntil<=clock(),snap=d.snapshotId?s.get('aiSnapshot',d.snapshotId):null;if(d.snapshotId&&(!snap||snap.data.runId!==row.id||snap.data.versionId!==d.versionId))fail('STORAGE_UNAVAILABLE',503,'추출 결과를 확인할 수 없습니다.');return{id:row.id,versionId:d.versionId,attempt:d.attempt,state:interrupted?'interrupted' as const:d.state,issue:interrupted?'INTERRUPTED':d.issue,startedAt:d.startedAt,endedAt:d.endedAt,leaseUntil:d.leaseUntil,createdAt:row.createdAt,retryable:d.attempt<runLimits.attempts&&(interrupted||!!d.issue&&transientIssues.has(d.issue)),snapshot:snap?readSnapshot(snap.data.payload,snap.data.snapshotHash):null};}
export function inputDetail(s:UnitOfWork,p:Principal,inputId:string,clock:Clock,versionId?:string){const input=resolveInput(s,p,inputId,clock);const selected=versionId??input.data.currentVersionId;if(!selected)fail('STORAGE_UNAVAILABLE',503,'입력 버전을 확인할 수 없습니다.');const{version,content}=resolveVersion(s,p,inputId,selected,clock),sources=sourceIdentities(s,version,content).map((source,index)=>({...source,provenance:provenance(source.sha256),url:content.kind==='text'?null:`/api/ai-input/${input.id}/sources/${index}?versionId=${version.id}`}));
 const history=s.list('aiVersion',input.contextId!).filter(v=>v.data.inputId===input.id).flatMap(v=>{try{const r=resolveVersion(s,p,inputId,v.id,clock);return[{id:v.id,sequence:v.data.sequence,title:r.content.title,createdAt:v.createdAt,creatorLabel:userLabel(s,p,input.contextId!,v.data.createdBy),contentHash:v.data.contentHash}];}catch(e){if(e instanceof AuthError&&[403,404].includes(e.status))return[];throw e;}}).sort((a,b)=>b.sequence-a.sequence);
 const productVersions=content.products.map(ref=>({productId:ref.productId,productVersionId:ref.productVersionId,contextProductVersionId:ref.contextProductVersionId,common:commonDTO(s.get('productVersion',ref.productVersionId)!.data.common),local:contextDTO(s.get('contextProductVersion',ref.contextProductVersionId)!.data.fields)}));
 const submission=content.submission?{taskId:content.submission.taskId,taskTitle:s.get('task',content.submission.taskId)!.data.title,requestId:content.submission.requestId,requestSequence:s.get('requestVersion',content.submission.requestId)!.data.sequence,submissionId:content.submission.submissionId,submissionSequence:s.get('submission',content.submission.submissionId)!.data.sequence,products:content.submission.productUseIds.map(useId=>{const u=readProductUse(s,p,useId,clock);return{id:u.id,productId:u.productId,productVersionId:u.productVersionId,contextProductVersionId:u.contextProductVersionId,common:u.common,local:u.context};})}:null;
 const runs=s.list('aiRun',input.contextId!).filter(v=>v.data.versionId===version.id).sort((a,b)=>b.data.attempt-a.data.attempt).map(v=>runDTO(s,v,clock));
 for(const run of runs)if(run.snapshot&&JSON.stringify(run.snapshot.sources)!==JSON.stringify(sources.map(({sourceId,versionId,contextId,sha256})=>({sourceId,versionId,contextId,sha256}))))fail('STORAGE_UNAVAILABLE',503,'추출 원본과 저장된 결과가 일치하지 않습니다.');
 return{id:input.id,contextId:input.contextId!,revision:input.revision,visibility:input.data.visibility,currentVersionId:input.data.currentVersionId,createdAt:input.createdAt,creatorLabel:userLabel(s,p,input.contextId!,input.data.createdBy),version:{id:version.id,sequence:version.data.sequence,previousId:version.data.previousId,contentHash:version.data.contentHash,createdAt:version.createdAt,content},sources,productVersions,submission,history,runs,capabilities:{revise:input.data.createdBy===p.user.id||p.user.data.role==='gsg',extract:true,createInternal:p.user.data.role==='gsg'},limits:runLimits,analysis:{connected:true as const,status:p.user.data.role==='gsg'?'GSG_INTERNAL' as const:'RESTRICTED' as const,url:p.user.data.role==='gsg'?`/ai-review/inputs/${input.id}?context=${input.contextId}&versionId=${version.id}`:null,providerCalled:false as const},transfer:{requiresFreshCheck:true as const,provenanceEligible:sources.every(s=>s.provenance==='synthetic'),reason:sources.every(s=>s.provenance==='synthetic')?'FRESH_PERMISSION_AND_HASH_REQUIRED':'EXTERNAL_USE_DENIED'}};
}
export type AiInputDetail=ReturnType<typeof inputDetail>;
