"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { TaskCatalog,TaskService } from "@/server/tasks/service";
import { TargetEditor,initialTarget,Checks } from "@/features/tasks/target-editor";
import { request,useCommand } from "@/features/tasks/client";
import { taskLabels } from "@/components/workspace";
import s from "@/features/tasks/ui.module.css";
export type ProjectDetail=Awaited<ReturnType<TaskService["project"]>>;
export function Projects({catalog,contextId}:{catalog:TaskCatalog;contextId:string}) {
    const router=useRouter(),command=useCommand();const [title,setTitle]=useState(""),[target,setTarget]=useState(()=>initialTarget(contextId,catalog)),[templateIds,setTemplateIds]=useState<string[]>([]);
    return <div className={s.stack}><header className={s.heading}><div><p className="eyebrow">LAUNCH PROJECTS</p><h1>신규 입점 프로젝트</h1><p>필요한 작업만 선택하고, 병렬 진행과 선행 관계를 관리하세요.</p></div><Link className="button subtle" href={`/tasks?context=${contextId}`}>업무 목록</Link></header>
    <section className={s.list} aria-label="프로젝트 목록">{catalog.projects.length?catalog.projects.map(p=><Link key={p.id} href={`/projects/${p.id}?context=${contextId}`} className={s.card}><h2>{p.title} ↗</h2><span className="badge">{p.status==="active"?"진행 중":"프로젝트 완료"}</span></Link>):<div className={s.empty}>아직 입점 프로젝트가 없습니다.</div>}</section>
    {catalog.canManage&&<section className={s.panel}><h2>새 입점 프로젝트</h2><form className={s.stack} onSubmit={e=>{e.preventDefault();void command.run<{ids:string[]}>("/api/projects",{mode:"publish",title,target,templateVersionIds:templateIds},r=>router.push(`/projects/${r.ids[0]}?context=${contextId}&registered=1`),"프로젝트를 저장하고 브랜드에 요청을 전달했습니다.");}}><fieldset disabled={command.busy} className={s.stack} style={{border:0,padding:0,margin:0}}><label className={s.field}>프로젝트 이름<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></label><TargetEditor value={target} onChange={setTarget} catalog={catalog}/><Checks label="필요한 업무 선택" options={catalog.templates.map(t=>({id:t.id,name:`${t.name} · v${t.sequence}`}))} value={templateIds} onChange={setTemplateIds}/><p className={s.hint}>저장하면 선택한 모든 업무의 요청이 브랜드에 바로 전달됩니다. 담당·기한은 각 업무에서 바꿀 수 있고, 선행 관계가 없는 업무는 병렬입니다.</p><button className="button" disabled={command.busy||!templateIds.length}>{command.busy?"만드는 중…":"프로젝트와 업무 등록"}</button></fieldset>{command.error&&<p role="alert" className={s.error}>{command.error}</p>}</form></section>}</div>;
}
export function Project({initial,catalog}:{initial:ProjectDetail;catalog:TaskCatalog}) {
    const search=useSearchParams();
    const [project,setProject]=useState(initial),[edges,setEdges]=useState(initial.data.dependencies),[before,setBefore]=useState(""),[after,setAfter]=useState("");const command=useCommand();
    async function refresh(){const fresh=await request<ProjectDetail>(`/api/projects/${project.id}`);setProject(fresh);return fresh;}
    return <div className={s.stack}><Link className="back-link" href={`/projects?context=${project.contextId}`}>← 입점 프로젝트</Link><header className={s.heading}><div><p className="eyebrow">ONBOARDING</p><h1>{project.data.title}</h1><span className="badge">{project.data.status==="active"?"프로젝트 진행 중":"프로젝트 완료"}</span></div>{project.canManage&&<Link className="button" href={`/tasks/new?context=${project.contextId}&project=${project.id}`}>업무·추가 SKU 연결</Link>}</header><p className={s.notice}>개별 업무의 완료와 프로젝트 완료는 별개입니다. 선행 관계가 없는 업무는 병렬로 진행합니다.</p>
    {project.canManage&&search.get("registered")==="1"&&<p role="status" className={s.success}>프로젝트와 업무를 저장했습니다. 브랜드에 요청 전달을 완료했습니다.</p>}
    <section className={s.list} aria-label="프로젝트 업무 타임라인">{project.tasks.map(t=><Link className={s.card} key={t.id} href={`/tasks/${t.id}?context=${project.contextId}`}><div className={s.row}><h3>{t.data.title} ↗</h3><span className="badge">{taskLabels[t.data.status]}</span></div><p>{t.data.nextAction}</p><p className={s.small}>브랜드 {catalog.members.find(m=>m.id===t.data.assigneeId)?.name??"담당자 확인 필요"}{t.data.coAssigneeIds.map(id=>` · 공동 ${catalog.members.find(m=>m.id===id)?.name??"담당자 확인 필요"}`).join("")} · GSG {catalog.members.find(m=>m.id===t.data.ownerId)?.name??"담당자 확인 필요"} · {t.data.deadline??"기한 미정"}</p><p className={s.small}>관련 상품: {t.data.productIds.map(id=>catalog.products.find(p=>p.id===id)?.name??"현재 열람 가능 상품 확인 필요").join(", ")||"연결 없음"}</p><p className={s.small}>선행 업무: {project.data.dependencies.filter(e=>e.after===t.id).map(e=>project.tasks.find(x=>x.id===e.before)?.data.title??"업무").join(", ")||"없음 · 병렬 가능"}</p></Link>)}</section>
    {project.canManage&&<section className={s.panel}><h2>선행 관계 편집</h2><p className={s.hint}>관계가 있는 작업만 연결하세요. 자기 참조·순환·다른 프로젝트 연결은 서버에서 거부합니다.</p><div className={s.grid}><label className={s.field}>먼저 진행할 업무<select value={before} onChange={e=>setBefore(e.target.value)}><option value="">선택</option>{project.tasks.map(t=><option key={t.id} value={t.id}>{t.data.title}</option>)}</select></label><label className={s.field}>다음 업무<select value={after} onChange={e=>setAfter(e.target.value)}><option value="">선택</option>{project.tasks.map(t=><option key={t.id} value={t.id}>{t.data.title}</option>)}</select></label></div><div className={s.actions}><button className="button subtle" disabled={!before||!after} onClick={()=>{setEdges(v=>[...v,{before,after}]);setBefore("");setAfter("");}}>관계 추가</button></div><ul className={s.history}>{edges.map((e,i)=><li key={i}>{project.tasks.find(t=>t.id===e.before)?.data.title} → {project.tasks.find(t=>t.id===e.after)?.data.title} <button className="button subtle" onClick={()=>setEdges(v=>v.filter((_,n)=>n!==i))}>관계 삭제</button></li>)}</ul><button className="button" disabled={command.busy} onClick={()=>void command.run(`/api/projects/${project.id}`,{expectedRevision:project.revision,dependencies:edges},async()=>{const fresh=await refresh();setEdges(fresh.data.dependencies);},"선행 관계를 저장했습니다.")}>선행 관계 저장</button>{command.error&&<div role="alert" className={s.error}>{command.error}<button className="button subtle" onClick={()=>void refresh().catch(e=>command.setError(e instanceof Error?e.message:"다시 불러오지 못했습니다."))}>최신 버전 확인 · 관계 입력 유지</button></div>}{command.message&&<p role="status" className={s.success}>{command.message}</p>}</section>}</div>;
}
