'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import type {NoticeDetail,NoticeContent} from '@/server/notices/contracts';
import type {TaskCatalog} from '@/server/tasks/service';
import {request,RequestError} from '@/features/tasks/client';
import {CreateTask} from '@/features/tasks/create';
import {NoticeFields} from './fields';
import {PublicNotice,time,type PublicContent} from './views';
import {clearRecovery,readRecovery,recoveryKey,saveRecovery,clearNoticeRecovery,type Recovery} from './recovery';
import s from './ui.module.css';
type Upload={key:string;file:File;visibility:'public'|'internal';state:'ready'|'working'|'done'|'failed';message:string};
type Managed=Extract<NoticeDetail,{draft:NoticeContent}>;
function managed(d:NoticeDetail):d is Managed{return 'draft' in d&&!!d.draft;}
export function NoticeScreen({id,contextId}:{id:string;contextId:string}){
 const search=useSearchParams(),versions=search.getAll('version'),versionQuery=versions.map(v=>`version=${encodeURIComponent(v)}`).join('&'),url=`/api/notices/${encodeURIComponent(id)}${versionQuery?'?'+versionQuery:''}`;
 const [data,setData]=useState<NoticeDetail|null>(null),[loadedUrl,setLoadedUrl]=useState(''),[content,setContent]=useState<NoticeContent|null>(null),[revision,setRevision]=useState(0),[catalog,setCatalog]=useState<TaskCatalog|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[needsRefresh,setNeedsRefresh]=useState(false),[conflict,setConflict]=useState<NoticeDetail|null>(null),[preview,setPreview]=useState<PublicContent|null>(null),[recovery,setRecovery]=useState<Recovery|null>(null),[pendingTasks,setPendingTasks]=useState<string[]>([]),[creating,setCreating]=useState(false),[uploads,setUploads]=useState<Upload[]>([]),[visibility,setVisibility]=useState<'public'|'internal'>('public');
 const lock=useRef(false),key=useRef(''),initialized=useRef(false),intent=useRef<Recovery['intent']>(null),generation=useRef(0),currentUrl=useRef(url),live=useRef(true),local=useRef<{content:NoticeContent|null;revision:number;pendingTasks:string[]}>({content:null,revision:0,pendingTasks:[]});
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const persist=useCallback((c:NoticeContent,r:number,t:string[])=>{local.current={content:c,revision:r,pendingTasks:t};if(key.current)saveRecovery(key.current,{content:c,revision:r,pendingTasks:t,intent:intent.current,at:Date.now()});},[]);
 const deny=useCallback(()=>{generation.current++;clearNoticeRecovery(contextId,id);if(key.current)clearRecovery(key.current);key.current='';initialized.current=false;intent.current=null;local.current={content:null,revision:0,pendingTasks:[]};setBlocked(true);setData(null);setContent(null);setCatalog(null);setPreview(null);setConflict(null);setRecovery(null);setPendingTasks([]);setUploads([]);setCreating(false);setMessage('');},[contextId,id]);
 const failure=useCallback((e:unknown)=>{if(e instanceof RequestError&&[401,403,404].includes(e.status))deny();setError(e instanceof Error?e.message:'연결을 확인하지 못했습니다. 입력은 유지됩니다.');},[deny]);
 const fetchDetail=useCallback(async(target:string)=>{const d=await request<NoticeDetail>(target);if(d.context.id!==contextId)throw new RequestError('이 컨텍스트에서 공지를 찾을 수 없습니다.',404,'NOT_FOUND');return d;},[contextId]);
 useEffect(()=>{let active=true;const turn=++generation.current;currentUrl.current=url;fetchDetail(url).then(d=>{if(!active||!live.current||turn!==generation.current)return;setData(d);setLoadedUrl(url);setError('');setBlocked(false);if(managed(d)&&!initialized.current){initialized.current=true;key.current=recoveryKey(d.actorId,contextId,id);const stored=readRecovery(key.current);setContent(d.draft);setRevision(d.revision);local.current={content:d.draft,revision:d.revision,pendingTasks:[]};if(stored&&(JSON.stringify(stored.content)!==JSON.stringify(d.draft)||stored.pendingTasks.length||stored.intent))setRecovery(stored);else clearRecovery(key.current);request<TaskCatalog>(`/api/tasks?context=${encodeURIComponent(contextId)}`).then(c=>{if(live.current&&turn===generation.current)setCatalog(c);}).catch(failure);}}).catch(e=>{if(active&&live.current&&turn===generation.current){setLoadedUrl(url);setData(null);failure(e);}});return()=>{active=false;};},[url,contextId,id,fetchDetail,failure]);
 function edit(c:NoticeContent){setContent(c);setPreview(null);persist(c,revision,pendingTasks);}
 async function reload(){if(blocked){window.location.reload();return;}setError('');const target=currentUrl.current,turn=generation.current;try{const d=await fetchDetail(target);if(!live.current||turn!==generation.current||target!==currentUrl.current)return;setData(d);setLoadedUrl(target);setNeedsRefresh(false);setBlocked(false);if(managed(d)&&local.current.content){if(d.revision!==local.current.revision&&!needsRefresh)setConflict(d);else{setRevision(d.revision);persist(local.current.content,d.revision,local.current.pendingTasks);}}}catch(e){failure(e);}}
 async function run(body:Record<string,unknown>,success:string,onSaved?:()=>void){if(lock.current||blocked||needsRefresh||recovery)return;lock.current=true;setBusy(true);setError('');setMessage('');const fingerprint=JSON.stringify(body);if(intent.current?.fingerprint!==fingerprint)intent.current={fingerprint,key:crypto.randomUUID()};if(local.current.content)persist(local.current.content,local.current.revision,local.current.pendingTasks);try{await request(`/api/notices/${id}`,{...body,idempotencyKey:intent.current.key});intent.current=null;onSaved?.();setMessage(success);if(body.command!=='read')setPreview(null);if(local.current.content)persist(local.current.content,local.current.revision,local.current.pendingTasks);try{const target=currentUrl.current,turn=generation.current;const fresh=await fetchDetail(target);if(!live.current||turn!==generation.current||target!==currentUrl.current)return;setData(fresh);setLoadedUrl(target);if(managed(fresh)){setRevision(fresh.revision);if(local.current.content)persist(local.current.content,fresh.revision,local.current.pendingTasks);}setConflict(null);}catch(e){setNeedsRefresh(true);failure(e);}}catch(e){failure(e);if(e instanceof RequestError&&e.status===409){intent.current=null;try{setConflict(await fetchDetail(`/api/notices/${id}`));}catch(other){failure(other);}}}finally{lock.current=false;setBusy(false);}}
 async function save(c=content,linkIds:string[]=[]){if(!c)return;await run({command:'save',content:c,expectedRevision:revision},linkIds.length?'이미 만든 업무를 공지 초안에 연결했습니다. 공개하려면 공지를 다시 게시하세요.':'초안을 저장했습니다. 공개본은 바뀌지 않았습니다.',()=>{if(linkIds.length){const remaining=local.current.pendingTasks.filter(t=>!linkIds.includes(t));setPendingTasks(remaining);persist(c,local.current.revision,remaining);}});}
 async function created(result:{ids:string[]}){const c=local.current.content;if(!c)return;const pending=Array.from(new Set([...local.current.pendingTasks,...result.ids])),next={...c,taskIds:Array.from(new Set([...c.taskIds,...result.ids]))};setPendingTasks(pending);setContent(next);persist(next,local.current.revision,pending);setCreating(false);setMessage('업무 초안을 만들었습니다. 공지 연결을 확인하는 중입니다.');try{const cat=await request<TaskCatalog>(`/api/tasks?context=${contextId}`);setCatalog(cat);}catch(e){failure(e);return;}await save(next,result.ids);}
 async function upload(item:Upload){if(lock.current||blocked)return;lock.current=true;setBusy(true);setError('');setUploads(v=>v.map(x=>x.key===item.key?{...x,state:'working',message:''}:x));try{const form=new FormData();form.append('files',item.file);form.append('visibility',item.visibility);const r=await request<{files:{id:string}[]}>(`/api/files?noticeId=${id}`,form);if(local.current.content){const next={...local.current.content,fileIds:Array.from(new Set([...local.current.content.fileIds,...r.files.map(f=>f.id)]))};setContent(next);persist(next,local.current.revision,local.current.pendingTasks);}setUploads(v=>v.map(x=>x.key===item.key?{...x,state:'done',message:'업로드됨 · 공지 저장·공개는 별도'}:x));try{const target=currentUrl.current,turn=generation.current;const fresh=await fetchDetail(target);if(!live.current||turn!==generation.current||target!==currentUrl.current)return;setData(fresh);setLoadedUrl(target);}catch(e){failure(e);setMessage('파일 업로드는 완료됐습니다. 파일 목록만 새로 확인해 주세요.');}}catch(e){failure(e);setUploads(v=>v.map(x=>x.key===item.key?{...x,state:'failed',message:e instanceof Error?e.message:'업로드 실패'}:x));}finally{lock.current=false;setBusy(false);}}
 const ready=data&&loadedUrl===url&&!blocked;const d=ready?data:null,admin=d&&managed(d)?d:null;const dirty=!!(admin&&content&&JSON.stringify(content)!==JSON.stringify(admin.draft));
 return <div className={s.stack}><Link href={`/notices?context=${contextId}`}>← 공지·가이드</Link><header className={s.heading}><div><p className="eyebrow">NOTICE & GUIDE</p><h1>{d?.selected?.content.title||admin?.draft.title||'공지 상세'}</h1><p className={s.meta}>정보 확인과 업무 수행을 구분해 관리합니다.</p></div><button className="button subtle" disabled={busy} onClick={()=>void reload()}>서버에서 새로 확인</button></header>{error&&<p role="alert" className={s.error}>{error}{blocked?' 보호된 내용과 복구 기록을 비웠습니다. 새 권한을 확인한 뒤 다시 열어 주세요.':''}</p>}{message&&<p role="status" className={s.notice}>{message}</p>}{needsRefresh&&!blocked&&<div className={s.notice}>변경은 저장됐지만 화면을 다시 읽지 못했습니다. 같은 변경을 보내지 말고 새로 확인해 주세요.<button className="button subtle" onClick={()=>void reload()}>저장 결과 다시 읽기</button></div>}{!d&&!error&&<p role="status">정확한 공지 버전과 현재 권한을 확인하는 중…</p>}
 {d&&<><section className={s.panel}><div className={s.heading}><h2>{d.selected?`공개본 v${d.selected.sequence}${d.selected.id===d.currentVersionId?' · 현재':' · 과거 이력'}`:'아직 공개되지 않은 초안'}</h2>{d.selected&&<span className={s.badge}>{d.selected.ownReadAt?'이 버전 확인함':'이 버전 미읽음'}</span>}</div>{d.selected?<><p className={s.meta}>게시 {time(d.selected.publishedAt)} · {d.selected.authorLabel}</p><PublicNotice content={d.selected.content}/><div className={s.actions}><button className="button" disabled={busy||!!d.selected.ownReadAt||needsRefresh} onClick={()=>void run({command:'read',versionId:d.selected!.id},'선택한 공지 버전의 읽음을 기록했습니다. 업무 상태는 변경하지 않았습니다.')}>{d.selected.ownReadAt?'확인 완료':'이 공지 버전 읽음 확인'}</button><span className={s.meta}>내 확인 시각: {time(d.selected.ownReadAt)}</span></div></>:<p>저장한 초안은 GSG에게만 보입니다. 공개 전 브랜드 보기를 확인하세요.</p>}</section>
 {d.versions.length>0&&<section className={s.panel}><h2>공개본 이력</h2><nav className={s.tabs} aria-label="공지 공개본 이력">{d.versions.map(v=><Link key={v.id} aria-current={v.id===d.selected?.id?'page':undefined} href={`/notices/${id}?context=${contextId}&version=${v.id}`}>v{v.sequence}{v.id===d.currentVersionId?' · 현재':''} · {v.ownReadAt?'확인함':'미읽음'}</Link>)}</nav><p className={s.meta}>각 공개본의 본문·양식·게시·확인 이력은 따로 보존됩니다.</p><details className={s.records}><summary>공지 기록 정보</summary><p>공지 {d.id}</p>{d.selected&&<p>선택 공개본 {d.selected.id} · 원 작성 {time(d.createdAt)} · {d.authorLabel}</p>}</details></section>}
 {admin&&admin.roster&&<section className={s.panel}><h2>선택 공개본의 확인 현황</h2><p>현재 대상 {admin.roster.targetCount}명 · 확인 기록 {admin.roster.reads.length}건</p>{!admin.selected?<p>공개 후 버전별 확인 현황을 볼 수 있습니다.</p>:!admin.roster.targetCount?<p className={s.notice}>현재 확인 대상이 0명입니다. 과거 확인 기록은 보존됩니다.</p>:<ul className={s.roster}>{admin.roster.targets.map(u=><li key={u.id}>{u.name} · {u.readAt?`확인 ${time(u.readAt)}`:'미읽음'}</li>)}</ul>}<details><summary>선택 공개본의 전체 확인 기록</summary>{admin.roster.reads.length?<ul className={s.roster}>{admin.roster.reads.map(u=><li key={u.userId}>{u.name} · {time(u.readAt)}</li>)}</ul>:<p>아직 확인한 사용자가 없습니다.</p>}</details></section>}
 {admin&&content&&<><section className={s.panel}><h2>GSG 초안 편집</h2><p className={s.meta}>위 공개본과 별도로 저장됩니다. {dirty?'저장하지 않은 변경이 있습니다.':'입력 내용이 서버 초안과 같습니다.'}</p>{recovery&&<div className={s.notice}><h3>이 브라우저에 저장한 입력이 있습니다</h3><p>현재 권한을 확인했습니다. 복구 후 서버 초안과 비교해 저장하세요. 파일 자체는 재선택해야 합니다.</p><div className={s.actions}><button className="button" onClick={()=>{setContent(recovery.content);setRevision(recovery.revision);setPendingTasks(recovery.pendingTasks);intent.current=recovery.intent;persist(recovery.content,recovery.revision,recovery.pendingTasks);setRecovery(null);}}>보관된 입력 복구</button><button className="button subtle" onClick={()=>{clearRecovery(key.current);setRecovery(null);}}>서버 초안 사용</button></div></div>}{conflict&&managed(conflict)&&<div className={s.notice}><h3>서버 초안이 변경되었습니다</h3><p>내 입력은 유지했습니다. 아래 서버 내용을 비교한 뒤 저장 기준을 선택하세요.</p><p><strong>{conflict.draft.title||'제목 없음'}</strong></p><p className={s.body}>{conflict.draft.body}</p><p>유형 {conflict.draft.type} · 문서 버전 {conflict.draft.documentVersion||'미지정'} · 파일 {conflict.draft.fileIds.length}개 · 업무 {conflict.draft.taskIds.length}개</p><details><summary>서버 초안의 전체 내용 비교</summary><pre className={s.body}>{JSON.stringify(conflict.draft,null,2)}</pre></details><div className={s.actions}><button className="button" onClick={()=>{setRevision(conflict.revision);persist(content,conflict.revision,pendingTasks);setData(conflict);setConflict(null);setError('');}}>내 입력 유지 · 최신 기준으로 저장 준비</button><button className="button subtle" onClick={()=>{const c=conflict.draft!;setContent(c);setRevision(conflict.revision);persist(c,conflict.revision,pendingTasks);setData(conflict);setConflict(null);setError('');}}>서버 내용으로 편집 교체</button></div></div>}
 <fieldset disabled={busy||needsRefresh||!!recovery||!!conflict} style={{border:0,padding:0,margin:0}} className={s.stack}><NoticeFields value={content} onChange={edit} members={admin.members}/><div className={s.actions}><button className="button" onClick={()=>void save()}>공지 초안 저장</button><button className="button subtle" disabled={dirty} onClick={()=>{setError('');const turn=generation.current;void request<PublicContent>(`/api/notices/${id}?preview=1`).then(p=>{if(live.current&&turn===generation.current)setPreview(p);}).catch(failure);}}>저장된 초안 브랜드 보기</button><button className="button" disabled={dirty} onClick={()=>void run({command:'publish',expectedRevision:revision},'새 공개본을 게시했습니다. 이전 읽음은 새 버전에 승계되지 않습니다.')}>저장된 초안 공개</button></div><p className={s.meta}>미저장 변경이 있으면 먼저 저장하세요. 제목·본문이 있어야 공개할 수 있습니다.</p></fieldset></section>
 {preview&&<section className={s.panel} aria-label="브랜드 보기 미리보기"><h2>브랜드 보기 미리보기</h2><p className={s.notice}>저장된 초안의 공개 내용입니다. 내부 파일과 비공개 업무는 제외합니다. 각 사용자의 파일 원본 권한에 따라 실제 다운로드 가능 여부가 달라집니다.</p><PublicNotice content={preview}/><button className="button subtle" onClick={()=>setPreview(null)}>미리보기 닫기</button></section>}
 <section className={s.panel}><h2>초안 파일</h2><p className={s.meta}>업로드·초안 저장·공개는 별도 단계입니다. 파일당 25MiB, 한 번에 최대 10개를 선택하세요. 공개하려면 내부 파일을 제외해야 합니다.</p><fieldset disabled={busy||needsRefresh||!!recovery||!!conflict} style={{border:0,padding:0}} className={s.stack}><label className={s.field}>업로드 공개 범위<select value={visibility} onChange={e=>setVisibility(e.target.value as 'public'|'internal')}><option value="public">브랜드 공개용</option><option value="internal">GSG 내부 전용</option></select></label><label className={s.field}>공지 파일 선택<input type="file" multiple onChange={e=>{const selected=Array.from(e.target.files??[]);if(selected.length>10){setError('한 번에 파일을 10개 이하로 선택해 주세요.');return;}setUploads(v=>[...v.filter(x=>x.state!=='done'),...selected.map(file=>({key:crypto.randomUUID(),file,visibility,state:'ready' as const,message:''}))]);e.target.value='';}}/></label>{uploads.map(u=><div className={s.item} key={u.key}><p>{u.file.name} · {u.state==='done'?'업로드됨':u.state==='failed'?'실패':u.state==='working'?'업로드 중':'업로드 대기'}</p>{u.message&&<p>{u.message}</p>}<div className={s.actions}>{u.state!=='done'&&<button className="button subtle" onClick={()=>void upload(u)}>{u.state==='failed'?'이 파일 다시 업로드':'이 파일 업로드'}</button>}<button className="button subtle" onClick={()=>setUploads(v=>v.filter(x=>x.key!==u.key))}>대기 목록에서 제외</button></div></div>)}<fieldset className={s.item}><legend>저장할 파일 선택</legend>{admin.files?.length?admin.files.map(f=><div className={s.item} key={f.id}><label className={s.check}><input type="checkbox" checked={content.fileIds.includes(f.id)} onChange={e=>edit({...content,fileIds:e.target.checked?[...content.fileIds,f.id]:content.fileIds.filter(id=>id!==f.id)})}/>{f.name} · {f.visibility==='internal'?'GSG 내부':'공개용'}</label><p className={s.meta}>{f.uploaderLabel} · 업로드 {time(f.uploadedAt)}</p><a href={f.downloadUrl}>원본 다운로드</a></div>):<p>현재 재사용 가능한 파일이 없습니다.</p>}</fieldset></fieldset></section>
 <section className={s.panel}><h2>요청 업무 연결</h2><p>답변·자료·기한이 필요한 일은 업무를 만들고 연결하세요. 공지와 업무는 각각 검토·공개해야 브랜드에 연결이 표시됩니다.</p>{pendingTasks.length>0&&<div className={s.notice}><h3>이미 만든 업무 · 공지 연결 확인 필요</h3><p>업무 생성은 완료됐습니다. 새로 만들지 않고 같은 업무의 연결만 다시 저장합니다.</p>{pendingTasks.map(t=><p key={t}><Link href={`/tasks/${t}?context=${contextId}`}>생성한 업무 열기 ↗</Link><details className={s.records}><summary>업무 기록 정보</summary>{t}</details></p>)}<button className="button" disabled={busy||!!recovery||!!conflict||needsRefresh} onClick={()=>void save({...content,taskIds:Array.from(new Set([...content.taskIds,...pendingTasks]))},pendingTasks)}>이미 만든 업무 연결만 다시 저장</button></div>}{catalog?<><fieldset className={s.item} disabled={busy||!!recovery||needsRefresh}><legend>같은 컨텍스트의 기존 업무</legend>{catalog.tasks.map(t=><div key={t.id} className={s.item}><label className={s.check}><input type="checkbox" checked={content.taskIds.includes(t.id)} onChange={e=>edit({...content,taskIds:e.target.checked?[...content.taskIds,t.id]:content.taskIds.filter(id=>id!==t.id)})}/>{t.data.title}</label><Link href={`/tasks/${t.id}?context=${contextId}`}>업무 상세 · 별도 공개 ↗</Link></div>)}</fieldset><div className={s.actions}><button className="button subtle" disabled={busy||!!recovery||needsRefresh||!!pendingTasks.length} onClick={()=>setCreating(v=>!v)}>{creating?'업무 작성 접기':'이 공지에서 요청 업무 만들기'}</button></div>{creating&&<section className={s.item} aria-label="공지 연결 업무 만들기"><CreateTask catalog={catalog} contextId={contextId} singleContext onCreated={created}/></section>}</>:<p>연결 가능한 업무를 불러오는 중입니다.</p>}</section></>}
 </>}
 </div>;
}
