import Link from 'next/link';
import type { NoticeDetail } from '@/server/notices/contracts';
import { noticeTypeLabels } from '@/domain/notices/types';
import { taskLabels } from '@/components/workspace';
import s from './ui.module.css';
export type PublicContent = NonNullable<NoticeDetail['selected']>['content'];
export function time(value:string|null|undefined){return value ? new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})+' KST':'기록 없음';}
export function NoticeFiles({files}:{files:PublicContent['files']}){return <div className={s.stack}>{files.length?files.map(f=><article key={f.id} className={s.item}><h3>{f.name}</h3><p className={s.meta}>{f.uploaderLabel} · 업로드 {time(f.uploadedAt)} · {f.bytes.toLocaleString()} bytes</p><div className={s.links}><a href={f.downloadUrl}>원본 다운로드</a>{f.previewUrl&&<a href={f.previewUrl} target="_blank" rel="noreferrer">미리보기 ↗</a>}</div><details className={s.records}><summary>파일 기록 정보</summary><p>파일 버전 {f.id}</p><p>SHA256 {f.sha256}</p></details></article>):<p className={s.meta}>첨부된 공개 파일이 없습니다.</p>}</div>;}
export function PublicNotice({content:c}:{content:PublicContent}){return <div className={s.stack}><div><span className={s.badge}>{noticeTypeLabels[c.type]}</span><p className={s.meta}>{c.category||'분류 미지정'} · 문서 버전 {c.documentVersion||'미지정'}</p><h2>{c.title||'제목 없는 초안'}</h2><p className={s.body}>{c.body||'작성된 본문이 없습니다.'}</p>{c.changeSummary&&<p className={s.notice}>변경 안내: {c.changeSummary}</p>}</div><section><h3>가이드·양식 파일</h3><NoticeFiles files={c.files}/></section><section><h3>연결된 공개 업무</h3><p className={s.meta}>공지 확인과 업무의 수락·제출·완료는 별개입니다. 답변과 자료 제출은 해당 업무에서 진행하세요.</p>{c.tasks.length?<div className={s.stack}>{c.tasks.map(t=><article className={s.item} key={t.id}><h3><Link href={t.url}>{t.title} ↗</Link></h3><p>{taskLabels[t.status as keyof typeof taskLabels]??t.status}</p><p className={s.meta}>내 업무 읽음: {time(t.ownReadAt)}<br/>내 작업 수락: {time(t.ownAcceptedAt)}<br/>최근 제출: {time(t.latestSubmittedAt)}<br/>GSG 업무 완료: {t.completed?'완료':'미완료'}</p></article>)}</div>:<p className={s.meta}>현재 조회 가능한 공개 업무가 없습니다.</p>}</section></div>;}
