'use client';
import {useId,type ReactNode} from 'react';
import type {AnswerInput,DateInput,LinkInput,PhysicalInput} from '@/domain/submissions/types';
import type {Requirement} from '@/domain/tasks/types';
import type {SubmissionWorkspace} from '@/server/submissions/contracts';
import s from '@/features/tasks/ui.module.css';
export type FileOption=Pick<SubmissionWorkspace['availableFiles'][number],'id'|'name'>;
export function Field({label,value,onChange,multiline=false,type='text',hint}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;type?:string;hint?:string}){const id=useId();return <div className={s.field}><label htmlFor={id}>{label}</label>{multiline?<textarea id={id} value={value} onChange={e=>onChange(e.target.value)} aria-describedby={hint?id+'-hint':undefined}/>:<input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} aria-describedby={hint?id+'-hint':undefined}/>} {hint&&<span id={id+'-hint'} className={s.hint}>{hint}</span>}</div>;}
export function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:ReactNode}){const id=useId();return <div className={s.field}><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{children}</select></div>;}
export function FileChoices({label,files,value,onChange}:{label:string;files:FileOption[];value:string[];onChange:(v:string[])=>void}){return <fieldset className={s.sub}><legend>{label}</legend>{files.length?files.map(f=><label className={s.check} key={f.id}><input type="checkbox" checked={value.includes(f.id)} onChange={e=>onChange(e.target.checked?[...value,f.id]:value.filter(x=>x!==f.id))}/>{f.name}</label>):<p>선택할 수 있는 파일이 없습니다. 파일을 업로드한 뒤 선택하세요.</p>}{value.filter(id=>!files.some(f=>f.id===id)).map(id=><p key={id} role="alert">다시 확인해야 하는 파일 참조 <button type="button" className="button subtle" onClick={()=>onChange(value.filter(x=>x!==id))}>이 파일 연결 제외</button></p>)}</fieldset>;}
export function DateFields({value:v,onChange:set}:{value:DateInput;onChange:(v:DateInput)=>void}){return <div className={s.grid}><Select label="날짜 정밀도" value={v.precision} onChange={x=>set({...v,precision:x as DateInput['precision']})}><option value="date">날짜</option><option value="datetime">일시</option></Select><Field label={v.precision==='date'?'날짜':'일시 (오프셋 포함)'} value={v.value} onChange={value=>set({...v,value})} type={v.precision==='date'?'date':'text'} hint={v.precision==='datetime'?'예: 2026-09-21T10:00:00+09:00':undefined}/><Field label="시간대" value={v.timezone} onChange={timezone=>set({...v,timezone})}/></div>;}
export function LinkFields({value:v,onChange:set,files}:{value:LinkInput;onChange:(v:LinkInput)=>void;files:FileOption[]}){return <div className={s.stack}><Field label="링크 URL" value={v.url} onChange={url=>set({...v,url})}/><Field label="링크 설명" value={v.description} onChange={description=>set({...v,description})}/><p className={s.hint}>외부 링크·내용 미고정. 확정해서 사용할 자료는 보관 사본이나 고정 버전을 함께 기록하세요.</p><Select label="고정 참조" value={v.fixedReference?.kind??'none'} onChange={kind=>set({...v,fixedReference:kind==='file'?{kind,fileVersionId:''}:kind==='external'?{kind,identifier:'',source:''}:null})}><option value="none">없음 · 내용 미고정</option><option value="file">보관 파일</option><option value="external">외부 버전 식별자</option></Select>{v.fixedReference?.kind==='file'&&<Select label="보관 파일 버전" value={v.fixedReference.fileVersionId} onChange={fileVersionId=>set({...v,fixedReference:{kind:'file',fileVersionId}})}><option value="">파일 선택</option>{files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</Select>}{v.fixedReference?.kind==='external'&&<><Field label="고정 버전 식별자" value={v.fixedReference.identifier} onChange={identifier=>set({...v,fixedReference:{kind:'external',identifier,source:v.fixedReference?.kind==='external'?v.fixedReference.source:''}})}/><Field label="고정 버전 출처" value={v.fixedReference.source} onChange={source=>set({...v,fixedReference:{kind:'external',source,identifier:v.fixedReference?.kind==='external'?v.fixedReference.identifier:''}})}/></>}</div>;}
export function PhysicalFields({value:v,onChange:set,files,products}:{value:PhysicalInput;onChange:(v:PhysicalInput)=>void;files:FileOption[];products:SubmissionWorkspace['products']}){return <div className={s.stack}><Field label="실물 관련 제공 사실" value={v.summary} onChange={summary=>set({...v,summary})} multiline/><Field label="실물 기록 출처" value={v.source} onChange={source=>set({...v,source})}/>{v.items.map((item,i)=><fieldset className={s.sub} key={i}><legend>실물 항목 {i+1}</legend><Select label="대상 상품" value={item.productId??''} onChange={productId=>set({...v,items:v.items.map((x,j)=>j===i?{...x,productId:productId||null}:x)})}><option value="">공통</option>{products.map(p=><option key={p.productId} value={p.productId}>{p.common.name}</option>)}</Select><Field label="수량" value={item.quantity} onChange={quantity=>set({...v,items:v.items.map((x,j)=>j===i?{...x,quantity}:x)})}/><Field label="단위" value={item.unit} onChange={unit=>set({...v,items:v.items.map((x,j)=>j===i?{...x,unit}:x)})}/><button type="button" className="button subtle" onClick={()=>set({...v,items:v.items.filter((_,j)=>j!==i)})}>실물 항목 {i+1} 제외</button></fieldset>)}<button type="button" className="button subtle" onClick={()=>set({...v,items:[...v.items,{productId:null,quantity:'',unit:''}]})}>실물 항목 추가</button><label className={s.check}><input type="checkbox" checked={!!v.observedAt} onChange={e=>set({...v,observedAt:e.target.checked?{value:'',precision:'date',timezone:'Asia/Seoul'}:null})}/>실물 사실 확인 시점 기록</label>{v.observedAt&&<DateFields value={v.observedAt} onChange={observedAt=>set({...v,observedAt})}/>}<FileChoices label="실물 기록 근거 파일" files={files} value={v.evidenceFileVersionIds} onChange={evidenceFileVersionIds=>set({...v,evidenceFileVersionIds})}/><p className={s.hint}>제공된 사실의 기록입니다. 자료 제출이나 송장만으로 실제 수령·승인을 처리하지 않습니다.</p></div>;}
export function AnswerFields({answer:a,onChange:set,requirement:q,files,products}:{answer:AnswerInput;onChange:(v:AnswerInput)=>void;requirement:Requirement;files:FileOption[];products:SubmissionWorkspace['products']}){switch(a.type){case 'short_text':case 'long_text':return <Field label={q.label} value={a.input.text} multiline={a.type==='long_text'} onChange={text=>set({...a,input:{text}})}/>;case 'number':return <Field label={q.label} value={a.input.value} onChange={value=>set({...a,input:{value}})} hint={q.unit?`단위: ${q.unit} · 0과 미입력은 다릅니다.`:'0과 미입력은 다릅니다.'}/>;case 'choice':return <fieldset className={s.sub}><legend>{q.label}</legend>{q.options.map(v=><label className={s.check} key={v}><input type="checkbox" checked={a.input.selected.includes(v)} onChange={e=>set({...a,input:{selected:e.target.checked?[...a.input.selected,v]:a.input.selected.filter(x=>x!==v)}})}/>{v}</label>)}</fieldset>;case 'file':return <FileChoices label={q.label} files={files} value={a.input.fileVersionIds} onChange={fileVersionIds=>set({...a,input:{fileVersionIds}})}/>;case 'date':return <DateFields value={a.input} onChange={input=>set({...a,input})}/>;case 'link':return <LinkFields value={a.input} onChange={input=>set({...a,input})} files={files}/>;case 'physical_record':return <PhysicalFields value={a.input} onChange={input=>set({...a,input})} files={files} products={products}/>;}}
