import type { DraftContent, Provider } from '@/domain/submissions/types';
export const RECOVERY_PREFIX='gs-hale:submission-recovery:';
export type QueueRow={id:string;name:string;size:number;mime:string;state:'pending'|'uploading'|'ready'|'failed'|'reselect';fileId?:string;error?:string};
export interface Recovery {userId:string;contextId:string;taskId:string;baseRequestId:string;revision:number;content:DraftContent;provider:Provider;queue:QueueRow[];at:number;receipt?:{fingerprint:string;key:string};previousContent?:DraftContent}
const key=(r:Pick<Recovery,'userId'|'contextId'|'taskId'|'baseRequestId'>)=>RECOVERY_PREFIX+JSON.stringify([r.userId,r.contextId,r.taskId,r.baseRequestId]);
export function clearSubmissionRecovery(){if(typeof window==='undefined')return;try{for(const k of Object.keys(sessionStorage))if(k.startsWith(RECOVERY_PREFIX))sessionStorage.removeItem(k);}catch{}}
export function clearRecoveryScope(userId:string,contextId:string,taskId:string){try{for(const k of Object.keys(sessionStorage)){if(!k.startsWith(RECOVERY_PREFIX))continue;const r=JSON.parse(sessionStorage.getItem(k)||'null');if(r?.userId===userId&&r.contextId===contextId&&r.taskId===taskId)sessionStorage.removeItem(k);}}catch{}}
export function readRecovery(userId:string,contextId:string,taskId:string):Recovery|null{try{const rows:Recovery[]=[];for(const k of Object.keys(sessionStorage)){if(!k.startsWith(RECOVERY_PREFIX))continue;const raw=sessionStorage.getItem(k)||'';if(raw.length>512*1024){sessionStorage.removeItem(k);continue;}const r=JSON.parse(raw);if(!r||r.userId!==userId||Date.now()-r.at>8*3600000){sessionStorage.removeItem(k);continue;}if(r.contextId===contextId&&r.taskId===taskId&&typeof r.baseRequestId==='string'&&Number.isInteger(r.revision)&&r.content&&Array.isArray(r.content.answers)&&Array.isArray(r.content.artifacts)&&Array.isArray(r.content.links)&&Array.isArray(r.content.productSelections)&&typeof r.content.narrative==='string'&&r.provider&&Array.isArray(r.queue))rows.push(r);}return rows.sort((a,b)=>b.at-a.at)[0]??null;}catch{return null;}}
export function writeRecovery(r:Recovery):string{try{const value=JSON.stringify(r);if(value.length>512*1024)return '복구 가능한 입력 크기를 넘었습니다. 서버 임시 저장을 이용해 주세요.';const keys=Object.keys(sessionStorage).filter(k=>k.startsWith(RECOVERY_PREFIX)&&k!==key(r));while(keys.length>=3)sessionStorage.removeItem(keys.shift()!);sessionStorage.setItem(key(r),value);return '';}catch{return '이 브라우저에 복구 입력을 보관하지 못했습니다. 화면을 닫기 전에 서버 임시 저장을 확인해 주세요.';}}
