'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {SubmissionWorkspace,SubmissionSnapshot,RebasePreview,EvaluationResult,CommandResult} from '@/server/submissions/contracts';
import {blankDraft,blankInput,answerKey,type AnswerInput,type DraftContent,type Provider} from '@/domain/submissions/types';
import type {Requirement} from '@/domain/tasks/types';
import {matchesSubmissionReference,referenceKeys,type ReferenceSelection} from './reference';
import {request,RequestError} from '@/features/tasks/client';
import {Field,Select,AnswerFields,LinkFields} from './fields';
import {SubmissionFiles} from './files';
import {ProductSelections} from './products';
import {EvaluationView,SnapshotView,AnswerValue,labels,type DisplayFile} from './views';
import {readRecovery,writeRecovery,clearRecoveryScope,type Recovery,type QueueRow} from './recovery';
import s from '@/features/tasks/ui.module.css';
import u from './ui.module.css';
const copyProvider=(v:Provider):Provider=>v.kind==='user'?{kind:'user',userId:v.userId}:{kind:'external_source',label:v.label,source:v.source};
const workspaceProvider=(w:SubmissionWorkspace):Provider=>w.capabilities.proxy&&w.draft?copyProvider(w.draft.providedBy):{kind:'user',userId:w.userId};
function blankAnswer(q:Requirement,requestId:string,productId:string|null):AnswerInput{return {requestId,requirementKey:q.key,productId,type:q.type,input:blankInput(q.type)} as AnswerInput;}
function ReferencePanel({selection,contextId,onDenied}:{selection:Exclude<ReferenceSelection,{kind:'none'}>;contextId:string;onDenied:()=>void}){
 const [snapshot,setSnapshot]=useState<SubmissionSnapshot|null>(null),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);const panel=useRef<HTMLElement>(null),denial=useRef(onDenied);
 useEffect(()=>{denial.current=onDenied;},[onDenied]);
 const invalid=selection.kind==='invalid'||selection.value.contextId!==contextId;
 useEffect(()=>{if(invalid||selection.kind!=='reference')return;let active=true;const target=selection.value;
 request<SubmissionSnapshot>(`/api/submissions/${encodeURIComponent(target.submissionId)}`).then(v=>{if(active){if(matchesSubmissionReference(v,target))setSnapshot(v);else setFailed(true);}}).catch(e=>{if(active){setFailed(true);if(e instanceof RequestError&&[401,403].includes(e.status))denial.current();}});return()=>{active=false;};
 // Selection is fixed by the keyed parent; cleanup suppresses obsolete responses.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[retry]);
 useEffect(()=>{if(snapshot){const selected=panel.current?.querySelector<HTMLElement>('[data-reference-selected="true"]');selected?.focus({preventScroll:true});selected?.scrollIntoView({block:'center'});}},[snapshot]);
 function close(){const query=new URLSearchParams(window.location.search);referenceKeys.forEach(k=>query.delete(k));query.set('context',contextId);window.history.pushState(null,'',`${window.location.pathname}?${query}#submissions`);}
 return <section aria-label="링크로 선택한 과거 자료" className={s.panel} ref={panel}><h2>링크로 선택한 과거 자료 · 읽기 전용</h2><p className={s.hint}>아래 현재 요청의 작성값과 별도입니다. 링크를 열어도 저장·제출·읽음·수락을 기록하지 않습니다.</p>{invalid||failed?<div role="alert" className={s.error}>지정한 자료를 열 수 없습니다. 주소의 업무·컨텍스트·요청·제출·답변 항목과 현재 접근 권한을 확인해 주세요. 최신 제출로 대신 표시하지 않습니다.{!invalid&&<button type="button" className="button subtle" onClick={()=>{setSnapshot(null);setFailed(false);setRetry(x=>x+1);}}>지정 자료 다시 조회</button>}</div>:snapshot&&selection.kind==='reference'?<><section className={s.sub} aria-label="선택한 제출의 당시 요청"><h3>당시 요청 v{snapshot.request.sequence}: {snapshot.request.content.title}</h3><p className={s.prose}>{snapshot.request.content.description}</p><p>선택 항목: {snapshot.request.content.requirements.find(q=>q.key===selection.value.requirementKey)?.label} · {selection.value.productId?'상품별':'공통'}</p></section><SnapshotView value={snapshot} selected={selection.value}/></>:<p role="status">지정한 과거 자료를 확인하는 중…</p>}<button type="button" className="button subtle" onClick={close}>자료 링크 닫고 현재 업무 보기</button></section>;
}
export function SubmissionSurface({taskId,contextId,reference,refreshKey,onChanged}:{taskId:string;contextId:string;reference:ReferenceSelection;refreshKey:number;onChanged:()=>Promise<unknown>}){
 const[w,setWorkspace]=useState<SubmissionWorkspace|null>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const next=await request<SubmissionWorkspace>(`/api/tasks/${taskId}/submissions`);setWorkspace(next);setError('');return next;}catch(e){throw e;}},[taskId]);
 useEffect(()=>{let active=true;request<SubmissionWorkspace>(`/api/tasks/${taskId}/submissions`).then(v=>{if(active){setWorkspace(v);setError('');}}).catch(e=>{if(active){setWorkspace(null);setError(e instanceof Error?e.message:'답변 자료를 읽지 못했습니다.');}});return()=>{active=false;};},[taskId,refreshKey]);
 const denied=()=>{if(w)clearRecoveryScope(w.userId,w.contextId,w.taskId);setWorkspace(null);setError('현재 답변 접근 권한을 다시 확인해 주세요. 로그인 또는 담당자 변경 후 다시 조회해 주세요.');};
 return <section id="submissions" aria-label="답변 작성과 제출" className={s.stack}>{reference.kind!=='none'&&<ReferencePanel key={JSON.stringify([reference,refreshKey])} selection={reference} contextId={contextId} onDenied={denied}/>} {error?<div role="alert" className={s.error}>{error}<button type="button" className="button subtle" onClick={()=>void load().catch(()=>undefined)}>답변 자료 다시 조회</button></div>:!w?<p role="status">답변 자료를 불러오는 중…</p>:<SubmissionEditor key={JSON.stringify([w.userId,w.contextId,w.taskId])} workspace={w} load={load} onChanged={onChanged} onDenied={denied} referenceActive={reference.kind!=='none'}/>}</section>;
}
function SubmissionEditor({workspace:w,load,onChanged,onDenied,referenceActive}:{referenceActive:boolean;workspace:SubmissionWorkspace;load:()=>Promise<SubmissionWorkspace>;onChanged:()=>Promise<unknown>;onDenied:()=>void}){
 const initial=w.draft?.content??blankDraft();const[content,setContent]=useState<DraftContent>(initial),[baseRequestId,setBase]=useState(w.draft?.baseRequestId??w.request.id),[revision,setRevision]=useState(w.draft?.revision??0),[provider,setProvider]=useState<Provider>(()=>workspaceProvider(w)),[queue,setQueue]=useState<QueueRow[]>([]);
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[storageError,setStorageError]=useState(''),[recovery,setRecovery]=useState<Recovery|null>(null),[comparison,setComparison]=useState<SubmissionWorkspace|null>(null),[preview,setPreview]=useState<RebasePreview|null>(null),[carry,setCarry]=useState<string[]>([]),[oldInput,setOldInput]=useState<DraftContent|null>(null),[snapshot,setSnapshot]=useState<SubmissionSnapshot|null>(w.latest),[extraFiles,setExtraFiles]=useState<DisplayFile[]>([]),[evaluation,setEvaluation]=useState<EvaluationResult|null>(null),[evaluatedContent,setEvaluatedContent]=useState(''),[evaluating,setEvaluating]=useState(false);
 const previousInput=useRef<DraftContent|null>(null), recoveryChecked=useRef(false);const locked=useRef(false),receipt=useRef<{fingerprint:string;key:string}>({fingerprint:'',key:''});
 const current=useRef({content,baseRequestId,revision,provider,queue});useEffect(()=>{current.current={content,baseRequestId,revision,provider,queue};},[content,baseRequestId,revision,provider,queue]);const base=`/api/tasks/${w.taskId}`;
 const files=Array.from(new Map([...w.availableFiles,...(w.draft?.files??[]),...extraFiles].map(f=>[f.id,f])).values());
 const mismatch=baseRequestId!==w.request.id||w.requiresRebase;
 const dirty=JSON.stringify(content)!==JSON.stringify(w.draft?.content??blankDraft())||JSON.stringify(provider)!==JSON.stringify(workspaceProvider(w));
 function persist(){if(!w.capabilities.editDraft)return;const x=current.current;setStorageError(writeRecovery({...x,userId:w.userId,contextId:w.contextId,taskId:w.taskId,at:Date.now(),receipt:receipt.current,previousContent:previousInput.current??undefined}));}
 function updateContent(next:DraftContent){current.current.content=next;setContent(next);persist();}
 function patch<K extends keyof DraftContent>(key:K,value:DraftContent[K]){updateContent({...current.current.content,[key]:value});}
 function updateQueue(next:QueueRow[]){current.current.queue=next;setQueue(next);persist();}
 function updateProvider(next:Provider){current.current.provider=next;setProvider(next);persist();}
 useEffect(()=>{if(recoveryChecked.current||!w.capabilities.editDraft)return;recoveryChecked.current=true;Promise.resolve().then(()=>{const found=readRecovery(w.userId,w.contextId,w.taskId);if(found?.previousContent){previousInput.current=found.previousContent;setOldInput(found.previousContent);}if(found&&(JSON.stringify(found.content)!==JSON.stringify(w.draft?.content??blankDraft())||found.queue.some(q=>q.state!=='ready'))){setRecovery(found);}});},[w.userId,w.contextId,w.taskId,w.capabilities.editDraft,w.draft]); // Server authorization precedes this component.
 function restore(){if(!recovery)return;setContent(recovery.content);setBase(recovery.baseRequestId);setRevision(recovery.revision);setProvider(copyProvider(recovery.provider));setQueue(recovery.queue.map(q=>q.state==='ready'?q:{...q,state:'reselect'}));if(recovery.receipt)receipt.current=recovery.receipt;previousInput.current=recovery.previousContent??null;setOldInput(previousInput.current);setRecovery(null);setMessage('이 브라우저의 작성값을 복구했습니다. 서버 저장값과 기준 버전을 확인한 뒤 저장하세요.');}
 function replace(next:SubmissionWorkspace){const c=next.draft?.content??blankDraft(),p=workspaceProvider(next);setContent(c);setBase(next.draft?.baseRequestId??next.request.id);setRevision(next.draft?.revision??0);setProvider(p);current.current={...current.current,content:c,baseRequestId:next.draft?.baseRequestId??next.request.id,revision:next.draft?.revision??0,provider:p};persist();}
 function handleError(e:unknown){if(e instanceof RequestError&&[401,403,404].includes(e.status)){onDenied();return;}setError(e instanceof Error?e.message:'연결을 확인한 뒤 다시 시도해 주세요. 작성값은 유지됩니다.');}
 async function evaluate(){setEvaluating(true);try{const x=current.current;const result=await request<EvaluationResult>(base+'/submission-evaluation',{baseRequestId:x.baseRequestId,content:x.content});setEvaluation(result);setEvaluatedContent(JSON.stringify(x.content));return result;}catch(e){handleError(e);return null;}finally{setEvaluating(false);}}
 async function post(url:string,input:Record<string,unknown>){const fingerprint=url+JSON.stringify(input);if(receipt.current.fingerprint!==fingerprint)receipt.current={fingerprint,key:crypto.randomUUID()};persist();const result=await request<CommandResult>(url,{...input,idempotencyKey:receipt.current.key});return result;}
 async function execute(action:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){handleError(e);}finally{locked.current=false;setBusy(false);}}
 async function save(){const x=current.current;await post(base+'/submission-draft',{command:'save',baseRequestId:x.baseRequestId,expectedDraftRevision:x.revision,providedBy:copyProvider(x.provider),content:x.content});setMessage('답변 임시 저장은 완료됐습니다. 최신 자료를 다시 확인합니다.');const next=await load();replace(next);receipt.current={fingerprint:'',key:''};persist();setComparison(null);setMessage('답변을 임시 저장했습니다. 아직 제출하지 않았습니다.');return next;}
 async function submit(mode:'partial'|'full'){let next=w;const x=current.current;const changed=JSON.stringify(x.content)!==JSON.stringify(w.draft?.content??blankDraft())||JSON.stringify(x.provider)!==JSON.stringify(workspaceProvider(w));if(changed||!w.draft)next=await save();const result=await post(base+'/submissions',{baseRequestId:current.current.baseRequestId,expectedDraftRevision:current.current.revision,expectedTaskRevision:next.taskRevision,mode});setMessage(`${mode==='full'?'전체':'부분'} 제출은 완료됐습니다. 제출본을 다시 불러옵니다.`);const fresh=await load();replace(fresh);const exact=await request<SubmissionSnapshot>(`/api/submissions/${result.ids[0]}`);setSnapshot(exact);receipt.current={fingerprint:'',key:''};persist();await onChanged();setMessage(`제출 v${exact.sequence}을 ${mode==='full'?'전체':'부분'} 제출했습니다. 검토 승인·수령·업무 완료와 별도입니다.`);}
 async function compare(){const next=await load();setComparison(next);setMessage('현재 입력은 유지했습니다. 서버 최신 초안과 비교한 뒤 적용 기준을 선택하세요.');}
 async function showRebase(){const v=await request<RebasePreview>(base+'/submission-draft');setPreview(v);setCarry([]);}
 async function rebase(){if(!preview)return;const previous=current.current.content;previousInput.current=previous;setOldInput(previous);persist();await post(base+'/submission-draft',{command:'rebase_apply',baseRequestId:preview.fromRequestId??baseRequestId,targetRequestId:preview.currentRequestId,expectedDraftRevision:preview.draftRevision,carryAnswers:preview.answers.filter(a=>a.compatible&&carry.includes(answerKey(a))).map(a=>({requirementKey:a.requirementKey,productId:a.productId})),providedBy:copyProvider(current.current.provider)});const next=await load();replace(next);setPreview(null);setMessage('새 요청 기준으로 초안을 바꿨습니다. 가져오지 않은 작성값은 아래 이전 입력에서 확인할 수 있습니다.');receipt.current={fingerprint:'',key:''};}
 async function copySubmission(id:string){await post(base+'/submission-draft',{command:'copy_submission',baseRequestId:w.request.id,expectedDraftRevision:revision,sourceSubmissionId:id,providedBy:copyProvider(provider)});replace(await load());setMessage('선택한 제출본을 새 답변 초안으로 가져왔습니다. 수정 후 명시적으로 제출하세요.');receipt.current={fingerprint:'',key:''};}
 const readOnly=!w.capabilities.editDraft;
 return <div className={s.stack}>{readOnly&&error&&<p role="alert" className={s.error}>{error}</p>}<section className={s.panel}><h2>답변·제출</h2><p>현재 요청 v{w.request.sequence} · {w.latest?`최근 제출 v${w.latest.sequence}`:'아직 실제 제출 없음'}</p><p className={s.hint}>읽음·작업 수락·답변 제출은 서로 다른 기록입니다. 제출만으로 검토·외부 승인·수령·업무 완료를 처리하지 않습니다.</p>{w.submittedEvaluation?<EvaluationView title={w.submittedEvaluation.isCurrentRequest?'실제 제출 진행':'실제 제출 진행 · 요청 변경 후 비교'} value={w.submittedEvaluation.evaluation}/>:<p>아직 제출된 답변이 없습니다.</p>}{w.priorFixture&&<p className={s.hint}>기존 답변 예시는 실제 제출 이력과 구별됩니다.</p>}</section>
 {!readOnly&&<section className={s.panel} aria-label="답변 편집"><h2>답변 작성</h2><p>{w.draft?`서버 임시 저장 v${w.draft.revision} · ${w.draft.editorLabel} · ${w.draft.lastEditedAt}`:'서버에 저장된 답변 초안이 없습니다.'}</p><p className={s.hint}>{dirty?'아직 서버에 저장하지 않은 작성값이 있습니다.':'화면 입력이 서버 초안과 같습니다.'}{w.draft?.consumedBy?' 이 초안은 이미 제출되었습니다. 수정·저장하면 새 제출을 준비할 수 있습니다.':''}</p>{!w.capabilities.submit&&<p className={s.notice}>현재 업무는 확정 제출할 수 없습니다. 보류·취소 상태의 답변 초안은 저장·복구할 수 있으며 재개 후 제출하세요.</p>}
 {recovery&&<section className={s.notice} aria-label="작성값 복구"><h3>이 브라우저에 남은 작성값이 있습니다</h3><p>현재 사용자와 업무의 입력만 확인했습니다. 서버 저장본과 다를 수 있습니다.</p><button type="button" className="button" onClick={restore}>작성값 복구하기</button><button type="button" className="button subtle" onClick={()=>{clearRecoveryScope(w.userId,w.contextId,w.taskId);setRecovery(null);}}>복구 입력 버리고 서버 값 유지</button></section>}
 {storageError&&<p role="alert" className={s.error}>{storageError}</p>}{error&&<div role="alert" className={s.error}>{error}<p>작성한 입력과 성공한 파일 참조는 유지됩니다.</p></div>}{message&&<p role="status" className={s.success}>{message}</p>}
 <div className={s.actions}><button type="button" className="button subtle" disabled={busy} onClick={()=>void execute(compare)}>최신 초안 비교 · 작성값 유지</button>{mismatch&&<button type="button" className="button" disabled={busy} onClick={()=>void execute(showRebase)}>변경된 요청과 비교</button>}</div>
 {comparison&&<section className={s.sub} aria-label="서버 초안 비교"><h3>서버 최신 초안</h3><p>저장 버전 {comparison.draft?.revision??0} · {comparison.draft?.editorLabel??'저장 전'}</p><p className={s.prose}>{comparison.draft?.content.narrative||'전달할 말 없음'}</p>{comparison.draft?.content.answers.map(a=><div key={answerKey(a)}><strong>{comparison.request.content.requirements.find(q=>q.key===a.requirementKey)?.label??'이전 항목'}</strong><AnswerValue answer={a} fileName={id=>files.find(f=>f.id===id)?.name??'파일 확인 필요'}/></div>)}<div className={s.actions}><button type="button" className="button subtle" disabled={(comparison.draft?.baseRequestId??comparison.request.id)!==baseRequestId} onClick={()=>{setRevision(comparison.draft?.revision??0);current.current.revision=comparison.draft?.revision??0;setComparison(null);persist();setMessage('입력은 유지하고 확인한 최신 버전을 저장 기준으로 선택했습니다. 다시 저장하세요.');}}>입력 유지 · 최신 저장 기준 선택</button><button type="button" className="button subtle" onClick={()=>{replace(comparison);setComparison(null);setMessage('화면 입력을 서버 최신값으로 바꿨습니다.');}}>서버 최신값으로 입력 교체</button></div></section>}
 {preview&&<section className={s.sub} aria-label="요청 변경 비교"><h3>새 요청에 가져올 답변 선택</h3><p>호환되지 않는 항목은 새 기준으로 다시 작성해야 합니다. 선택하지 않은 값은 이전 입력에 보존합니다.</p>{preview.answers.map(a=><div className={s.sub} key={answerKey(a)}><label className={s.check}><input type="checkbox" disabled={!a.compatible} checked={carry.includes(answerKey(a))} onChange={e=>setCarry(e.target.checked?[...carry,answerKey(a)]:carry.filter(k=>k!==answerKey(a)))}/>{w.request.content.requirements.find(q=>q.key===a.requirementKey)?.label??'제거된 이전 항목'} · {a.compatible?'가져오기 가능':'다시 확인 필요'}</label><AnswerValue answer={a.answer} fileName={id=>files.find(f=>f.id===id)?.name??'파일 확인 필요'}/></div>)}<button type="button" className="button" disabled={busy} onClick={()=>void execute(rebase)}>선택한 답변으로 새 요청 적용</button></section>}
 {oldInput&&<details className={s.details}><summary>요청 변경 전 작성값 보관</summary><p className={s.prose}>{oldInput.narrative}</p>{oldInput.answers.map(a=><div key={answerKey(a)}><strong>{a.requirementKey}</strong><AnswerValue answer={a} fileName={id=>files.find(f=>f.id===id)?.name??'파일 확인 필요'}/></div>)}</details>}
 <fieldset disabled={busy||mismatch||!!recovery} className={s.stack} style={{border:0,padding:0,margin:0,minWidth:0}}>{mismatch&&<p className={s.notice}>요청 버전이 변경됐습니다. 작성값을 보존한 채 먼저 요청 변경을 비교·적용하세요.</p>}
 {w.capabilities.proxy?<section className={s.sub}><h3>자료 제공자와 기록자</h3><Select label="실제 자료 제공자" value={provider.kind==='user'?provider.userId:'external'} onChange={id=>updateProvider(id==='external'?{kind:'external_source',label:'',source:''}:{kind:'user',userId:id})}><option value={w.userId}>본인 제공</option>{w.providers.filter(p=>p.userId!==w.userId).map(p=><option key={p.userId} value={p.userId}>{p.label}</option>)}<option value="external">외부 출처 기록</option></Select>{provider.kind==='external_source'&&<><Field label="외부 제공자 이름" value={provider.label} onChange={label=>updateProvider({...provider,label})}/><Field label="자료 제공 출처" value={provider.source} onChange={source=>updateProvider({...provider,source})}/></>}<p className={s.hint}>기록자는 현재 로그인 사용자로 남습니다. 외부 제공자 기록은 로그인 계정을 만들지 않습니다.</p></section>:<p className={s.hint}>새로 작성한 자료의 제공자·기록자는 현재 사용자로 저장합니다. 기존 답변의 원저자는 보존합니다.</p>}
 <Field label="제출할 때 전할 말" value={content.narrative} onChange={v=>patch('narrative',v)} multiline/>
 <SubmissionFiles workspace={w} queue={queue} setQueue={updateQueue} files={files} value={content.artifacts} onChange={v=>patch('artifacts',v)} onReady={ready=>{setExtraFiles(old=>Array.from(new Map([...old,...ready].map(f=>[f.id,f])).values()));void load().catch(handleError);}} onError={handleError}/>
 {[null,...w.products.map(p=>p.productId)].map(productId=>{const requirements=w.request.content.requirements.filter(q=>productId?q.productIds.includes(productId):!q.productIds.length);return requirements.length?<section className={s.stack} key={productId??'common'} aria-label={productId?`${w.products.find(p=>p.productId===productId)?.common.name} 상품별 답변`:'공통 답변'}><h3>{productId?`${w.products.find(p=>p.productId===productId)?.common.name} · 상품별 답변`:'공통 답변'}</h3>{requirements.map(q=>{const existing=content.answers.find(a=>a.requirementKey===q.key&&a.productId===productId),a=existing&&existing.type===q.type?existing:blankAnswer(q,baseRequestId,productId),ev=evaluation?.evaluation.items.find(x=>x.requirementKey===q.key&&x.productId===productId);return <fieldset className={s.sub} key={JSON.stringify([q.key,productId])}><legend>{q.label} · {q.required?'필수':'선택'}</legend>{q.help&&<p className={s.hint}>{q.help}</p>}{q.specifications.map((v,i)=><p className={s.hint} key={i}>{v.severity==='required'?'필수':'권장'} 규격: {v.text} · {v.source} / {v.version} · 사람 확인 필요</p>)}{ev&&<p className={s.hint}>{labels[ev.status]}</p>}<AnswerFields answer={a} requirement={q} files={files} products={w.products} onChange={next=>patch('answers',[...current.current.content.answers.filter(x=>answerKey(x)!==answerKey(next)),next])}/>{ev?.issues.map((v,i)=><p role="alert" className={s.error} key={i}>{v.message}</p>)}</fieldset>;})}</section>:null;})}
 <section className={s.sub}><h3>추가 참고 링크</h3>{content.links.map((v,i)=><fieldset key={i} className={s.sub}><legend>참고 링크 {i+1}</legend><LinkFields value={v} files={files} onChange={next=>patch('links',current.current.content.links.map((x,j)=>j===i?next:x))}/><button type="button" className="button subtle" onClick={()=>patch('links',content.links.filter((_,j)=>j!==i))}>참고 링크 {i+1} 제외</button></fieldset>)}<button type="button" className="button subtle" onClick={()=>patch('links',[...content.links,{url:'',description:'',contentFixed:false,fixedReference:null}])}>참고 링크 추가</button></section>
 <ProductSelections products={w.products} value={content.productSelections} onChange={v=>patch('productSelections',v)} refresh={()=>void execute(async()=>{await load();setMessage('최신 상품정보를 확인했습니다. 답변은 유지되며 변경된 상품 버전은 명시적으로 다시 선택하세요.');})}/>
 <EvaluationView title="현재 작성값 확인" value={evaluation?.evaluation??w.draftEvaluation} extra={evaluation} stale={evaluatedContent!==JSON.stringify(content)}/>
 <div className={`${s.actions} ${u.commitActions}`}><button type="button" className="button subtle" disabled={evaluating} onClick={()=>void evaluate()}>{evaluating?'확인 중…':'작성값 형식·남은 항목 확인'}</button><button type="button" className="button subtle" onClick={()=>void execute(async()=>{await save();await evaluate();})}>답변 임시 저장</button><button type="button" className="button" disabled={!w.capabilities.submit||!!w.draft?.consumedBy&&!dirty} onClick={()=>void execute(async()=>{await submit('partial');})}>부분 제출</button><button type="button" className="button" disabled={!w.capabilities.submit||!!w.draft?.consumedBy&&!dirty} onClick={()=>void execute(async()=>{await submit('full');})}>전체 제출</button></div><p className={s.hint}>제출 버튼은 현재 입력을 먼저 저장하고 확정합니다. 남은 필수 항목이 있으면 부분 제출할 수 있습니다.</p></fieldset></section>}
 {!referenceActive&&<section className={s.panel} aria-label="제출 이력"><h2>제출 이력</h2>{w.history.length?<div className={s.actions}>{w.history.map(v=><button key={v.id} type="button" className="button subtle" disabled={busy} onClick={()=>void execute(async()=>{setSnapshot(await request<SubmissionSnapshot>(`/api/submissions/${v.id}`));})}>제출 v{v.sequence} 보기 · {v.mode==='full'?'전체':'부분'}</button>)}</div>:<p>아직 제출된 답변이 없습니다.</p>}{snapshot&&<><SnapshotView value={snapshot}/>{w.capabilities.editDraft&&snapshot.requestId===w.request.id&&<button type="button" className="button subtle" disabled={busy} onClick={()=>void execute(()=>copySubmission(snapshot.id))}>제출 v{snapshot.sequence}을 새 답변 초안으로 가져오기</button>}</>}<p className={s.hint}>사람 검토·외부 진행·업무 완료는 별도의 기록으로 연결됩니다.</p></section>}</div>;
}
