import Link from 'next/link';
import {referenceHref,type SubmissionReference} from './reference';
import u from './ui.module.css';
import type {AnswerInput,Evaluation} from '@/domain/submissions/types';
import type {SubmissionWorkspace,SubmissionSnapshot,EvaluationResult} from '@/server/submissions/contracts';
import {CommonView,ContextView,PriceView,Pairs} from '@/features/products/views';
import s from '@/features/tasks/ui.module.css';
export const labels={missing:'추가 제출 필요',received:'입력 확인',prior_received:'이전 제출에서 충족',needs_reconfirmation:'재확인 필요',not_applicable:'해당 없음',optional:'선택 항목',invalid:'입력 확인 필요'};
export const roleLabels={editable_original:'편집 원본',review_copy:'확인본',evidence:'근거자료'};
export function SubmissionProgress({value}:{value:{sequence:number;mode:'partial'|'full';isCurrentRequest:boolean}|null|undefined}){return value?<span className="badge">제출 v{value.sequence} · {value.mode==='full'?'전체 제출':'부분 제출'}{!value.isCurrentRequest?' · 요청 변경 후 확인 필요':''}</span>:null;}
export type DisplayFile=Pick<SubmissionWorkspace['availableFiles'][number],'id'|'name'|'mime'|'bytes'|'sha256'|'preview'|'previewUrl'|'originalUrl'|'downloadUrl'>&{uploaderLabel?:string;uploadedAt?:string};
export function SubmissionFile({file:f}:{file:DisplayFile}){return <div className={s.file}><div><strong>{f.name}</strong><p className={s.small}>{f.mime} · {f.bytes.toLocaleString()} bytes · 업로더 {f.uploaderLabel||'확인 중'} · {f.uploadedAt||'시각 확인 중'}</p><details><summary>파일 버전 정보</summary><p className={s.hint}>{f.id}<br/>{f.sha256}</p></details></div><div className={s.actions}><a className={s.link} href={f.downloadUrl}>다운로드 · {f.name}</a><a className={s.link} href={f.originalUrl} target="_blank" rel="noreferrer">원본 ↗</a>{f.preview&&f.previewUrl?<a className={s.link} href={f.previewUrl} target="_blank" rel="noreferrer">미리보기 ↗</a>:<span className={s.hint}>원본 다운로드 전용</span>}</div></div>;}
export function EvaluationView({value:v,title,extra,stale=false}:{value:Evaluation|null;title:string;extra?:EvaluationResult|null;stale?:boolean}){return <section className={s.sub} aria-label={title}><h3>{title}</h3>{!v?<p>아직 확인한 입력이 없습니다.</p>:<><p>필수 {v.required}개 · 충족 {v.satisfied}개 · 남은 항목 {v.missing}개 · 형식 오류 {v.invalid}개</p>{stale&&<p className={s.notice}>작성한 내용이 바뀌었습니다. 입력 확인을 눌러 최신 결과를 확인하세요.</p>}<div className={s.list}>{v.items.map(item=><div key={JSON.stringify([item.requirementKey,item.productId])}><strong>{item.label}</strong> · {labels[item.status]}{item.productId&&<span className={s.small}> · 상품별 항목</span>}{item.issues.map((v,i)=><p key={i} className={s.error}>{v.message}</p>)}{item.warnings.map((v,i)=><p key={i} className={s.hint}>{v}</p>)}{item.humanReviewPending&&<p className={s.hint}>규격은 사람이 확인해야 합니다. 형식적 제출과 검토 결과는 다릅니다.</p>}</div>)}</div></>}{extra&&<>{extra.fileIssues.length>0&&<p className={s.error}>연결한 파일 {extra.fileIssues.length}개를 현재 권한으로 다시 확인해 주세요.</p>}{extra.productIssues.length>0&&<p className={s.error}>상품 선택 {extra.productIssues.length}개가 변경되었거나 조회되지 않습니다. 입력을 유지하고 최신 상품을 확인해 주세요.</p>}{extra.missingProductIds.length>0&&<p className={s.error}>업무에 연결된 상품의 당시 정보를 선택해 주세요. 미선택 {extra.missingProductIds.length}개</p>}{extra.invalidLinkIndexes.length>0&&<p className={s.error}>참고 링크의 URL·설명을 확인해 주세요.</p>}</>}</section>;}
export function AnswerValue({answer:a,fileName}:{answer:AnswerInput;fileName:(id:string)=>string}){switch(a.type){case 'short_text':case 'long_text':return <p className={s.prose}>{a.input.text||'미입력'}</p>;case 'number':return <p>{a.input.value||'미입력'}</p>;case 'choice':return <p>{a.input.selected.join(' · ')||'미선택'}</p>;case 'file':return <ul>{a.input.fileVersionIds.map(id=><li key={id}>{fileName(id)}</li>)}</ul>;case 'date':return <p>{a.input.value||'미입력'} · {a.input.precision==='date'?'날짜':'일시'} · {a.input.timezone}</p>;case 'link':return <><p className={s.prose}>{a.input.url} — {a.input.description}</p><p className={s.hint}>외부 링크·내용 미고정 {a.input.fixedReference?`· 고정 참조: ${a.input.fixedReference.kind==='file'?fileName(a.input.fixedReference.fileVersionId):a.input.fixedReference.identifier}`:''}</p></>;case 'physical_record':return <><p className={s.prose}>{a.input.summary}</p><p>출처: {a.input.source||'미입력'}</p><ul>{a.input.items.map((x,i)=><li key={i}>{x.quantity||'수량 미확인'} {x.unit} · {x.productId||'공통'}</li>)}</ul>{a.input.observedAt&&<p>기록 시점: {a.input.observedAt.value} · {a.input.observedAt.timezone}</p>}<p>실제 수령·승인 상태와 별도의 제공 기록입니다.</p></>;}}
export function SnapshotView({value:v,selected}:{value:SubmissionSnapshot;selected?:SubmissionReference}){const fileName=(id:string)=>v.files.find(f=>f.id===id)?.name??'파일 확인 필요';return <section className={s.panel} aria-label={`제출 v${v.sequence} 상세`}><h3>제출 v{v.sequence} · {v.mode==='full'?'전체 제출':'부분 제출'}</h3><p>요청 v{v.request.sequence} · {v.submittedAt}</p><p>제공자 {v.providedBy.label} · 기록자 {v.recorderLabel}</p><p className={s.notice}>당시 확정한 내용입니다. 새 답변과 상품정보가 바뀌어도 이 제출본은 바뀌지 않습니다. 제출은 검토 승인이나 업무 완료가 아닙니다.</p><h4>전달할 말</h4><p className={s.prose}>{v.content.narrative||'없음'}</p>{v.answers.map(a=><article className={`${s.sub} ${selected?.requirementKey===a.requirementKey&&selected.productId===a.productId?u.selectedAnswer:''}`} tabIndex={selected?.requirementKey===a.requirementKey&&selected.productId===a.productId?-1:undefined} data-reference-selected={selected?.requirementKey===a.requirementKey&&selected.productId===a.productId?"true":undefined} aria-label={selected?.requirementKey===a.requirementKey&&selected.productId===a.productId?"링크로 선택한 답변":undefined} key={JSON.stringify([a.requirementKey,a.productId])}><h4>{v.request.content.requirements.find(q=>q.key===a.requirementKey)?.label??'이전 요청 항목'}{a.productId?` · ${v.products.find(p=>p.productId===a.productId)?.common.name??'상품별'}`:' · 공통'}</h4><AnswerValue answer={a} fileName={fileName}/><Link className={s.link} scroll={false} href={referenceHref({taskId:v.taskId,contextId:v.contextId,requestId:v.requestId,submissionId:v.id,requirementKey:a.requirementKey,productId:a.productId})}>이 답변의 정확한 링크</Link><p className={s.hint}>제공자 {a.provenance.providedBy.label} · 기록자 {a.provenance.recorderLabel} · {a.provenance.at}{a.provenance.originSubmissionId?' · 이전 제출에서 가져온 답변':''}</p></article>)}<h4>파일과 사용 역할</h4>{v.content.artifacts.map((a,i)=><p key={i}>{fileName(a.fileVersionId)} · {roleLabels[a.role]}</p>)}{v.files.map(f=><SubmissionFile key={f.id} file={f}/>)}{v.content.links.map((input,i)=><AnswerValue key={i} answer={{requestId:v.requestId,requirementKey:`link-${i}`,productId:null,type:'link',input}} fileName={fileName}/>)}<h4>당시 상품정보</h4>{v.products.map(p=><details className={s.details} key={p.id}><summary>{p.common.name} · 당시 사용본</summary><Pairs items={[["상품 버전",p.productVersionId],["컨텍스트 버전",p.contextProductVersionId],["소비자가 버전",p.retailPriceVersionId],["내용 해시",p.contentHash]]}/><CommonView value={p.common}/><ContextView value={p.context}/>{p.files.map(f=><Pairs key={f.fileVersionId} items={[["당시 상품 자료",f.binding.title],["자료 파일 버전",f.fileVersionId],["원본 해시",f.sha256],["문서 유형",f.binding.documentType],["출처",f.binding.source]]}/>)}{p.retailPrice&&<PriceView value={p.retailPrice}/>}<Link className={s.link} href={`/products/${p.productId}?context=${v.contextId}`}>현재 상품 보기 ↗</Link></details>)}<details className={s.details}><summary>제출 식별 정보</summary><p className={s.hint}>제출 ID {v.id}<br/>내용 해시 {v.contentHash}</p></details></section>;}
