'use client';
import Link from 'next/link';
import type {CorrectionBatch} from '@/server/corrections/contracts';
import type {Controller} from './controller';
import {targetFor,statusLabels,issueLabels,priorityLabels} from './model';
import {TargetPicker,TargetView,Field,Select} from './fields';
import {SubmissionFile} from '@/features/submissions/views';
import s from './ui.module.css';
export function Batches({c}:{c:Controller}){const w=c.w!;return <section className={s.stack} aria-label="공개 수정 묶음"><h2>공개 수정 묶음</h2><p className={s.notice}>파일 업로드·자료 제출은 반영 제출과 다릅니다. 브랜드가 해당 항목을 선택해 반영한 뒤 GSG가 해소 여부를 확인합니다.</p><p>공개 수정항목 {w.remainder.items.length}개 · 해소되지 않은 항목 {w.remainder.unresolved}개</p>{w.capabilities.reflect&&<Link href={`/tasks/${w.taskId}?context=${w.contextId}#submissions`} className="button subtle">업무에서 수정 자료 제출하기 ↗</Link>}{w.batches.length?w.batches.map(b=><Batch key={b.id} c={c} b={b}/>):<div className={s.panel}><h3>아직 공개된 수정 묶음이 없습니다</h3><p>공개된 의견이 여기에 표시됩니다. 내부 작성 여부는 표시하지 않습니다.</p></div>}</section>;}
function Batch({c,b}:{c:Controller;b:CorrectionBatch}){const w=c.w!,e=c.editors,actions=e.actions[b.id]??{};const update=(key:string,value:typeof actions[string])=>c.edit({...e,actions:{...e.actions,[b.id]:{...actions,[key]:value}}});const selected=b.items.filter(i=>actions[i.key]?.selected);const blocked=c.busy||!!c.pending;
 return <article className={s.panel} aria-label={`공개 묶음 v${b.sequence}`} id={`batch-${b.id}`}><header className={s.heading}><div><p className={s.eyebrow}>공개 v{b.sequence} · {b.publisherLabel} · {b.publishedAt}</p><h3>{b.title}</h3></div><a href={`#batch-${b.id}`} className={s.link}>이 공개 버전</a></header><p className={s.prose}>{b.summary}</p>{b.previousBatchVersionId&&<p><a className={s.link} href={`#batch-${b.previousBatchVersionId}`}>이전 묶음 v{w.batches.find(v=>v.id===b.previousBatchVersionId)?.sequence??'확인 필요'}에서 이어진 의견</a></p>}{b.mode==='urgent_partial'&&<section className={s.notice}><h4>긴급 부분 공개 · 대기 의견</h4>{b.pendingScopes.map((p,i)=><p key={i}>{p.agency} · {p.scope} · 예상 수신 {p.expectedOn??'미정'}</p>)}</section>}
 {b.items.map((i,n)=>{const original=w.submissions.find(v=>v.id===i.target.submissionId),later=w.submissions.filter(v=>v.sequence>(original?.sequence??Infinity));const action=actions[i.key]??{selected:false,target:later.length?{...targetFor(w,later[0]),answer:i.target.answer}:i.target,note:'',decision:'resolved' as const,reason:''};return <section className={s.sub} key={i.key} aria-label={`공개 항목 ${n+1}`}><h4>{n+1}. {i.change}</h4><p><span className="badge">{statusLabels[i.state.status]}</span> · {issueLabels[i.issue]} · 우선순위 {priorityLabels[i.priority]}</p><TargetView value={i.target} w={w}/><dl><dt>공개 출처</dt><dd>{i.publicSource}</dd><dt>수정 이유</dt><dd className={s.prose}>{i.reason}</dd><dt>브랜드 공개 설명</dt><dd className={s.prose}>{i.publicDescription}</dd></dl>{i.source.files.map(f=><SubmissionFile key={f.id} file={f}/>)}{i.source.products.map(p=><details key={p.id}><summary>{p.common.name} · 당시 상품 사용본</summary><p className={s.mono}>사용본 {p.id}<br/>상품 버전 {p.productVersionId}<br/>컨텍스트 버전 {p.contextProductVersionId}<br/>소비자가 버전 {p.retailPriceVersionId??'선택 없음'}<br/>해시 {p.contentHash}</p></details>)}
 {w.capabilities.reflect&&<fieldset disabled={blocked||!later.length} className={s.actionForm}><legend>브랜드 반영 제출 · 항목 {n+1}</legend>{!later.length?<p>이전 제출보다 새 버전의 답변·파일을 먼저 업무에서 제출해 주세요.</p>:<><label className={s.check}><input type="checkbox" checked={action.selected} onChange={ev=>update(i.key,{...action,selected:ev.target.checked})}/>항목 {n+1} 반영 대상으로 선택</label>{action.selected&&<><TargetPicker w={w} value={action.target} onChange={target=>update(i.key,{...action,target})} guarded={c.guarded} minSequence={original!.sequence} answerLocked/><Field label={`반영 설명 ${n+1}`} value={action.note} multiline onChange={note=>update(i.key,{...action,note})}/></>}</>}</fieldset>}
 {w.capabilities.manage&&i.state.reflection&&<fieldset disabled={blocked} className={s.actionForm}><legend>GSG 해소 확인 · 항목 {n+1}</legend><label className={s.check}><input type="checkbox" checked={action.selected} onChange={ev=>update(i.key,{...action,selected:ev.target.checked})}/>항목 {n+1} 해소 확인 대상으로 선택</label><TargetView value={i.state.reflection.target} w={w}/><p>반영자 {i.state.reflection.recorderLabel} · {i.state.reflection.recordedAt}</p><p className={s.prose}>{i.state.reflection.note}</p>{action.selected&&<><Select label={`해소 판단 ${n+1}`} value={action.decision} onChange={decision=>update(i.key,{...action,decision:decision as typeof action.decision})}><option value="resolved">해소 확인</option><option value="needs_confirmation">추가 확인 필요</option><option value="not_reflected">미반영 확인</option></Select><Field label={`판단 사유 ${n+1}`} value={action.reason} multiline onChange={reason=>update(i.key,{...action,reason})}/><p className={s.hint}>현재 반영 기록 {i.state.reflectionId}를 확인합니다. 잘못된 파일·누락 여부는 실제 자료를 보고 판단해 주세요.</p></>}</fieldset>}
 <details className={s.details}><summary>항목 {n+1} 반영·해소 이력</summary>{!i.history.reflections.length&&<p>아직 반영 기록이 없습니다.</p>}{i.history.reflections.map(r=><div key={r.id} className={s.sub}><h5>반영 · {r.recorderLabel} · {r.recordedAt}</h5><TargetView value={r.target} w={w}/><p className={s.prose}>{r.note}</p>{r.files.map(f=><SubmissionFile key={f.id} file={f}/>)}{i.history.resolutions.filter(x=>x.reflectionId===r.id).map(x=><p key={x.id}>{statusLabels[x.decision]} · {x.resolverLabel} · {x.resolvedAt}<br/>{x.reason}</p>)}</div>)}</details></section>;})}
 {w.capabilities.reflect&&<button className="button" disabled={blocked||!selected.length} onClick={()=>void c.execute({command:'reflect',batchVersionId:b.id,items:selected.map(i=>({itemKey:i.key,expectedItemRevision:i.state.revision,target:actions[i.key].target,note:actions[i.key].note}))})}>선택한 {selected.length}개 항목 반영 제출</button>}{w.capabilities.manage&&<button className="button" disabled={blocked||!selected.length||selected.some(i=>!i.state.reflectionId)} onClick={()=>void c.execute({command:'resolve',batchVersionId:b.id,items:selected.map(i=>({itemKey:i.key,expectedItemRevision:i.state.revision,reflectionId:i.state.reflectionId!,decision:actions[i.key].decision,reason:actions[i.key].reason}))})}>선택한 {selected.length}개 항목 해소 판단 저장</button>}
 <details><summary>공개 버전 식별 정보</summary><p className={s.mono}>{b.id}<br/>공개 내용 해시 {b.contentHash}</p><p className={s.hint}>공개 내용은 고정되고 반영·해소 사실은 별도 이력으로 추가됩니다.</p></details></article>;
}
