'use client';
import type { CorrectionPreview } from '@/server/corrections/contracts';
import type { Controller } from './controller';
import { blankBatch, targetFor, issueLabels, priorityLabels, type Workspace } from './model';
import { Field, Select, Checks, TargetPicker, TargetView } from './fields';
import s from './ui.module.css';
export function PublicContent({ value: v, w }: {
    value: CorrectionPreview;
    w: Workspace;
}) { return <div className={s.stack}><h3>{v.title || '제목 미입력'}</h3><p className={s.prose}>{v.summary || '요약 없음'}</p>{v.mode === 'urgent_partial' && <div className={s.notice}><strong>긴급 부분 공개 · 남은 의견</strong>{v.pendingScopes.map((p, i) => <p key={i}>{p.agency} · {p.scope} · 예상 {p.expectedOn ?? '미정'}</p>)}</div>}{v.previousBatchVersionId && <p>후속 묶음 · 이전 공개 v{w.batches.find(b => b.id === v.previousBatchVersionId)?.sequence ?? '확인 필요'}</p>}{v.items.map((i, n) => <article className={s.sub} key={i.key}><h4>{n + 1}. {i.change || '수정 내용 미입력'}</h4><p>{issueLabels[i.issue]} · 우선순위 {priorityLabels[i.priority]}</p><TargetView value={i.target} w={w}/><dl><dt>공개 출처</dt><dd>{i.publicSource}</dd><dt>수정 이유</dt><dd className={s.prose}>{i.reason}</dd><dt>브랜드 공개 설명</dt><dd className={s.prose}>{i.publicDescription}</dd></dl></article>)}</div>; }
export function Drafts({ c }: {
    c: Controller;
}) {
    const w = c.w!, e = c.editors, d = e.draft, staff = w.staff!, stored = staff.drafts.find(v => v.id === e.draftId), changed = !stored || JSON.stringify(stored.draft) !== JSON.stringify(d) || stored.revision !== e.draftRevision;
    const patch = (next: typeof d) => c.edit({ ...e, draft: next });
    return <section className={s.stack} aria-label="공개 수정 초안"><div className={s.heading}><h2>공개 수정 초안</h2><button className="button subtle" disabled={!!c.pending} onClick={() => c.edit({ ...e, draftId: null, draftRevision: 0, draft: blankBatch() })}>새 공개 초안</button></div><p className={s.notice}>내부 원문은 복사되지 않습니다. 실행 가능한 공개 설명을 작성한 뒤 서버 미리보기로 확인하세요.</p>{staff.drafts.length > 0 && <Select label="저장된 공개 초안" value={e.draftId ?? ''} onChange={id => { const v = staff.drafts.find(v => v.id === id); if (v)
        c.edit({ ...e, draftId: v.id, draftRevision: v.revision, draft: v.draft });
    else
        c.edit({ ...e, draftId: null, draftRevision: 0, draft: blankBatch() }); }}><option value="">새 초안</option>{staff.drafts.map(v => <option value={v.id} key={v.id}>{v.draft.title || '제목 없음'} · 저장 r{v.revision}{v.publishedVersionId ? ' · 공개 완료' : ''}</option>)}</Select>}
 {stored?.publishedVersionId && <p className={s.notice}>이미 공개한 내용은 바꿀 수 없습니다. 새 공개 초안에서 이전 묶음을 선택해 후속 의견을 작성하세요.</p>}
 <form onSubmit={ev => { ev.preventDefault(); void c.execute({ command: 'save_draft', draftId: e.draftId, expectedRevision: e.draftRevision, draft: d }); }} className={s.panel}><fieldset className={s.stack} disabled={c.busy || !!c.pending || !!stored?.publishedVersionId}><legend>브랜드 전달 내용</legend><Field label="공개 제목" value={d.title} max={200} onChange={title => patch({ ...d, title })}/><Field label="공개 요약" value={d.summary} multiline onChange={summary => patch({ ...d, summary })}/><Select label="이전 공개 묶음 · 후속 연결" value={d.previousBatchVersionId ?? ''} onChange={v => patch({ ...d, previousBatchVersionId: v || null })}><option value="">최초 공개</option>{w.batches.map(b => <option key={b.id} value={b.id}>공개 v{b.sequence} · {b.title}</option>)}</Select><Select label="공개 방식" value={d.mode} onChange={mode => patch({ ...d, mode: mode as typeof d.mode })}><option value="normal">일반 공개</option><option value="urgent_partial">긴급 부분 공개</option></Select>{d.mode === 'urgent_partial' && <section className={s.sub}><h3>아직 대기 중인 의견</h3>{d.pendingScopes.map((p, n) => <div className={s.sub} key={n}><Field label={`대기 기관 ${n + 1}`} value={p.agency} max={200} onChange={agency => patch({ ...d, pendingScopes: d.pendingScopes.map((v, i) => i === n ? { ...v, agency } : v) })}/><Field label={`대기 범위 ${n + 1}`} value={p.scope} max={2000} onChange={scope => patch({ ...d, pendingScopes: d.pendingScopes.map((v, i) => i === n ? { ...v, scope } : v) })}/><Field label={`예상 수신일 ${n + 1}`} value={p.expectedOn ?? ''} type="date" onChange={expectedOn => patch({ ...d, pendingScopes: d.pendingScopes.map((v, i) => i === n ? { ...v, expectedOn: expectedOn || null } : v) })}/><button className="button subtle" type="button" onClick={() => patch({ ...d, pendingScopes: d.pendingScopes.filter((_, i) => i !== n) })}>대기 범위 {n + 1} 삭제</button></div>)}<button className="button subtle" type="button" onClick={() => patch({ ...d, pendingScopes: [...d.pendingScopes, { agency: '', scope: '', expectedOn: null }] })}>대기 의견 범위 추가</button></section>}
 {d.items.map((item, n) => { const update = (next: typeof item) => patch({ ...d, items: d.items.map((x, i) => i === n ? next : x) }); return <section className={s.sub} key={item.key} aria-label={`수정항목 ${n + 1}`}><div className={s.heading}><h3>수정항목 {n + 1}</h3><button type="button" className="button subtle" onClick={() => patch({ ...d, items: d.items.filter((_, i) => i !== n) })}>항목 {n + 1} 삭제</button></div><TargetPicker w={w} value={item.target} onChange={target => update({ ...item, target, internalOpinionVersionIds: [] })} guarded={c.guarded}/><Checks label="근거로 선택할 내부 의견의 정확 버전" value={item.internalOpinionVersionIds} onChange={internalOpinionVersionIds => update({ ...item, internalOpinionVersionIds })} options={staff.opinions.flatMap(o => o.versions.filter(v => v.target.submissionId === item.target.submissionId).map(v => ({ id: v.id, label: `${v.source.source} · 의견 v${v.sequence} · ${v.id}` })))}/><p className={s.hint}>이 연결은 내부용입니다. 선택한 과거 의견 버전이 이후 편집으로 바뀌지 않습니다.</p><Field label="공개 출처" value={item.publicSource} max={2000} onChange={publicSource => update({ ...item, publicSource })}/><Field label="수정 내용" value={item.change} multiline onChange={change => update({ ...item, change })}/><Field label="수정 이유" value={item.reason} multiline onChange={reason => update({ ...item, reason })}/><Field label="브랜드 공개 설명" value={item.publicDescription} multiline onChange={publicDescription => update({ ...item, publicDescription })}/><div className={s.grid}><Select label="우선순위" value={item.priority} onChange={v => update({ ...item, priority: v as typeof item.priority })}>{Object.entries(priorityLabels).map(([k, l]) => <option key={k} value={k}>{l}</option>)}</Select><Select label="문제 유형" value={item.issue} onChange={v => update({ ...item, issue: v as typeof item.issue })}>{Object.entries(issueLabels).map(([k, l]) => <option key={k} value={k}>{l}</option>)}</Select></div>{item.issue === 'conflicting_opinions' && <p className={s.notice}>서로 상충하는 실제 의견 버전을 2개 이상 선택해 주세요. 공개 후에도 추가 확인으로 남습니다.</p>}</section>; })}<button type="button" className="button subtle" disabled={!w.submissions.length || d.items.length >= 80} onClick={() => patch({ ...d, items: [...d.items, { key: crypto.randomUUID(), target: targetFor(w, w.submissions[0]), internalOpinionVersionIds: [], publicSource: '', change: '', reason: '', publicDescription: '', priority: 'normal', issue: 'correction' }] })}>수정항목 추가</button><button className="button" type="submit">공개 초안 저장</button></fieldset></form>
 <button className="button subtle" disabled={changed || !!stored?.publishedVersionId || c.busy || !!c.pending} onClick={() => void c.showPreview()}>저장한 공개 초안 미리보기</button>{changed && <p className={s.hint}>작성 내용을 먼저 저장해 주세요.</p>}{c.preview && <section className={`${s.panel} ${s.preview}`} aria-label="브랜드 보기 미리보기"><h2>브랜드 보기 미리보기</h2><p>서버가 반환한 공개 내용입니다. 아직 공개·알림이 발생하지 않았습니다.</p><PublicContent value={c.preview.value} w={w}/><button className="button" disabled={changed || c.busy || !!c.pending} onClick={() => void c.execute({ command: 'publish', draftId: c.preview!.draftId, expectedRevision: c.preview!.revision })}>이 묶음 공개하기</button></section>}</section>;
}
