'use client';
import type {Controller} from './controller';
import {blankOpinion,targetFor} from './model';
import {Field,SourceFields,TargetPicker,TargetView,Checks} from './fields';
import {InternalFiles} from './uploads';
import {SubmissionFile} from '@/features/submissions/views';
import s from './ui.module.css';
export function Opinions({c}:{c:Controller}){const w=c.w!,e=c.editors,o=e.opinion,staff=w.staff!;return <section className={s.stack} aria-label="내부 의견 취합"><div className={s.heading}><h2>내부 의견 취합</h2><button className="button subtle" disabled={!w.submissions.length||!!c.pending} onClick={()=>c.edit({...e,opinionId:null,opinionRevision:0,opinion:blankOpinion(targetFor(w,w.submissions[0]))})}>새 내부 의견</button></div><p className={s.notice}>원문과 내부 근거는 GSG만 확인합니다. 브랜드에 전달할 설명은 공개 초안에서 별도로 작성합니다.</p>{o&&<form className={s.panel} onSubmit={ev=>{ev.preventDefault();void c.execute({command:'save_opinion',opinionId:e.opinionId,expectedRevision:e.opinionRevision,opinion:o});}}><fieldset disabled={c.busy||!!c.pending} className={s.stack}><legend>{e.opinionId?'의견 새 버전 편집':'새 의견 입력'}</legend><TargetPicker w={w} value={o.target} onChange={target=>c.edit({...e,opinion:{...o,target}})} guarded={c.guarded}/><SourceFields value={o.source} onChange={source=>c.edit({...e,opinion:{...o,source}})}/><Field label="의견 원문 · 내부 전용" value={o.originalText} multiline max={20000} onChange={originalText=>c.edit({...e,opinion:{...o,originalText}})}/><Field label="의견 수신일" type="date" value={o.receivedOn??''} onChange={receivedOn=>c.edit({...e,opinion:{...o,receivedOn:receivedOn||null}})}/><Checks label="상충하는 기존 의견 버전" value={o.conflictingOpinionVersionIds} onChange={conflictingOpinionVersionIds=>c.edit({...e,opinion:{...o,conflictingOpinionVersionIds}})} options={staff.opinions.flatMap(root=>root.versions.map(v=>({id:v.id,label:`${v.source.source} · 의견 v${v.sequence} · ${v.id}`})))}/><InternalFiles c={c} selected={o.internalFileVersionIds} onChange={internalFileVersionIds=>c.edit({...c.editors,opinion:c.editors.opinion?{...c.editors.opinion,internalFileVersionIds}:null})}/><button className="button" type="submit">의견 버전 저장</button></fieldset></form>}
 {staff.opinions.length?staff.opinions.map(root=><article className={s.panel} key={root.id}><h3>{root.versions[0]?.source.source??'의견'} · {root.versions.length}개 버전</h3>{root.versions.map(v=><details className={s.details} key={v.id}><summary>의견 v{v.sequence} · {v.source.kind==='external_opinion'?'외부 기관 의견':'내부 검토'} · {v.recordedAt}</summary><TargetView value={v.target} w={w}/><p>{v.source.kind==='external_opinion'?`${v.source.agency} · `:''}{v.source.kind!=='ai_candidate'?v.source.reviewer:''} · 수신 {v.receivedOn??'미기록'}</p><p className={s.prose}>{v.originalText||'원문 미입력'}</p><p className={s.hint}>기록자 {v.recorderLabel} · 정확 버전 {v.id}</p>{v.files.map(f=><SubmissionFile key={f.id} file={f}/>)}<button className="button subtle" disabled={!!c.pending} onClick={()=>c.edit({...e,opinionId:root.id,opinionRevision:root.revision,opinion:{target:v.target,source:v.source,originalText:v.originalText,internalFileVersionIds:v.internalFileVersionIds,receivedOn:v.receivedOn,conflictingOpinionVersionIds:v.conflictingOpinionVersionIds}})}>이 의견 v{v.sequence}에서 새 버전 작성</button></details>)}</article>):<p>아직 저장된 내부 의견이 없습니다.</p>}</section>;}
