'use client';
import type {AiContent,AiSourcePicker,AiVisibility,AssetReference} from '@/server/ai-input/contracts';
import type {Draft,UploadIntent} from './model';
import s from './ui.module.css';
const refId=(r:AssetReference)=>r.kind==='upload'?r.assetId:r.fileVersionId;
export function InputForm({value,onChange,picker,disabled,existing,onFile,onUpload,uploading,taskFilter}:{value:Draft;onChange:(d:Draft)=>void;picker:AiSourcePicker;disabled:boolean;existing:boolean;onFile:(file:File,index?:number)=>void;onUpload:(index:number)=>void;uploading:number|null;taskFilter?:string}){
 const c=value.content,sub=picker.submissions.find(v=>v.id===c.submission?.submissionId);const edit=(patch:Partial<AiContent>)=>onChange({...value,content:{...c,...patch},intent:null});
 function choose(r:AssetReference,checked:boolean){edit({sources:c.kind==='pdf'?(checked?[r]:[]):checked?[...c.sources,r]:c.sources.filter(x=>refId(x)!==refId(r))});}
 const allowed=(mime:string)=>c.kind==='pdf'?mime==='application/pdf':mime.startsWith('image/');
 const uploads=[...picker.uploads,...value.uploads.flatMap(u=>u.asset&&!picker.uploads.some(a=>a.id===u.asset!.id)?[u.asset]:[])].filter(a=>value.visibility==='staff'||a.visibility==='context');
 function uploadRow(u:UploadIntent,i:number){return <div className={s.item} key={u.key}><strong>{u.name}</strong><p className={s.meta}>{u.asset?'업로드됨 · 아래 자료 목록에서 선택할 수 있습니다.':uploading===i?'업로드 중…':u.error||'전송 대기 · 새로고침했다면 같은 파일을 다시 선택하세요.'}</p>{!u.asset&&<div className={s.actions}><label className={s.field}>같은 파일 다시 선택<input aria-label={`${u.name} 다시 선택`} type="file" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f,i);}}/></label><button type="button" className="button subtle" disabled={disabled} onClick={()=>onUpload(i)}>이 파일 업로드 재시도</button><button type="button" className="button subtle" disabled={disabled} onClick={()=>onChange({...value,uploads:value.uploads.filter((_,n)=>n!==i)})}>이 파일 제외</button></div>}</div>;}
 return <fieldset disabled={disabled} className={s.form}><div className={s.grid}><label className={s.field}>입력 제목<input value={c.title} maxLength={200} required onChange={e=>edit({title:e.target.value})}/></label><label className={s.field}>공개 범위<select aria-label="공개 범위" aria-describedby="ai-visibility-hint" value={value.visibility} disabled={existing} onChange={e=>onChange({...value,visibility:e.target.value as AiVisibility,content:{...c,sources:[]},intent:null})}><option value="context">현재 컨텍스트 팀</option>{picker.capabilities.createInternal&&<option value="staff">GSG 내부</option>}</select><span id="ai-visibility-hint" className={s.meta}>저장 후에는 공개 범위를 바꿀 수 없습니다.</span></label><label className={s.field}>제품 분류<select value={c.scope.classification} onChange={e=>edit({scope:{...c.scope,classification:e.target.value}})}><option value="unknown">분류 미확인</option><option value="general_cosmetic">일반 화장품</option><option value="medicated">약용 화장품</option><option value="quasi_drug">의약부외품</option><option value="other">기타</option></select></label><label className={s.field}>언어<select value={c.scope.language} onChange={e=>edit({scope:{...c.scope,language:e.target.value}})}><option value="ja">일본어</option><option value="ko">한국어</option><option value="en">영어</option><option value="unknown">미확인</option></select></label><label className={s.field}>매체<select value={c.scope.media} onChange={e=>edit({scope:{...c.scope,media:e.target.value}})}><option value="pop">POP</option><option value="leaflet">리플렛</option><option value="package">패키지·라벨</option><option value="sds">SDS·전성분</option><option value="press_release">프레스릴리즈</option><option value="other">기타</option></select></label><label className={s.field}>사용처<input value={c.scope.use} maxLength={1000} required onChange={e=>edit({scope:{...c.scope,use:e.target.value}})}/></label></div>
 <p className={s.notice}>일반 화장품의 일본어 POP·리플렛만 읽기 지원 대상입니다. 약용·분류 미확인·그 밖의 매체는 범위 밖으로 표시합니다.</p>
 <fieldset className={s.item}><legend>관련 업무·정확한 제출 버전</legend><label className={s.field}>제출 버전<select value={c.submission?.submissionId??''} onChange={e=>{const chosen=picker.submissions.find(v=>v.id===e.target.value);edit({submission:chosen?{taskId:chosen.taskId,requestId:chosen.requestId,submissionId:chosen.id,productUseIds:[]}:null,sources:c.sources.filter(r=>r.kind==='upload')});}}><option value="">연결하지 않음 · 독립 입력</option>{picker.submissions.filter(v=>!taskFilter||v.taskId===taskFilter).map(v=><option value={v.id} key={v.id}>{v.taskTitle} · 요청 v{v.requestSequence} / 제출 v{v.sequence}</option>)}</select></label>{taskFilter&&!picker.submissions.some(v=>v.taskId===taskFilter)&&<p className={s.meta}>이 업무에서 현재 접근할 수 있는 실제 제출이 없습니다. 독립 입력으로 작성할 수 있습니다.</p>}{sub&&<><p className={s.meta}>새 제출이 생겨도 이 선택은 바뀌지 않습니다. 붙여 넣은 문장은 해당 제출 답변의 원본이라고 간주하지 않습니다.</p>{sub.products.map(p=><label className={s.check} key={p.id}><input type="checkbox" checked={c.submission!.productUseIds.includes(p.id)} onChange={e=>edit({submission:{...c.submission!,productUseIds:e.target.checked?[...c.submission!.productUseIds,p.id]:c.submission!.productUseIds.filter(id=>id!==p.id)}})}/>{p.name} · 이 제출의 상품 사용본</label>)}</>}</fieldset>
 <fieldset className={s.item}><legend>독립적으로 연결할 상품 버전</legend>{!picker.products.length&&<p>선택할 상품이 없습니다.</p>}{picker.products.map(p=>{const selected=c.products.find(v=>v.productId===p.productId);return <div className={s.item} key={p.productId}><label className={s.check}><input type="checkbox" checked={!!selected} onChange={e=>edit({products:e.target.checked?[...c.products,{productId:p.productId,productVersionId:p.currentProductVersionId,contextProductVersionId:p.currentContextProductVersionId}]:c.products.filter(v=>v.productId!==p.productId)})}/>{p.name}</label>{selected&&<div className={s.grid}><label className={s.field}>공통 버전 · {p.name}<select value={selected.productVersionId} onChange={e=>edit({products:c.products.map(v=>v.productId===p.productId?{...v,productVersionId:e.target.value}:v)})}>{p.commonVersions.map(v=><option key={v.id} value={v.id}>v{v.sequence} · {v.name}</option>)}</select></label><label className={s.field}>컨텍스트 버전 · {p.name}<select value={selected.contextProductVersionId} onChange={e=>edit({products:c.products.map(v=>v.productId===p.productId?{...v,contextProductVersionId:e.target.value}:v)})}>{p.contextVersions.map(v=><option key={v.id} value={v.id}>v{v.sequence}</option>)}</select></label></div>}</div>;})}</fieldset>
 <label className={s.field}>입력 형식<select value={c.kind} onChange={e=>edit({kind:e.target.value as AiContent['kind'],text:e.target.value==='text'?'':null,sources:[],selectedPages:[]})}><option value="text">텍스트</option><option value="pdf">PDF</option><option value="images">이미지</option></select></label>
 {c.kind==='text'?<label className={s.field}>입력 문안<textarea aria-label="입력 문안" aria-describedby="ai-text-limit" value={c.text??''} rows={9} required onChange={e=>edit({text:e.target.value})}/><span id="ai-text-limit" className={s.meta}>{[...(c.text??'')].length.toLocaleString()} / 10,000자</span></label>:<><p className={s.meta}>{c.kind==='pdf'?'PDF 1개, 10 MiB 이하 · 실제 읽을 페이지 최대 10개':'이미지 최대 4개, 합계 10 MiB 이하'} · Illustrator .ai 파일은 읽기 대상이 아닙니다.</p><label className={s.field}>새 원본 파일<input type="file" accept={c.kind==='pdf'?'.pdf,application/pdf':'.png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp'} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f);e.target.value='';}}/></label>{value.uploads.map(uploadRow)}<fieldset className={s.item}><legend>실제로 읽을 자료 선택</legend>{uploads.filter(a=>allowed(a.mime)).map(a=><label className={s.check} key={a.id}><input type={c.kind==='pdf'?'radio':'checkbox'} name="ai-source" checked={c.sources.some(r=>refId(r)===a.id)} onChange={e=>choose({kind:'upload',assetId:a.id},e.target.checked)}/>{a.filename} · {a.visibility==='staff'?'GSG 내부':'컨텍스트 자료'}</label>)}{sub?.files.filter(f=>allowed(f.mime)).map(f=><label className={s.check} key={f.id}><input type={c.kind==='pdf'?'radio':'checkbox'} name="ai-source" checked={c.sources.some(r=>refId(r)===f.id)} onChange={e=>choose({kind:'submission_file',fileVersionId:f.id},e.target.checked)}/>{f.name} · 제출 v{sub.sequence} 원본</label>)}{!uploads.some(a=>allowed(a.mime))&&!sub?.files.some(f=>allowed(f.mime))&&<p>이 형식의 원본을 업로드하거나 파일이 있는 제출 버전을 선택해 주세요.</p>}</fieldset>{c.kind==='pdf'&&<label className={s.field}>읽을 PDF 페이지<input aria-label="읽을 PDF 페이지" aria-describedby="ai-page-hint" value={value.pages} onChange={e=>onChange({...value,pages:e.target.value,intent:null})} placeholder="예: 2, 10 또는 2-4" required/><span id="ai-page-hint" className={s.meta}>선택: {value.pages||'없음'} · 다른 페이지는 읽기 결과에 포함하지 않습니다.</span></label>}</>}
 </fieldset>;
}
