import type {AiContent,AiVisibility,AiAsset} from '@/server/ai-input/contracts';
export type UploadIntent={key:string;name:string;size:number;mime:string;visibility:AiVisibility;asset:AiAsset|null;error:string};
export type Draft={content:AiContent;pages:string;visibility:AiVisibility;expectedRevision:number;uploads:UploadIntent[];intent:{fingerprint:string;key:string}|null;confirmed:{id:string;versionId:string;operation?:'save'|'extract'}|null};
export const blank=():Draft=>({content:{title:'',scope:{classification:'unknown',language:'ja',media:'pop',use:''},kind:'text',text:'',sources:[],selectedPages:[],submission:null,products:[]},pages:'1',visibility:'context',expectedRevision:0,uploads:[],intent:null,confirmed:null});
export function pages(raw:string){const out=new Set<number>();for(const token of raw.split(/[ ,，、]+/).filter(Boolean)){const m=/^(\d+)(?:-(\d+))?$/.exec(token);if(!m)throw Error('페이지는 2, 10 또는 2-4처럼 입력해 주세요.');const a=Number(m[1]),b=Number(m[2]??m[1]);if(a<1||b<a||b>10000||b-a>9)throw Error('1~10,000쪽에서 최대 10페이지를 선택해 주세요.');for(let n=a;n<=b;n++)out.add(n);}if(!out.size||out.size>10)throw Error('실제로 읽을 PDF 페이지를 1~10개 선택해 주세요.');return [...out].sort((a,b)=>a-b);}
export function readyContent(d:Draft):AiContent{const c=d.content;if(c.kind==='text'&&[...(c.text??'')].length>10000)throw Error('텍스트는 최대 10,000자입니다.');return{...c,text:c.kind==='text'?c.text:null,selectedPages:c.kind==='pdf'?pages(d.pages):[],sources:c.kind==='text'?[]:c.sources};}
export const stateLabel:Record<string,string>={not_extracted:'읽기 전',queued:'읽기 대기',reading:'읽는 중',finished:'읽기 결과 저장됨',unread:'읽지 못함',rejected:'입력 확인 필요',out_of_scope:'지원 범위 밖',failed:'읽기 실패',interrupted:'읽기 중단',read:'선택 범위 읽음',partial:'일부만 읽음',unselected:'선택 제외'};
export const issueLabel:Record<string,string>={SCOPE_UNKNOWN:'제품 분류를 확인해 주세요.',OUT_OF_SCOPE:'일반 화장품의 일본어 POP·리플렛만 지원합니다.',INVALID_INPUT:'입력 형식을 확인해 주세요.',EMPTY_INPUT:'읽을 내용이 없습니다.',SIZE_LIMIT:'파일 용량 한도를 초과했습니다.',PAGE_LIMIT:'선택 페이지 한도를 초과했습니다.',IMAGE_LIMIT:'이미지 개수 한도를 초과했습니다.',TYPE_MISMATCH:'파일 확장자와 실제 형식이 일치하지 않습니다.',SOURCE_CHANGED:'원본 파일이 변경되어 다시 확인해야 합니다.',PDF_LOCKED:'잠긴 PDF는 읽을 수 없습니다.',PDF_CORRUPT:'손상된 PDF를 읽을 수 없습니다.',INVALID_SELECTION:'PDF에 없는 페이지가 선택되었습니다.',IMAGE_CORRUPT:'손상된 이미지를 읽을 수 없습니다.',RESOLUTION_LIMIT:'이미지 해상도 한도를 초과했습니다.',NO_TEXT:'읽을 수 있는 텍스트를 찾지 못했습니다.',LOW_CONTRAST:'대비가 낮아 읽지 못한 구간이 있습니다.',LOW_CONFIDENCE:'인식 신뢰도가 낮은 구간은 원문 확인이 필요합니다.',OCR_COVERAGE_UNKNOWN:'이미지의 모든 문자를 읽었는지 확인할 수 없습니다.',TEXT_LAYER_UNCERTAIN:'PDF 텍스트와 화면의 일치 여부를 확인해 주세요.',WORKER_TIMEOUT:'읽기 시간이 초과되었습니다.',WORKER_MEMORY:'읽기 처리 용량을 초과했습니다.',WORKER_UNAVAILABLE:'읽기 도구를 사용할 수 없습니다.',WORKER_FAILED:'읽기 도구 실행에 실패했습니다.',TOKEN_LIMIT:'후속 분석 입력 한도를 초과했습니다.',STORAGE_UNAVAILABLE:'결과 저장을 확인하지 못했습니다.',INTERRUPTED:'이전 읽기 작업이 중단되었습니다.',ACCESS_CHANGED:'원본 또는 컨텍스트 접근 권한이 변경되었습니다.'};
export const message=(e:unknown)=>e instanceof Error?e.message:'연결을 확인한 뒤 다시 시도해 주세요.';
export const recoveryPrefix='gs-hale.ai-input.v1:';
export function readRecovery(key:string):Draft|null{try{const v=JSON.parse(sessionStorage.getItem(key)||'null');return v?.expires>Date.now()&&v.draft?.content&&Array.isArray(v.draft.uploads)?v.draft:null;}catch{return null;}}
export function saveRecovery(key:string,draft:Draft){try{sessionStorage.setItem(key,JSON.stringify({expires:Date.now()+86400000,draft}));}catch{/* the on-screen input remains usable when storage is unavailable */}}
export function purgeRecovery(){for(let n=sessionStorage.length-1;n>=0;n--){const key=sessionStorage.key(n);if(key?.startsWith(recoveryPrefix))sessionStorage.removeItem(key);}}
