'use client';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {AiAsset,AiInputDetail,AiInputList,AiSourcePicker} from '@/server/ai-input/contracts';
import type {IdentityService} from '@/server/auth/service';
import {request,RequestError} from '@/features/tasks/client';
import {blank,message,purgeRecovery,readRecovery,readyContent,recoveryPrefix,saveRecovery,stateLabel,type Draft} from './model';
import {InputForm} from './form';
import {InputResult} from './result';
import s from './ui.module.css';
type Me=Awaited<ReturnType<IdentityService['me']>>;
type LoadedView={key:string;inputId?:string;versionId?:string;runId?:string};
type TransferStatus=LoadedView&{message:string};
const denied=(error:unknown)=>error instanceof RequestError&&[401,403,404].includes(error.status);
export function AiInputListScreen({contextId}:{contextId:string}){const [data,setData]=useState<AiInputList|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[forbidden,setForbidden]=useState(false);const epoch=useRef(0),blocked=useRef(false);
 const load=useCallback(async()=>{const stamp=++epoch.current;setBusy(true);try{const d=await request<AiInputList>(`/api/ai-input?contextId=${contextId}`);if(stamp!==epoch.current||blocked.current)return;setData(d);setError('');}catch(e){if(stamp!==epoch.current)return;if(denied(e)){blocked.current=true;setForbidden(true);epoch.current++;setData(null);purgeRecovery();}setError(message(e));}finally{if(stamp===epoch.current||blocked.current)setBusy(false);}},[contextId]);
 useEffect(()=>{const counter=epoch,timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);counter.current++;};},[load]);
 return <div className={s.stack}><header className={s.heading}><div><p className="eyebrow">원문과 읽은 범위를 함께</p><h1>AI 입력·텍스트 읽기</h1><p>일본어 POP·리플렛의 원문과 실제 읽은 구간을 보관합니다.</p></div>{data?.capabilities.create&&<Link className="button" href={`/ai-input/new?context=${contextId}`}>새 입력 작성</Link>}</header>{error&&<p className={s.error} role="alert">{error}</p>}<div className={s.actions}><button className="button subtle" disabled={busy||forbidden} onClick={load}>{busy?'불러오는 중…':'목록 새로 확인'}</button></div>{data?.items.length===0&&<section className={s.empty}><h2>저장된 입력이 없습니다</h2><p>텍스트나 파일을 선택하고 읽을 범위를 지정해 주세요.</p></section>}{data?.items.map(item=><article className={s.panel} key={item.id}><h2><Link href={`/ai-input/${item.id}?context=${contextId}`}>{item.title}</Link></h2><p>v{item.sequence} · {stateLabel[item.state]} · {item.visibility==='staff'?'GSG 내부':'컨텍스트 팀'}</p></article>)}</div>;
}
export function AiInputScreen({contextId,inputId}:{contextId:string;inputId?:string}){
 const router=useRouter(),query=useSearchParams(),versionId=query.get('version')??undefined,taskFilter=query.get('task')??undefined;
 const selectionKey=`${inputId??'new'}?${query.toString()}`;
 const [picker,setPicker]=useState<AiSourcePicker|null>(null),[detail,setDetail]=useState<AiInputDetail|null>(null),[draft,setDraft]=useState<Draft|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[blocked,setBlocked]=useState(false),[uploading,setUploading]=useState<number|null>(null),[uncertain,setUncertain]=useState(false),[conflict,setConflict]=useState<AiInputDetail|null>(null),[transfer,setTransfer]=useState<TransferStatus|null>(null),[loadedKey,setLoadedKey]=useState<string|null>(null);
 const auth=useRef(0),serial=useRef(0),blockedRef=useRef(false),alive=useRef(true),draftRef=useRef<Draft|null>(null),storage=useRef(''),files=useRef(new Map<string,File>()),locked=useRef(false),initialized=useRef(false),selection=useRef(versionId);selection.current=versionId;
 const loaded=useRef<LoadedView|null>(null);
 const atAddress=useCallback((key:string)=>alive.current&&!blockedRef.current&&window.location.pathname===`/ai-input/${inputId??'new'}`&&`${inputId??'new'}?${new URLSearchParams(window.location.search).toString()}`===key,[inputId]);
 const acceptView=useCallback((d:AiInputDetail|null,key:string)=>{loaded.current={key,inputId:d?.id,versionId:d?.version.id,runId:d?.runs[0]?.id};setLoadedKey(key);setDetail(d);},[]);
 function selected(d=detail){const v=loaded.current;return !!v&&v.key===selectionKey&&atAddress(v.key)&&v.inputId===d?.id&&v.versionId===d?.version.id&&v.runId===d?.runs[0]?.id;}
 function changingSelection(){serial.current++;loaded.current=null;setLoadedKey(null);setLoading(true);setNotice('');setTransfer(null);}

 const persist=useCallback((next:Draft)=>{draftRef.current=next;setDraft(next);if(storage.current)saveRecovery(storage.current,next);},[]);
 const fail=useCallback((e:unknown)=>{if(denied(e)){auth.current++;serial.current++;blockedRef.current=true;loaded.current=null;setLoadedKey(null);setBlocked(true);setPicker(null);setDetail(null);setDraft(null);draftRef.current=null;setConflict(null);setTransfer(null);setNotice('');files.current.clear();purgeRecovery();storage.current='';}setError(message(e));},[]);
 const fetchDetail=useCallback(async(id:string,version?:string)=>{const d=await request<AiInputDetail>(`/api/ai-input/${id}${version?`?versionId=${encodeURIComponent(version)}`:''}`);if(d.contextId!==contextId)throw new RequestError('선택한 컨텍스트의 입력이 아닙니다.',404,'NOT_FOUND');return d;},[contextId]);
 const load=useCallback(async()=>{if(blockedRef.current)return;const ticket=++serial.current,stamp=auth.current,key=selectionKey;loaded.current=null;setLoadedKey(null);setLoading(true);setError('');setNotice('');setTransfer(null);try{const [me,p,d]=await Promise.all([request<Me>('/api/auth/me'),request<AiSourcePicker>(`/api/ai-input/sources?contextId=${contextId}`),inputId?fetchDetail(inputId,selection.current):Promise.resolve(null)]);if(!alive.current||ticket!==serial.current||stamp!==auth.current||blockedRef.current)return;setPicker(p);storage.current=`${recoveryPrefix}${me.user.id}:${contextId}:${inputId??'new'}`;
 if(!initialized.current){initialized.current=true;let recovered=readRecovery(storage.current);if(recovered&&d&&recovered.visibility!==d.visibility)recovered=null;const editD=d&&d.version.id!==d.currentVersionId?await fetchDetail(d.id):d;if(!alive.current||ticket!==serial.current||stamp!==auth.current||blockedRef.current)return;const fresh=editD?{...blank(),content:editD.version.content,pages:editD.version.content.selectedPages.join(', ')||'1',visibility:editD.visibility,expectedRevision:editD.revision}:blank();const next=recovered??fresh;persist(next);if(recovered){setNotice('이 계정의 미저장 입력을 복구했습니다. 파일 바이트는 다시 선택해야 합니다.');setUncertain(!!recovered.intent&&!recovered.confirmed);}if(!inputId){const supplied=['task','request','submission'].filter(k=>query.has(k));if(supplied.length&&query.has('submission')){const sub=p.submissions.find(v=>v.id===query.get('submission')&&v.taskId===query.get('task')&&v.requestId===query.get('request'));if(!sub)throw new RequestError('지정한 정확한 제출을 찾을 수 없습니다. 최신 제출로 대신 선택하지 않습니다.',404,'NOT_FOUND');if(!recovered)persist({...next,content:{...next.content,submission:{taskId:sub.taskId,requestId:sub.requestId,submissionId:sub.id,productUseIds:[]}}});}}}
 if(atAddress(key)){acceptView(d,key);}
 }catch(e){if(alive.current&&ticket===serial.current&&stamp===auth.current)fail(e);}finally{if(alive.current&&ticket===serial.current)setLoading(false);}},[contextId,inputId,fetchDetail,persist,fail,query,selectionKey,atAddress,acceptView]);
 useEffect(()=>{alive.current=true;const life=alive,sequence=serial,authority=auth,timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);life.current=false;sequence.current++;authority.current++;};},[load]);
 const invalid=['context','version','task','request','submission'].some(k=>query.getAll(k).length>1)||(query.has('version')&&!query.get('version'))||(!inputId&&query.has('request')&&!query.has('submission'));
 async function retrieveConfirmed(){const saved=draftRef.current?.confirmed;if(!saved||!atAddress(selectionKey))return;const stamp=auth.current,ticket=serial.current;setBusy(true);try{const d=await fetchDetail(saved.id,saved.versionId);if(stamp!==auth.current||ticket!==serial.current||!atAddress(selectionKey))return;const next={...draftRef.current!,...(saved.operation==='extract'?{}:{content:d.version.content,pages:d.version.content.selectedPages.join(', ')||'1',expectedRevision:d.revision}),confirmed:null,intent:null};persist(next);setUncertain(false);setNotice(`입력 v${d.version.sequence}${saved.operation==='extract'?'의 읽기 결과를':' 저장을'} 확인했습니다.`);const target=`/ai-input/${d.id}?context=${contextId}&version=${d.version.id}`;if(!inputId)sessionStorage.removeItem(storage.current);if(window.location.pathname+window.location.search===target){acceptView(d,selectionKey);}else{changingSelection();router.replace(target);}}catch(e){if(stamp===auth.current&&ticket===serial.current&&atAddress(selectionKey))fail(e);}finally{if(alive.current)setBusy(false);}}
 async function save(){if(locked.current||!draftRef.current||!selected())return;locked.current=true;setBusy(true);setError('');setNotice('');const stamp=auth.current,ticket=serial.current;let sent=false;try{const d=draftRef.current,content=readyContent(d);const url=inputId?`/api/ai-input/${inputId}/versions`:'/api/ai-input',body=inputId?{expectedRevision:d.expectedRevision,content}:{contextId,visibility:d.visibility,content},fingerprint=url+JSON.stringify(body);const intent=d.intent?.fingerprint===fingerprint?d.intent:{fingerprint,key:crypto.randomUUID()};persist({...d,intent});sent=true;const result=await request<AiInputDetail>(url,{...body,idempotencyKey:intent.key});if(stamp!==auth.current||ticket!==serial.current||!selected())return;persist({...draftRef.current!,confirmed:{id:result.id,versionId:result.version.id,operation:'save'}});setNotice('저장은 완료되었습니다. 저장 결과를 다시 확인하고 있습니다.');await retrieveConfirmed();}catch(e){if(stamp!==auth.current||ticket!==serial.current||!selected())return;if(e instanceof RequestError&&e.status===409){persist({...draftRef.current!,intent:null});setUncertain(false);setConflict(null);setError(`${e.message} 입력은 유지했습니다. 현재 버전을 확인한 뒤 명시적으로 다시 저장해 주세요.`);}else{setUncertain(sent&&!(e instanceof RequestError&&e.status<500));if(e instanceof RequestError&&e.status<500&&draftRef.current)persist({...draftRef.current,intent:null});fail(e);}}finally{locked.current=false;if(alive.current)setBusy(false);}}
 async function compare(){if(!inputId||!selected())return;const stamp=auth.current,ticket=serial.current;setBusy(true);try{const d=await fetchDetail(inputId);if(stamp===auth.current&&ticket===serial.current&&selected())setConflict(d);}catch(e){if(stamp===auth.current&&ticket===serial.current&&atAddress(selectionKey))fail(e);}finally{setBusy(false);}}
 async function onFile(file:File,index?:number){if(!draftRef.current||!selected())return;const d=draftRef.current;if(file.size>10485760){setError('파일은 10 MiB 이하로 선택해 주세요.');return;}if(index!==undefined){const u=d.uploads[index];if(file.name!==u.name||file.size!==u.size||file.type!==u.mime){setError('같은 이름·크기·형식의 파일을 선택하거나 실패 항목을 제외하고 새로 추가해 주세요.');return;}files.current.set(u.key,file);setNotice('같은 파일을 다시 선택했습니다. 업로드 재시도를 눌러 주세요.');return;}const item={key:crypto.randomUUID(),name:file.name,size:file.size,mime:file.type,visibility:d.visibility,asset:null,error:''};files.current.set(item.key,file);persist({...d,uploads:[...d.uploads,item]});await upload(d.uploads.length);}
 async function upload(index:number){if(locked.current||!selected()||!draftRef.current)return;const item=draftRef.current.uploads[index],file=files.current.get(item.key);if(!file){setError('같은 파일을 다시 선택해 주세요. 파일 바이트는 브라우저 복구함에 저장하지 않습니다.');return;}locked.current=true;setBusy(true);setUploading(index);setError('');const stamp=auth.current,ticket=serial.current;try{const body=new FormData();body.set('file',file);body.set('idempotencyKey',item.key);const asset=await request<AiAsset>(`/api/ai-input/assets?contextId=${contextId}&visibility=${item.visibility}`,body);if(stamp!==auth.current||ticket!==serial.current||!selected())return;await request<AiSourcePicker>(`/api/ai-input/sources?contextId=${contextId}`);if(stamp!==auth.current||ticket!==serial.current||!selected())return;persist({...draftRef.current!,uploads:draftRef.current!.uploads.map(u=>u.key===item.key?{...u,asset,error:''}:u)});setNotice('파일을 업로드했습니다. 실제 읽을 자료로 선택한 뒤 입력을 저장하세요.');}catch(e){if(stamp!==auth.current||ticket!==serial.current||!selected())return;if(!denied(e)&&draftRef.current)persist({...draftRef.current,uploads:draftRef.current.uploads.map(u=>u.key===item.key?{...u,error:message(e)}:u)});fail(e);}finally{locked.current=false;if(alive.current){setUploading(null);setBusy(false);}}}
 async function extract(){if(locked.current||!detail||!selected()||!draftRef.current)return;locked.current=true;setBusy(true);setError('');setNotice('');setTransfer(null);const stamp=auth.current,ticket=serial.current,selectedVersion=detail.version.id;try{const last=detail.runs[0],url=`/api/ai-input/${detail.id}/extract`,existing=draftRef.current.intent,body=existing?.fingerprint.startsWith(url+'{')&&JSON.parse(existing.fingerprint.slice(url.length)).versionId===selectedVersion?JSON.parse(existing.fingerprint.slice(url.length)) as {versionId:string;expectedRunId:string|null}:{versionId:selectedVersion,expectedRunId:last?.id??null},fingerprint=url+JSON.stringify(body);const intent=existing?.fingerprint===fingerprint?existing:{fingerprint,key:crypto.randomUUID()};persist({...draftRef.current,intent});const result=await request<{runId:string;detail:AiInputDetail}>(url,{...body,idempotencyKey:intent.key});if(stamp!==auth.current||ticket!==serial.current||!selected())return;persist({...draftRef.current!,confirmed:{id:detail.id,versionId:selectedVersion,operation:'extract'}});const current=await fetchDetail(detail.id,selectedVersion);if(stamp!==auth.current||ticket!==serial.current||!selected())return;acceptView(current,selectionKey);persist({...draftRef.current!,confirmed:null,intent:null});setUncertain(false);setNotice(`입력 v${result.detail.version.sequence}의 읽기 상태를 확인했습니다.`);}catch(e){if(stamp!==auth.current||ticket!==serial.current||!selected())return;setUncertain(!(e instanceof RequestError&&e.status<500));if(e instanceof RequestError&&e.status===409&&draftRef.current)persist({...draftRef.current,intent:null});fail(e);}finally{locked.current=false;if(alive.current)setBusy(false);}}
 async function checkTransfer(){if(locked.current||!detail?.runs[0]||!selected())return;const stamp=auth.current,ticket=serial.current,owner={...loaded.current!};setBusy(true);setTransfer(null);try{const r=await request<{allowed:boolean;reason?:string;providerCalled:false}>(`/api/ai-input/${detail.id}/transfer-readiness`,{runId:owner.runId});if(stamp!==auth.current||ticket!==serial.current||!selected())return;setTransfer({...owner,message:r.allowed?'현재 원문 해시와 권한으로 등록된 합성 자료임을 확인했습니다. 외부 모델 호출은 실행하지 않았습니다.':'외부 전송 대상이 아닙니다. 미등록 원문은 로컬 읽기만 가능하며 외부로 보내지 않았습니다.'});}catch(e){if(stamp===auth.current&&ticket===serial.current&&atAddress(selectionKey))fail(e);}finally{if(alive.current)setBusy(false);}}

 if(invalid)return <p className={s.error} role="alert">컨텍스트·버전·제출 주소를 하나씩 정확히 지정해 주세요. 최신 버전으로 대신 열지 않습니다.</p>;
 const uncertainExtract=uncertain&&!!draft?.intent?.fingerprint.includes('/extract{');
 const viewReady=!loading&&!blocked&&loadedKey===selectionKey;
 const current=!!detail&&detail.version.id===detail.currentVersionId,canEdit=!inputId||current&&detail!.capabilities.revise,run=detail?.runs[0],confirmed=!!draft?.confirmed;
 return <div className={s.stack}><Link className="back-link" href={`/ai-input?context=${contextId}`}>← AI 입력 목록</Link><header><p className="eyebrow">원문과 읽은 범위를 함께</p><h1>{detail?.version.content.title??(inputId?'저장된 입력':'새 입력 작성')}</h1></header>{error&&<p role="alert" className={s.error}>{error}</p>}{notice&&viewReady&&<p role="status" className={s.notice}>{notice}</p>}{loading&&!blocked&&<p role="status">현재 권한과 자료를 확인하는 중…</p>}<div className={s.actions}><button type="button" className="button subtle" disabled={loading||blocked} onClick={load}>서버에서 새로 확인</button>{confirmed&&<button className="button" disabled={busy||blocked} onClick={retrieveConfirmed}>저장 결과 다시 읽기</button>}</div>{blocked&&<p>접근 가능한 화면으로 이동하거나 다시 로그인해 주세요. 이 화면의 자료와 복구 입력을 지웠습니다.</p>}
 {detail&&picker&&<><nav aria-label="입력 버전" className={s.tabs}>{detail.history.map(v=><Link key={v.id} aria-current={viewReady&&v.id===detail.version.id?'page':undefined} href={`/ai-input/${detail.id}?context=${contextId}&version=${v.id}`} onNavigate={()=>{if(selectionKey!==`${detail.id}?context=${contextId}&version=${v.id}`)changingSelection();}}>v{v.sequence}{v.id===detail.currentVersionId?' · 현재':''}</Link>)}</nav>{viewReady&&<InputResult detail={detail} picker={picker}/>} <section className={s.panel}><div className={s.actions}><button className="button" disabled={!viewReady||busy||confirmed||!(detail.capabilities.extract&&(!run||run.state==='queued'||run.retryable||uncertain))} onClick={extract}>{busy?'처리 중…':run?.state==='queued'?'대기 작업 이어 읽기':run?.retryable?'명시적으로 다시 읽기':uncertain?'같은 읽기 요청 다시 확인':'저장한 입력 읽기'}</button>{run?.snapshot&&<button className="button subtle" disabled={!viewReady||busy||confirmed} onClick={checkTransfer}>외부 전송 대상 여부 확인</button>}</div><p className={s.meta}>원본 권한과 해시는 실행할 때마다 서버가 확인합니다. 사용자가 공개 자료라고 체크하는 방식으로 전송을 허용하지 않습니다.</p>{viewReady&&transfer?.key===selectionKey&&transfer.versionId===detail.version.id&&transfer.runId===run?.id&&<p role="status" className={s.notice}>{transfer.message}</p>}</section></>}
 {draft&&picker&&canEdit&&!blocked&&<section className={s.panel}><h2>{inputId?'새 입력 버전 작성':'입력 내용'}</h2><p className={s.meta}>미저장 입력은 이 계정·컨텍스트·입력별로 현재 브라우저 세션에 최대 24시간 보관합니다. 파일 바이트는 보관하지 않습니다.</p>{uncertain&&<p className={s.notice}>이전 응답을 확인하지 못했습니다. 내용을 바꾸기 전에 같은 요청을 다시 확인해 주세요.</p>}<form onSubmit={e=>{e.preventDefault();void save();}}><InputForm value={draft} onChange={next=>{if(selected())persist(next);}} picker={picker} existing={!!inputId} disabled={!viewReady||busy||confirmed||uncertain} onFile={onFile} onUpload={upload} uploading={uploading} taskFilter={taskFilter}/>{conflict&&<div className={s.notice}><h3>현재 서버 버전 v{conflict.version.sequence}</h3><p>{conflict.version.content.title}</p><p className={s.body}>{conflict.version.content.text}</p><button type="button" className="button subtle" disabled={!viewReady||busy||confirmed} onClick={()=>{if(!selected())return;persist({...draftRef.current!,expectedRevision:conflict.revision,intent:null});setConflict(null);setError('');setNotice('현재 버전 기준으로 작성값을 유지했습니다. 확인 후 새 버전을 저장하세요.');}}>현재 버전 기준으로 내 입력 유지</button></div>}<div className={s.actions}><button className="button" type="submit" disabled={!viewReady||busy||confirmed||uncertainExtract}>{busy?'처리 중…':uncertain?'같은 저장 요청 다시 확인':inputId?'새 버전 저장':'입력 저장'}</button>{inputId&&<button type="button" className="button subtle" disabled={!viewReady||busy||confirmed} onClick={compare}>최신 버전 비교 · 작성값 유지</button>}</div></form></section>}{detail&&!canEdit&&<p className={s.notice}>{current?'다른 작성자의 입력입니다. 읽기 실행과 조회만 할 수 있습니다.':'과거 입력 버전입니다. 현재 버전으로 돌아가면 작성 중인 입력을 이어갈 수 있습니다.'}</p>}
 </div>;
}
