import type {ReactNode} from 'react';
import type {EvidenceMetadata, EvidenceSources, MaterialTable} from '@/server/evidence/contracts';
import s from '@/features/tasks/ui.module.css';
import u from './ui.module.css';
export const cellLabels={missing:'미제출',submitted:'제출됨',content_confirmation:'내용 확인 필요',application_confirmed:'적용 확인',correction_needed:'보완 필요',not_applicable:'해당 없음'};
export const assessmentLabels={pending:'확인 대기',application_confirmed:'적용 확인',correction_needed:'보완 필요',not_applicable:'해당 없음'};
export function Field({label,value,onChange,type='text',required=false,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;multiline?:boolean}){return <label className={u.control}>{label}{multiline?<textarea value={value} onChange={e=>onChange(e.target.value)} required={required}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/>}</label>;}
export function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:ReactNode}){return <label className={u.control}>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>;}
export function MetadataFields({value:v,onChange}:{value:EvidenceMetadata;onChange:(v:EvidenceMetadata)=>void}){return <div className={s.grid}>{([['title','자료 제목'],['documentType','문서 유형'],['issuer','발행자'],['issuedAt','발행일'],['signedAt','서명일'],['statedValidFrom','명시된 유효기간 시작'],['statedValidTo','명시된 유효기간 종료'],['validityRaw','기간 원문'],['language','자료 언어'],['source','자료 출처']] as const).map(([key,label])=><Field key={key} label={label} value={v[key]??''} type={['issuedAt','signedAt','statedValidFrom','statedValidTo'].includes(key)?'date':'text'} required={key==='title'||key==='documentType'} onChange={x=>onChange({...v,[key]:['issuedAt','signedAt','statedValidFrom','statedValidTo'].includes(key)?x||null:x})}/>)}<p className={s.hint}>문서 유형 예: SDS/MSDS, 서명 질문지, 보증/확인서, 갱신 청구서, 제품 목록, 실제 인증서. 알 수 없는 날짜는 비워 두세요.</p></div>;}
export function Products({rows,value,onChange}:{rows:MaterialTable['rows'];value:string[];onChange:(v:string[])=>void}){return <fieldset className={s.sub}><legend>적용 상품 선택</legend><div className={u.checks}>{rows.map(p=><label key={p.productId}><input type="checkbox" checked={value.includes(p.productId)} onChange={e=>onChange(e.target.checked?[...value,p.productId]:value.filter(v=>v!==p.productId))}/>{p.name} · {p.code}</label>)}</div>{!rows.length&&<p>연결할 상품이 없습니다. 먼저 상품을 등록하세요.</p>}</fieldset>;}
export function SourceInfo({item}:{item:EvidenceSources['items'][number]}){return <div className={`${s.sub} ${u.wrap}`}><strong>{item.file.name}</strong><p>{item.label} · 원본 업로더 {item.file.uploaderLabel} · {item.file.uploadedAt}</p><p className={s.small}>파일 버전 {item.source.fileVersionId}</p><div className={u.actions}><a href={item.file.downloadUrl}>원문 다운로드</a>{item.file.previewUrl&&<a href={item.file.previewUrl} target="_blank" rel="noreferrer">원문 미리보기 ↗</a>}</div></div>;}
