'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {EvidenceList,EvidenceSources,MaterialTable,MaterialCell} from '@/server/evidence/contracts';
import {blankEvidenceMetadata} from '@/domain/evidence/types';
import {useCommand} from '@/features/tasks/client';
import {MetadataFields,Products,SourceInfo,Select,cellLabels,assessmentLabels} from './fields';
import s from '@/features/tasks/ui.module.css';
import u from './ui.module.css';
export function MaterialCounts({contextId,productId,value}:{contextId:string;productId?:string;value:{requested:number;missing:number;unconfirmed:number}}){return <div className={u.actions} aria-label="실제 자료 집계">{([['requested','요청'],['missing','부족'],['unconfirmed','미확인']] as const).map(([key,label])=><Link key={key} className={s.link} href={`/materials?${new URLSearchParams({context:contextId,...productId?{productId}:{},count:key})}`}>{label} {value[key]}개</Link>)}</div>;}
function Cell({cell:c,list}:{cell:MaterialCell;list:EvidenceList}){return <div className={u.stack}><span className={u.status}>{cellLabels[c.status]}</span><span className={s.small}>{c.required?'필수':'선택'} · {c.answerProductId?'상품별 답변':'공통 답변'}</span>{c.humanReviewPending&&<p className={s.hint}>내용·규격의 사람 확인 대기. 자료 적용 확인과 별개입니다.</p>}{c.issues.map((i,n)=><p className={s.error} key={n}>{i.message}</p>)}{c.warnings.map((v,n)=><p className={s.hint} key={n}>{v}</p>)}<Link className={s.link} href={c.requestUrl}>현재 요청 보기 ↗</Link>{c.submissionUrl&&<Link className={s.link} href={c.submissionUrl}>해당 제출·답변 원문 ↗</Link>}{c.evidenceLinks.map(l=>{const e=list.items.find(e=>e.current.links.some(x=>x.id===l.linkId)),link=e?.current.links.find(x=>x.id===l.linkId);return e&&link?<div className={u.wrap} key={l.linkId}><Link href={`/materials/${e.id}?context=${list.contextId}`}>{e.current.metadata.title} · 증빙 v{e.current.sequence}</Link><p className={s.small}>자료 적용: {assessmentLabels[link.assessments[0]?.status??'pending']}</p><a className={s.link} href={link.file.downloadUrl}>연결된 파일 다운로드</a></div>:null;})}</div>;}
function Registration({sources,table,onCreated}:{sources:EvidenceSources;table:MaterialTable;onCreated:(id:string)=>void}){const [sourceIndex,setSourceIndex]=useState(''),[metadata,setMetadata]=useState(blankEvidenceMetadata),[products,setProducts]=useState<string[]>([]);const command=useCommand(),item=sources.items[Number(sourceIndex)];return <section className={s.panel} aria-label="자료 등록"><h2>보유 자료를 증빙으로 등록</h2><p className={s.notice}>자료 등록은 업무 제출이나 인증 승인이 아닙니다. 원본 하나에 상품별 적용 상태를 따로 기록합니다.</p>{sources.items.length?<form className={u.stack} onSubmit={e=>{e.preventDefault();if(sourceIndex==='')return;void command.run<{ids:string[]}>('/api/evidence',{contextId:table.contextId,source:item.source,metadata,productIds:products},async r=>onCreated(r.ids[0]),'자료를 등록했습니다.');}}><fieldset disabled={command.busy} className={u.stack} style={{border:0,padding:0,minWidth:0}}><Select label="등록할 원문 버전" value={sourceIndex} onChange={setSourceIndex}><option value="">원문 선택</option>{sources.items.map((x,i)=><option key={i} value={i}>{x.file.name} · {x.label} · {x.source.fileVersionId}</option>)}</Select>{sourceIndex!==''&&<><SourceInfo item={item}/><button type="button" className="button subtle" onClick={()=>setMetadata({...item.metadata,title:item.metadata.title||item.file.name})}>선택 원문의 메타데이터 가져오기</button></>}<MetadataFields value={metadata} onChange={setMetadata}/><Products rows={table.rows} value={products} onChange={setProducts}/><button className="button" disabled={sourceIndex===''||products.length===0}>자료 등록</button></fieldset>{command.error&&<p role="alert" className={s.error}>{command.error} 선택과 입력은 유지됩니다.</p>}{command.message&&<p role="status">{command.message}</p>}</form>:<p>등록할 공개 자료가 없습니다. 상품의 자료 연결 또는 업무의 실제 제출에서 원문을 먼저 제공하세요.</p>}</section>;}
export function MaterialScreen({table,list,sources,productId='',taskId='',count='',status=''}:{table:MaterialTable;list:EvidenceList;sources:EvidenceSources;productId?:string;taskId?:string;count?:string;status?:string}){const router=useRouter();const rows=table.rows.filter(r=>!productId||r.productId===productId),columns=table.columns.filter(c=>!taskId||c.taskId===taskId);const visible=(c:MaterialCell)=>{if(status&&c.status!==status)return false;if(count==='missing')return c.applicable&&(c.status==='correction_needed'||['invalid','needs_reconfirmation'].includes(c.canonicalStatus)||c.required&&c.status==='missing');if(count==='unconfirmed')return c.applicable&&c.submissionId!==null&&['submitted','content_confirmation'].includes(c.status);return count==='requested'?c.applicable:true;};
 return <div className={s.stack}><header className={s.heading}><div><p className="eyebrow">MATERIALS & EVIDENCE</p><h1>자료함·제출표</h1><p>보유 자료, 실제 제출, 상품별 적용 확인을 구분합니다.</p></div><Link className="button" href={`/products/import?context=${table.contextId}`}>상품 Excel 가져오기</Link></header><form className={s.panel}><input type="hidden" name="context" value={table.contextId}/><div className={s.grid}><label className={u.control}>상품 필터<select name="productId" defaultValue={productId}><option value="">전체 상품</option>{table.rows.map(r=><option value={r.productId} key={r.productId}>{r.name} · {r.code}</option>)}</select></label><label className={u.control}>업무 필터<select name="taskId" defaultValue={taskId}><option value="">전체 업무</option>{Array.from(new Map(table.columns.map(c=>[c.taskId,c.taskTitle])).entries()).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label className={u.control}>상태 필터<select name="status" defaultValue={status}><option value="">전체 상태</option>{Object.entries(cellLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className={u.control}>집계 필터<select name="count" defaultValue={count}><option value="">전체 셀</option><option value="requested">요청 자료</option><option value="missing">부족 자료</option><option value="unconfirmed">미확인 자료</option></select></label><label className={u.control}>업무 범위<select name="history" defaultValue={table.history?'1':'0'}><option value="0">진행 중 · 보류 포함</option><option value="1">완료·취소 이력</option></select></label></div><div className={u.actions}><button className="button">표 필터 적용</button><Link href={`/materials?context=${table.contextId}`} className="button subtle">필터 해제</Link><button type="button" className="button subtle" onClick={()=>router.refresh()}>최신 표 다시 조회</button></div></form>
 <section className={s.panel}><h2>{table.history?'완료·취소 업무의 자료 이력':'현재 공개 요청의 자료 현황'}</h2><p className={s.notice}>{table.notice}</p><p className={s.hint}>요청 수는 적용 대상 셀, 부족은 필수 미제출·형식 오류·보완 필요, 미확인은 제출 후 확인 대기입니다. 필터는 표시할 셀을 바꾸며 상품 집계는 전체 요청 기준입니다.</p>{productId&&rows[0]?<MaterialCounts contextId={table.contextId} productId={productId} value={rows[0].counts}/>:!productId&&<MaterialCounts contextId={table.contextId} value={table.counts}/>}{!rows.length?<p>조건에 맞는 상품이 없습니다.</p>:!columns.length?<p>이 범위에 공개된 요청 항목이 없습니다. 자료 보유 목록은 아래에서 볼 수 있습니다.</p>:!rows.some(r=>r.cells.some(c=>columns.some(x=>x.id===c.columnId)&&visible(c)))?<p>조건에 맞는 자료 셀이 없습니다.</p>:<><div className={`${u.scroll} ${u.desktop}`} role="region" aria-label="제품별 요청 자료 표" tabIndex={0}><table className={u.table}><caption>상품 × 공개 요청 항목 · 같은 이름의 항목도 업무와 요청 ID로 구분합니다.</caption><thead><tr><th scope="col">상품</th>{columns.map(c=><th scope="col" key={c.id}>{c.label}<p>{c.taskTitle}</p><span className={s.small}>{c.documentBearing?'자료 포함 항목':'답변 항목'} · {c.type}</span></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.productId}><th scope="row"><Link href={`/products/${r.productId}?context=${table.contextId}`}>{r.name}</Link><p>{r.code}</p><MaterialCounts contextId={table.contextId} productId={r.productId} value={r.counts}/></th>{columns.map(col=>{const c=r.cells.find(c=>c.columnId===col.id)!;return <td key={col.id}>{visible(c)?<Cell cell={c} list={list}/>:<span className={s.hint}>필터에서 제외</span>}</td>;})}</tr>)}</tbody></table></div><div className={u.mobile} aria-label="상품별 자료 카드">{rows.map(r=><section className={s.sub} key={r.productId} aria-label={`${r.name} 자료`}><h3><Link href={`/products/${r.productId}?context=${table.contextId}`}>{r.name}</Link></h3><MaterialCounts contextId={table.contextId} productId={r.productId} value={r.counts}/>{r.cells.filter(c=>visible(c)&&columns.some(x=>x.id===c.columnId)).map(c=><section className={s.sub} key={c.columnId}><h4>{columns.find(x=>x.id===c.columnId)!.label}</h4><p>{columns.find(x=>x.id===c.columnId)!.taskTitle}</p><Cell cell={c} list={list}/></section>)}</section>)}</div></>}</section>
 <section className={s.panel}><h2>등록한 증빙 · 현재 버전</h2><p className={s.notice}>{list.notice}</p>{list.items.filter(e=>!productId||e.current.links.some(l=>l.active&&l.productId===productId)).map(e=><article className={s.sub} key={e.id}><h3><Link href={`/materials/${e.id}?context=${table.contextId}`}>{e.current.metadata.title} · v{e.current.sequence}</Link></h3><p>{e.current.metadata.documentType} · 기록자 {e.current.recorderLabel} · {e.current.recordedAt}</p><p>원본 {e.current.file.name} · 적용 상품 {e.current.links.filter(l=>l.active).length}개</p></article>)}{!list.items.some(e=>!productId||e.current.links.some(l=>l.active&&l.productId===productId))&&<p>이 범위에 등록한 증빙이 없습니다.</p>}</section>{list.capabilities.register&&<Registration sources={sources} table={table} onCreated={id=>router.push(`/materials/${id}?context=${table.contextId}`)}/>}</div>;
}
