'use client';
import type { MenuDraft, SourceConflict, StatementField } from '@/domain/campaigns/types';
import type { Controller } from './controller';
import { Field, SourceEditor, blankSource } from './fields';
import { statementLabels } from './model';
import s from './ui.module.css';
export function MenuSources({ value, onChange, c }: {
    value: MenuDraft;
    onChange: (m: MenuDraft) => void;
    c: Controller;
}) { const d = c.state.data!, catalogs = d.catalogs?.items.flatMap(x => x.versions) ?? []; return <div className={s.stack}><div className={s.grid}><label className={s.field}>메뉴 카탈로그 버전<select required value={value.identity.catalogVersionId} onChange={e => onChange({ ...value, identity: { ...value.identity, catalogVersionId: e.target.value } })}><option value="">버전 선택</option>{catalogs.map(x => <option key={x.id} value={x.id}>{x.title} · {x.versionLabel} · v{x.sequence}</option>)}</select></label><Field label="메뉴 이름" required value={value.identity.menuName} onChange={menuName => onChange({ ...value, identity: { ...value.identity, menuName } })}/><Field label="카탈로그 메뉴 번호" value={value.identity.menuNumber} onChange={menuNumber => onChange({ ...value, identity: { ...value.identity, menuNumber } })}/></div><p className={s.hint}>번호가 같아도 카탈로그 버전·메뉴 식별자가 다르면 별개 메뉴입니다.</p><h4>출처별 문장 (GSG 내부)</h4>{value.sourceStatements.map((x, i) => <fieldset className={s.sub} key={x.id}><legend>원문 근거 {i + 1}</legend><label className={s.field}>근거 항목<select value={x.field} onChange={e => onChange({ ...value, sourceStatements: value.sourceStatements.map((v, j) => i === j ? { ...v, field: e.target.value as StatementField } : v) })}>{Object.entries(statementLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><Field label="원문 값" required value={x.rawValue} onChange={rawValue => onChange({ ...value, sourceStatements: value.sourceStatements.map((v, j) => i === j ? { ...v, rawValue } : v) })}/><SourceEditor value={x.source} files={d.task.files} onChange={source => onChange({ ...value, sourceStatements: value.sourceStatements.map((v, j) => i === j ? { ...v, source } : v) })}/><label className={s.check}><input type="checkbox" checked={value.conditions.sourceStatementIds.includes(x.id)} onChange={e => onChange({ ...value, conditions: { ...value.conditions, sourceStatementIds: e.target.checked ? [...value.conditions.sourceStatementIds, x.id] : value.conditions.sourceStatementIds.filter(k => k !== x.id) } })}/>공개 조건 확인에 참조한 근거</label><button type="button" className="button subtle" onClick={() => onChange({ ...value, sourceStatements: value.sourceStatements.filter(v => v.id !== x.id), conditions: { ...value.conditions, sourceStatementIds: value.conditions.sourceStatementIds.filter(k => k !== x.id) }, conflicts: value.conflicts.filter(v => !v.statementIds.includes(x.id)) })}>이 근거 제거</button></fieldset>)}<button type="button" className="button subtle" onClick={() => onChange({ ...value, sourceStatements: [...value.sourceStatements, { id: crypto.randomUUID(), field: 'price', rawValue: '', source: blankSource() }] })}>원문 근거 추가</button><h4>상충 원문 확인</h4>{Object.entries(statementLabels).map(([key, label]) => { const field = key as StatementField, statements = value.sourceStatements.filter(x => x.field === field), conflict = value.conflicts.find(x => x.field === field); if (statements.length < 2 && !conflict)
    return null; const set = (next: SourceConflict | null) => onChange({ ...value, conflicts: [...value.conflicts.filter(x => x.field !== field), ...(next ? [next] : [])] }); return <fieldset className={s.sub} key={field}><legend>{label} 충돌</legend><label className={s.check}><input type="checkbox" checked={!!conflict} onChange={e => set(e.target.checked ? { field, statementIds: statements.map(x => x.id), state: 'needs_confirmation', resolution: '' } : null)}/>상충하는 원문을 보존하고 확인 필요로 관리</label>{conflict && <><p>{statements.map(x => x.rawValue).join(' / ')}</p><label className={s.field}>충돌 확인 상태<select value={conflict.state} onChange={e => set({ ...conflict, state: e.target.value as SourceConflict['state'] })}><option value="needs_confirmation">확인 필요</option><option value="confirmed">명시 확인</option></select></label><Field label="충돌 확인 설명" required={conflict.state === 'confirmed'} multiline value={conflict.resolution} onChange={resolution => set({ ...conflict, resolution })}/></>}</fieldset>; })}</div>; }
