'use client';
import type { MenuDraft } from '@/domain/campaigns/types';
import { DeadlineEditor } from '@/features/tasks/deadline-editor';
import type { Controller } from './controller';
import { Field } from './fields';
import s from './ui.module.css';
export function MenuConditions({ value, onChange, c }: {
    value: MenuDraft;
    onChange: (m: MenuDraft) => void;
    c: Controller;
}) { const x = value.conditions, set = (v: typeof x) => onChange({ ...value, conditions: v }); return <div className={s.stack}><h4>사람이 확인한 공개 조건</h4><p className={s.notice}>이 영역만 브랜드에 공개됩니다. 과거 원문 금액을 현재 견적으로 자동 옮기지 않습니다. 빈 금액은 미정이며 0원과 다릅니다.</p><label className={s.field}>공개 조건 확인 상태<select value={x.state} onChange={e => set({ ...x, state: e.target.value as typeof x.state })}><option value="needs_confirmation">확인 필요</option><option value="confirmed">GSG 확인</option></select></label><Field label="브랜드 공개 설명" required multiline value={x.publicExplanation} onChange={publicExplanation => set({ ...x, publicExplanation })}/><div className={s.grid}><Field label="현재 확인 비용 (미정이면 빈칸)" value={x.cost.amount ?? ''} onChange={amount => set({ ...x, cost: { ...x.cost, amount: amount || null } })}/><Field label="통화 (ISO 3자리)" value={x.cost.currency ?? ''} onChange={currency => set({ ...x, cost: { ...x.cost, currency: currency ? currency.toUpperCase() : null } })}/><label className={s.field}>세금 포함<select value={x.cost.taxIncluded} onChange={e => set({ ...x, cost: { ...x.cost, taxIncluded: e.target.value as typeof x.cost.taxIncluded } })}><option value="unknown">미확인</option><option value="yes">포함</option><option value="no">별도</option></select></label><Field label="확인한 할인 조건" value={x.discount} onChange={discount => set({ ...x, discount })}/><Field label="확인한 포인트 조건" value={x.points} onChange={points => set({ ...x, points })}/></div><Field label="취소 조건" multiline value={x.cancellationTerms} onChange={cancellationTerms => set({ ...x, cancellationTerms })}/>{x.schedules.map((a, i) => <fieldset className={s.sub} key={a.key}><legend>외부 일정 {i + 1}</legend><label className={s.field}>일정 종류<select value={a.kind} onChange={e => set({ ...x, schedules: x.schedules.map((v, j) => i === j ? { ...v, kind: e.target.value as typeof a.kind } : v) })}><option value="application">외부 신청</option><option value="delivery">납품</option><option value="publication">게시·사용</option></select></label><DeadlineEditor value={a.deadline} members={c.state.data!.catalog.members} onChange={deadline => set({ ...x, schedules: x.schedules.map((v, j) => i === j ? { ...v, deadline } : v) })}/><button type="button" className="button subtle" onClick={() => set({ ...x, schedules: x.schedules.filter((_, j) => i !== j) })}>일정 제거</button></fieldset>)}<button type="button" className="button subtle" onClick={() => set({ ...x, schedules: [...x.schedules, { key: crypto.randomUUID(), kind: 'application', deadline: structuredClone(value.request.deadline) }] })}>외부 일정 추가</button></div>; }
