'use client';
import type { MenuDraft, FollowupRequirement } from '@/domain/campaigns/types';
import { DeadlineEditor } from '@/features/tasks/deadline-editor';
import type { Controller } from './controller';
import { Field } from './fields';
import s from './ui.module.css';
export function MenuDeliverables({ value, onChange, c }: {
    value: MenuDraft;
    onChange: (m: MenuDraft) => void;
    c: Controller;
}) { const d = c.state.data!; return <div className={s.stack}><h4>목적지·용도별 실물 요청</h4><p className={s.hint}>촬영용 1개와 배포용 100개를 별도 행으로 요청하세요. 아래는 요청 정의이며 발송·수령 사실은 공개 후 별도로 기록합니다.</p>{value.physical.map((x, i) => { const set = (next: typeof x) => onChange({ ...value, physical: value.physical.map((v, j) => i === j ? next : v) }); return <fieldset className={s.sub} key={x.key}><legend>실물 요청 {i + 1}</legend><div className={s.grid}><Field label="사용 목적" required value={x.purpose} onChange={purpose => set({ ...x, purpose })}/><Field label="목적지" required value={x.destination} onChange={destination => set({ ...x, destination })}/><label className={s.field}>실물 상품·변형<select value={value.products.findIndex(p => JSON.stringify(p) === JSON.stringify(x.product))} onChange={e => { const p = value.products[Number(e.target.value)]; if (p)
    set({ ...x, product: p }); }}><option value="-1">상품을 다시 선택해 주세요</option>{value.products.map((p, j) => <option value={j} key={j}>{d.catalog.products.find(v => v.id === p.productId)?.name ?? '상품'} · {p.sampleVariant || '기본 변형'} {p.productUseId ? '· 제출 당시 버전' : ''}</option>)}</select></label><Field label="요구 수량 (미정이면 빈칸)" value={x.requestedQuantity ?? ''} onChange={requestedQuantity => set({ ...x, requestedQuantity: requestedQuantity || null })}/><Field label="수량 단위" required value={x.unit} onChange={unit => set({ ...x, unit })}/></div><DeadlineEditor label="예정 발송" value={x.plannedShip} members={d.catalog.members} onChange={plannedShip => set({ ...x, plannedShip })}/><DeadlineEditor label="예정 도착" value={x.plannedArrival} members={d.catalog.members} onChange={plannedArrival => set({ ...x, plannedArrival })}/><button type="button" className="button subtle" onClick={() => onChange({ ...value, physical: value.physical.filter((_, j) => i !== j) })}>실물 요청 제거</button></fieldset>; })}<button type="button" className="button subtle" disabled={!value.products.length} onClick={() => onChange({ ...value, physical: [...value.physical, { key: crypto.randomUUID(), destination: '', purpose: '', product: structuredClone(value.products[0]), requestedQuantity: null, unit: '개', plannedShip: structuredClone(value.request.deadline), plannedArrival: structuredClone(value.request.deadline) }] })}>실물 요청 추가</button><h4>후속 산출물 요청</h4>{value.followups.map((x, i) => { const set = (next: typeof x) => onChange({ ...value, followups: value.followups.map((v, j) => i === j ? next : v) }); return <fieldset className={s.sub} key={x.key}><legend>후속 산출물 {i + 1}</legend><div className={s.grid}><label className={s.field}>산출물 종류<select value={x.kind} onChange={e => set({ ...x, kind: e.target.value as FollowupRequirement['kind'], requirementKey: '' })}><option value="publication_url">게시 URL</option><option value="execution_photo">실행 사진</option><option value="performance_report">성과 리포트</option><option value="custom">기타 실제 답변</option></select></label><label className={s.field}>실제 요청 항목<select required value={x.requirementKey} onChange={e => set({ ...x, requirementKey: e.target.value })}><option value="">항목 선택</option>{value.request.requirements.filter(q => x.kind === 'custom' || q.type === (x.kind === 'publication_url' ? 'link' : 'file')).map(q => <option key={q.key} value={q.key}>{q.label}</option>)}</select></label></div><DeadlineEditor label="후속 제출 기한" value={x.deadline} members={d.catalog.members} onChange={deadline => set({ ...x, deadline })}/><button type="button" className="button subtle" onClick={() => onChange({ ...value, followups: value.followups.filter((_, j) => i !== j) })}>후속 요청 제거</button></fieldset>; })}<button type="button" className="button subtle" onClick={() => onChange({ ...value, followups: [...value.followups, { key: crypto.randomUUID(), kind: 'publication_url', requirementKey: '', deadline: structuredClone(value.request.deadline) }] })}>후속 산출물 추가</button></div>; }
