'use client';
import { useState } from 'react';
import type { MenuDraft } from '@/domain/campaigns/types';
import type { RequestContent } from '@/domain/tasks/types';
import { typeLabels } from '@/domain/tasks/types';
import { DeadlineEditor } from '@/features/tasks/deadline-editor';
import type { Controller } from './controller';
import { Field } from './fields';
import s from './ui.module.css';
export function MenuRequirements({ value, onChange, c }: {
    value: MenuDraft;
    onChange: (m: MenuDraft) => void;
    c: Controller;
}) { const d = c.state.data!, versions = d.task.versions; const [basisId, setBasisId] = useState(d.task.task.data.currentRequestId ?? ''); const basis = versions.find(v => v.id === basisId)?.content ?? d.task.request; return <div className={s.stack}><h4>실제 업무 요청의 준비물 선택</h4><p className={s.notice}>현재 공개 요청과 형식·상품·조건이 호환되는 실제 항목만 공개할 수 있습니다. 규격을 바꾸려면 업무 요청에서 수정·공개한 뒤 확인하세요. 조건부 항목은 조건 부모도 함께 선택하세요.</p><label className={s.field}>참조할 공개 요청<select value={basisId} onChange={e => { const v = versions.find(x => x.id === e.target.value); if (v) { setBasisId(v.id);
    onChange({ ...value, request: { ...structuredClone(v.content), internalOriginal: '', internalMemo: '', requirements: [] } }); } }}><option value="">요청 내용으로 기준 바꾸기 (항목 다시 선택)</option>{versions.map(v => <option value={v.id} key={v.id}>요청 v{v.sequence}{v.id === d.task.task.data.currentRequestId ? ' · 현재' : ''}</option>)}</select></label><Field label="메뉴 준비물 요청 제목" required value={value.request.title} onChange={title => onChange({ ...value, request: { ...value.request, title } })}/><Field label="준비물 안내" multiline value={value.request.description} onChange={description => onChange({ ...value, request: { ...value.request, description } })}/><fieldset className={s.sub}><legend>포함할 요청 항목</legend>{(basis?.requirements ?? []).map(q => <label className={s.check} key={q.key}><input type="checkbox" checked={value.request.requirements.some(x => x.key === q.key)} onChange={e => onChange({ ...value, request: { ...value.request, requirements: e.target.checked ? [...value.request.requirements, structuredClone(q)] : value.request.requirements.filter(x => x.key !== q.key) } })}/>{q.label} · {typeLabels[q.type]} · {q.required ? '필수' : '선택'}{q.condition ? ' · 조건부' : ''}</label>)}{value.request.requirements.filter(q => !basis?.requirements.some(x => x.key === q.key)).map(q => <label className={s.check} key={q.key}><input type="checkbox" checked onChange={() => onChange({ ...value, request: { ...value.request, requirements: value.request.requirements.filter(x => x.key !== q.key) } })}/>{q.label} · 기존 메뉴의 원래 항목 (현재 선택 범위 밖)</label>)}</fieldset>{value.request.requirements.map(q => <details className={s.details} key={q.key}><summary>{q.label} · 규격·상품 범위</summary><p>{q.help}</p><p>{q.productIds.map(id => d.catalog.products.find(p => p.id === id)?.name ?? '상품 확인').join(', ') || '공통 항목'} · {q.unit}</p>{q.condition && <p>조건: {value.request.requirements.find(x => x.key === q.condition?.key)?.label ?? '부모 항목 확인'} = {q.condition.equals}</p>}{q.specifications.map((x, i) => <p key={i}>{x.severity === 'required' ? '필수' : '권장'} · {x.text} · {x.source} {x.version} · {x.check === 'human' ? '사람 확인' : '자동 규칙 대상'}</p>)}</details>)}<DeadlineEditor label="준비물 제출 기한" value={value.request.deadline} members={d.catalog.members} onChange={deadline => onChange({ ...value, request: { ...value.request, deadline } })}/><label className={s.field}>관련 요청 템플릿<select value={value.templateVersionId ?? ''} onChange={e => onChange({ ...value, templateVersionId: e.target.value || null })}><option value="">별도 연결 없음</option>{d.catalog.templates.map(x => <option key={x.id} value={x.id}>{x.name} v{x.sequence}</option>)}</select></label></div>; }
export function requestFromCurrent(c: Controller): RequestContent | null { const r = c.state.data?.task.request; return r ? { ...structuredClone(r), internalOriginal: '', internalMemo: '', requirements: [] } : null; }
