import {expect,type APIRequestContext,type Page,type TestInfo} from '@playwright/test';
import {randomUUID,createHash} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {api,post,get,login,ctx,origin,tracing} from '../tests/fixtures/notices';
import {content,create,extract} from '../tests/fixtures/ai-input-ui';
import {blankContent,blankRequirement} from '@/domain/tasks/types';
import {blankDraft} from '@/domain/submissions/types';
import type {AiReviewDetail,AiReviewWorkspace} from '@/server/ai-review/contracts';
import type {AiContent} from '@/server/ai-input/contracts';
import type {SubmissionWorkspace} from '@/server/submissions/contracts';
export {api,post,get,login,ctx,origin,tracing};
export const claim='合成テスト。絶対安全。No.1。根拠不明。';
export async function ready(r:APIRequestContext,text=claim,extra:Partial<AiContent>={}){const d=await create(r,{...content(text),title:'G16 合成 UI '+randomUUID().slice(0,6),...extra});await extract(r,d);return d;}
export async function start(r:APIRequestContext,inputId:string,versionId?:string){const w=await get<AiReviewWorkspace>(r,`/api/ai-review/inputs/${inputId}${versionId?`?versionId=${versionId}`:''}`);return post(r,`/api/ai-review/inputs/${inputId}/start`,{inputVersionId:w.inputVersionId,extractionRunId:w.extractionOptions[0].id,expectedRunId:w.runs[0]?.id??null,corpusReleaseId:w.corpus.id,corpusManifestHash:w.corpus.manifestHash,engine:'synthetic_demo',idempotencyKey:randomUUID()}) as Promise<{runId:string;detail:AiReviewDetail}>;}
export async function runDetail(r:APIRequestContext,id:string){return get<AiReviewDetail>(r,`/api/ai-review/runs/${id}`);}
export async function open(page:Page,id:string){await page.goto(`/ai-review/runs/${id}?context=${ctx}`);await expect(page.getByText('현재 권한과 저장본을 확인하는 중입니다.',{exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'분석 실행',exact:true})).toBeVisible();}
export function form(page:Page,findingId:string){return page.getByRole('form',{name:`후보 ${findingId} 사람 검토`,exact:true});}
export async function review(page:Page,id:string,decision:'accept'|'edit'|'reject',reason:string){const f=form(page,id);await f.getByRole('combobox').selectOption(decision);await f.getByRole('textbox',{name:'판단 사유 (필수)',exact:true}).fill(reason);if(decision==='edit')await f.getByRole('textbox',{name:'조정한 참고 수정안 (필수)',exact:true}).fill('合成参考修正文。');await f.getByRole('button',{name:'사람 검토 기록',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'사람 검토 기록을 저장했습니다.'})).toBeVisible();}
export async function record(info:TestInfo,name:string,value:unknown){await writeFile(info.outputPath(name+'.json'),JSON.stringify(value,null,2));}
export async function geometry(page:Page,info:TestInfo,name:string){await page.evaluate(()=>scrollTo(0,0));const configured=page.viewportSize()!,metrics=await page.evaluate(()=>({innerWidth,width:document.documentElement.scrollWidth,dpr:devicePixelRatio,controls:[...document.querySelectorAll('main h1,main h2,main button,main select,main textarea')].filter(e=>e.getClientRects().length).map(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right}))}));const view=await page.screenshot({path:info.outputPath(name+'-viewport-private.png')}),full=await page.screenshot({path:info.outputPath(name+'-full-private.png'),fullPage:true});await record(info,name+'-geometry',{configured,metrics,pngWidth:{viewport:view.readUInt32BE(16),full:full.readUInt32BE(16)}});expect(metrics.innerWidth).toBe(configured.width);expect(metrics.width).toBeLessThanOrEqual(configured.width);expect(metrics.controls.every(v=>v.left>=-1&&v.right<=configured.width+1)).toBe(true);expect(view.readUInt32BE(16)).toBe(configured.width*metrics.dpr);expect(full.readUInt32BE(16)).toBe(configured.width*metrics.dpr);}
export async function membership(r:APIRequestContext,status:'active'|'suspended'){const members=await get<{members:{id:string;revision:number;data:{userId:string;scope:string}}[]}>(r,`/api/contexts/${ctx}/members`),m=members.members.find(v=>v.data.userId==='user-gsg')!;const csrf=await(await r.get('/api/auth/csrf')).json();const response=await r.patch(`/api/contexts/${ctx}/members/${m.id}`,{headers:{Origin:origin(),'X-CSRF-Token':csrf.csrfToken},data:{expectedRevision:m.revision,status,scope:m.data.scope,internalPriceAccess:false}});expect(response.status(),await response.text()).toBe(200);}
export async function actualSubmission(admin:APIRequestContext,brand:APIRequestContext){const c=blankContent();c.title='G16 실제 제출 연결 '+randomUUID().slice(0,6);c.description='합성 제출 원문';c.deadline.responsibleUserId='user-gsg';c.requirements=[{...blankRequirement('claim','long_text'),label:'일본어 문안'}];const taskId=(await post(admin,'/api/tasks',{category:'spot',content:c,targets:[{contextId:ctx,ownerId:'user-gsg',assigneeId:'user-luna',coAssigneeIds:[],productIds:[]}],idempotencyKey:randomUUID()},201)).ids[0];await post(admin,`/api/tasks/${taskId}`,{command:'publish',expectedRevision:1,idempotencyKey:randomUUID()});let w=await get<SubmissionWorkspace>(brand,`/api/tasks/${taskId}/submissions`);await post(brand,`/api/tasks/${taskId}/submission-draft`,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:0,content:{...blankDraft(),answers:[{requestId:w.request.id,requirementKey:'claim',productId:null,type:'long_text',input:{text:claim}}]},idempotencyKey:randomUUID()});w=await get<SubmissionWorkspace>(brand,`/api/tasks/${taskId}/submissions`);const submissionId=(await post(brand,`/api/tasks/${taskId}/submissions`,{baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,expectedTaskRevision:w.taskRevision,mode:'full',idempotencyKey:randomUUID()},201)).ids[0];return{taskId,requestId:w.request.id,submissionId,productUseIds:[]};}
export async function captureRSC(page:Page,info:TestInfo){const rows:{url:string;path:string;sha256:string;status:number;contentType:string}[]=[];await page.route(/_rsc=/,async route=>{const response=await route.fetch(),bytes=await response.body(),path=info.outputPath(`clicked-rsc-${rows.length}-private.txt`);await writeFile(path,bytes);rows.push({url:route.request().url(),path,sha256:createHash('sha256').update(bytes).digest('hex'),status:response.status(),contentType:response.headers()['content-type']??''});await route.fulfill({response});});return rows;}
