import assert from 'node:assert/strict';
import { randomUUID,createHash } from 'node:crypto';
import { spawn,execFileSync,type ChildProcess } from 'node:child_process';
import { createWriteStream,mkdirSync,mkdtempSync,writeFileSync,readFileSync,symlinkSync } from 'node:fs';
import { createServer } from 'node:net';
import path from 'node:path';
import { openDatabase,migrate } from '@/server/db/database';
import { createSqliteRepository } from '@/server/repositories/sqlite';
import { seed } from '@/server/db/seed';
import { DEMO_PASSWORD } from '@/domain/catalog';
import { SYNTHETIC_TEXT } from '@/server/ai-input/provenance';
import type { AiContent,AiInputDetail,AiAsset,AiSourcePicker } from '@/server/ai-input/contracts';
import type { SubmissionWorkspace,SubmissionSnapshot } from '@/server/submissions/read';
import type { ProductDetail } from '@/server/products/service';
import { blankContent,blankRequirement } from '@/domain/tasks/types';
import { blankDraft } from '@/domain/submissions/types';
const mode=process.env.AI_INPUT_MODE??'sqlite';assert(['mock','sqlite'].includes(mode));
const port=Number(process.env.E2E_PORT??4233),aux=Number(process.env.E2E_AUX_PORT??4234);assert(port!==aux);
const root=path.resolve(process.env.AI_INPUT_ROOT??'.local/g15-http');mkdirSync(root,{recursive:true});const directory=mkdtempSync(path.join(root,`${mode}-`)),database=path.join(directory,'ai.db'),files=path.join(directory,'files'),report=path.resolve(process.env.AI_INPUT_REPORT??path.join(directory,'report.json'));mkdirSync(path.dirname(report),{recursive:true});
const planned=['H01','H02','H03','H04','H05','H06','H07','H08','H09-unknown','H09-medicated','H09-nonja','H09-nonpop','H10','H11','H12','H13','H14','H15-locked.pdf','H15-corrupt.pdf','H15-blank.pdf','H15-low-contrast.png','H16','H17','H18','H19','H20','H21','H22','H23','H24','H25'];
const candidate=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),cwd=process.cwd(),startAt=new Date().toISOString();
const sha=(b:string|Buffer)=>createHash('sha256').update(b).digest('hex');
const checks:{id:string;requirements:string[];level:string;status:'PASS'|'FAIL'|'SKIP';reason?:string}[]=[],transcript:{url:string;method:string;status:number;path:string;sha256:string}[]=[],processes:{pid?:number;port:number;cwd:string;argv:string[];log:string;stopped?:boolean;exitCode?:number|null;signal?:string|null}[]=[];const children=new Map<number,ChildProcess>();let failure:string|undefined;
const check=(id:string,condition:unknown,requirements=['AC-15-03'],level='HTTP')=>{checks.push({id,requirements,level,status:condition?'PASS':'FAIL'});assert(condition,id);};
async function capture(response:Response,method:string,url:string){const b=Buffer.from(await response.clone().arrayBuffer()),p=`${report}.responses/${String(transcript.length+1).padStart(4,'0')}.body`;mkdirSync(path.dirname(p),{recursive:true});writeFileSync(p,b,{mode:0o600});transcript.push({url,method,status:response.status,path:p,sha256:sha(b)});}
async function free(p:number){await new Promise<void>((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(p,'127.0.0.1',()=>s.close(e=>e?reject(e):resolve()));});}
async function start(p=port,serverCwd=cwd){await free(p);const origin=`http://127.0.0.1:${p}`,args=['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(p)],log=`${report}.server-${processes.length+1}.log`,out=createWriteStream(log,{mode:0o600});const child=spawn(process.execPath,args,{cwd:serverCwd,stdio:['ignore','pipe','pipe'],env:{...process.env,DATA_SOURCE:mode,DATABASE_FILE:database,FILE_STORAGE_DIR:files,APP_ORIGIN:origin,SESSION_COOKIE_NAME:`gs_hale_g15_${p}`,OPENAI_API_KEY:'',OPENAI_MODEL:'',OPENAI_BASE_URL:'https://api.openai.com/v1',NEXT_TELEMETRY_DISABLED:'1'}});children.set(p,child);processes.push({pid:child.pid,port:p,cwd:serverCwd,argv:[process.execPath,...args],log});child.stdout!.pipe(out,{end:false});child.stderr!.pipe(out,{end:false});child.once('exit',()=>out.end());for(let n=0;n<200;n++){if(child.exitCode!==null)throw Error('owned server exited');try{if((await fetch(origin+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,50));}throw Error('server readiness');}
async function stop(p:number){const child=children.get(p);if(!child)return;const closed=new Promise<void>(r=>child.once('exit',()=>r()));child.kill('SIGTERM');if(child.exitCode===null&&child.signalCode===null)await closed;Object.assign(processes.findLast(x=>x.pid===child.pid)!,{stopped:true,exitCode:child.exitCode,signal:child.signalCode});children.delete(p);}
class Client{cookie='';constructor(readonly slot=port){}get origin(){return`http://127.0.0.1:${this.slot}`;}async send(url:string,method='GET',body?:unknown,csrf?:string){const r=await fetch(this.origin+url,{method,redirect:'manual',headers:{Cookie:this.cookie,...method!=='GET'?{'Content-Type':'application/json',Origin:this.origin,'X-CSRF-Token':csrf??''}:{}},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie')!.split(';')[0];await capture(r,method,url);return r;}async get<T>(url:string){const r=await this.send(url);assert.equal(r.status,200,await r.clone().text());return r.json() as Promise<T>;}async mutate(url:string,body:unknown,method='POST'){const csrf=await this.get<{csrfToken:string}>('/api/auth/csrf');return this.send(url,method,body,csrf.csrfToken);}async ok<T>(url:string,body:unknown,method='POST'){const r=await this.mutate(url,body,method);assert([200,201].includes(r.status),await r.clone().text());return r.json() as Promise<T>;}async login(email:string){await this.ok('/api/auth/login',{email,password:DEMO_PASSWORD});}async form(url:string,form:FormData){const csrf=await this.get<{csrfToken:string}>('/api/auth/csrf'),r=await fetch(this.origin+url,{method:'POST',headers:{Cookie:this.cookie,Origin:this.origin,'X-CSRF-Token':csrf.csrfToken},body:form});await capture(r,'POST multipart',url);return r;}}
const A='ctx-jp-a-luna',brand=new Client(),admin=new Client(),gsg=new Client(),foreign=new Client();
const content=(text=SYNTHETIC_TEXT):AiContent=>({title:'G15 합성 실제 HTTP',scope:{classification:'general_cosmetic',language:'ja',media:'pop',use:'매장'},kind:'text',text,sources:[],selectedPages:[],submission:null,products:[]});
const create=(c=content(),client=brand,visibility='context')=>client.ok<AiInputDetail>('/api/ai-input',{contextId:A,visibility,content:c,idempotencyKey:randomUUID()});
const detail=(id:string,c=brand)=>c.get<AiInputDetail>(`/api/ai-input/${id}`);
const extract=(d:AiInputDetail,c=brand,body={versionId:d.version.id,expectedRunId:null as string|null,idempotencyKey:randomUUID()})=>c.ok<{runId:string;detail:AiInputDetail}>(`/api/ai-input/${d.id}/extract`,body);
async function upload(filename:string,client=brand,vis='context',key=randomUUID(),bytes=readFileSync(`tests/fixtures/ai-input/${filename}`)){const form=new FormData();form.append('file',new Blob([new Uint8Array(bytes)],{type:filename.endsWith('.pdf')?'application/pdf':'image/png'}),filename);form.append('idempotencyKey',key);const response=await client.form(`/api/ai-input/assets?contextId=${A}&visibility=${vis}`,form);assert.equal(response.status,200,await response.clone().text());return response.json() as Promise<AiAsset>;}
const binaryContent=(a:AiAsset,kind:'pdf'|'images',pages=[1]):AiContent=>({...content(),kind,text:null,sources:[{kind:'upload',assetId:a.id}],selectedPages:kind==='pdf'?pages:[]});
async function setMember(status:'active'|'suspended'){const data=await admin.get<{members:{id:string;revision:number;data:{userId:string}}[]}>(`/api/contexts/${A}/members`);const m=data.members.find(m=>m.data.userId==='user-luna');assert(m);await admin.ok(`/api/contexts/${A}/members/${m.id}`,{expectedRevision:m.revision,status},'PATCH');}
async function waitReading(d:AiInputDetail){for(let n=0;n<100;n++){const current=await detail(d.id);if(current.runs[0]?.state==='reading')return;await new Promise(r=>setTimeout(r,20));}throw Error('reading not observed');}
try{
 if(mode==='sqlite'){const db=openDatabase(database,true);migrate(db);const repo=createSqliteRepository(db);await seed(repo);repo.close();}
 await start();await brand.login('luna@example.test');await admin.login('admin@example.test');await gsg.login('operator@example.test');await foreign.login('wave@example.test');
 const d=await create(),body={versionId:d.version.id,expectedRunId:null,idempotencyKey:randomUUID()},first=await extract(d,brand,body);check('H01 actual text persisted snapshot and restricted analysis capability, no provider',first.detail.runs[0].snapshot?.text===SYNTHETIC_TEXT&&JSON.stringify(first.detail.analysis)===JSON.stringify({connected:true,status:'RESTRICTED',url:null,providerCalled:false}),['AC-15-01','AC-15-04']);check('H02 same extract intent stable', (await extract(d,brand,body)).runId===first.runId);
 const v2=await brand.ok<AiInputDetail>(`/api/ai-input/${d.id}/versions`,{expectedRevision:d.revision,content:content('새 입력'),idempotencyKey:randomUUID()});check('H03 old exact version retained across v2',(await brand.get<AiInputDetail>(`/api/ai-input/${d.id}?versionId=${d.version.id}`)).runs[0].snapshot?.snapshotHash===first.detail.runs[0].snapshot?.snapshotHash&&v2.version.sequence===2);
 check('H04 stale CAS and invented version rejected',(await brand.mutate(`/api/ai-input/${d.id}/versions`,{expectedRevision:d.revision,content:content(),idempotencyKey:randomUUID()})).status===409&&(await brand.send(`/api/ai-input/${d.id}?versionId=forged`)).status===404);
 check('H05 exact registered synthetic ready locally only',(await brand.ok<{allowed:boolean;providerCalled:boolean}>(`/api/ai-input/${d.id}/transfer-readiness`,{runId:first.runId})).allowed,['AC-15-04']);const u=await create(content('public synthetic checkbox is not proof')),ur=await extract(u);check('H06 unregistered text denied transfer',(await brand.ok<{allowed:boolean}>(`/api/ai-input/${u.id}/transfer-readiness`,{runId:ur.runId})).allowed===false,['AC-15-04']);
 check('H07 client provenance/unknown keys rejected',(await brand.mutate('/api/ai-input',{contextId:A,visibility:'context',content:content(),idempotencyKey:randomUUID(),synthetic:true})).status===422,['AC-15-04']);
 const hidden=await create(content('PRIVATE_G15_CANARY'),gsg,'staff');check('H08 brand private detail/list and other-context boundary',(await brand.send(`/api/ai-input/${hidden.id}`)).status===404&&!(JSON.stringify(await brand.get(`/api/ai-input?contextId=${A}`)).includes(hidden.id))&&(await foreign.send(`/api/ai-input/${d.id}`)).status===404,['A19','AC-15-04']);
 for(const [name,change]of Object.entries({unknown:{classification:'unknown'},medicated:{classification:'medicated'},nonja:{language:'ko'},nonpop:{media:'website'}})){const out=await create({...content(),scope:{...content().scope,...change}});check(`H09-${name} honest out-of-scope`,(await extract(out)).detail.runs[0].state==='out_of_scope',['AC-15-01']);}
 const max=await create(content('肌'.repeat(10000)));check('H10 10000 Unicode exact',(await extract(max)).detail.runs[0].snapshot?.characterCount===10000);check('H11 10001/empty denied',(await brand.mutate('/api/ai-input',{contextId:A,visibility:'context',content:content('肌'.repeat(10001)),idempotencyKey:randomUUID()})).status===422&&(await brand.mutate('/api/ai-input',{contextId:A,visibility:'context',content:content(' '),idempotencyKey:randomUUID()})).status===422);
 const pdf=await upload('native-12.pdf'),pdfD=await create(binaryContent(pdf,'pdf',[2,10])),pdfR=await extract(pdfD);check('H12 production PDF worker selected pages only',pdfR.detail.runs[0].snapshot?.text.includes('PAGE_02')&&pdfR.detail.runs[0].snapshot?.text.includes('PAGE_10')&&!pdfR.detail.runs[0].snapshot?.text.includes('PAGE_01')&&pdfR.detail.runs[0].snapshot?.units.filter(u=>u.status==='unselected').length===10,['AC-15-02']);check('H13 actual authorized source download hash',sha(Buffer.from(await(await brand.send(pdfR.detail.sources[0].url!)).arrayBuffer()))===pdf.sha256,['AC-15-02']);
 const img=await upload('japanese.png'),imgD=await create(binaryContent(img,'images')),imgR=await extract(imgD);check('H14 actual Japanese OCR local assets partial readable',imgR.detail.runs[0].snapshot?.status==='partial'&&!!imgR.detail.runs[0].snapshot?.text&&!!imgR.detail.runs[0].snapshot?.engines.languageAssetSha256&&imgR.detail.runs[0].snapshot?.issues.includes('OCR_COVERAGE_UNKNOWN'),['AC-15-03']);
 for(const[name,issue]of [['locked.pdf','PDF_LOCKED'],['corrupt.pdf','PDF_CORRUPT'],['blank.pdf','NO_TEXT'],['low-contrast.png','LOW_CONTRAST']]as const){const a=await upload(name),input=await create(binaryContent(a,name.endsWith('.pdf')?'pdf':'images')),r=await extract(input);check(`H15-${name} unread explicit`,r.detail.runs[0].state==='unread'&&r.detail.runs[0].snapshot?.issues.includes(issue)&&r.detail.runs[0].snapshot?.text==='',['AC-15-03']);}
 check('H16 page11/fifth image rejected',(await brand.mutate('/api/ai-input',{contextId:A,visibility:'context',content:{...binaryContent(pdf,'pdf'),selectedPages:Array.from({length:11},(_,i)=>i+1)},idempotencyKey:randomUUID()})).status===422&&(await brand.mutate('/api/ai-input',{contextId:A,visibility:'context',content:{...binaryContent(img,'images'),sources:Array.from({length:5},()=>({kind:'upload',assetId:img.id}))},idempotencyKey:randomUUID()})).status===422);
 const secret=await upload('japanese.png',gsg,'staff');check('H17 internal asset denied and cannot be made context input',(await brand.send(secret.url)).status===404&&(await gsg.mutate('/api/ai-input',{contextId:A,visibility:'context',content:binaryContent(secret,'images'),idempotencyKey:randomUUID()})).status===422,['A19','AC-15-04']);
 const c={...blankContent(),title:'G15 HTTP 실제 S1/S2',description:'PDF를 제출해 주세요',deadline:{...blankContent().deadline,responsibleUserId:'user-gsg'},requirements:[{...blankRequirement('pdf','file'),label:'제출 PDF'}]},created=await admin.ok<{ids:string[]}>('/api/tasks',{targets:[{contextId:A,ownerId:'user-gsg',assigneeId:'user-luna',coAssigneeIds:[],productIds:['product-serum']}],content:c,category:'spot',idempotencyKey:randomUUID()}),taskId=created.ids[0];const task=await admin.get<{task:{revision:number}}>(`/api/tasks/${taskId}`);await admin.ok(`/api/tasks/${taskId}`,{command:'publish',expectedRevision:task.task.revision,idempotencyKey:randomUUID()});let w=await brand.get<SubmissionWorkspace>(`/api/tasks/${taskId}/submissions`);const sf=new FormData();sf.append('files',new Blob([new Uint8Array(readFileSync('tests/fixtures/ai-input/native-12.pdf'))],{type:'application/pdf'}),'submitted.pdf');sf.append('clientItemIds',randomUUID());const sfR=await brand.form(`/api/tasks/${taskId}/submission-files?requestId=${w.request.id}`,sf);assert.equal(sfR.status,200);const sfFile=(await sfR.json()).items[0];assert.equal(sfFile.state,'ready');const product=await brand.get<ProductDetail>(`/api/products/product-serum?context=${A}`);const draft={...blankDraft(),answers:[{requestId:w.request.id,requirementKey:'pdf',productId:null,type:'file',input:{fileVersionIds:[sfFile.file.id]}}],productSelections:[{productId:product.productId,expectedCommonRevision:product.commonRevision,expectedContextRevision:product.contextRevision,bindingIds:[],retailPriceVersionId:null,asOfDate:'2026-09-21'}]};
 async function submit(narrative:string){w=await brand.get<SubmissionWorkspace>(`/api/tasks/${taskId}/submissions`);await brand.ok(`/api/tasks/${taskId}/submission-draft`,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:w.draft?.revision??0,content:{...draft,narrative},idempotencyKey:randomUUID()});w=await brand.get<SubmissionWorkspace>(`/api/tasks/${taskId}/submissions`);return(await brand.ok<{ids:string[]}>(`/api/tasks/${taskId}/submissions`,{baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,expectedTaskRevision:w.taskRevision,mode:'full',idempotencyKey:randomUUID()})).ids[0];}
 const s1=await submit('S1'),snap=await brand.get<SubmissionSnapshot>(`/api/submissions/${s1}`),use=snap.products[0],linked=await create({...binaryContent(pdf,'pdf',[2]),sources:[{kind:'submission_file',fileVersionId:sfFile.file.id}],submission:{taskId,requestId:snap.requestId,submissionId:s1,productUseIds:[use.id]},products:[{productId:use.productId,productVersionId:use.productVersionId,contextProductVersionId:use.contextProductVersionId}]}),s2=await submit('S2'),lr=await extract(linked);check('H18 real S1 file/request/product use preserved after S2',s1!==s2&&lr.detail.submission?.submissionId===s1&&lr.detail.sources[0].sourceId===sfFile.file.id&&lr.detail.version.content.products[0].productVersionId===use.productVersionId,['G05','G06','AC-15-02']);
 const picker=await brand.get<AiSourcePicker>(`/api/ai-input/sources?contextId=${A}`);check('H19 actual picker contains S1/S2 no private-price properties',picker.submissions.some(s=>s.id===s1)&&picker.submissions.some(s=>s.id===s2)&&!JSON.stringify(picker).includes('internalPrice'),['A19','G05']);
 const four=[img,...await Promise.all([1,2,3].map(()=>upload('japanese.png')))],revokeD=await create({...binaryContent(img,'images'),sources:four.map(a=>({kind:'upload',assetId:a.id}))});const pending=brand.mutate(`/api/ai-input/${revokeD.id}/extract`,{versionId:revokeD.version.id,expectedRunId:null,idempotencyKey:randomUUID()});await waitReading(revokeD);await setMember('suspended');const denied=await pending;check('H20 current revoke during real OCR denies source/result',denied.status===404&&!JSON.stringify(await denied.json()).includes('PRIVATE_G15_CANARY'),['A19','AC-15-04']);await setMember('active');check('H21 sanitized failed run retains no snapshot',(await detail(revokeD.id)).runs[0].issue==='ACCESS_CHANGED'&&(await detail(revokeD.id)).runs[0].snapshot===null,['A19']);
 if(mode==='sqlite'){
  await start(aux);const second=new Client(aux);await second.login('luna@example.test');const raceD=await create({...binaryContent(img,'images'),sources:four.map(a=>({kind:'upload',assetId:a.id}))}),raceBody={versionId:raceD.version.id,expectedRunId:null,idempotencyKey:randomUUID()},race1=extract(raceD,brand,raceBody);await waitReading(raceD);const race2=await extract(raceD,second,raceBody),raceDone=await race1;check('H22 two OS processes one durable claim/run/snapshot',race2.runId===raceDone.runId&&raceDone.detail.runs.length===1&&raceDone.detail.runs[0].attempt===1,['AC-15-03'],'PROCESS');await stop(aux);const before=await detail(pdfD.id),oldPid=processes.findLast(p=>p.port===port)!.pid;await stop(port);await start();const fresh=new Client();await fresh.login('luna@example.test');const after=await detail(pdfD.id,fresh);check('H23 fresh PID/login preserves exact version/hash/files',processes.findLast(p=>p.port===port)!.pid!==oldPid&&after.version.id===before.version.id&&after.runs[0].snapshot?.snapshotHash===before.runs[0].snapshot?.snapshotHash&&sha(Buffer.from(await(await fresh.send(after.sources[0].url!)).arrayBuffer()))===pdf.sha256,['AC-15-02'],'PROCESS');brand.cookie=fresh.cookie;
 await start(aux);const crashing=new Client(aux);await crashing.login('luna@example.test');const crashD=await create({...binaryContent(img,'images'),sources:four.map(a=>({kind:'upload',assetId:a.id}))}),crashBody={versionId:crashD.version.id,expectedRunId:null,idempotencyKey:randomUUID()};const lost=crashing.mutate(`/api/ai-input/${crashD.id}/extract`,crashBody).then(()=>false,()=>true);await waitReading(crashD);const child=children.get(aux)!,closed=new Promise<void>(r=>child.once('exit',()=>r()));child.kill('SIGKILL');await closed;Object.assign(processes.findLast(x=>x.pid===child.pid)!,{stopped:true,exitCode:child.exitCode,signal:child.signalCode});children.delete(aux);assert(await lost,'actual in-flight connection lost on process crash');const crashed=await detail(crashD.id),crashRun=crashed.runs[0];assert.equal(crashRun.state,'reading');
  // Isolated test DB time fixture after a real killed worker claim, without modifying product clock/routes.
  const fixtureRepo=createSqliteRepository(openDatabase(database));const oldRun=await fixtureRepo.get('aiRun',crashRun.id);assert(oldRun);await fixtureRepo.transaction(s=>{const row=s.get('aiRun',crashRun.id)!;s.update('aiRun',row.id,row.revision,{...row.data,leaseUntil:new Date(Date.now()-1000).toISOString()});});const expired=await fixtureRepo.get('aiRun',crashRun.id);fixtureRepo.close();writeFileSync(`${report}.crash-lease-expiry-fixture.json`,JSON.stringify({meaning:'Actual OS process SIGKILL after durable claim; elapsed lease represented by isolated DB fixture, not 90s wall time wait',oldRun,expired},null,2));const interrupted=await detail(crashD.id),recovered=await extract(crashD,brand,{...crashBody,expectedRunId:crashRun.id,idempotencyKey:randomUUID()});check('H25 actual crash durable claim explicit expired-lease retry',interrupted.runs[0].state==='interrupted'&&recovered.detail.runs[0].attempt===2&&recovered.detail.runs[0].state==='finished'&&recovered.detail.runs.find(r=>r.id===crashRun.id)?.issue==='INTERRUPTED',['AC-15-03'],'PROCESS_AND_EXPIRED_LEASE_DB_FIXTURE');
 }else for(const id of ['H22','H23','H25'])checks.push({id:`${id} durable SQLite-only`,requirements:['AC-15-03'],level:'PROCESS',status:'SKIP',reason:'Mock is process-local; actual SQLite run verifies persistence/claim.'});
 const deploy=path.join(directory,'missing-worker-deployment');mkdirSync(deploy);symlinkSync(path.join(cwd,'.next'),path.join(deploy,'.next'),'dir');symlinkSync(path.join(cwd,'node_modules'),path.join(deploy,'node_modules'),'dir');writeFileSync(path.join(deploy,'package.json'),'{"type":"module"}');await start(aux,deploy);const unavailable=new Client(aux);await unavailable.login('luna@example.test');const unavailableAsset=await upload('native-12.pdf',unavailable),unavailableD=await create(binaryContent(unavailableAsset,'pdf'),unavailable),unavailableRun=await extract(unavailableD,unavailable);check('H24 actual production missing worker is explicit failed/unread',unavailableRun.detail.runs[0].state==='failed'&&['WORKER_FAILED','WORKER_UNAVAILABLE'].includes(unavailableRun.detail.runs[0].issue??'')&&unavailableRun.detail.runs[0].snapshot?.text==='', ['AC-15-03'],'PROCESS');
}catch(error){failure=error instanceof Error?error.stack:String(error);process.exitCode=1;}finally{for(const p of [...children.keys()])await stop(p);writeFileSync(report,JSON.stringify({candidate,cwd,sourceDirty:execFileSync('git',['status','--porcelain'],{encoding:'utf8'}),mode,startedAt:startAt,endedAt:new Date().toISOString(),providerCalls:0,normalProductionStartup:true,fixtureMode:'Actual authorized HTTP producers; no injected product endpoint or mock repo cache',directory,database,files,checks,counts:{pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length,skip:checks.filter(c=>c.status==='SKIP').length,unit:'assertion'},notRun:planned.filter(id=>!checks.some(c=>c.id.split(' ')[0]===id)),failure,transcript,processes},null,2)+'\n',{mode:0o600});console.log(JSON.stringify({report,pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length,failure}));}
