import {expect,request as apiRequest,type APIRequestContext,type Page,type TestInfo} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {blankCommon,blankFileBinding} from '@/domain/products/types';
import {blankContent,blankRequirement} from '@/domain/tasks/types';
import {blankDraft} from '@/domain/submissions/types';
import type {ProductDetail} from '@/server/products/service';
import type {EvidenceSources} from '@/server/evidence/contracts';
import type {TaskDetail} from '@/server/tasks/service';
import type {SubmissionWorkspace,SubmissionSnapshot} from '@/server/submissions/contracts';
export const contextId='ctx-jp-a-luna',origin=()=>`http://127.0.0.1:${process.env.E2E_PORT}`;
export async function get<T>(r:APIRequestContext,url:string):Promise<T>{const response=await r.get(url);expect(response.status(),url).toBe(200);return response.json();}
export async function post<T>(r:APIRequestContext,url:string,data:unknown,status=200):Promise<T>{const csrf=await get<{csrfToken:string}>(r,'/api/auth/csrf');const response=await r.post(url,{data,headers:{Origin:origin(),'X-CSRF-Token':csrf.csrfToken}});expect(response.status(),`${url}: ${await response.text()}`).toBe(status);return response.json();}
export async function login(r:APIRequestContext,email='admin@example.test'){await post(r,'/api/auth/login',{email,password:'Demo-Hale-2026!'});}
export async function command(r:APIRequestContext,id:string,command:string,extra:Record<string,unknown>={}){const t=await get<TaskDetail>(r,`/api/tasks/${id}`);return post(r,`/api/tasks/${id}`,{command,expectedRevision:t.task.revision,idempotencyKey:randomUUID(),...extra});}
export async function product(r:APIRequestContext,name:string,code=`UI-${randomUUID()}`){const made=await post<{ids:string[]}>(r,'/api/products',{contextId,brandId:'brand-luna',common:{...blankCommon(),name,code},idempotencyKey:randomUUID()},201);return made.ids[0];}
export async function evidenceFixture(page:Page){const admin=await apiRequest.newContext({baseURL:origin()}),brand=await apiRequest.newContext({baseURL:origin()});await login(admin);await login(brand,'luna@example.test');try{const suffix=randomUUID().slice(0,6),names=['자료 상품 A','자료 상품 B','범위 밖 C'].map(n=>`${n} ${suffix}`),products:string[]=[];for(const name of names)products.push(await product(admin,name));const csrf=await get<{csrfToken:string}>(admin,'/api/auth/csrf'),buffer=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a+ZkAAAAASUVORK5CYII=','base64');const response=await admin.post(`/api/files?contextId=${contextId}&productId=${products[0]}`,{headers:{Origin:origin(),'X-CSRF-Token':csrf.csrfToken},multipart:{visibility:'public',files:{name:'갱신-청구서.png',mimeType:'image/png',buffer}}});expect(response.status()).toBe(201);const fileId=(await response.json()).files[0].id as string,p=await get<ProductDetail>(admin,`/api/products/${products[0]}?context=${contextId}`);await post(admin,`/api/products/${products[0]}`,{command:'save_files',contextId,expectedContextRevision:p.contextRevision,files:[{...blankFileBinding('invoice',fileId),title:'갱신 청구서',documentType:'청구서',productIds:products.slice(0,2)}],idempotencyKey:randomUUID()});
 const content={...blankContent(),description:'합성 실제 자료 제출 요청',title:`자료표 요청 ${randomUUID().slice(0,6)}`,requirements:[{...blankRequirement('file','file'),label:'원문 자료'},{...blankRequirement('human','file'),label:'사람 확인 자료',specifications:[{text:'서명 확인',source:'합성 규정',version:'1',severity:'required' as const,check:'human' as const}]},{...blankRequirement('missing','long_text'),label:'필수 미제출'},{...blankRequirement('text','long_text'),label:'제출 내용'}]};content.deadline.responsibleUserId='user-gsg';const t=await post<{ids:string[]}>(admin,'/api/tasks',{category:'spot',content,targets:[{contextId,ownerId:'user-gsg',assigneeId:'user-luna',coAssigneeIds:[],productIds:products.slice(0,2)}],idempotencyKey:randomUUID()},201),taskId=t.ids[0];await command(admin,taskId,'publish');const w=await get<SubmissionWorkspace>(brand,`/api/tasks/${taskId}/submissions`);await post(brand,`/api/tasks/${taskId}/submission-draft`,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:0,content:{...blankDraft(),productSelections:w.products.map(p=>({productId:p.productId,expectedCommonRevision:p.commonRevision,expectedContextRevision:p.contextRevision,bindingIds:p.bindings.map(b=>b.id),retailPriceVersionId:null,asOfDate:'2026-09-21'})),answers:[...['file','human'].map(requirementKey=>({requestId:w.request.id,requirementKey,productId:null,type:'file',input:{fileVersionIds:[fileId]}})),{requestId:w.request.id,requirementKey:'text',productId:null,type:'long_text',input:{text:'실제 제출한 설명'}}]},idempotencyKey:randomUUID()});const saved=await get<SubmissionWorkspace>(brand,`/api/tasks/${taskId}/submissions`),made=await post<{ids:string[]}>(brand,`/api/tasks/${taskId}/submissions`,{baseRequestId:w.request.id,expectedDraftRevision:saved.draft!.revision,expectedTaskRevision:saved.taskRevision,mode:'partial',idempotencyKey:randomUUID()},201),submission=await get<SubmissionSnapshot>(brand,`/api/submissions/${made.ids[0]}`);expect(submission.answers).toHaveLength(3);expect(submission.products.map(p=>p.productId).sort()).toEqual(products.slice(0,2).sort());expect(submission.products.find(p=>p.productId===products[0])!.files[0].fileVersionId).toBe(fileId);await login(page.request);const sources=await get<EvidenceSources>(page.request,`/api/evidence/sources?context=${contextId}`),sourceIndex=sources.items.findIndex(s=>s.source.kind==='product_binding'&&s.source.fileVersionId===fileId);expect(sourceIndex).toBeGreaterThanOrEqual(0);return {products,names,fileId,taskId,submission,sourceIndex};}finally{await admin.dispose();await brand.dispose();}}
export async function capture(page:Page,info:TestInfo){await writeFile(info.outputPath('final-dom-private.html'),await page.content());await page.screenshot({path:info.outputPath(info.status===info.expectedStatus?'final-private.png':'failure-private.png'),fullPage:true});await page.context().tracing.stop({path:info.outputPath('journey-private-trace.zip')});}
