/** Actual PostgreSQL stored-corruption regression. Synthetic DB stages; no upload/provider calls. */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {execFileSync} from 'node:child_process';
import {parsePostgresConfig} from '@/server/postgres/config';
import {createPostgresRepository} from '@/server/postgres/repository';
import {IdentityService} from '@/server/auth/service';
import {ImportService,type SourceStage,type PreviewStage} from '@/server/imports/service';
import {authorizedPrivateJsonResponse} from '@/server/imports/storage-http';
import {createImportStage} from '@/server/storage/staging';
import {digest} from '@/domain/storage/validate';
import {createFixture,fixtureIds} from './verify-storage-app-shared';
const [envFile,out]=process.argv.slice(2);if(!envFile?.startsWith('/')||!out?.startsWith('/'))throw Error('Absolute paths required');
const original=readFileSync(envFile),env=parseEnv(original.toString()),schema=process.env.S4_SCHEMA||'gs_hale_storage_excel_ai_20260922';if(!/^gs_hale_storage_excel_ai(?:_ind)?_[a-z0-9_]{1,25}$/.test(schema))throw Error('Own schema required');
const repo=createPostgresRepository(parsePostgresConfig({...env,SUPABASE_DB_SCHEMA:schema},'migration')),clock=()=>new Date().toISOString(),runId=randomUUID(),f=fixtureIds(runId),service=new ImportService(new IdentityService(repo,clock));
const report={candidate:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),cwd:process.cwd(),pid:process.pid,session:process.env.CODEX_THREAD_ID,schema,runId,startedAt:clock(),checks:[] as {name:string;status:string;details?:unknown}[],sourceKind:'Synthetic own DB stages, not public-input injection',storageHTTPCalls:0,providerCalls:0,envUnchanged:false};
writeFileSync(out,JSON.stringify(report,null,2),{flag:'wx',mode:0o600});const save=()=>writeFileSync(out,JSON.stringify(report,null,2)+'\n',{mode:0o600});const pass=(name:string,details?:unknown)=>{report.checks.push({name,status:'PASS',details});save();};let stage='setup';
const preview=(id:string,fields:string[])=>service.preview(f.token,{sourceId:id,sheetId:1,headerRow:1,mapping:fields.map((field,i)=>({column:i+1,field})),choices:[]});
async function source(code:string,privatePrice=false){const fields=['contextKey','common.code','common.name',...privatePrice?['internal.supplyAmount','internal.currency']:['local.jan']],values=[f.contextId,code,'合成価格検証',...privatePrice?['731927.0001','JPY']:['0000123']],payload:SourceStage={actorId:f.userId,contextId:f.contextId,name:'synthetic-db-fixture.xlsx',sourceHash:digest(JSON.stringify([fields,values])),createdAt:clock(),workbook:{date1904:false,omittedHiddenSheets:0,sheets:[{id:1,name:'商品',hidden:false,mergedRanges:[],rows:[fields,values].map((row,i)=>({row:i+1,hidden:false,cells:row.map((text,j)=>({column:j+1,type:'text',text,error:null,hidden:false}))}))}]}};const made=await repo.transaction(s=>createImportStage(s,f.userId,{contextId:f.contextId,stageType:'source',sourceObjectId:null,sourceStageId:null,sourceHash:payload.sourceHash,payload},Date.parse(clock())));return {id:made.id,fields};}
async function corrupted(id:string,mutate:(value:PreviewStage)=>void){const original=(await repo.get('importStage',id))!,value=JSON.parse(original.data.payload!) as PreviewStage;mutate(value);const payload=JSON.stringify(value),next=randomUUID();await repo.transaction(s=>s.create('importStage',{id:next,contextId:f.contextId,data:{...original.data,payload,payloadHash:digest(payload)}}));return next;}
const metadata=(id:string)=>authorizedPrivateJsonResponse(new Request(`https://app.invalid/api/imports/preview/${id}?transfer=1`),()=>service.readPreview(f.token,id),id,`/api/imports/preview/${id}`);
try{
 await createFixture(repo,runId,clock);await repo.transaction(async s=>{const c=(await s.get('context',f.contextId))!;await s.update('context',c.id,c.revision,{...c.data,brandId:'brand-luna'});});
 stage='PG01 public preview valid hash and immutable source preserved';const initial=await source('PUBLIC-'+runId.slice(0,8)),p=await preview(initial.id,initial.fields),originalPreview=(await repo.get('importStage',p.id))!;assert.equal(p.canApply,true);assert(!JSON.stringify(p).includes('internal.'));const beforeWrites=digest(JSON.stringify(await Promise.all([repo.list('productVersion',f.contextId),repo.list('internalPriceVersion',f.contextId),repo.list('importBatch',f.contextId)])));pass(stage);
 stage='PG02 valid payloadHash cannot authorize injected raw/normalized internal values';for(const field of ['raw','normalized'] as const){const id=await corrupted(p.id,value=>{value.plans[0].preview[field]['internal.supplyAmount']='731927';});await assert.rejects(service.readPreview(f.token,id),{status:503,code:'STORAGE_UNAVAILABLE'});await assert.rejects(metadata(id),{status:503});await assert.rejects(service.apply(f.token,{previewId:id,idempotencyKey:randomUUID()}),{status:503});assert.equal((await repo.get('importStage',id))!.data.state,'active');}assert.equal(digest(JSON.stringify(await Promise.all([repo.list('productVersion',f.contextId),repo.list('internalPriceVersion',f.contextId),repo.list('importBatch',f.contextId)]))),beforeWrites);assert.deepEqual(await repo.get('importStage',p.id),originalPreview);pass(stage,{readMetadataApplyDenied:6,businessUnchanged:true});
 stage='PG03 public DTO/Range ignores unused diff extension and normal apply still succeeds';const extension=await corrupted(p.id,value=>{Object.assign(value.plans[0].preview,{diff:{'internal.supplyAmount':'731927'}});}),meta=await(await metadata(extension)).json(),range=await authorizedPrivateJsonResponse(new Request(`https://app.invalid/api/imports/preview/${extension}`,{headers:{Range:`bytes=0-${meta.bytes-1}`,'If-Match':meta.etag}}),()=>service.readPreview(f.token,extension),extension,`/api/imports/preview/${extension}`);assert.equal(range.status,206);const body=await range.text();assert(!body.includes('731927'));assert(!body.includes('internal.'));assert.equal(digest(body),meta.sha256);await service.apply(f.token,{previewId:p.id,idempotencyKey:randomUUID()});assert.equal((await repo.list('internalPriceVersion',f.contextId)).length,0);pass(stage,{rangeSHA:meta.sha256,privateWrites:0});
 stage='PG04 legitimate current price permission preserves exact decimal read and write';await repo.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,internalPriceAccess:true});});const internal=await source('PRIVATE-'+runId.slice(0,8),true),allowed=await preview(internal.id,internal.fields);assert.equal((await service.readPreview(f.token,allowed.id)).rows[0].normalized['internal.supplyAmount'],'731927.0001');await service.apply(f.token,{previewId:allowed.id,idempotencyKey:randomUUID()});assert((await repo.list('internalPriceVersion',f.contextId)).some(v=>v.data.fields.supplyAmount==='731927.0001'));pass(stage);
 stage='PG05 committed revocation denies current read metadata range and write';const pending=await preview(internal.id,internal.fields),before=await metadata(pending.id),oldMeta=await before.json(),versions=await repo.list('internalPriceVersion',f.contextId);await repo.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,internalPriceAccess:false});});await assert.rejects(service.readPreview(f.token,pending.id),{status:404});await assert.rejects(metadata(pending.id),{status:404});await assert.rejects(authorizedPrivateJsonResponse(new Request(`https://app.invalid/api/imports/preview/${pending.id}`,{headers:{Range:'bytes=0-9','If-Match':oldMeta.etag}}),()=>service.readPreview(f.token,pending.id),pending.id,`/api/imports/preview/${pending.id}`),{status:404});await assert.rejects(service.apply(f.token,{previewId:pending.id,idempotencyKey:randomUUID()}),{status:404});assert.deepEqual(await repo.list('internalPriceVersion',f.contextId),versions);assert.equal((await repo.get('importStage',pending.id))!.data.state,'active');pass(stage,{denied:4,privateVersionsUnchanged:true});
}catch(error){report.checks.push({name:stage,status:'FAIL',details:{code:error&&typeof error==='object'&&'code'in error&&typeof error.code==='string'&&/^[A-Z0-9_]+$/.test(error.code)?error.code:'ASSERTION_OR_UNCLASSIFIED'}});save();process.exitCode=1;}
finally{report.envUnchanged=digest(readFileSync(envFile))===digest(original);save();await repo.close();console.log(JSON.stringify({checks:report.checks,pid:process.pid,schemaRetained:true}));}
