/** S4 actual synthetic PostgreSQL/Storage consumer proof; never uses a production schema. */
import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { parseEnv } from 'node:util';
import { execFileSync } from 'node:child_process';
import ExcelJS from 'exceljs';
import { parsePostgresConfig, quoteSchema } from '@/server/postgres/config';
import { createPostgresRepository } from '@/server/postgres/repository';
import { createPostgresPool, connect } from '@/server/postgres/client';
import { migratePostgres } from '@/server/postgres/migrate';
import { SupabasePrivateStorage } from '@/server/storage/supabase';
import { digest } from '@/domain/storage/validate';
import { STORAGE_LIMITS } from '@/domain/storage/types';
import { IdentityService } from '@/server/auth/service';
import { ImportStorage } from '@/server/imports/storage';
import { ImportService } from '@/server/imports/service';
import { ImportExports } from '@/server/imports/storage-export';
import { AiAssetStorage } from '@/server/ai-input/storage';
import { VersionSourceStorage } from '@/server/ai-input/storage-source';
import { AiInputService } from '@/server/ai-input/service';
import { ProductService } from '@/server/products/service';
import { createFixture, fixtureIds } from './verify-storage-app-shared';
import { workbookBytes } from '@/server/imports/workbook';
import { importFields } from '@/domain/imports/fields';
const [envFile,outputFile,mode='main',inheritedRun,sourceId] = process.argv.slice(2);
if(!envFile?.startsWith('/') || !outputFile?.startsWith('/')) throw Error('Absolute private paths required');
const original=readFileSync(envFile), env=parseEnv(original.toString()), runId=inheritedRun||randomUUID(), namespace=`s4_${runId.replaceAll('-','')}`;
const schema=process.env.S4_SCHEMA||'gs_hale_storage_excel_ai_20260922';
if(!/^gs_hale_storage_excel_ai(?:_ind)?_[a-z0-9_]{1,25}$/.test(schema))throw Error('Dedicated schema required');
const config=parsePostgresConfig({...env,SUPABASE_DB_SCHEMA:schema},'migration'), f=fixtureIds(runId), clock=()=>new Date().toISOString();
for(const key of ['SUPABASE_URL','SUPABASE_SECRET_KEY','SUPABASE_SERVICE_ROLE_KEY','SUPABASE_STORAGE_BUCKET'])if(env[key])process.env[key]=env[key];
process.env.SUPABASE_STORAGE_NAMESPACE=namespace;
const storageConfig={projectUrl:env.SUPABASE_URL||'',secretKey:env.SUPABASE_SECRET_KEY||env.SUPABASE_SERVICE_ROLE_KEY||'',bucket:env.SUPABASE_STORAGE_BUCKET||'gs-hale-private',namespace,timeoutMs:120000};
const remote=new SupabasePrivateStorage(storageConfig), repo=createPostgresRepository(config), other=createPostgresRepository(config), identity=new IdentityService(repo,clock), second=new IdentityService(other,clock);
const candidate=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
if(mode==='child'){
 try{const r=await new ImportService(identity).source(f.token,sourceId);writeFileSync(outputFile,JSON.stringify({pid:process.pid,candidate,sourceHash:r.sourceHash,sheets:r.sheets.length}),{flag:'wx',mode:0o600});}finally{await repo.close();await other.close();}
}else{
 const owned=new Set<string>(), checks:{name:string;status:'PASS'|'FAIL';code?:string;details?:unknown}[]=[], report={candidate,cwd:process.cwd(),pid:process.pid,session:process.env.CODEX_THREAD_ID,runId,schema,startedAt:clock(),checks,counts:{pass:0,fail:0,notRun:11},actualStorageHTTP:'EXECUTED/count not instrumented',aiProviderCalls:0,browser:'NOT_RUN',envUnchanged:false};
 writeFileSync(outputFile,JSON.stringify(report,null,2),{flag:'wx',mode:0o600});
 const save=()=>{report.counts={pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length,notRun:Math.max(0,11-checks.length)};writeFileSync(outputFile,JSON.stringify(report,null,2)+'\n',{mode:0o600});};
 async function check(name:string,operation:()=>Promise<unknown>){try{checks.push({name,status:'PASS',details:await operation()});}catch(e){checks.push({name,status:'FAIL',code:e&&typeof e==='object'&&'code'in e&&typeof e.code==='string'&&/^[A-Z0-9_]+$/.test(e.code)?e.code:'ASSERTION_OR_UNCLASSIFIED'});}save();console.log(JSON.stringify(checks.at(-1)));if(checks.at(-1)?.status==='FAIL')throw Error('check failed');}
 const tracked=()=>({allocateStagingKey:()=>{const k=remote.allocateStagingKey();owned.add(k);return k;},allocateFinalKey:()=>{const k=remote.allocateFinalKey();owned.add(k);return k;},issueUploadGrant:remote.issueUploadGrant.bind(remote),inspect:remote.inspect.bind(remote),readSnapshot:remote.readSnapshot.bind(remote),promoteVerified:remote.promoteVerified.bind(remote),readRange:remote.readRange.bind(remote),cleanupExpiredStaging:remote.cleanupExpiredStaging.bind(remote),createGeneratedPart:remote.createGeneratedPart.bind(remote)});
 const a=new ImportService(identity,undefined,undefined,tracked),b=new ImportService(second,undefined,undefined,tracked),source=new ImportStorage(identity,tracked),sourceB=new ImportStorage(second,tracked),ai=new AiAssetStorage(identity,tracked);
 const pool=createPostgresPool(config,'migration'), table=`${quoteSchema(schema)}.records`;
 async function sql(text:string,args:unknown[]=[]){const c=await connect(pool);try{return await c.query(text,args);}finally{c.release();}}
 async function upload(bytes:Buffer,name:string,mime:string,kind:'import'|'ai'){
  const metadata={contextId:f.contextId,clientItemId:randomUUID(),originalName:name,declaredMime:mime,expectedBytes:bytes.length,expectedSha256:digest(bytes)},grant=kind==='import'?await source.issue(f.token,{...metadata,owner:{purpose:'import_source'},visibility:'internal'}):await ai.issue(f.token,{...metadata,owner:{purpose:'ai_asset',inputKind:mime==='application/pdf'?'pdf':'image'},visibility:'public'});
  assert(grant.capability);const r=await fetch(grant.capability.signedUrl,{method:'PUT',body:bytes as BodyInit,headers:{'content-type':mime},signal:AbortSignal.timeout(120000)});const status=r.status;await r.body?.cancel();assert.equal(status,200);return grant.status.id;
 }
 const headers=['contextKey','common.code','common.name','local.jan','retail.amount','retail.currency','internal.supplyAmount','internal.currency'];let sid='',previewId='',aiId='',inputId='',versionId='',exportId='';
 try{
  await check('P01 additive migration19/repeat0 preserves any prior rows',async()=>{const exists=(await sql('SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname=$1) AS yes',[schema])).rows[0].yes;const before=exists?(await sql(`SELECT * FROM ${table} ORDER BY kind,id`)).rows:[];const oldHash=digest(JSON.stringify(before)),m=await migratePostgres(config);assert.equal(m.total,19);assert.equal(digest(JSON.stringify((await sql(`SELECT * FROM ${table} ORDER BY kind,id`)).rows)),oldHash);assert.equal((await migratePostgres(config)).applied,0);await createFixture(repo,runId,clock);await repo.transaction(async s=>{const c=(await s.get('context',f.contextId))!,member=(await s.get('membership',f.memberId))!;await s.update('context',c.id,c.revision,{...c.data,brandId:'brand-luna'});await s.update('membership',member.id,member.revision,{...member.data,internalPriceAccess:true});});assert.equal((await remote.ensurePrivateBucket()).created,false);return{applied:m.applied,total:19,preserved:before.length};});
  await check('P02 actual XLSX direct upload A/finalize B/shared preview/new PID',async()=>{const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('商品');sheet.addRows([headers,[f.contextId,'000-S4','日本語合成','00000021','19.0001','JPY','99123.456','JPY']]);const bytes=Buffer.from(await book.xlsx.writeBuffer()),grant=await upload(bytes,'source.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','import'),ready=await sourceB.finalize(f.token,grant);sid=ready.result!.id;assert.equal((await a.source(f.token,sid)).sourceHash,digest(bytes));const childFile=outputFile+'.child.json';execFileSync(process.execPath,['--conditions=react-server','--import','tsx',process.argv[1],envFile,childFile,'child',runId,sid],{cwd:process.cwd(),stdio:'pipe',timeout:180000});const child=JSON.parse(readFileSync(childFile,'utf8'));assert.notEqual(child.pid,process.pid);assert.equal(child.sourceHash,digest(bytes));const p=await b.preview(f.token,{sourceId:sid,sheetId:(await a.source(f.token,sid)).sheets[0].id,headerRow:1,mapping:headers.map((field,i)=>({column:i+1,field})),choices:[]});assert.equal(p.errorRows,0);previewId=p.id;return{sourceHash:digest(bytes),newPID:true,previewRows:p.totalRows};});
  await check('P03 forced late apply rolls back consume/products/receipt/audit then exact replay',async()=>{const before=(await repo.list('productVersion')).length;const fault=new ImportService(identity,undefined,()=>{throw Error('S4_ROW_ROLLBACK');},tracked);await assert.rejects(fault.apply(f.token,{previewId,idempotencyKey:randomUUID()}));assert.equal((await other.get('importStage',previewId))!.data.state,'active');assert.equal((await repo.list('productVersion')).length,before);const command={previewId,idempotencyKey:randomUUID()},saved=await a.apply(f.token,command);assert.deepEqual(await b.apply(f.token,command),saved);assert.equal((await other.get('importStage',previewId))!.data.state,'consumed');const batch=await b.batch(f.token,saved.ids[0]),product=await new ProductService(identity).detail(f.token,batch.rows[0].productId!,f.contextId);assert.equal(product.common.code,'000-S4');assert.equal(product.local.jan,'00000021');assert.equal(product.retail.current!.fields.amount,'19.0001');return{rollback:true,replay:true};});
  await check('P04 fresh price revoke/expiry/CAS shared preview fails without partial apply',async()=>{const preview=await b.preview(f.token,{sourceId:sid,sheetId:1,headerRow:1,mapping:headers.map((field,i)=>({column:i+1,field})),choices:[]});await other.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,internalPriceAccess:false});});await assert.rejects(a.readPreview(f.token,preview.id),{status:404});await other.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,internalPriceAccess:true});});const future=new ImportService(new IdentityService(other,()=>new Date(Date.now()+31*60000).toISOString()),undefined,undefined,tracked);await assert.rejects(future.apply(f.token,{previewId:preview.id,idempotencyKey:randomUUID()}));const plan=preview.rows[0].target!,products=new ProductService(identity),current=await products.detail(f.token,plan.productId,f.contextId);await products.command(f.token,plan.productId,{contextId:f.contextId,command:'save_common',common:{...current.common,name:'並行変更'},expectedCommonRevision:current.commonRevision,idempotencyKey:randomUUID()});await assert.rejects(a.apply(f.token,{previewId:preview.id,idempotencyKey:randomUUID()}),{code:'CONFLICT'});return{priceDenied:true,expiredDenied:true,CASDenied:true};});
  await check('P05 actual AI PDF immutable asset and exact historical parent source',async()=>{const bytes=readFileSync('tests/fixtures/ai-input/native-12.pdf'),grant=await upload(bytes,'native.pdf','application/pdf','ai'),ready=await new AiAssetStorage(second,tracked).finalize(f.token,grant);aiId=ready.result!.id;assert.equal((await repo.list('aiInput',f.contextId)).length,0);assert.equal(digest((await ai.snapshot(f.token,aiId)).bytes),digest(bytes));const d=await new AiInputService(identity).create(f.token,{contextId:f.contextId,visibility:'context',idempotencyKey:randomUUID(),content:{title:'合成PDF',scope:{classification:'general_cosmetic',language:'ja',media:'pop',use:'店頭'},kind:'pdf',text:null,sources:[{kind:'upload',assetId:aiId}],selectedPages:[1,3],submission:null,products:[]}});inputId=d.id;versionId=d.version.id;const loaded=await new VersionSourceStorage(second,tracked).snapshot(f.token,inputId,versionId,0);assert.equal(digest(loaded.bytes),digest(bytes));await assert.rejects(new VersionSourceStorage(second,tracked).metadata(f.token,inputId,randomUUID(),0),{status:404});return{sameSHA:true,bytes:bytes.length};});
  await check('P06 actual PDF worker reads bounded Storage original and preserves unselected pages',async()=>{const result=await new AiInputService(second).extract(f.token,inputId,{versionId,expectedRunId:null,idempotencyKey:randomUUID()});const snapshot=result.detail.runs[0].snapshot;assert(snapshot);assert(snapshot.units.some(u=>u.page===1&&u.status==='read'));assert(snapshot.units.some(u=>u.page===2&&u.status==='unselected'));assert.equal(snapshot.units.filter(u=>u.status==='unselected').length,10);return{state:result.detail.runs[0].state,unselected:10,providerCalls:0};});
  await check('P07 generated XLSX over4MiB immutable artifact with whole SHA/cross-part reads',async()=>{const fields=importFields.filter(f=>['contextKey','common.code','common.name','common.description'].includes(f.key)),rows=Array.from({length:125},(_,i)=>({'contextKey':f.contextId,'common.code':String(i),'common.name':'合成','common.description':randomBytes(42000).toString('base64')}));const bytes=await workbookBytes(fields,rows);assert(bytes.length>STORAGE_LIMITS.chunkBytes);const svc=new ImportExports(identity,tracked),meta=await svc.publish(f.token,f.contextId,true,bytes);exportId=meta.id;const collected:Buffer[]=[];for(let start=0;start<meta.bytes;start+=STORAGE_LIMITS.chunkBytes)collected.push((await new ImportExports(second,tracked).chunk(f.token,meta.id,start,Math.min(start+STORAGE_LIMITS.chunkBytes-1,meta.bytes-1))).bytes);assert.equal(digest(Buffer.concat(collected)),digest(bytes));assert.deepEqual((await svc.chunk(f.token,meta.id,STORAGE_LIMITS.chunkBytes-3,STORAGE_LIMITS.chunkBytes+3)).bytes,bytes.subarray(STORAGE_LIMITS.chunkBytes-3,STORAGE_LIMITS.chunkBytes+4));const manifest=(await repo.get('importExport',meta.id))!;await assert.rejects(remote.createGeneratedPart({key:manifest.data.parts[0].descriptor.key,bytes:bytes.subarray(0,STORAGE_LIMITS.chunkBytes),filename:manifest.data.filename,sha256:manifest.data.parts[0].descriptor.sha256}));return{bytes:bytes.length,parts:manifest.data.parts.length,wholeSHA:meta.sha256};});
  await check('P08 rawSQL manifest immutable UPDATE/DELETE and reused parts crosscontext rejected',async()=>{await assert.rejects(sql(`UPDATE ${table} SET data=data||'{"includeInternal":false}'::jsonb WHERE kind='importExport' AND id=$1`,[exportId]),{code:'23514'});await assert.rejects(sql(`DELETE FROM ${table} WHERE kind='importExport' AND id=$1`,[exportId]),{code:'23514'});const row=(await repo.get('importExport',exportId))!;await assert.rejects(repo.transaction(s=>s.create('importExport',{id:randomUUID(),contextId:f.contextId,data:row.data})),{code:'INVALID_RECORD'});return{immutableSQL:2,reusedPartsDenied:true};});
  await check('P09 current price revoke denies export metadata and chunk',async()=>{await other.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,internalPriceAccess:false});});const svc=new ImportExports(identity,tracked);await assert.rejects(svc.metadata(f.token,exportId),{status:404});await assert.rejects(svc.chunk(f.token,exportId,0,3),{status:404});return{denied:2};});
  await check('P10 current membership revoke denies asset/source/grant replay',async()=>{await other.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});await assert.rejects(ai.snapshot(f.token,aiId),{status:404});await assert.rejects(new VersionSourceStorage(identity,tracked).metadata(f.token,inputId,versionId,0),{status:404});await assert.rejects(a.source(f.token,sid),{status:404});return{denied:3};});
 }catch{if(!checks.some(c=>c.status==='FAIL'))checks.push({name:'execution prerequisite',status:'FAIL',code:'PREREQUISITE'});save();}
 finally{
  try{await check('C01 exact owned synthetic object cleanup; DB/schema retained',async()=>{if(owned.size){assert([...owned].every(k=>k.startsWith(namespace+'/')));const url=new URL(storageConfig.projectUrl).origin,r=await fetch(`${url}/storage/v1/object/${storageConfig.bucket}`,{method:'DELETE',headers:{apikey:storageConfig.secretKey,authorization:`Bearer ${storageConfig.secretKey}`,'content-type':'application/json'},body:JSON.stringify({prefixes:[...owned]}),signal:AbortSignal.timeout(60000)});const status=r.status;await r.body?.cancel();assert.equal(status,200);}return{ownedKeys:owned.size,schemaRetained:true};});}catch{}
  report.envUnchanged=digest(readFileSync(envFile))===digest(original);save();await repo.close();await other.close();await pool.end();if(report.counts.fail)process.exitCode=1;
 }
}
