import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,copyFileSync,readdirSync,statSync,createWriteStream} from 'node:fs';
import path from 'node:path';
import {chromium,expect} from '@playwright/test';
import sharp from 'sharp';
import {login,get,type Fixture} from './verify-search-ui-journeys';
import {A} from './verify-search-ui-fixtures';
import type {SearchDetail,SearchList} from '@/domain/search/types';
import type {AuditList} from '@/domain/audit/view';
import type {ProductDetail} from '@/server/products/service';
const source=path.resolve(process.argv[2]),root=path.resolve(process.argv[3]);mkdirSync(root,{recursive:true});
const port=Number(process.env.E2E_PORT??4262),origin=`http://127.0.0.1:${port}`,candidate=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),startedAt=new Date().toISOString();
const f=JSON.parse(readFileSync(path.join(source,'fixture.json'),'utf8')) as Fixture,record=JSON.parse(readFileSync(path.join(source,'ui-created-record.json'),'utf8')) as {productId:string;name:string;commonRevision:number;events:{id:string}[];oldRequest:string};
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex'),copies:{source:string;copy:string;sha256:string}[]=[],checks:{id:string;status:'PASS'|'FAIL';detail:string}[]=[];
function copy(dir:string,to:string){mkdirSync(to,{recursive:true});for(const name of readdirSync(dir)){const s=path.join(dir,name),t=path.join(to,name);if(statSync(s).isDirectory())copy(s,t);else{copyFileSync(s,t);const sha256=hash(readFileSync(s));assert.equal(hash(readFileSync(t)),sha256);copies.push({source:s,copy:t,sha256});}}}
copy(path.join(source,'closed-copy'),path.join(root,'runtime-copy'));const copyCompletedAt=new Date().toISOString();
const env={...process.env,DATA_SOURCE:'sqlite',DATABASE_FILE:path.join(root,'runtime-copy/data.db'),FILE_STORAGE_DIR:path.join(root,'runtime-copy/files'),IMPORT_STORAGE_DIR:path.join(root,'imports'),APP_ORIGIN:origin,SESSION_COOKIE_NAME:`gs_hale_g14_restart_${port}`,OPENAI_API_KEY:'',OPENAI_MODEL:'',OPENAI_BASE_URL:'https://api.openai.com/v1',NEXT_TELEMETRY_DISABLED:'1'};
const argv=['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],log=createWriteStream(path.join(root,'server.log'),{flags:'wx'}),server=spawn(process.execPath,argv,{env,stdio:['ignore','pipe','pipe']});server.stdout.pipe(log,{end:false});server.stderr.pipe(log,{end:false});
const closed=new Promise<void>(resolve=>server.once('close',()=>{log.end();resolve();}));const browser=await chromium.launch(),context=await browser.newContext({baseURL:origin,viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();let failure:string|undefined;
const pass=(id:string,detail:string)=>checks.push({id,status:'PASS',detail});
try{
 for(let n=0;;n++){if(server.exitCode!==null)throw Error('new PID exited');try{if((await fetch(origin+'/api/health',{signal:AbortSignal.timeout(1000)})).ok)break;}catch{}if(n>400)throw Error('new PID readiness');await new Promise(r=>setTimeout(r,50));}
 pass('R14-01','Closed UI-produced SQLite and files copied/hashed before new process opens copy');await login(page.request,origin,'admin@example.test');pass('R14-02','New PID and actual fresh cookie login succeed');
 const product=await get<ProductDetail>(page.request,`/api/products/${record.productId}?context=${A}`);expect(product.common.name).toBe(record.name);expect(product.commonRevision).toBe(record.commonRevision);pass('R14-03','UI response-loss retry saved exact common version survives restart');
 const audits=await get<AuditList>(page.request,`/api/audit?context=${A}&product=${record.productId}&status=product.save_common`);expect(audits.items.map(x=>x.id).sort()).toEqual(record.events.map(x=>x.id).sort());expect(audits.total).toBe(3);writeFileSync(path.join(root,'audit.json'),JSON.stringify(audits,null,2));pass('R14-04','Exact three canonical save audits persist; lost-response replay added once');
 await page.goto(`/search?context=${A}&q=${encodeURIComponent(record.name)}`);await expect(page.getByRole('link',{name:record.name,exact:true})).toBeVisible();pass('R14-05','New PID search UI shows actual UI-created saved name');
 const exact=await get<SearchDetail>(page.request,`/api/search/history?context=${A}&kind=requestVersion&id=${f.oldRequest}`);expect(exact.item.actor).toEqual({id:'user-selected-admin',label:'이전 작성자'});writeFileSync(path.join(root,'exact-history.json'),JSON.stringify(exact,null,2));await page.goto(exact.item.historyUrl);await expect(page.getByRole('article',{name:'선택한 기록'})).toContainText('G14_OLD_BODY 정확 원문');await expect(page.getByRole('article',{name:'선택한 기록'})).not.toContainText('G14_NEW_BODY');pass('R14-06','Exact old request and deactivated historical writer survive current revision/restart');
 const file=exact.files.find(x=>x.id===f.file.id)!;expect(file).toBeTruthy();const bytes=await page.request.get(file.downloadUrl);expect(bytes.status()).toBe(200);expect(hash(await bytes.body())).toBe(f.file.sha256);pass('R14-07','Copied exact private file remains authorized and byte-identical');
 const history=await get<SearchList>(page.request,`/api/search?context=${A}&mode=history&q=G14_OLD_`);expect(history.items.some(x=>x.sourceId===f.oldProductVersion)).toBe(true);pass('R14-08','Six-month historical product version remains independently searchable');
 await page.goto(`/search?context=${A}&q=G14_LONG`);await expect(page.getByRole('link',{name:f.longTitle,exact:true})).toBeVisible();const geometry=await page.evaluate(()=>({width:innerWidth,dpr:devicePixelRatio,rectangles:[...document.querySelectorAll('[data-g14-view] input,[data-g14-view] select,[data-g14-view] button,[data-g14-view] article')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right};})}));expect(geometry.width).toBe(390);expect(geometry.dpr).toBe(3);for(const r of geometry.rectangles){expect(r.left).toBeGreaterThanOrEqual(-1);expect(r.right).toBeLessThanOrEqual(391);}await page.screenshot({path:path.join(root,'viewport.png')});await page.screenshot({path:path.join(root,'full.png'),fullPage:true});expect((await sharp(path.join(root,'viewport.png')).metadata()).width).toBe(1170);expect((await sharp(path.join(root,'full.png')).metadata()).width).toBe(1170);writeFileSync(path.join(root,'geometry.json'),JSON.stringify(geometry,null,2));pass('R14-09','Actual 390/DPR3 long CJK+Latin controls and viewport/full PNG widths fit');
}catch(e){failure=e instanceof Error?e.stack:String(e);checks.push({id:'R14-FAILED',status:'FAIL',detail:failure??'unknown'});writeFileSync(path.join(root,'failed.html'),await page.content().catch(()=>''));await page.screenshot({path:path.join(root,'failed.png'),fullPage:true}).catch(()=>{});}
finally{await context.tracing.stop({path:path.join(root,'trace.zip')});await context.close();await browser.close();server.kill('SIGTERM');const timer=setTimeout(()=>server.kill('SIGKILL'),10000);await closed;clearTimeout(timer);const immutable=copies.every(x=>hash(readFileSync(x.source))===x.sha256);if(immutable)pass('R14-10','All original closed-copy database/files hashes remain unchanged');else{failure='Original source changed';checks.push({id:'R14-10',status:'FAIL',detail:failure});}const report={candidate,cwd:process.cwd(),startedAt,finishedAt:new Date().toISOString(),source,copyCompletedAt,copies,server:{pid:server.pid,argv,cwd:process.cwd(),exitCode:server.exitCode,signalCode:server.signalCode,stopped:true},checks,counts:{pass:checks.filter(x=>x.status==='PASS').length,fail:checks.filter(x=>x.status==='FAIL').length,not_run:Math.max(0,10-checks.length),unit:'assertion'},failure,realProviderCalls:0};writeFileSync(path.join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({counts:report.counts,failure}));if(failure)process.exitCode=1;}
