/** Author's bounded real PostgreSQL/Storage browser proof; own synthetic context only. */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync,openSync,closeSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {chromium,expect} from '@playwright/test';
import ExcelJS from 'exceljs';
import {parsePostgresConfig} from '@/server/postgres/config';
import {createPostgresRepository} from '@/server/postgres/repository';
import {migratePostgres} from '@/server/postgres/migrate';
import {createFixture,fixtureIds} from './verify-storage-app-shared';
import {digest} from '@/domain/storage/validate';
const [envFile,out]=process.argv.slice(2);if(!envFile?.startsWith('/')||!out?.startsWith('/'))throw Error('Absolute paths required');
const original=readFileSync(envFile),env=parseEnv(original.toString()),runId=randomUUID(),f=fixtureIds(runId),schema=process.env.S4_SCHEMA||'gs_hale_storage_excel_ai_20260922',namespace=`s4_ui_${runId.replaceAll('-','')}`;
if(!/^gs_hale_storage_excel_ai(?:_ind)?_[a-z0-9_]{1,25}$/.test(schema))throw Error('Own schema required');
const config=parsePostgresConfig({...env,SUPABASE_DB_SCHEMA:schema},'migration'),repo=createPostgresRepository(config),ports=[4511,4512],bases=ports.map(p=>`http://127.0.0.1:${p}`),cookieName='gs_hale_s4_ui',clock=()=>new Date().toISOString();
const report={candidate:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),cwd:process.cwd(),pid:process.pid,session:process.env.CODEX_THREAD_ID,runId,schema,namespace,startedAt:clock(),checks:[] as {name:string;status:string;details?:unknown}[],responses:[] as {path:string;status:number;range:string|null;length:string|null}[],actualStorage:'EXECUTED',aiProviderCalls:0,envUnchanged:false};
writeFileSync(out,JSON.stringify(report,null,2),{flag:'wx',mode:0o600});const save=()=>writeFileSync(out,JSON.stringify(report,null,2)+'\n',{mode:0o600});
const processes:ChildProcess[]=[],logs:number[]=[];let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;let stage='setup';
async function stop(child:ChildProcess){if(child.exitCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise<void>(resolve=>child.once('exit',()=>resolve())),new Promise<void>(resolve=>setTimeout(resolve,10000))]);if(child.exitCode===null)child.kill('SIGKILL');}
async function start(index:number){const log=openSync(`${out}.server${index}.log`,'a',0o600);logs.push(log);const child=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(ports[index])],{cwd:process.cwd(),env:{...process.env,...env,DATA_SOURCE:'supabase',SUPABASE_DB_SCHEMA:schema,SUPABASE_STORAGE_NAMESPACE:namespace,APP_ORIGIN:bases[index],SESSION_COOKIE_NAME:cookieName},stdio:['ignore',log,log]});processes.push(child);for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error('Server exited');try{if((await fetch(bases[index]+'/login')).ok)return child;}catch{}await new Promise(resolve=>setTimeout(resolve,300));}throw Error('Server unavailable');}
const pass=(name:string,details?:unknown)=>{report.checks.push({name,status:'PASS',details});save();};
async function get(base:string,path:string,headers:Record<string,string>={}){return fetch(base+path,{headers:{cookie:`${cookieName}=${f.token}`,...headers},signal:AbortSignal.timeout(180000)});}
try{
 assert.equal((await migratePostgres(config)).total,19);await createFixture(repo,runId,clock);await repo.transaction(async s=>{const c=(await s.get('context',f.contextId))!,m=(await s.get('membership',f.memberId))!;await s.update('context',c.id,c.revision,{...c.data,brandId:'brand-luna'});await s.update('membership',m.id,m.revision,{...m.data,internalPriceAccess:true});});
 await Promise.all([start(0),start(1)]);browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.addCookies([{name:cookieName,value:f.token,url:bases[0],httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage();page.setDefaultTimeout(180000);page.setDefaultNavigationTimeout(180000);const check=expect.configure({timeout:180000});
 page.on('response',response=>{const url=new URL(response.url());if(url.hostname==='127.0.0.1'&&url.pathname.startsWith('/api/imports/')||url.hostname==='127.0.0.1'&&url.pathname.startsWith('/api/ai-input/'))report.responses.push({path:url.pathname,status:response.status(),range:response.headers()['content-range']??null,length:response.headers()['content-length']??null});});
 stage='B01 desktop direct XLSX/preview/apply/export';const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('商品'),code=`000-UI-${runId.slice(0,8)}`;sheet.addRows([['contextKey','common.code','common.name','local.sku'],[f.contextId,code,'合成ブラウザ商品','0000123']]);const sourceBytes=Buffer.from(await book.xlsx.writeBuffer());
 await page.goto(`${bases[0]}/products/import?context=${f.contextId}`);await page.getByLabel('상품 Excel 원본',{exact:true}).setInputFiles({name:'browser.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:sourceBytes});await page.getByRole('button',{name:'원본 읽기 · 다시 시도',exact:true}).click();await check(page.getByRole('status')).toContainText('원본을 읽었습니다.');await page.getByRole('button',{name:'선택한 머리글의 표준 키로 매핑 채우기',exact:true}).click();await page.getByRole('button',{name:'전체 미리보기 만들기 · 다시 검증',exact:true}).click();await check(page.getByRole('status')).toContainText('전체 행 검증을 마쳤습니다.');await check(page.getByRole('article',{name:'원본 2행',exact:true})).toContainText('0000123');await page.getByRole('button',{name:'확인한 모든 행 반영',exact:true}).click();await check(page.getByRole('region',{name:'가져오기 반영 결과',exact:true})).toContainText('반영 행 1개');
 const savedURL=page.url(),download=page.waitForEvent('download',{timeout:180000});await page.getByRole('button',{name:'현재 상품 내보내기',exact:true}).click();const file=await download,stream=await file.createReadStream();assert(stream);const chunks:Buffer[]=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));const downloaded=Buffer.concat(chunks),exported=new ExcelJS.Workbook();await exported.xlsx.load(Uint8Array.from(downloaded).buffer);assert(JSON.stringify(exported.getWorksheet(1)!.getSheetValues()).includes(code));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:out+'.desktop.png'});pass(stage,{uploadBytes:sourceBytes.length,exportBytes:downloaded.length,exportSHA:digest(downloaded),rangeResponses:report.responses.filter(r=>r.status===206).length});
 stage='B02 second Next process reads same committed source/batch';await page.goto(savedURL.replace(bases[0],bases[1]));await check(page.getByRole('region',{name:'가져오기 반영 결과',exact:true})).toBeVisible();const stages=await repo.list('importStage',f.contextId),source=stages.find(s=>s.data.stageType==='source')!;const metadataResponse=await get(bases[1],`/api/imports/source/${source.id}?transfer=1`);assert.equal(metadataResponse.status,200);const metadata=await metadataResponse.json();const read=await get(bases[1],metadata.downloadUrl,{Range:`bytes=0-${metadata.bytes-1}`,'If-Match':metadata.etag});assert.equal(read.status,206);const inspection=JSON.parse(Buffer.from(await read.arrayBuffer()).toString());assert.equal(inspection.sourceHash,digest(sourceBytes));pass(stage,{sameSourceHash:true,serverPids:processes.map(p=>p.pid)});
 stage='B03 mobile direct PDF/save/exact parent source bounded download';await page.setViewportSize({width:390,height:844});await page.goto(`${bases[0]}/ai-input/new?context=${f.contextId}`);await check(page.getByLabel('입력 제목',{exact:true})).toBeEnabled();await page.getByLabel('입력 제목',{exact:true}).fill('合成ブラウザPDF');await page.getByLabel('제품 분류',{exact:true}).selectOption('general_cosmetic');await page.getByLabel('사용처',{exact:true}).fill('店頭');await page.getByLabel('입력 형식',{exact:true}).selectOption('pdf');const pdf=readFileSync('tests/fixtures/ai-input/native-12.pdf');await page.getByLabel('새 원본 파일',{exact:true}).setInputFiles({name:'browser.pdf',mimeType:'application/pdf',buffer:pdf});await check(page.getByRole('status').filter({hasText:'파일을 업로드했습니다.'})).toBeVisible();await page.getByRole('group',{name:'실제로 읽을 자료 선택'}).getByRole('radio',{name:/browser.pdf/}).check();await page.getByLabel('읽을 PDF 페이지',{exact:true}).fill('1, 3');await page.getByRole('button',{name:'입력 저장',exact:true}).click();await check(page.getByRole('heading',{name:'저장된 입력 v1',exact:true})).toBeVisible();const sourceDownload=page.waitForEvent('download',{timeout:180000});await page.getByRole('button',{name:/browser.pdf · 저장한 원본 내려받기/}).click();const sourceFile=await sourceDownload,sourceStream=await sourceFile.createReadStream();assert(sourceStream);const pieces:Buffer[]=[];for await(const piece of sourceStream)pieces.push(Buffer.from(piece));assert.equal(digest(Buffer.concat(pieces)),digest(pdf));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:out+'.mobile.png'});pass(stage,{samePDFHash:true,selectedPages:[1,3],width:390});
 stage='B04 restart and fresh revocation deny range/UI';const input=(await repo.list('aiInput',f.contextId))[0],version=(await repo.list('aiInputVersion',f.contextId)).find(v=>v.data.inputId===input.id)!;const parentPath=`/api/ai-input/${input.id}/sources/0?versionId=${version.id}`;await stop(processes[0]);await start(0);const before=await get(bases[0],parentPath+'&metadata=1');assert.equal(before.status,200);const sourceMeta=await before.json();await repo.transaction(async s=>{const m=(await s.get('membership',f.memberId))!;await s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});for(const base of bases){assert.equal((await get(base,parentPath+'&metadata=1')).status,404);assert.equal((await get(base,parentPath,{Range:'bytes=0-9','If-Match':sourceMeta.etag})).status,404);}await page.getByRole('button',{name:/browser.pdf · 저장한 원본 내려받기/}).click();await check(page.getByText('접근 가능한 화면으로 이동하거나 다시 로그인해 주세요. 이 화면의 자료와 복구 입력을 지웠습니다.',{exact:true})).toBeVisible();await check(page.getByRole('heading',{name:'저장된 입력 v1',exact:true})).toHaveCount(0);pass(stage,{denied:4,clientProtectedValuesPurged:true});
}catch(error){report.checks.push({name:stage,status:'FAIL',details:{name:error instanceof Error?error.name:'unknown',code:error&&typeof error==='object'&&'code'in error&&typeof error.code==='string'&&/^[A-Z0-9_]+$/.test(error.code)?error.code:'ASSERTION_OR_UNCLASSIFIED'}});save();process.exitCode=1;}
finally{
 await browser?.close();await Promise.all(processes.map(stop));for(const fd of logs)closeSync(fd);
 try{const grants=await repo.list('storageUploadGrant',f.contextId),exports=await repo.list('importExport',f.contextId),keys=[...new Set([...grants.flatMap(g=>[g.data.identity.stagingKey,g.data.identity.finalKey]),...exports.flatMap(e=>e.data.parts.map(p=>p.descriptor.key))])];assert(keys.every(k=>k.startsWith(namespace+'/')));if(keys.length){const secret=env.SUPABASE_SECRET_KEY||env.SUPABASE_SERVICE_ROLE_KEY||'',response=await fetch(`${new URL(env.SUPABASE_URL).origin}/storage/v1/object/${env.SUPABASE_STORAGE_BUCKET||'gs-hale-private'}`,{method:'DELETE',headers:{apikey:secret,authorization:`Bearer ${secret}`,'content-type':'application/json'},body:JSON.stringify({prefixes:keys}),signal:AbortSignal.timeout(60000)});const status=response.status;await response.body?.cancel();assert.equal(status,200);}pass('C01 own UUID Storage objects removed; own schema retained',{count:keys.length,serversStopped:true});}catch{report.checks.push({name:'cleanup',status:'FAIL'});process.exitCode=1;}
 report.envUnchanged=digest(readFileSync(envFile))===digest(original);save();await repo.close();console.log(JSON.stringify({candidate:report.candidate,checks:report.checks,pid:process.pid}));
}
