/** Historical DBs are filesystem-copied, including sidecars and files, before any SQLite open. */
import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
import {createHash} from 'node:crypto';
import {copyFile,mkdir,readdir,readFile,stat,writeFile} from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {createServer} from 'node:net';
import path from 'node:path';
import {openDatabase,migrate} from '@/server/db/database';
import {createSqliteRepository} from '@/server/repositories/sqlite';
import {seed} from '@/server/db/seed';
import type {AiInputDetail} from '@/server/ai-input/contracts';
import type {SubmissionSnapshot} from '@/server/submissions/contracts';
const [label,sourceDb,sourceFiles,destination]=process.argv.slice(2);assert(['accepted-g12','prior-g15-ui'].includes(label)&&sourceDb&&sourceFiles&&destination,'label originalDB files newDestination required');
const cwd=process.cwd(),candidate=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),port=Number(process.env.E2E_PORT??4233),origin=`http://127.0.0.1:${port}`,hash=(b:string|Buffer)=>createHash('sha256').update(b).digest('hex'),checks:{id:string;status:'PASS'|'FAIL'}[]=[],copies:{source:string;copy:string;sha256:string;bytes:number}[]=[],processes:object[]=[],responses:object[]=[];
let db:ReturnType<typeof openDatabase>|null=null,server:ChildProcess|undefined,closed:Promise<void>|undefined,error:string|null=null,firstOpenAt:string|null=null,copyCompletedAt:string|null=null;
const check=(id:string,ok:unknown)=>{checks.push({id,status:ok?'PASS':'FAIL'});assert(ok,id);},targetDb=path.join(destination,'upgrade.db'),files=path.join(destination,'files');
async function copy(a:string,b:string){const bytes=await readFile(a);await mkdir(path.dirname(b),{recursive:true});await copyFile(a,b);assert.equal(hash(await readFile(b)),hash(bytes));copies.push({source:a,copy:b,sha256:hash(bytes),bytes:bytes.length});}
async function tree(a:string,b:string){await mkdir(b,{recursive:true});for(const e of await readdir(a,{withFileTypes:true})){if(e.isDirectory())await tree(path.join(a,e.name),path.join(b,e.name));else if(e.isFile())await copy(path.join(a,e.name),path.join(b,e.name));}}
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function start(){await new Promise<void>((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(port,'127.0.0.1',()=>s.close(e=>e?reject(e):resolve()));});const log=path.join(destination,`server-${processes.length+1}.log`),out=createWriteStream(log);server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],{cwd,env:{...process.env,DATA_SOURCE:'sqlite',DATABASE_FILE:targetDb,FILE_STORAGE_DIR:files,APP_ORIGIN:origin,SESSION_COOKIE_NAME:`g15_union_${port}`,OPENAI_API_KEY:'',OPENAI_MODEL:'',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});server.stdout!.pipe(out);server.stderr!.pipe(out);const child=server;processes.push({pid:child.pid,cwd,argv:['next','start','--port',String(port)],log});closed=new Promise(r=>child.on('close',(code,signal)=>{processes.push({pid:child.pid,exitCode:code,signal});out.end();r();}));for(let i=0;i<200;i++){try{if((await fetch(origin+'/api/health')).ok)return child.pid;}catch{}if(child.exitCode!==null)throw Error('server exited');await pause(50);}throw Error('server unavailable');}
async function stop(){if(server?.exitCode===null)server.kill('SIGTERM');await closed;server=undefined;}
let cookie='';async function request(url:string,body?:unknown){const r=await fetch(origin+url,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,...body!==undefined?{'Content-Type':'application/json',Origin:origin,'X-CSRF-Token':await csrf()}:{}},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie')!.split(';')[0];const bytes=Buffer.from(await r.arrayBuffer()),p=path.join(destination,'responses',`${responses.length+1}.body`);await mkdir(path.dirname(p),{recursive:true});await writeFile(p,bytes);responses.push({url,status:r.status,path:p,sha256:hash(bytes)});assert.equal(r.status,200,bytes.toString().slice(0,500));return bytes;}
async function csrf():Promise<string>{return JSON.parse((await request('/api/auth/csrf')).toString()).csrfToken;}
async function login(){cookie='';await request('/api/auth/login',{email:'admin@example.test',password:'Demo-Hale-2026!'});check('fresh HTTP session established',!!cookie);}
type Raw={kind:string;id:string;context_id:string|null;data:string};
try{
 await mkdir(destination,{recursive:true});for(const suffix of ['','-wal','-shm']){try{await stat(sourceDb+suffix);}catch{continue;}await copy(sourceDb+suffix,path.join(destination,'pristine','original.db'+suffix));await copy(sourceDb+suffix,targetDb+suffix);}await tree(sourceFiles,path.join(destination,'pristine','files'));await tree(sourceFiles,files);copyCompletedAt=new Date().toISOString();
 firstOpenAt=new Date().toISOString();db=openDatabase(targetDb);const before=db.prepare('SELECT * FROM records ORDER BY kind,id').all() as Raw[],ledger=db.prepare('SELECT * FROM schema_migrations ORDER BY name').all() as {name:string;sha256:string}[],expected=label==='accepted-g12'?[1,2,3,4,5,6,7,8,9,10]:[1,2,3,4,5,6,7,8,12];check('filesystem copies complete before first SQLite open',!!copyCompletedAt&&copyCompletedAt<=firstOpenAt);check('historical exact SQL membership',JSON.stringify(ledger.map(r=>Number(r.name.slice(0,4))))===JSON.stringify(expected));check('populated historical records',before.length>50);
 const result=migrate(db);check('only missing SQL added and total11',result.applied===(label==='accepted-g12'?1:2)&&result.total===11);const afterLedger=db.prepare('SELECT * FROM schema_migrations ORDER BY name').all() as {name:string;sha256:string}[];check('old migration ledger exact metadata preserved',JSON.stringify(afterLedger.filter(r=>ledger.some(p=>p.name===r.name)))===JSON.stringify(ledger));check('all old record JSON metadata bytes preserved',JSON.stringify(db.prepare('SELECT * FROM records ORDER BY kind,id').all())===JSON.stringify(before));
 const required=label==='accepted-g12'?['campaignVersion','campaignSelection','submission','productUseSnapshot']:['aiVersion','aiSnapshot','aiAsset'];for(const kind of required){const row=before.find(r=>r.kind===kind);check(`historical positive ${kind} exists`,!!row);let rejected=false;try{db.prepare('UPDATE records SET data=data WHERE kind=? AND id=?').run(kind,row!.id);}catch{rejected=true;}check(`immutable ${kind} guard retained`,rejected);}
 const repeat=migrate(db);check('repeat applied0 total11',repeat.applied===0&&repeat.total===11);await seed(createSqliteRepository(db));check('seed and guard attempts write no historical rows',JSON.stringify(db.prepare('SELECT * FROM records ORDER BY kind,id').all())===JSON.stringify(before));
 await writeFile(path.join(destination,'before-records-private.json'),JSON.stringify(before,null,2));await writeFile(path.join(destination,'migration-facts.json'),JSON.stringify({beforeLedger:ledger,afterLedger,result,repeat,beforeRows:before.length,beforeHash:hash(JSON.stringify(before))},null,2));db.close();db=null;
 const ai=before.filter(r=>r.kind==='aiSnapshot').find(r=>{const d=JSON.parse(r.data);const payload=JSON.parse(d.payload);return payload.segments.some((segment:{method:string})=>segment.method==='ocr')&&payload.text;}),sub=before.filter(r=>r.kind==='submission').find(r=>JSON.parse(r.data).fileVersionIds.length>0),campaign=before.find(r=>r.kind==='campaignVersion');
 if(label==='prior-g15-ui')check('actual historical OCR snapshot exists',!!ai);else check('actual historical campaign and submitted file exist',!!campaign&&!!sub);
 let firstPayload:unknown,pid:number|undefined;for(let round=1;round<=2;round++){const currentPid=await start();if(round===2)check('restart uses another OS process',pid!==currentPid);pid=currentPid;await login();
  if(label==='prior-g15-ui'){const d=JSON.parse(ai!.data),detail=JSON.parse((await request(`/api/ai-input/${d.inputId}?versionId=${d.versionId}`)).toString()) as AiInputDetail,snap=detail.runs.find(r=>r.id===d.runId)!.snapshot!;check(`round${round} exact old OCR snapshot hash`,snap.snapshotHash===d.snapshotHash);check(`round${round} exact old OCR text/units`,isDeepStrictEqual(snap,JSON.parse(d.payload)));const bytes=await request(detail.sources[0].url!);check(`round${round} original OCR source download hash`,hash(bytes)===detail.sources[0].sha256);if(round===1)firstPayload=detail;else check('newPID exact old input/version/runs unchanged',JSON.stringify(detail)===JSON.stringify(firstPayload));}
  else{const d=JSON.parse(sub!.data),snapshot=JSON.parse((await request(`/api/submissions/${sub!.id}`)).toString()) as SubmissionSnapshot;check(`round${round} old submission identity and content hash`,snapshot.id===sub!.id&&snapshot.requestId===d.requestId&&snapshot.contentHash===d.contentHash);const file=snapshot.files[0],bytes=await request(file.originalUrl);check(`round${round} original submitted bytes hash`,hash(bytes)===file.sha256);const c=JSON.parse(campaign!.data),body=JSON.parse((await request(`/api/campaigns/${c.campaignId}?versionId=${campaign!.id}`)).toString());check(`round${round} old campaign readable`,body.id===c.campaignId);if(round===1)firstPayload=snapshot;else check('newPID exact submitted snapshot unchanged',JSON.stringify(snapshot)===JSON.stringify(firstPayload));}
  await stop();
 }
 check('all original source DB sidecars/files hashes unchanged',(await Promise.all(copies.map(async c=>hash(await readFile(c.source))===c.sha256))).every(Boolean));
}catch(e){error=e instanceof Error?e.stack??e.message:String(e);process.exitCode=1;}finally{db?.close();await stop();await writeFile(path.join(destination,'report.json'),JSON.stringify({candidate,cwd,label,sourceDb,sourceFiles,sourceOpened:false,copyCompletedAt,firstOpenAt,copies,checks,processes,responses,error,providerCalls:0,counts:{unit:'assertion',pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length,skip:0,not_run:Math.max(0,(label==='accepted-g12'?28:26)-checks.length)}},null,2));console.log(JSON.stringify({report:path.join(destination,'report.json'),counts:{pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length},error}));}
