import assert from 'node:assert/strict';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdirSync,writeFileSync,readFileSync,existsSync,createWriteStream,readdirSync,statSync,copyFileSync} from 'node:fs';
import path from 'node:path';
import {createServer} from 'node:net';
import {chromium,expect} from '@playwright/test';
import sharp from 'sharp';
import {openDatabase} from '@/server/db/database';
import {createSqliteRepository} from '@/server/repositories/sqlite';
import {business} from './verify-search-ui-fixtures';
import {journey,type Fixture} from './verify-search-ui-journeys';
const mode=process.argv[2],project=process.argv[3],root=path.resolve(process.argv[4]);assert(mode==='mock'||mode==='sqlite');assert(project==='desktop'||project==='mobile');mkdirSync(root,{recursive:true});
const port=Number(process.env.E2E_PORT??4261),origin=`http://127.0.0.1:${port}`,candidate=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),cwd=process.cwd(),startedAt=new Date().toISOString(),viewport=project==='mobile'?{width:390,height:844}:{width:1280,height:900},dpr=project==='mobile'?3:1;
const selection=process.env.G14_CASE?Number(process.env.G14_CASE):null,groups=[1,2,3,4,5,6],checks:{id:string;status:'PASS'|'FAIL'|'NOT_RUN';requirements:string[];failure?:string;directory?:string}[]=[],processes:{pid?:number;argv:string[];cwd:string;log:string;exit:number|null;stopped:boolean}[]=[],copies:{source:string;copy:string;sha256:string}[]=[];let active:ChildProcess|undefined;const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
const delay=(n:number)=>new Promise(resolve=>setTimeout(resolve,n));
function start(argv:string[],env:NodeJS.ProcessEnv,log:string){const out=createWriteStream(log,{flags:'wx'}),p=spawn(process.execPath,argv,{cwd,env,stdio:['ignore','pipe','pipe']});p.stdout!.pipe(out,{end:false});p.stderr!.pipe(out,{end:false});const record={pid:p.pid,argv:[process.execPath,...argv],cwd,log,exit:null as number|null,stopped:false};processes.push(record);p.once('close',code=>{record.exit=code;record.stopped=true;out.end();});return p;}
async function stopped(p:ChildProcess){if(p.exitCode!==null||p.signalCode!==null)return;await new Promise<void>(resolve=>p.once('close',()=>resolve()));}
async function stop(){if(!active)return;const p=active,done=stopped(p);p.kill('SIGTERM');const t=setTimeout(()=>p.kill('SIGKILL'),10000);await done;clearTimeout(t);active=undefined;}
function copy(source:string,target:string){mkdirSync(path.dirname(target),{recursive:true});copyFileSync(source,target);const bytes=readFileSync(source);assert.equal(hash(readFileSync(target)),hash(bytes));copies.push({source,copy:target,sha256:hash(bytes)});}
function files(source:string,target:string){if(!existsSync(source))return;for(const name of readdirSync(source)){const f=path.join(source,name),to=path.join(target,name);if(statSync(f).isDirectory())files(f,to);else copy(f,to);}}
async function server(directory:string){await new Promise<void>((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(port,'127.0.0.1',()=>s.close(e=>e?reject(e):resolve()));});const env={...process.env,DATA_SOURCE:mode,DATABASE_FILE:path.join(directory,'data.db'),FILE_STORAGE_DIR:path.join(directory,'files'),IMPORT_STORAGE_DIR:path.join(directory,'imports'),APP_ORIGIN:origin,SESSION_COOKIE_NAME:`gs_hale_g14_ui_${port}`,E2E_PORT:String(port),OPENAI_API_KEY:'',OPENAI_MODEL:'',OPENAI_BASE_URL:'https://api.openai.com/v1',NEXT_TELEMETRY_DISABLED:'1'};
 if(mode==='sqlite'){const p=start(['--import','tsx','scripts/verify-search-ui-server.ts',mode,directory],env,path.join(directory,'fixture-prepare.log'));await stopped(p);assert.equal(p.exitCode,0,'fixture preflight');active=start(['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],env,path.join(directory,'server.log'));}
 else active=start(['--import','tsx','scripts/verify-search-ui-server.ts',mode,directory],env,path.join(directory,'server.log'));
 for(let n=0;n<600;n++){if(active.exitCode!==null)throw Error('owned server exited; inspect private server log');try{if((await fetch(origin+'/api/health',{signal:AbortSignal.timeout(1000)})).ok)return JSON.parse(readFileSync(path.join(directory,'fixture.json'),'utf8')) as Fixture;}catch{}await delay(50);}throw Error('own server readiness');
}
let failure:string|undefined;const browser=await chromium.launch();
try{for(const group of groups){if(selection&&selection!==group){checks.push({id:`UI14-T0${group}`,status:'NOT_RUN',requirements:['AC-14-01'],failure:'Explicit focused selection'});continue;}const directory=path.join(root,`T0${group}`);mkdirSync(directory,{recursive:true});let context:Awaited<ReturnType<typeof browser.newContext>>|undefined,aux:typeof context;const requests:{url:string;method:string}[]=[],responses:{url:string;status:number;file:string;sha256?:string;captureError?:string}[]=[],pending:Promise<void>[]=[];let f:Fixture|undefined;
 try{f=await server(directory);context=await browser.newContext({baseURL:origin,viewport,deviceScaleFactor:dpr,isMobile:project==='mobile',hasTouch:project==='mobile'});aux=await browser.newContext({baseURL:origin,viewport});await context.tracing.start({screenshots:true,snapshots:true,sources:true});await aux.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();page.on('request',r=>requests.push({url:r.url(),method:r.method()}));page.on('response',r=>{if(!/\/api\/(search|audit)|\/_?search|\/search|\/audit/.test(r.url()))return;const file=path.join(directory,'bodies',`${responses.length+1}.body`);mkdirSync(path.dirname(file),{recursive:true});const entry={url:r.url(),status:r.status(),file};responses.push(entry);pending.push((async()=>{try{const body=await r.body();writeFileSync(file,body);Object.assign(entry,{sha256:hash(body)});}catch(e){Object.assign(entry,{captureError:String(e)});}})());});
 await journey(group,page,aux,origin,f,directory);
 const geometry=await page.evaluate(()=>({innerWidth,clientWidth:document.documentElement.clientWidth,dpr:devicePixelRatio,controls:[...document.querySelectorAll('[data-g14-view] input,[data-g14-view] select,[data-g14-view] button,[data-g14-view] article,[data-g14-view] h2')].filter(e=>e.getClientRects().length).map(e=>{const b=e.getBoundingClientRect();return {tag:e.tagName,left:b.left,right:b.right,width:b.width,label:e.getAttribute('aria-label')??e.textContent?.slice(0,80)};})}));writeFileSync(path.join(directory,'geometry.json'),JSON.stringify(geometry,null,2));expect(geometry.innerWidth).toBe(viewport.width);for(const r of geometry.controls){expect(r.left).toBeGreaterThanOrEqual(-1);expect(r.right).toBeLessThanOrEqual(viewport.width+1);}await page.screenshot({path:path.join(directory,'final-viewport.png')});await page.screenshot({path:path.join(directory,'final-full.png'),fullPage:true});const image=await sharp(path.join(directory,'final-viewport.png')).metadata();expect(image.width).toBe(viewport.width*dpr);writeFileSync(path.join(directory,'final.html'),await page.content());
 if(group===1||group===3)expect(requests.filter(r=>r.method!=='GET')).toEqual([]);
 checks.push({id:`UI14-T0${group}`,status:'PASS',requirements:['AC-14-01','AC-14-02','AC-14-03','AC-14-04','SA-55','SA-56'],directory});
 }catch(e){failure=e instanceof Error?e.stack:String(e);checks.push({id:`UI14-T0${group}`,status:'FAIL',requirements:['AC-14-01','AC-14-02','AC-14-03','AC-14-04'],failure,directory});if(context){const page=context.pages()[0];if(page){writeFileSync(path.join(directory,'failed.html'),await page.content().catch(()=>''));await page.screenshot({path:path.join(directory,'failed.png'),fullPage:true}).catch(()=>{});}}}
 finally{if(context){await context.tracing.stop({path:path.join(directory,'trace.zip')});await context.close();}if(aux){await aux.tracing.stop({path:path.join(directory,'aux-trace.zip')});await aux.close();}await Promise.allSettled(pending);writeFileSync(path.join(directory,'transcript.json'),JSON.stringify({requests,responses},null,2));await stop();}
 if(f&&mode==='sqlite'){const copydir=path.join(directory,'closed-copy');for(const suffix of['','-wal','-shm'])if(existsSync(f.database+suffix))copy(f.database+suffix,path.join(copydir,'data.db'+suffix));files(f.files,path.join(copydir,'files'));const copyCompletedAt=new Date().toISOString();if((group===1||group===3)&&!failure){const repo=createSqliteRepository(openDatabase(path.join(copydir,'data.db')));try{const after=await business(repo);writeFileSync(path.join(directory,'readonly-proof.json'),JSON.stringify({copyCompletedAt,inspectionStartedAt:new Date().toISOString(),before:f.businessBefore,after,unchanged:JSON.stringify(after)===JSON.stringify(f.businessBefore)},null,2));assert.deepEqual(after,f.businessBefore);}finally{repo.close();}}}
 else if(f&&(group===1||group===3)&&!failure)assert.deepEqual(JSON.parse(readFileSync(path.join(directory,'business-after.json'),'utf8')),f.businessBefore);
 if(failure)break;
 }}catch(e){failure=e instanceof Error?e.stack:String(e);const last=checks.findLast(c=>c.status==='PASS');if(last){last.status='FAIL';last.failure=failure;}}finally{await stop();await browser.close();for(const group of groups)if(!checks.some(c=>c.id===`UI14-T0${group}`))checks.push({id:`UI14-T0${group}`,status:'NOT_RUN',requirements:['AC-14-01'],failure:'Prior failure stopped run'});const report={candidate,cwd,mode,project,viewport,dpr,startedAt,finishedAt:new Date().toISOString(),checks,failure,counts:{pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length,not_run:checks.filter(c=>c.status==='NOT_RUN').length,unit:'browser_journey'},processes,copies,realProviderCalls:0,fixture:'Actual canonical Task/Product/Notice/Submission/File services; sixmonth injected clock. Mock cache-injected custom Next server; SQLite normal Next production start.'};writeFileSync(path.join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({counts:report.counts,report:path.join(root,'report.json'),failure}));if(failure)process.exitCode=1;}
