import { randomUUID, createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createMockRepository } from '@/server/repositories/mock';
import { createSqliteRepository } from '@/server/repositories/sqlite';
import { openDatabase, migrate } from '@/server/db/database';
import { seed } from '@/server/db/seed';
import { IdentityService } from '@/server/auth/service';
import { ProductService } from '@/server/products/service';
import { TaskService } from '@/server/tasks/service';
import { NoticeService } from '@/server/notices/service';
import { FileService } from '@/server/files/service';
import { SubmissionService } from '@/server/submissions/service';
import { SearchService } from '@/server/search/service';
import { blankContent, blankRequirement } from '@/domain/tasks/types';
import { blankNotice } from '@/domain/notices/types';
import { blankInternalPrice, blankRetailPrice } from '@/domain/products/types';
import { blankDraft } from '@/domain/submissions/types';
import type { RecordRepository, RecordKind } from '@/domain/records';
export const A = 'ctx-jp-a-luna', B = 'ctx-jp-b-luna';
export const businessKinds: RecordKind[] = ['taskActivity', 'noticeRead', 'inquiryRead', 'submission', 'completionSnapshot', 'notification', 'notificationReceipt', 'notificationAttempt', 'commandReceipt', 'audit'];
export async function business(repo: RecordRepository) { const out: Record<string, string> = {}; for (const kind of businessKinds)
    out[kind] = createHash('sha256').update(JSON.stringify(await repo.list(kind))).digest('hex'); return out; }
export async function fixtures(mode: 'mock' | 'sqlite', directory: string) {
    mkdirSync(directory, { recursive: true });
    const database = path.join(directory, 'data.db'), files = path.join(directory, 'files');
    mkdirSync(files, { recursive: true });
    let fixed: string | null = '2026-02-01T01:00:00.000Z';
    const clock = () => fixed ?? new Date().toISOString();
    const repo = mode === 'mock' ? createMockRepository(clock) : (() => { const db = openDatabase(database, true); migrate(db); return createSqliteRepository(db, clock); })();
    await seed(repo);
    const identity = new IdentityService(repo, clock), products = new ProductService(identity), tasks = new TaskService(identity), notices = new NoticeService(identity), fs = new FileService(identity, files), sub = new SubmissionService(identity), search = new SearchService(identity);
    const login = async (email: string) => (await identity.login(undefined, { email, password: 'Demo-Hale-2026!' })).token;
    const old = await login('selected@example.test'), brandOld = await login('luna@example.test');
    const createProduct = async (token: string, name: string, contextId = A) => (await products.create(token, { contextId, brandId: 'brand-luna', common: { name, code: randomUUID() }, idempotencyKey: randomUUID() })).ids[0];
    const content = (title: string, description = '실제 합성 요청 본문') => ({ ...blankContent(), title, description, deadline: { ...blankContent().deadline, responsibleUserId: 'user-gsg' }, requirements: [{ ...blankRequirement('answer', 'long_text'), label: '답변' }] });
    const createTask = async (token: string, title: string, productIds: string[] = [], contextId = A) => { const id = (await tasks.create(token, { category: 'spot', content: { ...content(title), deadline: { ...content(title).deadline, responsibleUserId: contextId === A ? 'user-gsg' : 'user-admin' } }, targets: [{ contextId, ownerId: contextId === A ? 'user-gsg' : 'user-admin', assigneeId: 'user-luna', coAssigneeIds: contextId === A ? ['user-co'] : [], productIds }], idempotencyKey: randomUUID() })).ids[0]; await tasks.command(token, id, { command: 'publish', expectedRevision: (await repo.get('task', id))!.revision, idempotencyKey: randomUUID() }); return id; };
    const oldProduct = await createProduct(old, 'G14_OLD_原文 상품'), oldProductVersion = (await repo.get('product', oldProduct))!.data.currentVersionId!, oldTask = await createTask(old, 'G14_OLD_原文 업무', [oldProduct]);
    const file = (await fs.upload(old, oldTask, [{ name: 'historical-source.png', type: 'image/png', bytes: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS0cAAAAASUVORK5CYII=', 'base64') }], 'public')).files[0];
    await tasks.command(old, oldTask, { command: 'save', expectedRevision: (await repo.get('task', oldTask))!.revision, content: { ...content('G14_OLD_原文 업무', 'G14_OLD_BODY 정확 원문'), referenceFileIds: [file.id] }, idempotencyKey: randomUUID() });
    await tasks.command(old, oldTask, { command: 'publish', expectedRevision: (await repo.get('task', oldTask))!.revision, idempotencyKey: randomUUID() });
    const oldRequest = (await repo.get('task', oldTask))!.data.currentRequestId!;
    const pw = await products.detail(brandOld, oldProduct, A), sw = await sub.workspace(brandOld, oldTask);
    await sub.draft(brandOld, oldTask, { command: 'save', baseRequestId: sw.request.id, expectedDraftRevision: 0, content: { ...blankDraft(), answers: [{ requestId: sw.request.id, requirementKey: 'answer', productId: null, type: 'long_text', input: { text: 'G14_OLD_ANSWER 제출 원문' } }], productSelections: [{ productId: oldProduct, expectedCommonRevision: pw.commonRevision, expectedContextRevision: pw.contextRevision, bindingIds: [], retailPriceVersionId: null, asOfDate: '2026-02-01' }] }, idempotencyKey: randomUUID() });
    const draft = await sub.workspace(brandOld, oldTask);
    const submit = await sub.submit(brandOld, oldTask, { mode: 'full', expectedDraftRevision: draft.draft!.revision, baseRequestId: draft.request.id, expectedTaskRevision: draft.taskRevision, idempotencyKey: randomUUID() });
    fixed = null;
    const admin = await login('admin@example.test'), brand = await login('luna@example.test');
    const pd = await products.detail(brand, oldProduct, A);
    await products.command(brand, oldProduct, { contextId: A, command: 'save_common', expectedCommonRevision: pd.commonRevision, common: { ...pd.common, name: 'G14_NEW_현재 상품' }, idempotencyKey: randomUUID() });
    await tasks.command(admin, oldTask, { command: 'save', expectedRevision: (await repo.get('task', oldTask))!.revision, content: { ...content('G14_NEW_현재 업무', 'G14_NEW_BODY 최신 원문'), referenceFileIds: [file.id] }, idempotencyKey: randomUUID() });
    await tasks.command(admin, oldTask, { command: 'publish', expectedRevision: (await repo.get('task', oldTask))!.revision, idempotencyKey: randomUUID() });
    const oldUser = (await repo.get('user', 'user-selected-admin'))!;
    await identity.setUserStatus(admin, oldUser.id, { expectedRevision: oldUser.revision, status: 'suspended' });
    const product = await createProduct(admin, '공통찾기 상품A'), task = await createTask(admin, '공통찾기 업무A', [product]);
    const notice = (await notices.create(admin, { contextId: A, content: { ...blankNotice(), title: '공통찾기 공지A', body: '브랜드 공개 안내', documentVersion: 'v1' }, idempotencyKey: randomUUID() })).ids[0];
    await notices.command(admin, notice, { command: 'publish', expectedRevision: (await repo.get('notice', notice))!.revision, idempotencyKey: randomUUID() });
    const noticeVersion = (await repo.get('notice', notice))!.data.currentVersionId!;
    const ownerInvite = await identity.invite(admin, B, { email: 'admin@example.test', name: 'GSG 관리자', role: 'operator' });
    await identity.accept(admin, { token: ownerInvite.token });
    await createProduct(admin, '공통찾기 상품B', B);
    await createTask(admin, '공통찾기 업무B', [], B);
    let p = await products.detail(admin, product, A);
    await products.command(admin, product, { contextId: A, command: 'save_context', expectedContextRevision: p.contextRevision, fields: { ...p.local, sku: '000014', jan: '4900000000014' }, idempotencyKey: randomUUID() });
    await products.command(admin, product, { contextId: A, command: 'save_retail', expectedPriceRevision: 0, price: { ...blankRetailPrice(), amount: '1800', currency: 'JPY', source: '합성 공개 소비자가' }, idempotencyKey: randomUUID() });
    await products.command(admin, product, { contextId: A, command: 'save_retail', expectedPriceRevision: (await products.detail(admin, product, A)).retail.revision, price: { ...blankRetailPrice(), amount: '1980', currency: 'JPY', source: '합성 공개 소비자가' }, idempotencyKey: randomUUID() });
    await products.command(admin, product, { contextId: A, command: 'save_internal', expectedPriceRevision: 0, price: { ...blankInternalPrice(), supplyAmount: '923456789', currency: 'JPY', source: 'G14_UI_INTERNAL_PRICE_ONLY' }, idempotencyKey: randomUUID() });
    await repo.transaction(async (s) => (await s.create('audit', { id: 'g14-legacy-source', contextId: A, data: { action: 'product.created', targetId: product, actorId: 'user-admin', at: '2026-02-01T01:00:00.000Z', before: {}, after: {} } })));
    const longTitle = 'G14_LONG_長い商品名_' + ('LongLatinIdentifier'.repeat(7));
    const longProduct = await createProduct(admin, longTitle);
    p = await products.detail(admin, product, A);
    const before = await business(repo), visible = await search.list(brand, new URLSearchParams({ context: A, q: '공통찾기' }));
    if (visible.total !== 3)
        throw Error('Fixture literal allowed3 preflight: ' + visible.total);
    const result = { mode, database, files, oldProduct, oldProductVersion, oldTask, oldRequest, oldSubmission: submit, oldAt: '2026-02-01T01:00:00.000Z', file, product, task, notice, noticeVersion, longProduct, longTitle, businessBefore: before, visible: visible.items.map(x => x.sourceId), productCommon: p.common, productRevision: p.commonRevision };
    writeFileSync(path.join(directory, 'fixture.json'), JSON.stringify(result, null, 2));
    return { repo, result };
}
