import {expect,type Page,type BrowserContext,type APIRequestContext} from '@playwright/test';
import {randomUUID,createHash} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import path from 'node:path';
import type {fixtures} from './verify-search-ui-fixtures';
import {A,B} from './verify-search-ui-fixtures';
import type {SearchList,SearchDetail} from '@/domain/search/types';
import type {AuditList} from '@/domain/audit/view';
import type {ProductDetail} from '@/server/products/service';
import type {TaskDetail} from '@/server/tasks/service';
export type Fixture=Awaited<ReturnType<typeof fixtures>>['result'];
export async function mutate(r:APIRequestContext,url:string,body:unknown,origin:string,method:'POST'|'PATCH'='POST'){const c=await r.get('/api/auth/csrf');expect(c.status()).toBe(200);return r.fetch(url,{method,data:body,headers:{Origin:origin,'X-CSRF-Token':(await c.json()).csrfToken}});}
export async function login(r:APIRequestContext,origin:string,email='team@example.test'){const result=await mutate(r,'/api/auth/login',{email,password:'Demo-Hale-2026!'},origin);expect(result.status(),await result.text()).toBe(200);}
export async function get<T>(r:APIRequestContext,url:string):Promise<T>{const response=await r.get(url);expect(response.status(),await response.text()).toBe(200);return response.json();}
async function open(page:Page,url:string){await page.goto(url);await expect(page.locator('[data-g14-view]')).toBeVisible();await expect(page.getByText('현재 권한과 기록을 확인하고 있습니다…',{exact:true})).toHaveCount(0);}
const count=(page:Page,n:number)=>expect(page.getByRole('status').filter({hasText:`조회 가능한 기록·버전 ${n}건`})).toBeVisible();
const query=(q:Record<string,string>)=>new URLSearchParams({context:A,...q}).toString();
export async function journey(group:number,page:Page,aux:BrowserContext,origin:string,f:Fixture,out:string){
 await login(page.request,origin,group===3?'operator@example.test':group===5?'admin@example.test':'team@example.test');await login(aux.request,origin,'admin@example.test');
 if(group===1){
  const api=await get<SearchList>(page.request,`/api/search?${query({q:'공통찾기',pageSize:'1'})}`);expect(api.total).toBe(3);expect(api.items).toHaveLength(1);expect(JSON.stringify(api)).not.toMatch(/상품B|업무B|G14_UI_INTERNAL_PRICE_ONLY|923456789/);
  expect((await page.request.get(`/api/search?context=${B}`)).status()).toBe(404);
  await open(page,`/search?${query({q:'공통찾기',pageSize:'1'})}`);await count(page,3);await expect(page.locator('[data-search-hit]')).toHaveCount(1);await expect(page.getByRole('navigation',{name:'검색·감사 메뉴'}).getByRole('link',{name:'변경 기록',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'다음 페이지',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'2 / 3페이지'})).toBeVisible();await page.goBack();await expect(page.getByRole('status').filter({hasText:'1 / 3페이지'})).toBeVisible();
  await page.getByRole('textbox',{name:'제목·본문·파일명·담당 검색',exact:true}).fill('[.*]');await page.getByRole('textbox',{name:'제목·본문·파일명·담당 검색',exact:true}).press('Enter');await expect(page.getByRole('heading',{name:'조건에 맞는 결과가 없습니다',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'필터 해제',exact:true}).click();await page.getByRole('textbox',{name:'SKU',exact:true}).fill('000014');await page.getByRole('textbox',{name:'JAN',exact:true}).fill('4900000000014');await page.getByRole('button',{name:'검색·필터 적용',exact:true}).click();await expect(page.getByRole('textbox',{name:'SKU',exact:true})).toHaveValue('000014');await expect(page.getByRole('link',{name:'공통찾기 상품A',exact:true})).toBeVisible();
  const html=await page.request.get(`/search?${query({q:'공통찾기'})}`);const raw=await html.text();writeFileSync(path.join(out,'positive-ssr.html'),raw);expect(raw).toContain('공통찾기 상품A');expect(raw).not.toMatch(/상품B|업무B|G14_UI_INTERNAL_PRICE_ONLY|923456789/);
 }
 if(group===2){
  await open(page,`/search?${query({q:'G14_OLD_原文',mode:'history',to:'2026-02-02'})}`);const history=await get<SearchList>(page.request,`/api/search?${query({q:'G14_OLD_原文',mode:'history',to:'2026-02-02'})}`);expect(history.items.some(x=>x.sourceId===f.oldProductVersion)).toBe(true);const old=history.items.find(x=>x.sourceId===f.oldRequest)!;expect(old.actor).toEqual({id:'user-selected-admin',label:'이전 작성자'});
  await page.locator(`a[href="${old.historyUrl}"]`).first().click();await expect(page.getByRole('article',{name:'선택한 기록'})).toContainText('G14_OLD_BODY 정확 원문');await expect(page.getByRole('article',{name:'선택한 기록'})).not.toContainText('G14_NEW_BODY');await expect(page.getByRole('link',{name:'관련 현재 화면',exact:true})).toBeVisible();
  const exact=await get<SearchDetail>(page.request,`/api/search/history?${query({kind:'requestVersion',id:f.oldRequest})}`);const file=exact.files.find(x=>x.id===f.file.id)!;expect(file).toBeTruthy();const bytes=await page.request.get(file.downloadUrl);expect(bytes.status()).toBe(200);expect(createHash('sha256').update(await bytes.body()).digest('hex')).toBe(f.file.sha256);
  const submission=await get<SearchDetail>(page.request,`/api/search/history?${query({kind:'submission',id:f.oldSubmission.ids[0]})}`);expect(submission.item.sourceId).toBe(f.oldSubmission.ids[0]);await open(page,submission.item.historyUrl);await expect(page.getByRole('article',{name:'선택한 기록'})).toContainText('G14_OLD_ANSWER 제출 원문');await expect(page.getByRole('link',{name:'관련 현재 화면',exact:true})).toBeVisible();
  const productUse=history.items.find(x=>x.sourceKind==='productUseSnapshot')!;expect(productUse).toBeTruthy();await open(page,productUse.historyUrl);await expect(page.getByRole('article',{name:'선택한 기록'})).toContainText('G14_OLD_原文 상품');await expect(page.getByRole('article',{name:'선택한 기록'})).not.toContainText('G14_NEW_현재 상품');
  await open(page,`/search/history?${query({kind:'noticeVersion',id:f.oldRequest})}`);await expect(page.locator('[data-g14-view]').getByRole('alert')).toContainText('현재 기록을 열 수 없습니다');await expect(page.getByRole('article',{name:'선택한 기록'})).toHaveCount(0);
  await open(page,`/search?${query({task:f.oldTask,mode:'history',assignee:'user-co'})}`);expect((await get<SearchList>(page.request,`/api/search?${query({task:f.oldTask,assignee:'user-co'})}`)).total).toBeGreaterThan(0);await expect(page.getByText(/현재 관련 업무 담당:.*공동 담당자/).first()).toBeVisible();
  const task=await get<TaskDetail>(aux.request,`/api/tasks/${f.oldTask}?context=${A}`);const assign=await mutate(aux.request,`/api/tasks/${f.oldTask}`,{command:'assign',expectedRevision:task.task.revision,assignment:{ownerId:'user-price',assigneeId:'user-team',coAssigneeIds:[]},idempotencyKey:randomUUID()},origin);expect(assign.status(),await assign.text()).toBe(200);
  await page.getByRole('button',{name:'현재 기록 다시 확인',exact:true}).click();await count(page,0);await page.getByRole('combobox',{name:'현재 관련 업무 담당',exact:true}).selectOption('user-team');await page.getByRole('combobox',{name:'기록 작성자',exact:true}).selectOption('user-selected-admin');await page.getByRole('button',{name:'검색·필터 적용',exact:true}).click();await expect(page.locator(`a[href*="id=${f.oldRequest}"]`).first()).toBeVisible();
  const after=await get<SearchList>(page.request,`/api/search?${query({task:f.oldTask,mode:'history',actor:'user-selected-admin',assignee:'user-team'})}`);expect(after.items.some(x=>x.sourceId===f.oldRequest&&x.actor.id==='user-selected-admin'&&x.assignees.some(a=>a.id==='user-price'))).toBe(true);
  const n=await get<SearchList>(page.request,`/api/search?${query({q:'공통찾기 공지A'})}`);await open(page,n.items[0].historyUrl);await page.getByRole('link',{name:'이 버전 원본 화면',exact:true}).click();await expect(page).toHaveURL(new RegExp(f.noticeVersion));await expect(page.getByRole('heading',{name:'공통찾기 공지A',exact:true})).toBeVisible();
 }
 if(group===3){
  await open(page,`/audit?${query({product:f.product})}`);const safe=await get<AuditList>(page.request,`/api/audit?${query({product:f.product})}`);expect(safe.items.some(x=>x.action==='product.save_internal')).toBe(false);expect(JSON.stringify(safe)).not.toMatch(/G14_UI_INTERNAL_PRICE_ONLY|923456789/);
  const price=await get<AuditList>(aux.request,`/api/audit?${query({product:f.product,status:'product.save_internal'})}`);expect(price.total).toBe(1);const privateVersion=price.items[0].versions.find(x=>x.kind==='internalPriceVersion')!;expect(privateVersion).toBeTruthy();const privateDetail=await get<SearchDetail>(aux.request,privateVersion.url.replace('/search/history?','/api/search/history?'));expect(privateDetail.fields.some(x=>x.label==='공급가'&&x.value==='923456789')).toBe(true);
  const retail=safe.items.find(x=>x.action==='product.save_retail'&&x.changes.some(c=>c.label==='금액'&&c.before==='1800'&&c.after==='1980'))!;expect(retail).toBeTruthy();await page.locator(`a[href*="/audit/${retail.id}?"]`).first().click();await expect(page.getByRole('article',{name:'선택한 변경 기록'})).toContainText('1980');await expect(page.getByRole('article',{name:'선택한 변경 기록'})).toContainText('변경 후');await expect(page.getByRole('article',{name:'선택한 변경 기록'})).not.toContainText('923456789');
  await open(page,`/audit/g14-legacy-source?context=${A}`);await page.getByText('기록 정보',{exact:true}).click();await expect(page.getByRole('article',{name:'선택한 변경 기록'})).toContainText('이전 기록에 연결 정보가 없습니다');
  await login(page.request,origin,'team@example.test');await open(page,`/audit?context=${A}`);await expect(page.locator('[data-g14-view]').getByRole('alert')).toContainText('현재 기록을 열 수 없습니다');await expect(page.getByRole('article')).toHaveCount(0);
 }
 if(group===4){
  await open(page,`/search?${query({q:'공통찾기'})}`);let release:()=>Promise<void>=async()=>{},captured=false;await page.route('**/api/search?**',async route=>{if(captured)return route.continue();captured=true;const response=await route.fetch();writeFileSync(path.join(out,'held-actual-body.json'),await response.body());await new Promise<void>(resolve=>{release=async()=>{await route.fulfill({response});resolve();};});});
  await page.getByRole('button',{name:'현재 기록 다시 확인',exact:true}).click();await expect.poll(()=>captured).toBe(true);await page.getByRole('textbox',{name:'제목·본문·파일명·담당 검색',exact:true}).fill('G14_LONG');await page.getByRole('button',{name:'검색·필터 적용',exact:true}).click();await count(page,1);await release();await expect(page.getByRole('link',{name:f.longTitle,exact:true})).toBeVisible();await page.unroute('**/api/search?**');
  await page.getByRole('textbox',{name:'제목·본문·파일명·담당 검색',exact:true}).fill('검색의도 유지');await page.route('**/api/search?**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'합성 일시 조회 실패'}})}));await page.getByRole('button',{name:'현재 기록 다시 확인',exact:true}).click();await expect(page.locator('[data-g14-view]').getByRole('alert')).toContainText('조회 실패는 검색 결과 0건과 다릅니다');await expect(page.getByRole('textbox',{name:'제목·본문·파일명·담당 검색',exact:true})).toHaveValue('검색의도 유지');await page.unroute('**/api/search?**');await page.getByRole('button',{name:'같은 조건으로 다시 조회',exact:true}).click();await count(page,1);
  captured=false;await page.route('**/api/search?**',async route=>{if(captured)return route.continue();captured=true;const response=await route.fetch();writeFileSync(path.join(out,'held-before-revocation.json'),await response.body());await new Promise<void>(resolve=>{release=async()=>{await route.fulfill({response});resolve();};});});await page.getByRole('button',{name:'현재 기록 다시 확인',exact:true}).click();await expect.poll(()=>captured).toBe(true);
  let releaseRsc:()=>Promise<void>=async()=>{},rscCaptured=false;await page.route('**/search/history?**',async route=>{if(!route.request().headers()['rsc'])return route.continue();const response=await route.fetch(),body=await response.body();writeFileSync(path.join(out,'held-actual-rsc.body'),body);expect(body.toString()).toContain(f.longTitle);rscCaptured=true;await new Promise<void>(resolve=>{releaseRsc=async()=>{await route.fulfill({response});resolve();};});});await page.getByRole('link',{name:f.longTitle,exact:true}).click();await expect.poll(()=>rscCaptured).toBe(true);
  const members=await get<{members:{id:string;revision:number;user:{id:string}}[]}>(aux.request,`/api/contexts/${A}/members`);const member=members.members.find(x=>x.user.id==='user-team')!;const revoked=await mutate(aux.request,`/api/contexts/${A}/members/${member.id}`,{expectedRevision:member.revision,status:'suspended'},origin,'PATCH');expect(revoked.status(),await revoked.text()).toBe(200);
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('[data-g14-view]').getByRole('alert')).toContainText('현재 기록을 열 수 없습니다');await page.evaluate(()=>{const root=document.querySelector('#main-content')!;(window as unknown as {g14Flashes:string[]}).g14Flashes=[];new MutationObserver(()=>{if(root.textContent?.includes('G14_LONG'))(window as unknown as {g14Flashes:string[]}).g14Flashes.push('protected-text');}).observe(root,{subtree:true,childList:true,characterData:true});});await release();await releaseRsc();await expect(page).toHaveURL(/\/search\/history\?/);await expect(page.locator('[data-g14-view="history"]')).toBeVisible();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));writeFileSync(path.join(out,'late-delivery-settled.json'),JSON.stringify({url:page.url(),actualOriginalResponsesDelivered:true,historySurfaceMounted:true}));await page.unroute('**/api/search?**');await page.unroute('**/search/history?**');await expect(page.locator('[data-g14-view]').getByRole('alert')).toContainText('현재 기록을 열 수 없습니다');await expect(page.getByRole('article',{name:'선택한 기록'})).toHaveCount(0);await expect(page.locator('[data-search-hit]')).toHaveCount(0);expect(await page.evaluate(()=>(window as unknown as {g14Flashes:string[]}).g14Flashes)).toEqual([]);await expect(page.getByRole('combobox',{name:'조회 컨텍스트',exact:true})).toHaveCount(0);
  const denied=await page.request.get(`/search?${query({q:'G14_LONG'})}`),raw=await denied.text();writeFileSync(path.join(out,'denied-fresh-ssr.html'),raw);expect(raw).not.toContain(f.longTitle);expect(raw).toContain('현재 기록을 열 수 없습니다');await page.getByRole('navigation',{name:'주 메뉴'}).getByRole('link',{name:/검색·이력/}).click();await expect(page.locator('[data-g14-view]').getByRole('alert')).toBeVisible();
 }
 if(group===5){
  await page.goto(`/products/${f.product}?context=${A}`);const editor=page.locator('#common');await editor.getByRole('textbox',{name:/^상품명\s*\*$/,exact:true}).fill('G14_UI_LOCAL_REAPPLY');const d=await get<ProductDetail>(aux.request,`/api/products/${f.product}?context=${A}`);
  await login(aux.request,origin,'luna@example.test');const win=await mutate(aux.request,`/api/products/${f.product}`,{contextId:A,command:'save_common',expectedCommonRevision:d.commonRevision,common:{...d.common,name:'G14_OTHER_WRITER_WIN'},idempotencyKey:randomUUID()},origin);expect(win.status()).toBe(200);
  await editor.getByRole('button',{name:'브랜드 공통 정보 저장',exact:true}).click();await expect(editor.getByRole('alert')).toBeVisible();await expect(editor.getByRole('textbox',{name:/^상품명\s*\*$/,exact:true})).toHaveValue('G14_UI_LOCAL_REAPPLY');await editor.getByRole('button',{name:'최신 저장값 확인',exact:true}).click();await expect(editor.getByRole('heading',{name:'최신 저장값 · 비교 후 선택',exact:true})).toBeVisible();await expect(editor).toContainText('G14_OTHER_WRITER_WIN');await editor.getByRole('button',{name:'입력 유지하고 최신 버전 기준 사용',exact:true}).click();await editor.getByRole('button',{name:'브랜드 공통 정보 저장',exact:true}).click();await expect(editor.getByRole('status').filter({hasText:'브랜드 공통 정보를 저장했습니다.'})).toBeVisible();
  const before=await get<AuditList>(page.request,`/api/audit?${query({product:f.product,status:'product.save_common'})}`);expect(before.total).toBe(2);let lost=false;const bodies:unknown[]=[];
  await page.route(`**/api/products/${f.product}`,async route=>{if(route.request().method()!=='POST')return route.continue();bodies.push(route.request().postDataJSON());if(lost)return route.continue();lost=true;const r=await route.fetch();expect(r.status()).toBe(200);writeFileSync(path.join(out,'committed-lost-response.json'),await r.body());await route.abort('failed');});
  await editor.getByRole('textbox',{name:/^상품명\s*\*$/,exact:true}).fill('G14_UI_DURABLE_AFTER_LOSS');await editor.getByRole('button',{name:'브랜드 공통 정보 저장',exact:true}).click();await expect(editor.getByRole('alert')).toBeVisible();await expect(editor.getByRole('textbox',{name:/^상품명\s*\*$/,exact:true})).toHaveValue('G14_UI_DURABLE_AFTER_LOSS');await editor.getByRole('button',{name:'브랜드 공통 정보 저장',exact:true}).click();await expect(editor.getByRole('status').filter({hasText:'브랜드 공통 정보를 저장했습니다.'})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[1]).toEqual(bodies[0]);await page.unroute(`**/api/products/${f.product}`);
  const after=await get<AuditList>(page.request,`/api/audit?${query({product:f.product,status:'product.save_common'})}`);expect(after.total).toBe(before.total+1);const current=await get<ProductDetail>(page.request,`/api/products/${f.product}?context=${A}`);writeFileSync(path.join(out,'ui-created-record.json'),JSON.stringify({productId:f.product,name:current.common.name,commonRevision:current.commonRevision,events:after.items,oldTask:f.oldTask,oldRequest:f.oldRequest,file:f.file},null,2));
  await open(page,`/audit?${query({product:f.product,status:'product.save_common'})}`);const event=after.items.find(x=>JSON.stringify(x).includes('G14_UI_DURABLE_AFTER_LOSS'))!;expect(event).toBeTruthy();await page.locator(`a[href*="/audit/${event.id}?"]`).first().click();await expect(page.getByRole('article',{name:'선택한 변경 기록'})).toContainText('G14_UI_DURABLE_AFTER_LOSS');
 }
 if(group===6){
  await open(page,`/search?${query({q:'G14_LONG'})}`);const textbox=page.getByRole('textbox',{name:'제목·본문·파일명·담당 검색',exact:true});await textbox.focus();await textbox.press('ControlOrMeta+A');await textbox.press('Backspace');await textbox.pressSequentially('G14_LONG');await textbox.press('Enter');await count(page,1);await page.getByRole('link',{name:f.longTitle,exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('article',{name:'선택한 기록'})).toContainText(f.longTitle);
 }
}
