import assert from 'node:assert/strict';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,readdirSync,statSync,existsSync,createWriteStream} from 'node:fs';
import path from 'node:path';
import {chromium} from '@playwright/test';
import type {CompletionWorkspace} from '@/server/completion/service';
const summaryPath=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);mkdirSync(out,{recursive:true});
const summary=JSON.parse(readFileSync(summaryPath,'utf8')),port=Number(process.env.E2E_PORT??4233);assert.equal(summary.mode,'sqlite');assert(Number.isSafeInteger(port));
const candidate=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),cwd=process.cwd(),checks:{id:string;status:'PASS';requirements:string[];level:string}[]=[],copies:{source:string;copy:string;sha256:string}[]=[],processes:{pid:number|undefined;argv:string[];log:string;stopped:boolean}[]=[];
function hash(b:Buffer){return createHash('sha256').update(b).digest('hex');}
function walk(p:string):string[]{return readdirSync(p).flatMap(n=>{const f=path.join(p,n);return statSync(f).isDirectory()?walk(f):[f];});}
function copy(source:string,target:string){mkdirSync(path.dirname(target),{recursive:true});const bytes=readFileSync(source);writeFileSync(target,bytes);copies.push({source,copy:target,sha256:hash(bytes)});}
function check(id:string,condition:unknown,level='HTTP'){assert(condition,id);checks.push({id,status:'PASS',requirements:['AC-11-02','AC-11-03','AC-11-04','A20'],level});}
let child:ChildProcess|undefined,failure:string|undefined;
async function stop(){if(!child)return;const p=child;const exited=new Promise<void>(r=>p.once('exit',()=>r()));if(p.exitCode===null&&p.signalCode===null){p.kill('SIGTERM');await exited;}processes.find(x=>x.pid===p.pid)!.stopped=true;child=undefined;}
try{for(const kind of ['flow','followup']){const file=summary.projects[0].files.find((f:{file:string})=>f.file.endsWith(`completion-${kind}.spec.ts`));assert(file&&file.exit_code===0);const dataFile=walk(file.artifacts).find(f=>f.endsWith(kind==='flow'?'ui-created-records.json':'ui-created-followup.json'));assert(dataFile);const record=JSON.parse(readFileSync(dataFile,'utf8')),dir=path.join(out,kind),db=path.join(dir,'database.db'),files=path.join(dir,'files');for(const suffix of['','-wal','-shm'])if(existsSync(file.database+suffix))copy(file.database+suffix,db+suffix);for(const source of walk(file.file_storage))copy(source,path.join(files,path.relative(file.file_storage,source)));check(kind+' FS copy before normal Next startup',true,'FS_COPY');const origin=`http://127.0.0.1:${port}`;
for(let iteration=1;iteration<=2;iteration++){const argv=['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],log=path.join(dir,`server-${iteration}.log`),output=createWriteStream(log);child=spawn(process.execPath,argv,{cwd,env:{...process.env,DATA_SOURCE:'sqlite',DATABASE_FILE:db,FILE_STORAGE_DIR:files,IMPORT_STORAGE_DIR:path.join(dir,'imports'),APP_ORIGIN:origin,SESSION_COOKIE_NAME:'gs_hale_completion_ui_restart_'+port,OPENAI_API_KEY:'',OPENAI_MODEL:'',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});child.stdout!.pipe(output,{end:false});child.stderr!.pipe(output,{end:false});child.once('exit',()=>output.end());processes.push({pid:child.pid,argv:[process.execPath,...argv],log,stopped:false});for(let n=0;n<200;n++){if(child.exitCode!==null)throw Error('Next exited');try{if((await fetch(origin+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,50));}
const browser=await chromium.launch();try{const context=await browser.newContext({baseURL:origin,viewport:{width:390,height:844}}),page=await context.newPage();await context.tracing.start({screenshots:true,snapshots:true,sources:true});await page.goto('/login');await page.getByRole('textbox',{name:'이메일',exact:true}).fill('admin@example.test');await page.getByLabel('비밀번호',{exact:true}).fill('Demo-Hale-2026!');await page.getByRole('button',{name:'로그인',exact:true}).click();await page.waitForURL(origin+'/');const response=await page.request.get(`/api/completion?taskId=${record.taskId}`);check(`${kind} PID${iteration} fresh login completion HTTP`,response.status()===200);const w:CompletionWorkspace=await response.json();writeFileSync(path.join(dir,`workspace-${iteration}.json`),JSON.stringify(w,null,2));if(kind==='flow'){check(`flow PID${iteration} immutable completion versions`,JSON.stringify(w.history.map(x=>x.id))===JSON.stringify(record.completionIds));const first=w.history.find(x=>x.id===record.completionIds[1])!;check(`flow PID${iteration} original residual basis`,JSON.stringify(first.basis)===JSON.stringify(record.basis));const external=w.externalActions.find(x=>x.id===record.externalId)!;assert(external);const f=external.source.files.find(x=>x.id===record.sourceFileId)!;const bytes=await page.request.get(f.downloadUrl);check(`flow PID${iteration} original file bytes`,bytes.status()===200&&hash(await bytes.body())===record.sourceHash);}else{check(`followup PID${iteration} actual created task association`,w.followups.some(x=>x.id===record.followup.id&&x.taskId===record.followup.taskId)&&w.history.some(x=>x.id===record.completionId));}
await page.goto(`/tasks/${record.taskId}/completion?context=${w.contextId}`);await page.getByText('현재 권한과 저장본을 확인하는 중입니다.',{exact:true}).waitFor({state:'hidden'});await page.getByRole('navigation',{name:'완료·외부 진행 화면',exact:true}).getByRole('button',{name:'완료·재개 이력',exact:true}).click();await page.getByRole('heading',{name:/완료 v1/}).waitFor();if(kind==='followup')await page.getByRole('link',{name:record.followup.title+' ↗',exact:true}).waitFor();check(`${kind} PID${iteration} actual UI history`,true,'BROWSER');await page.screenshot({path:path.join(dir,`ui-${iteration}-viewport.png`)});await page.screenshot({path:path.join(dir,`ui-${iteration}-full.png`),fullPage:true});await context.tracing.stop({path:path.join(dir,`ui-${iteration}.zip`)});await context.close();}finally{await browser.close();}await stop();}
}for(const c of copies)assert.equal(hash(readFileSync(c.source)),c.sha256);check('all closed UI source DB sidecars files unchanged',true,'FS_COPY');}catch(e){failure=e instanceof Error?e.stack:String(e);}finally{await stop();writeFileSync(path.join(out,'report.json'),JSON.stringify({candidate,cwd,summaryPath,summaryHash:hash(readFileSync(summaryPath)),copies,processes,checks,failure,counts:{unit:'assertion',pass:checks.length,fail:failure?1:0},realProviderCalls:0},null,2));}if(failure){console.error(failure);process.exitCode=1;}else console.log(JSON.stringify({pass:checks.length,report:path.join(out,'report.json')}));
