import {spawn,execFileSync} from 'node:child_process';
import {mkdirSync,createWriteStream,writeFileSync} from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import {expect,type APIRequestContext} from '@playwright/test';
import {api,ctx,createTask,taskCommand,partial,createNotice,detail,noticeCommand,post} from '../tests/fixtures/notices';
const output=path.resolve(process.env.EVIDENCE_ROOT!,'fixture-preflight-'+Date.now());mkdirSync(output,{recursive:true});const port=Number(process.env.E2E_PORT),origin=`http://127.0.0.1:${port}`;
const busy=await new Promise<boolean>(r=>{const s=net.connect(port,'127.0.0.1');s.once('connect',()=>{s.destroy();r(true);});s.once('error',()=>r(false));});if(busy)throw Error('Assigned port busy');
const log=path.join(output,'server.log'),stream=createWriteStream(log),command=[process.execPath,'node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)];const server=spawn(command[0],command.slice(1),{cwd:process.cwd(),env:{...process.env,DATA_SOURCE:'mock',FILE_STORAGE_DIR:path.join(output,'files'),APP_ORIGIN:origin,SESSION_COOKIE_NAME:`gs_hale_notice_preflight_${port}`,OPENAI_API_KEY:'',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});server.stdout.pipe(stream,{end:false});server.stderr.pipe(stream,{end:false});server.once('close',()=>stream.end());const sessions:APIRequestContext[]=[],checks:{id:string;status:string;unit:string}[]=[];let failed=false;
async function check(id:string,run:()=>Promise<unknown>){try{const value=await run();checks.push({id,status:'PASS',unit:'assertion'});return value;}catch(e){checks.push({id,status:'FAIL',unit:'assertion'});throw e;}}
try{for(let i=0;i<200;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error('Server exited');await new Promise(r=>setTimeout(r,50));}const admin=await api(),brand=await api('luna@example.test');sessions.push(admin,brand);const taskId=await check('P08-01 actual G04 create full required input products',()=>createTask(admin,'G08 fixture preflight',['product-serum'])) as string;await check('P08-02 actual G04 publish',()=>taskCommand(admin,taskId,'publish'));const baseline=await check('P08-03 actual G05 partial file and product capture',()=>partial(brand,taskId));const id=await check('P08-04 actual G08 create linked notice',()=>createNotice(admin,{taskIds:[taskId]},ctx)) as string;await check('P08-05 actual publication',()=>noticeCommand(admin,id,'publish'));const before=await detail(brand,id);await check('P08-06 actual exact read',()=>post(brand,`/api/notices/${id}`,{command:'read',versionId:before.selected!.id,idempotencyKey:crypto.randomUUID()}));await check('P08-07 actual read state and task relation',async()=>{const after=await detail(brand,id);expect(after.selected!.ownReadAt).toBeTruthy();expect(after.selected!.content.tasks[0].status).toBe('partial');writeFileSync(path.join(output,'preflight-private.json'),JSON.stringify({taskId,id,baseline,before,after},null,2));});}catch(e){failed=true;console.error(e);}finally{for(const s of sessions)await s.dispose();await new Promise<void>(r=>{if(server.exitCode!==null)return r();server.once('close',()=>r());server.kill('SIGTERM');});writeFileSync(path.join(output,'report.json'),JSON.stringify({source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),cwd:process.cwd(),command,server_pid:server.pid,exit:server.exitCode,signal:server.signalCode,log,checks,counts:{unit:'assertion',pass:checks.filter(c=>c.status==='PASS').length,fail:checks.filter(c=>c.status==='FAIL').length,skip:0,not_run:7-checks.length},outcome:failed?'FAIL':'PASS'},null,2));console.log(JSON.stringify({output,failed}));}if(failed)process.exitCode=1;
