'use client';
import { useState } from 'react';
import type { QuestionDTO, ActiveConversationDetailDTO, InquiryCommand } from '@/server/inquiries/contracts';
import type { InquiryController } from './controller';
import s from './ui.module.css';
export function StateEditor({ q, detail, c }: {
    q: QuestionDTO;
    detail: ActiveConversationDetailDTO;
    c: InquiryController;
}) { const [basis, setBasis] = useState(q.revision); const [state, setState] = useState<'gsg_waiting' | 'brand_supplement_waiting' | 'external_waiting'>(q.state === 'resolved' ? 'gsg_waiting' : q.state), [reason, setReason] = useState(''), [counterparty, setCounterparty] = useState(q.externalWait?.counterparty ?? ''), [sentAt, setSentAt] = useState(q.externalWait?.sentAt ?? ''), [responsible, setResponsible] = useState(''), [nextDate, setNextDate] = useState(q.externalWait?.nextCheckDate ?? ''), [timezone, setTimezone] = useState(q.externalWait?.timezone ?? 'Asia/Tokyo'), [result, setResult] = useState(q.externalWait?.latestResult ?? ''); if (q.state === 'resolved')
    return null; return <details><summary>질문 상태·외부 확인 기록</summary><form className={s.stack} onSubmit={e => { e.preventDefault(); const base = { command: 'state' as const, questionId: q.id, expectedQuestionRevision: basis, reason, idempotencyKey: crypto.randomUUID() }; const cmd: InquiryCommand = state === 'external_waiting' ? { ...base, state, externalWait: { counterparty, sentAt: sentAt || null, responsibleUserId: responsible, nextCheckDate: nextDate, timezone, latestResult: result } } : { ...base, state, externalWait: null }; void c.run(cmd); }}>{basis !== q.revision && <div className={s.notice}>서버의 질문 상태가 변경되었습니다. 작성한 값은 유지했습니다.<button type="button" className="button subtle" onClick={() => setBasis(q.revision)}>현재 상태 확인 · 작성값 유지하고 기준 갱신</button></div>}<fieldset disabled={c.busy || !!c.recovery.intent || !!c.recovery.committed} className={s.stack} style={{ border: 0, padding: 0, minWidth: 0 }}><label className={s.field}>질문 상태<select value={state} onChange={e => setState(e.target.value as typeof state)}><option value="gsg_waiting">GSG 답변 대기</option><option value="brand_supplement_waiting">브랜드 보완 대기</option><option value="external_waiting">외부 확인 대기</option></select></label><label className={s.field}>상태 변경 사유<textarea required value={reason} onChange={e => setReason(e.target.value)} maxLength={2000}/></label>{state === 'external_waiting' && <div className={s.grid}><label className={s.field}>외부 확인 상대<input required maxLength={500} value={counterparty} onChange={e => setCounterparty(e.target.value)}/></label><label className={s.field}>외부 요청 시각 · ISO 시각, 모르면 비움<input value={sentAt} placeholder="2026-10-01T10:00:00+09:00" onChange={e => setSentAt(e.target.value)}/></label><label className={s.field}>현재 확인 책임자<select aria-label="현재 확인 책임자" required value={responsible} onChange={e => setResponsible(e.target.value)}><option value="">현재 담당자를 명시적으로 선택</option>{detail.staffOptions.map(p => <option key={p.id} value={p.id}>{p.label} · {p.id}</option>)}</select><span className={s.meta}>기존 표시: {q.externalWait?.responsibleLabel ?? '미지정'}. 이름으로 신원을 추정하지 않습니다.</span></label><label className={s.field}>다음 확인일<input required type="date" value={nextDate} onChange={e => setNextDate(e.target.value)}/></label><label className={s.field}>확인일 시간대<input required value={timezone} onChange={e => setTimezone(e.target.value)}/></label><label className={s.field}>최신 외부 확인 결과<textarea maxLength={2000} value={result} onChange={e => setResult(e.target.value)}/></label></div>}<button className="button subtle">질문 상태 기록</button></fieldset></form></details>; }
