'use client';
import { useState } from 'react';
import Link from 'next/link';
import type { ScheduleDetail, ScheduleList } from '@/server/scheduling/contracts';
import { ScheduleEditor } from './editor';
import { ScheduleTimeline, ScheduleHistory, ScheduleCard } from './views';
import { kindLabels } from './presentation';
import { history, presentation, stateLabels } from './model';
import { useSchedule } from './controller';
import s from './ui.module.css';
export function ScheduleScreen({ actorId, list: initialList, detail: initialDetail, initialTask = '' }: {
    actorId: string;
    list: ScheduleList;
    detail: ScheduleDetail | null;
    initialTask?: string;
}) {
    const c = useSchedule({ actorId, list: initialList, detail: initialDetail }, initialTask), [editing, setEditing] = useState(!!initialDetail), [filters, setFilters] = useState({ task: initialTask, kind: '', from: '', to: '' }), [view, setView] = useState<'timeline' | 'list'>('timeline');
    if (!c.list)
        return <section className={s.empty}><h1>일정을 볼 수 없습니다</h1><p>{c.error}</p><Link href="/login">로그인 확인</Link></section>;
    const items = c.list.items.filter(r => (!filters.task || r.taskId === filters.task) && (!filters.kind || r.kind === filters.kind) && (!filters.from || r.calendar.dueDay !== null && r.calendar.dueDay >= filters.from) && (!filters.to || r.calendar.dueDay !== null && r.calendar.dueDay <= filters.to)), groups = new Map<string, ReturnType<typeof presentation>[]>();
    for (const row of items) {
        const key = row.calendar.dueDay ?? '날짜 미정';
        groups.set(key, [...(groups.get(key) ?? []), presentation(row)]);
    }
    const submitKinds = ['brand_reply', 'submission', 'correction'].includes(c.editor.value.kind);
    const options = c.list.actors.filter(a => a.taskIds.includes(c.editor.value.taskId));
    const canEdit = c.detail ? c.detail.capabilities.manage : c.list.capabilities.create;
    const filterOptions = [...new Map([...c.list.tasks.map(t => [t.id, t.title] as const), ...c.list.items.filter(r => r.taskId).map(r => [r.taskId!, r.title] as const)]).entries()];
    return <div className={s.stack}><header className={s.panel}><p className="eyebrow">SCHEDULE</p><h1>{c.detail ? '일정 상세' : '일정·다음 행동'}</h1><p>기한의 확인 주체와 실제 행동 담당자를 구분합니다. 일정별 확인 수준과 원문을 함께 보세요.</p><div className={s.actions}><Link className="button subtle" href={`/notifications?context=${c.list.contextId}`}>내 알림 보기</Link>{c.detail ? <Link className="button subtle" href={`/schedule?context=${c.list.contextId}`}>일정 목록</Link> : c.list.capabilities.create && <button className="button" onClick={() => setEditing(x => !x)}>{editing ? '일정 작성 접기' : '새 일정 기록'}</button>}</div></header>
 {!c.ready && <p role="status">현재 권한과 일정을 확인하고 있습니다.</p>}{c.error && <p role="alert" className={s.error}>{c.error}</p>}{c.message && <p role="status" className={s.note}>{c.message}</p>}{c.storageError && <p role="alert" className={s.warning}>{c.storageError}</p>}
 {c.recovery && <section className={s.panel}><h2>작성·요청 복구 기록</h2><p>이 계정과 컨텍스트에서 남긴 작성값이 있습니다. 결과를 모르는 요청은 같은 키로 확인합니다.</p><div className={s.actions}><button className="button" onClick={() => { c.restore(); setEditing(true); }}>작성·요청 복구</button><button className="button subtle" onClick={c.discardRecovery}>복구 기록 버리기</button></div></section>}
 {c.detail && <><ScheduleCard item={{ ...presentation(c.detail.calendar), content: c.detail.current.content, detailHref: null, activityLabel: stateLabels[c.detail.current.state] }}/><p className={s.hint}>현재 저장 버전 {c.detail.revision} · 공개 이력 v{c.detail.current.sequence}</p></>}
 {editing && canEdit && <form className={s.panel} onSubmit={e => { e.preventDefault(); void c.execute(); }}><h2>{c.editor.id ? '일정 수정' : '새 일정 기록'}</h2><ScheduleEditor value={c.editor.value} onChange={value => c.edit({ ...c.editor, value })} dateTime={c.editor.dateTime} onDateTimeChange={dateTime => c.edit({ ...c.editor, dateTime })} tasks={c.list.tasks.map(t => ({ id: t.id, label: t.title }))} responsibleOptions={options.map(a => ({ id: a.id, label: `${a.label} · ${a.role === 'gsg' ? 'GSG' : '브랜드'}` }))} responsibilityLabel={submitKinds ? '기한 확인 책임자' : '확인·다음 행동 책임자'} responsibilityHelp={submitKinds ? '이 사람은 기한 확인 주체입니다. 실제 제출·회신·수정은 현재 업무의 주·공동 브랜드 담당자가 수행합니다.' : '선택한 사람은 이 일정의 다음 행동을 담당합니다. 현재 업무의 주·공동 브랜드 담당자 또는 GSG를 명시적으로 선택해 주세요.'} disabled={!c.ready || c.busy || !!c.pending} taskLocked={!!c.editor.id} canSelectInternal={true}/><label className={s.field}>변경·처리 사유<textarea maxLength={2000} disabled={c.busy || !!c.pending} value={c.editor.reason} onChange={e => c.edit({ ...c.editor, reason: e.target.value })}/></label><div className={s.actions}><button className="button" disabled={!c.ready || c.busy || !!c.pending}>일정 저장</button>{c.detail && <>{c.detail.current.state === 'open' ? <><button type="button" className="button subtle" disabled={c.busy || !!c.pending} onClick={() => void c.execute('done')}>이 일정 행동 종료</button><button type="button" className="button subtle" disabled={c.busy || !!c.pending} onClick={() => void c.execute('cancel')}>이 일정 취소</button></> : <button type="button" className="button subtle" disabled={c.busy || !!c.pending} onClick={() => void c.execute('reopen')}>이 일정 다시 열기</button>}</>}</div><p className={s.hint}>일정 행동 종료·취소·다시 열기는 원 업무의 완료 상태를 바꾸지 않습니다.</p></form>}
 {c.pending && <section className={s.panel}><h2>{c.pending.ids ? '저장 완료 · 최신 조회 확인' : c.pending.conflict ? '동시 수정 · 기준 확인' : '요청 결과 확인 필요'}</h2><p>{c.pending.ids ? '이미 저장한 요청입니다. 새로운 일정을 만들지 않고 확정 기록을 다시 조회합니다.' : c.pending.conflict ? '작성값과 기존 기준 버전을 유지했습니다. 현재 기록을 비교하고 기준을 선택해 주세요.' : '입력값과 요청 키를 유지했습니다. 같은 요청으로 결과를 확인해 주세요.'}</p><div className={s.actions}><button className="button" disabled={c.busy} onClick={() => void (c.pending?.conflict ? c.rebase() : c.execute())}>{c.pending.conflict ? '작성값 유지·최신 기준 선택' : c.pending.ids ? '저장 결과 다시 조회' : '같은 요청으로 다시 확인'}</button><button className="button subtle" disabled={c.busy} onClick={() => void c.refresh()}>현재 서버 기록 비교</button></div></section>}
 {c.detail && <ScheduleHistory entries={history(c.detail)}/>}
 {!initialDetail && <><form className={s.panel} onSubmit={e => { e.preventDefault(); void c.refresh(undefined, '&' + new URLSearchParams(Object.entries(filters).filter(([, v]) => !!v)).toString()); }}><h2>일정 조회</h2><div className={s.grid}><label className={s.field}>업무 필터<select value={filters.task} onChange={e => setFilters({ ...filters, task: e.target.value })}><option value="">전체 업무</option>{filterOptions.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className={s.field}>종류 필터<select value={filters.kind} onChange={e => setFilters({ ...filters, kind: e.target.value })}><option value="">전체 종류</option>{Object.entries(kindLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className={s.field}>조회 시작일<input type="date" value={filters.from} onChange={e => setFilters({ ...filters, from: e.target.value })}/></label><label className={s.field}>조회 종료일<input type="date" value={filters.to} onChange={e => setFilters({ ...filters, to: e.target.value })}/></label></div><div className={s.actions}><button className="button subtle">조건 적용</button><button type="button" className="button subtle" aria-pressed={view === 'timeline'} onClick={() => setView('timeline')}>날짜별 타임라인</button><button type="button" className="button subtle" aria-pressed={view === 'list'} onClick={() => setView('list')}>목록 보기</button></div></form><ScheduleTimeline state={!c.ready ? { status: 'loading' } : { status: 'ready', groups: view === 'timeline' ? [...groups].map(([key, items]) => ({ key, label: key, items })) : [{ key: 'all', label: '일정 목록', items: items.map(presentation) }], emptyMessage: '조회 범위의 일정이 없습니다. 원 업무 일정 또는 새 일정을 확인해 주세요.' }}/></>}
 </div>;
}
