'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import type {ImportConfiguration,WorkbookInspection,ImportPreview,ImportBatch,PreviewInput,Mapping,RowChoice} from '@/server/imports/contracts';
import {request,RequestError} from '@/features/tasks/client';
import {boundedDownload,directUpload,type UploadResumeState,type DownloadMetadata} from '@/features/files/transfer';
import {Select,Field} from '@/features/evidence/fields';
import {MappingView,PreviewView,BatchView} from './views';
import s from '@/features/tasks/ui.module.css';
import u from '@/features/evidence/ui.module.css';
const subscribe=()=>()=>{};
type Receipt={previewId:string;key:string;batchId:string|null};
type Recovery={schema:1;sourceId:string;fileName:string;sheetId:number;headerRow:number;mapping:Mapping[];choices:RowChoice[];previewId:string|null;stale:boolean;receipt:Receipt|null};
function readRecovery(key:string,config:ImportConfiguration):Recovery|null{try{const x:unknown=JSON.parse(sessionStorage.getItem(key)||'null');if(!x||typeof x!=='object')return null;const r=x as Recovery;if(r.schema!==1||typeof r.sourceId!=='string'||typeof r.fileName!=='string'||!Number.isInteger(r.sheetId)||!Number.isInteger(r.headerRow)||!Array.isArray(r.mapping)||!r.mapping.every(m=>Number.isInteger(m.column)&&config.fields.some(f=>f.key===m.field))||!Array.isArray(r.choices)||!r.choices.every(c=>Number.isInteger(c.row)&&['new','update','skip'].includes(c.action)&&Array.isArray(c.clearFields)&&c.clearFields.every(f=>config.fields.some(x=>x.key===f)))||r.previewId!==null&&typeof r.previewId!=='string'||r.receipt!==null&&(!r.receipt||typeof r.receipt.previewId!=='string'||typeof r.receipt.key!=='string'||r.receipt.batchId!==null&&typeof r.receipt.batchId!=='string'))return null;return r;}catch{return null;}}
export function ImportScreen({configuration:config,userId,batch:initialBatch}:{configuration:ImportConfiguration;userId:string;batch:ImportBatch|null}){
 const key=`gs-hale-g07-import:${userId}:${config.contextId}`,lock=useRef(false),[working,setBusy]=useState(false),[accessLost,setAccessLost]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[filePending,setFilePending]=useState(false),[fileName,setFileName]=useState(''),[inspection,setInspection]=useState<WorkbookInspection|null>(null),[sourceId,setSourceId]=useState(''),[sheetId,setSheetId]=useState(1),[headerRow,setHeaderRow]=useState(1),[mapping,setMapping]=useState<Mapping[]>([]),[choices,setChoices]=useState<RowChoice[]>([]),[preview,setPreview]=useState<ImportPreview|null>(null),[previewId,setPreviewId]=useState<string|null>(null),[stale,setStale]=useState(true),[receipt,setReceipt]=useState<Receipt|null>(null),[batch,setBatch]=useState(initialBatch),[restored,setRestored]=useState(false),[storageError,setStorageError]=useState(''),[internal,setInternal]=useState(false);
 const busy=working||accessLost,unresolved=receipt!==null&&!batch,remote=config.storageMode==='supabase';
 const lifetime=useRef<AbortController|null>(null),uploadState=useRef<{file:File;key:string;state:UploadResumeState}|null>(null);
 useEffect(()=>{const controller=new AbortController();lifetime.current=controller;return()=>controller.abort();},[key]);
 const signal=()=>lifetime.current?.signal;
 async function dataRequest<T>(url:string,body?:Record<string,unknown>|FormData):Promise<T>{const active=signal();active?.throwIfAborted();const result=await request<T>(url,body);active?.throwIfAborted();return result;}
 async function sourceDTO<T>(url:string):Promise<T>{if(!remote)return dataRequest<T>(url);const result=await boundedDownload(`${url}${url.includes('?')?'&':'?'}transfer=1`,{signal:signal()});const value=JSON.parse(await result.blob.text()) as T;signal()?.throwIfAborted();return value;}
 const readPreview=(id:string,page=1)=>sourceDTO<ImportPreview>(`/api/imports/preview/${encodeURIComponent(id)}?page=${page}`);
 const hydrated=useSyncExternalStore(subscribe,()=>true,()=>false),recovery=hydrated&&!restored?readRecovery(key,config):null;
 const state:Recovery={schema:1,sourceId,fileName,sheetId,headerRow,mapping,choices,previewId,stale,receipt};
 function persist(next:Recovery){try{sessionStorage.setItem(key,JSON.stringify(next));setStorageError('');}catch{setStorageError('브라우저 복구 정보를 저장하지 못했습니다. 반영 결과를 확인하기 전 이 화면을 닫지 마세요.');}}
 useEffect(()=>{if(!restored)return;try{sessionStorage.setItem(key,JSON.stringify({schema:1,sourceId,fileName,sheetId,headerRow,mapping,choices,previewId,stale,receipt}));}catch{/* Explicit receipt writes also surface storage failure. */}},[restored,key,sourceId,fileName,sheetId,headerRow,mapping,choices,previewId,stale,receipt]);
 async function run(fn:()=>Promise<void>){if(lock.current||accessLost)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){if(signal()?.aborted)return;setError(e instanceof Error?e.message:'요청을 확인하지 못했습니다. 입력은 유지됩니다.');if(e instanceof RequestError&&[401,403,404].includes(e.status)){setPreview(null);setInspection(null);setBatch(null);setAccessLost(true);}}finally{lock.current=false;setBusy(false);}}
 function edit(){setStale(true);setMessage('선택이 바뀌었습니다. 전체 미리보기를 다시 확인한 후 반영하세요.');setRestored(true);}
 async function upload(){if(!file)return;let next:WorkbookInspection;if(remote){if(uploadState.current?.file!==file)uploadState.current={file,key:crypto.randomUUID(),state:{}};const pending=uploadState.current;next=await directUpload(file,{clientItemId:pending.key,state:pending.state,signal:signal(),maximumBytes:config.limits.inputBytes,callbacks:{issue:input=>dataRequest('/api/imports/uploads',{...input,contextId:config.contextId}),status:id=>dataRequest(`/api/imports/uploads/${id}`),finalize:id=>dataRequest(`/api/imports/uploads/${id}`,{}),resolve:status=>{if(status.result?.kind!=='importStage')throw new Error('업로드 원본을 확인하지 못했습니다.');return sourceDTO<WorkbookInspection>(`/api/imports/source/${status.result.id}`);}}});}else{const data=new FormData();data.append('file',file);next=await dataRequest<WorkbookInspection>(`/api/imports/source?context=${config.contextId}`,data);}setFilePending(false);setInspection(next);setSourceId(next.sourceId);setFileName(file.name);setSheetId(next.sheets[0]?.id??1);setHeaderRow(1);setMapping([]);setChoices([]);setPreview(null);setPreviewId(null);setReceipt(null);setStale(true);setRestored(true);setMessage('원본을 읽었습니다. 시트·머리글·열 매핑을 확인하세요.');}
 async function makePreview(){const body:PreviewInput={sourceId,sheetId,headerRow,mapping,choices};const result=await dataRequest<ImportPreview|{id:string}>('/api/imports/preview',{...body});const next=remote?await readPreview(result.id):result as ImportPreview;setPreview(next);setPreviewId(next.id);setStale(false);setReceipt(null);setRestored(true);persist({...state,previewId:next.id,stale:false,receipt:null});setMessage('전체 행 검증을 마쳤습니다. 오류와 반영 예정값을 확인하세요.');}
 async function readBatch(id:string){const next=await request<ImportBatch>(`/api/imports/batches/${encodeURIComponent(id)}`);if(next.contextId!==config.contextId)throw new Error('현재 컨텍스트의 결과가 아닙니다.');setBatch(next);window.history.replaceState(null,'',`/products/import?${new URLSearchParams({context:config.contextId,batch:id})}`);setMessage('저장된 배치 결과를 확인했습니다.');}
 async function apply(){const p=receipt?.previewId??preview?.id;if(!p)return;const current=receipt??{previewId:p,key:crypto.randomUUID(),batchId:null};setReceipt(current);persist({...state,receipt:current});setRestored(true);if(current.batchId){await readBatch(current.batchId);return;}let result:{ids:string[]};try{result=await request('/api/imports/apply',{previewId:current.previewId,idempotencyKey:current.key});}catch(e){if(e instanceof RequestError&&e.status===409){setReceipt(null);setStale(true);persist({...state,receipt:null,stale:true});}throw e;}const saved={...current,batchId:result.ids[0]};setReceipt(saved);persist({...state,receipt:saved});await readBatch(saved.batchId);}
 async function restore(){if(!recovery)return;setSourceId(recovery.sourceId);setFileName(recovery.fileName);setSheetId(recovery.sheetId);setHeaderRow(recovery.headerRow);setMapping(recovery.mapping);setChoices(recovery.choices);setPreviewId(recovery.previewId);setStale(recovery.stale);setReceipt(recovery.receipt);setRestored(true);if(recovery.receipt?.batchId){await readBatch(recovery.receipt.batchId);return;}if(recovery.previewId){const p=await readPreview(recovery.previewId);if(p.contextId!==config.contextId)throw new Error('복구 자료의 컨텍스트를 확인해 주세요.');setPreview(p);}setMessage('설정을 복구했습니다. 원본 파일 바이트는 저장하지 않으므로 새 업로드가 필요하면 다시 선택하세요.');}
 async function download(kind:'template'|'export'){const response=await fetch(`/api/imports/workbook?${new URLSearchParams({context:config.contextId,kind,...internal&&config.capabilities.internalPrice?{internal:'1'}:{}})}`,{cache:'no-store',signal:signal()});if(!response.ok){const data=await response.json().catch(()=>null);throw new RequestError(data?.error?.message||'다운로드 권한과 연결을 확인해 주세요.',response.status,data?.error?.code||'DOWNLOAD_FAILED');}let blob:Blob,name=`GS-HALE-${kind}.xlsx`;if(remote&&kind==='export'){const metadata=await response.json() as DownloadMetadata;const saved=await boundedDownload(`${metadata.downloadUrl}?metadata=1`,{signal:signal(),maximumBytes:Number.MAX_SAFE_INTEGER});blob=saved.blob;name=saved.metadata.name;}else blob=await response.blob();signal()?.throwIfAborted();const url=URL.createObjectURL(blob),a=document.createElement('a');try{a.href=url;a.download=name;a.click();}finally{URL.revokeObjectURL(url);}setMessage(kind==='template'?'표준 템플릿을 내려받았습니다.':'현재 권한의 표준 상품 데이터를 내려받았습니다.');}
 function reset(){uploadState.current=null;setFile(null);setFilePending(false);setFileName('');setInspection(null);setSourceId('');setSheetId(1);setHeaderRow(1);setMapping([]);setChoices([]);setPreview(null);setPreviewId(null);setReceipt(null);setBatch(null);setStale(true);setRestored(true);sessionStorage.removeItem(key);window.history.replaceState(null,'',`/products/import?context=${config.contextId}`);}
 return <div className={s.stack}><Link className="back-link" href={`/products?context=${config.contextId}`}>← 상품정보</Link><header className={s.heading}><div><p className="eyebrow">STANDARD PRODUCT WORKBOOK</p><h1>상품 Excel 가져오기·내보내기</h1><p>시트 확인 → 열 매핑 → 전체 검증 → 명시 반영 → 저장 결과</p></div><Link href={`/materials?context=${config.contextId}`}>자료함·제출표 ↗</Link></header><section className={s.panel}><h2>표준 양식과 현재 상품 내보내기</h2><p>{config.schema} · .xlsx 전용 · 최대 {config.limits.inputBytes/1024/1024}MB / {config.limits.rows}행 / {config.limits.columns}열</p><p className={s.notice}>.xls·.xlsm·CSV는 지원하지 않습니다. 수식·외부 통합 문서 연결·매크로·병합된 데이터 셀은 거부합니다. 숨김 시트는 제외하며 숨김 행·열의 데이터는 전체 검증합니다. 등록한 증빙 파일·상품별 적용 판단은 상품 Excel로 자동 생성하지 않습니다.</p><p>{config.operationalWorkbookNote} 현업 양식은 아직 미검증입니다. 일반 하이퍼링크의 표시값·URL은 외부 조회 없이 처리합니다.</p>{config.capabilities.internalPrice&&<label><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/>현재 권한의 내부 가격 포함</label>}<div className={u.actions}><button className="button subtle" disabled={busy} onClick={()=>void run(()=>download('template'))}>표준 템플릿 다운로드</button><button className="button subtle" disabled={busy} onClick={()=>void run(()=>download('export'))}>현재 상품 내보내기</button></div></section>
 {recovery&&!restored&&!initialBatch&&<section className={s.notice}><h2>이 계정·컨텍스트의 복구 기록</h2><p>{recovery.fileName} · {recovery.receipt?'반영 결과를 먼저 확인하세요.':'매핑과 행 선택을 복구할 수 있습니다.'} 원본 값·가격·파일 바이트는 브라우저에 저장하지 않습니다.</p><button className="button" disabled={busy} onClick={()=>void run(restore)}>이전 가져오기 복구</button>{!recovery.receipt&&<button className="button subtle" onClick={()=>{sessionStorage.removeItem(key);setRestored(true);}}>복구 기록 버리기</button>}</section>}
 {accessLost&&<section className={s.notice}><p>현재 접근 권한 또는 자료 주소를 확인할 수 없어 이전 보호 값을 화면에서 지웠습니다. 최신 권한으로 페이지를 다시 여세요.</p><button className="button subtle" onClick={()=>window.location.reload()}>현재 권한으로 다시 열기</button></section>}{(error||storageError)&&<p role="alert" className={s.error}>{error||storageError} 선택과 입력은 유지됩니다.</p>}{message&&<p role="status" className={s.success}>{message}</p>}
 {batch?<><BatchView batch={batch}/><button className="button subtle" onClick={reset}>다른 원본 가져오기</button></>:<><section className={s.panel}><h2>1. 원본 파일과 공개 시트 선택</h2><fieldset disabled={busy||unresolved||!!recovery&&!restored} className={u.stack} style={{border:0,padding:0,minWidth:0}}><label className={u.control}>상품 Excel 원본<input type="file" accept=".xlsx" onChange={e=>{setFile(e.target.files?.[0]??null);setFilePending(true);setStale(true);}}/></label><p>{file?.name||fileName||'파일 미선택'} · 업로드 실패 시 파일을 그대로 다시 시도할 수 있습니다.</p><button className="button" disabled={!file} onClick={()=>void run(upload)}>원본 읽기 · 다시 시도</button>{inspection&&<><p>{inspection.notice} · 제외된 숨김 시트 {inspection.omittedHiddenSheets}개</p><Select label="가져올 공개 시트" value={String(sheetId)} onChange={v=>{setSheetId(Number(v));setMapping([]);setChoices([]);edit();}}>{inspection.sheets.map(v=><option key={v.id} value={v.id}>{v.name} · {v.rowCount}행</option>)}</Select></>}{sourceId&&!inspection&&<p>복구한 시트 ID {sheetId}. 표본은 보관하지 않습니다. 시트를 바꾸려면 원본을 다시 읽으세요.</p>}</fieldset></section>
 {sourceId&&<section className={s.panel}><h2>2. 머리글·열 매핑</h2>{filePending&&<p className={s.notice}>새로 선택한 파일을 아직 읽지 못했습니다. 아래에는 이전 원본의 설정이 보존되어 있으며, 새 파일 읽기에 성공해야 다시 검증할 수 있습니다.</p>}<fieldset disabled={busy||unresolved||filePending} className={u.stack} style={{border:0,padding:0,minWidth:0}}><Field label="머리글 행 번호" value={String(headerRow)} type="number" onChange={v=>{setHeaderRow(Number(v));setChoices([]);edit();}}/><MappingView config={config} inspection={inspection} sheetId={sheetId} headerRow={headerRow} mapping={mapping} onMapping={v=>{setMapping(v);edit();}}/><button className="button" disabled={!mapping.length} onClick={()=>void run(makePreview)}>전체 미리보기 만들기 · 다시 검증</button></fieldset></section>}
 {preview&&<><p className={s.hint}>직전에 검증한 원본: {fileName}</p><PreviewView preview={preview} config={config} choices={choices} disabled={busy||unresolved} onChoice={v=>{setChoices(old=>[...old.filter(c=>c.row!==v.row),v]);edit();}} onPage={n=>void run(async()=>{setPreview(await readPreview(preview.id,n));})}/></>}
 {(preview||receipt)&&<section className={s.panel}><h2>3. 확인한 전체 행 반영</h2>{unresolved?<><p className={s.notice}>{receipt!.batchId?'반영 성공 응답을 받았습니다. 결과 재조회만 수행하며 새 배치를 만들지 않습니다.':'반영 결과가 아직 확인되지 않았습니다. 같은 미리보기·요청 키로만 다시 확인합니다. 결과 확인 전 새 파일이나 매핑으로 바꾸지 마세요.'}</p><p className={u.wrap}>요청 키 {receipt!.key}{receipt!.batchId?` · 배치 ${receipt!.batchId}`:''}</p><button className="button" disabled={busy} onClick={()=>void run(apply)}>{receipt!.batchId?'저장된 결과 다시 조회':'같은 반영 요청 결과 확인'}</button></>:<><p>{stale?'선택 변경 또는 충돌로 전체 미리보기를 다시 만들어야 합니다.':preview?.canApply?'전체 오류가 없습니다. 위 신규·갱신·건너뛰기와 명시 지우기를 확인하세요.':'전체 오류를 해결해야 반영할 수 있습니다.'}</p><p>오류가 있으면 아무 행도 저장하지 않습니다. 충돌 시 현재 값을 확인하고 미리보기를 다시 만드세요.</p><button className="button" disabled={busy||stale||!preview?.canApply} onClick={()=>void run(apply)}>확인한 모든 행 반영</button></>}</section>}</>}
 </div>;
}
