import { afterEach,describe,it,expect,vi } from 'vitest';
import { openaiTransport } from '@/server/ai-provider/transport';
import { candidateSchema } from '@/domain/ai-provider/schema';
const config={apiKey:'SYNTHETIC_TRANSPORT_SECRET',model:'gpt-6-astra',baseURL:'https://api.openai.com/v1'};
const request={model:config.model,instructions:'synthetic',input:[{role:'user' as const,content:[{type:'input_text' as const,text:'synthetic only'}]}],reasoning:{effort:'low' as const},text:{format:{type:'json_schema' as const,name:'gs_hale_ai_review_v1',strict:true,schema:candidateSchema}},max_output_tokens:3000 as const,store:false,stream:false as const,background:false,service_tier:'default' as const,truncation:'disabled' as const};
afterEach(()=>vi.unstubAllGlobals());
describe('actual SDK transport with intercepted fetch; no network',()=>{
 for(const status of [401,403,429,500,400])it(`AC17-01 SDK ${status} classification strips unsafe body and retries0`,async()=>{let calls=0,dispatched=0,before=0;vi.stubGlobal('fetch',async()=>{calls++;return new Response(JSON.stringify({error:{message:'SYNTHETIC_TRANSPORT_SECRET unsafe server echo',type:'synthetic'}}),{status,headers:{'content-type':'application/json','x-request-id':'req_fault'}});});const r=await openaiTransport(config,request,async()=>{before++;},async()=>{dispatched++;});expect(r.issue).toBe(({401:'PROVIDER_AUTH',403:'PROVIDER_PERMISSION',429:'RATE_LIMIT',500:'SERVER_ERROR',400:'CONFIGURATION'} as Record<number,string>)[status]);expect(calls).toBe(1);expect(before).toBe(1);expect(dispatched).toBe(1);expect(JSON.stringify(r)).not.toContain('SYNTHETIC_TRANSPORT_SECRET');expect(r.usage.inputTokens).toBeNull();});
 it('AC17-05 response extraction follows message parts, captures provided usage/request ID without unknown fields',async()=>{vi.stubGlobal('fetch',async(_input:unknown,init:RequestInit)=>{const body=JSON.parse(String(init.body));expect(body.store).toBe(false);expect(body.reasoning.effort).toBe('low');expect(body.text.format.strict).toBe(true);return new Response(JSON.stringify({id:'resp_fixture',model:'gpt-6-astra',service_tier:'default',status:'completed',unknownPrivate:'SHOULD_NOT_PROJECT',output:[{type:'reasoning',summary:[]},{type:'message',role:'assistant',content:[{type:'output_text',text:'{"schemaVersion":"gs-hale-ai-review/1","findings":[]}'}]}],usage:{input_tokens:20,input_tokens_details:{cached_tokens:0,cache_write_tokens:3},output_tokens:10,output_tokens_details:{reasoning_tokens:2},total_tokens:30}}),{headers:{'content-type':'application/json','x-request-id':'req_fixture'}});});const r=await openaiTransport(config,request,async()=>{},async()=>{});expect(r).toMatchObject({issue:null,responseId:'resp_fixture',requestId:'req_fixture',usage:{inputTokens:20,cacheWriteTokens:3,reasoningTokens:2}});expect(JSON.stringify(r)).not.toContain('SHOULD_NOT_PROJECT');});
 for(const [status,content,issue] of [['completed',[{type:'refusal',refusal:'refuse'}],'REFUSAL'],['incomplete',[],'INCOMPLETE'],['completed',[],'PARSE_ERROR']] as const)it(`AC17-01 ${issue} is not successful empty output`,async()=>{vi.stubGlobal('fetch',async()=>new Response(JSON.stringify({id:'resp_fixture',model:'gpt-6-astra',service_tier:'default',status,output:[{type:'message',content}]}),{headers:{'content-type':'application/json'}}));expect((await openaiTransport(config,request,async()=>{},async()=>{})).issue).toBe(issue);});
});
