import { afterEach,describe,expect,it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import type { RecordRepository } from '@/domain/records';
import { createMockRepository } from '@/server/repositories/mock';
import { createSqliteRepository } from '@/server/repositories/sqlite';
import { openDatabase,migrate } from '@/server/db/database';
import { AiProviderService } from '@/server/ai-provider/service';
import { AiReviewService } from '@/server/ai-review/service';
import { SYNTHETIC_TEXT } from '@/server/ai-input/provenance';
import { emptyTransport,type Transport } from '@/server/ai-provider/transport';
import { providerUsage,estimateCost } from '@/domain/ai-provider/usage';
import { matchesSchema } from '@/domain/ai-provider/schema';
import { policyFixture,NOW,tokenFor } from '../fixtures/policy';
import { ctx,staff,admin,brand,readyInput,inputContent } from '../fixtures/ai-review/server';
import type { IdentityService } from '@/server/auth/service';
const config=()=>({config:{apiKey:'synthetic-test-key-no-network',model:'gpt-6-astra',baseURL:'https://api.openai.com/v1'},issue:null});
const usage=providerUsage({input_tokens:1000,input_tokens_details:{cached_tokens:200,cache_write_tokens:300},output_tokens:100,output_tokens_details:{reasoning_tokens:20},total_tokens:1100});
const rawCandidate=JSON.stringify({schemaVersion:'gs-hale-ai-review/1',findings:[]});
const success:Transport=async(_c,_r,before,sent)=>{await before();await sent();return {...emptyTransport('ENGINE_ERROR'),issue:null,responseId:'resp_synthetic',requestId:'req_synthetic',responseModel:'gpt-6-astra',serviceTier:'default',providerStatus:'completed',rawCandidate,responseHash:'a'.repeat(64),usage};};
for(const mode of ['mock','sqlite'] as const)describe(`${mode} G17 provider contract`,()=>{
 let repo:RecordRepository,identity:IdentityService,directory:string;
 async function setup(){directory=await mkdtemp(path.join(os.tmpdir(),'g17-unit-'));repo=mode==='mock'?createMockRepository(()=>NOW):(()=>{const db=openDatabase(':memory:',true);migrate(db);return createSqliteRepository(db,()=>NOW);})();identity=await policyFixture(repo);return new AiProviderService(identity,directory,{config,transport:success});}
 async function fixture(){const f=await readyInput(identity,directory,inputContent(SYNTHETIC_TEXT));return {...f,body:{...f.body,engine:'provider'}};}
 afterEach(async()=>{repo?.close();if(directory)await rm(directory,{recursive:true,force:true});});
 it('AC17-04/05 synthetic transport keeps one logical result with exact payload, attempts and disjoint cache-write cost',async()=>{const service=await setup(),f=await fixture();const r=await service.start(staff,f.input.id,f.body);expect(r.detail).toMatchObject({engine:'provider',state:'finished',providerCalled:true,legalApproval:false,provider:{remoteExactlyOnceGuaranteed:false,attempts:[{sequence:1,schemaValid:true,grounding:'insufficient',usage,cost:{amountUsd:0.01395}}]}});expect((await service.start(staff,f.input.id,f.body)).runId).toBe(r.runId);expect(await repo.list('aiProviderAttempt')).toHaveLength(1);expect(await repo.list('aiAnalysisResult')).toHaveLength(1);for(const kind of ['aiProviderPlan','aiProviderOutcome'] as const){const row=(await repo.list(kind))[0];await expect(repo.transaction(s=>s.update(kind,row.id,row.revision,row.data))).rejects.toMatchObject({code:'INVALID_RECORD'});}expect(await repo.list('correctionOpinion')).toHaveLength(0);});
 it('AC17-01 no key/disabled/config each persists not-called explicit failure without transport',async()=>{await setup();let calls=0;for(const issue of ['KEY_MISSING','CONFIGURATION','DISABLED'] as const){const f=await fixture();const service=new AiProviderService(identity,directory,{config:()=>issue==='DISABLED'?config():{config:config().config,issue},transport:async(...args)=>{calls++;return success(...args);}});if(issue==='DISABLED')await service.changeSettings(staff,ctx,{enabled:false,expectedRevision:0,idempotencyKey:randomUUID()});const r=await service.start(staff,f.input.id,f.body);expect(r.detail).toMatchObject({state:'failed',providerCalled:false,provider:{attempts:[{issue,dispatchedAt:null,usage:{inputTokens:null},cost:{amountUsd:null}}]}});}expect(calls).toBe(0);});
 it('AC17-01 permanent provider failure distinctions; no retry or empty success',async()=>{await setup();for(const issue of ['PROVIDER_AUTH','PROVIDER_PERMISSION','REFUSAL','INCOMPLETE','NETWORK','CONFIGURATION'] as const){const f=await fixture(),service=new AiProviderService(identity,directory,{config,transport:async(_c,_r,before,sent)=>{await before();await sent();return emptyTransport(issue,issue==='NETWORK');}});const r=await service.start(staff,f.input.id,f.body);expect(r.detail).toMatchObject({state:'failed',providerCalled:true,provider:{retryable:false,attempts:[{issue}]}});await expect(service.retry(staff,r.runId,{expectedRevision:r.detail.revision,idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'RETRY_UNAVAILABLE'});}expect(await repo.list('aiAnalysisResult')).toHaveLength(0);});
 it('AC17-02 transient timeout/429/5xx retry is explicit, same run, three attempts, durable replay no resend',async()=>{await setup();const f=await fixture();let calls=0;const service=new AiProviderService(identity,directory,{config,transport:async(_c,_r,before,sent)=>{await before();await sent();return emptyTransport((['TIMEOUT','RATE_LIMIT','SERVER_ERROR'] as const)[calls++],calls===1);}});let r=await service.start(staff,f.input.id,f.body);for(let n=1;n<3;n++){const command={expectedRevision:r.detail.revision,idempotencyKey:randomUUID()};r=await service.retry(staff,r.runId,command);await service.retry(staff,r.runId,command);expect(r.detail.provider!.attempts).toHaveLength(n+1);}expect(calls).toBe(3);expect(await repo.list('aiAnalysisRun')).toHaveLength(1);expect(r.detail.provider!.retryable).toBe(false);await expect(service.retry(staff,r.runId,{expectedRevision:r.detail.revision,idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'RETRY_UNAVAILABLE'});});
 it('AC17-02 actual held asynchronous transport one atomic claim and one result for concurrent duplicate',async()=>{await setup();const f=await fixture();let enter!:()=>void,release!:()=>void,calls=0;const gate=new Promise<void>(r=>release=r),entered=new Promise<void>(r=>enter=r);const service=new AiProviderService(identity,directory,{config,transport:async(...args)=>{calls++;enter();await gate;return success(...args);}});const pending=service.start(staff,f.input.id,f.body);await entered;expect((await service.start(staff,f.input.id,f.body)).detail.state).toBe('running');expect(calls).toBe(1);release();expect((await pending).detail.state).toBe('finished');expect(await repo.list('aiProviderAttempt')).toHaveLength(1);});
 it('D04 original/reference current ACL before dispatch and after response prevents publication',async()=>{await setup();for(const stage of ['afterPrepare','afterResponse'] as const){const f=await fixture();let calls=0;const service=new AiProviderService(identity,directory,{config,transport:async(...args)=>{calls++;return success(...args);},[stage]:async()=>{await repo.transaction(s=>{const m=s.list('membership',ctx).find(x=>x.data.userId==='user-gsg')!;s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});}});await expect(service.start(staff,f.input.id,f.body)).rejects.toMatchObject({status:404});expect(calls).toBe(stage==='afterPrepare'?0:1);expect(await repo.list('aiAnalysisResult')).toHaveLength(0);await repo.transaction(s=>{const m=s.list('membership',ctx).find(x=>x.data.userId==='user-gsg')!;s.update('membership',m.id,m.revision,{...m.data,status:'active'});});}});
 it('SA62 exact-hash provenance blocks arbitrary synthetic checkbox/text with zero provider dispatch',async()=>{const service=await setup(),f=await readyInput(identity,directory,inputContent('customer-like unregistered text'));const r=await service.start(staff,f.input.id,{...f.body,engine:'provider'});expect(r.detail).toMatchObject({state:'failed',providerCalled:false,provider:{attempts:[{issue:'EXTERNAL_USE_DENIED'}]}});});
 it('AC17-01 strict malformed JSON/schema does not become no findings',async()=>{await setup();for(const raw of ['not-json',JSON.stringify({schemaVersion:'gs-hale-ai-review/1',findings:[],secret:'unknown'}),JSON.stringify({schemaVersion:'gs-hale-ai-review/1'})]){const f=await fixture(),service=new AiProviderService(identity,directory,{config,transport:async(...args)=>({...await success(...args),rawCandidate:raw})});const r=await service.start(staff,f.input.id,f.body);expect(r.detail).toMatchObject({state:'failed',result:null,provider:{attempts:[{issue:'PARSE_ERROR',schemaValid:false}]}});}expect(await repo.list('aiAnalysisResult')).toHaveLength(0);});
 it('D04 settings current GSG only, CAS, duplicate receipt and source public brand cannot manage AI',async()=>{const service=await setup();for(const actor of [brand,tokenFor('user-wave')])await expect(service.settings(actor,ctx)).rejects.toMatchObject({status:404});const body={enabled:false,expectedRevision:0,idempotencyKey:randomUUID()};const one=await service.changeSettings(staff,ctx,body);expect(one.revision).toBe(1);expect((await service.changeSettings(staff,ctx,body)).revision).toBe(1);await expect(service.changeSettings(admin,ctx,{...body,idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'CONFLICT'});const f=await fixture();expect((await new AiReviewService(identity,directory).start(staff,f.input.id,{...f.body,engine:'synthetic_demo'})).detail.state).toBe('finished');});
 it('D04 settings changed after actual response suppresses result while retaining safe usage',async()=>{await setup();const f=await fixture(),service=new AiProviderService(identity,directory,{config,transport:success,afterResponse:async()=>{await new AiProviderService(identity,directory).changeSettings(admin,ctx,{enabled:false,expectedRevision:0,idempotencyKey:randomUUID()});}});const r=await service.start(staff,f.input.id,f.body);expect(r.detail).toMatchObject({state:'failed',result:null,provider:{attempts:[{issue:'SETTINGS_CHANGED',schemaValid:false,usage}]}});expect((await repo.list('aiProviderOutcome'))[0].data.rawCandidate).toBeNull();});
 it('SA62 underlying accepted input version rejects direct mutation during preparation',async()=>{await setup();const f=await fixture();let dispatched=0;const service=new AiProviderService(identity,directory,{config,afterPrepare:async()=>{await repo.transaction(s=>{const row=s.get('aiVersion',f.input.version.id)!;expect(()=>s.update('aiVersion',row.id,row.revision,{...row.data,text:'tampered'})).toThrow();});},transport:async(...args)=>{dispatched++;return success(...args);}});expect((await service.start(staff,f.input.id,f.body)).detail.state).toBe('finished');expect(dispatched).toBe(1);});
 it('AC17-02 currently active run prevents a second logical provider admission',async()=>{await setup();const f=await fixture();await repo.transaction(s=>{for(let n=0;n<2;n++){const row=s.get('aiRun',f.extraction.runId)!;s.create('aiAnalysisRun',{id:randomUUID(),contextId:ctx,data:{inputId:f.input.id,inputVersionId:f.input.version.id,extractionRunId:row.id,extractionSnapshotId:row.data.snapshotId!,snapshotHash:s.get('aiSnapshot',row.data.snapshotId!)!.data.snapshotHash,corpusReleaseId:f.body.corpusReleaseId,corpusManifestHash:f.body.corpusManifestHash,engine:'synthetic_demo',modelId:'synthetic',promptVersion:'1',providerCalled:false,taskId:null,createdBy:'user-gsg',attempt:n+1,previousRunId:null,state:'running',claimId:randomUUID(),leaseUntil:new Date(Date.parse(NOW)+90000).toISOString(),startedAt:NOW,endedAt:null,resultId:null,issue:null}});}});const runs=await repo.list('aiAnalysisRun');const service=new AiProviderService(identity,directory,{config,transport:success});await expect(service.start(staff,f.input.id,{...f.body,expectedRunId:runs.sort((a,b)=>b.data.attempt-a.data.attempt)[0].id})).rejects.toMatchObject({code:'RUN_ACTIVE'});expect(await repo.list('aiProviderAttempt')).toHaveLength(0);});
 it('AC17-02 transaction rollback at claim leaves no attempt, receipt or logical run',async()=>{await setup();const f=await fixture(),before=await repo.list('commandReceipt'),service=new AiProviderService(identity,directory,{config,transport:success,fault:stage=>{if(stage==='claim')throw Error('SYNTHETIC_CLAIM_FAULT');}});await expect(service.start(staff,f.input.id,f.body)).rejects.toThrow('SYNTHETIC_CLAIM_FAULT');expect(await repo.list('aiAnalysisRun')).toHaveLength(0);expect(await repo.list('aiProviderAttempt')).toHaveLength(0);expect(await repo.list('commandReceipt')).toEqual(before);});
});
describe('G17 usage independent arithmetic oracle',()=>{
 it('AC17-04 cached + cache-write subsets; reasoning included once; no amount cap',()=>{expect(estimateCost(usage,'gpt-6-astra','gpt-6-astra','default').amountUsd).toBe(0.01395);expect(estimateCost({...usage,inputTokens:300000,cachedTokens:0,cacheWriteTokens:0,outputTokens:100000,reasoningTokens:10000,totalTokens:400000},'gpt-6-astra','gpt-6-astra','default').amountUsd).toBe(13.5);});
 it('missing/negative/fraction/overflow/model/tier/subset mismatch remains unavailable, never zero',()=>{const base={input_tokens:100,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens:20,output_tokens_details:{reasoning_tokens:1},total_tokens:120};for(const v of [undefined,-1,1.1,Number.MAX_SAFE_INTEGER+1]){const u=providerUsage({...base,input_tokens:v});expect(estimateCost(u,'gpt-6-astra','gpt-6-astra','default').amountUsd).toBeNull();}for(const u of [{...usage,cachedTokens:900},{...usage,reasoningTokens:101},{...usage,totalTokens:2}])expect(estimateCost(u,'gpt-6-astra','gpt-6-astra','default').amountUsd).toBeNull();expect(estimateCost(usage,'other','other','default').amountUsd).toBeNull();expect(estimateCost(usage,'gpt-6-astra','gpt-6-astra','flex').amountUsd).toBeNull();expect(matchesSchema(JSON.parse(rawCandidate))).toBe(true);expect(matchesSchema({schemaVersion:'gs-hale-ai-review/1',findings:[],extra:1})).toBe(false);});
});
