import { EvidenceService } from '@/server/evidence/service';
import { blankCommon,blankContext } from '@/domain/products/types';
import { afterEach,describe,it,expect } from 'vitest';
import { randomUUID,createHash } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import type { RecordRepository,RecordKind } from '@/domain/records';
import { createMockRepository } from '@/server/repositories/mock';
import { createSqliteRepository } from '@/server/repositories/sqlite';
import { openDatabase,migrate } from '@/server/db/database';
import type { IdentityService } from '@/server/auth/service';
import { policyFixture,tokenFor,NOW } from '../fixtures/policy';
import { CampaignService } from '@/server/campaigns/service';
import { CampaignFileService } from '@/server/campaigns/files';
import { FileService } from '@/server/files/service';
import { TaskService } from '@/server/tasks/service';
import { SubmissionService } from '@/server/submissions/service';
import { SubmissionFiles } from '@/server/submissions/files';
import { ProductService } from '@/server/products/service';
import { blankContent,blankRequirement } from '@/domain/tasks/types';
import { blankDraft } from '@/domain/submissions/types';
import type { CampaignDraft,MenuDraft,SourceText,SubmittedReference } from '@/domain/campaigns/types';
const A='ctx-jp-a-luna',admin=tokenFor('user-admin'),brand=tokenFor('user-luna'),team=tokenFor('user-team'),foreign=tokenFor('user-wave');
const person={kind:'user' as const,userId:'user-luna'},external={kind:'external_source' as const,label:'합성 운송 담당',source:'합성 확인 기록'};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS0cAAAAASUVORK5CYII=','base64');
const source=():SourceText=>({source:'PRIVATE_SOURCE',sourceVersion:'v1',locator:'p2',language:'ja',originalText:'PRIVATE_ORIGINAL 10000円',translatedText:'PRIVATE_TRANSLATION',fileVersionIds:[]});
for(const mode of ['mock','sqlite'] as const)describe(`${mode} actual G12 campaign producer`,()=>{
 let repo:RecordRepository,identity:IdentityService,service:CampaignService,tasks:TaskService,sub:SubmissionService,dir:string,taskId:string,draft:CampaignDraft,campaignId:string,versionId:string;
 async function setup(){repo=mode==='mock'?createMockRepository(()=>NOW):(()=>{const db=openDatabase(':memory:',true);migrate(db);return createSqliteRepository(db,()=>NOW);})();identity=await policyFixture(repo);service=new CampaignService(identity);tasks=new TaskService(identity);sub=new SubmissionService(identity);dir=await mkdtemp(path.join(os.tmpdir(),'hale-campaign-'));
  const c={...blankContent(),title:'행사 실제 업무',description:'메뉴 자료',deadline:{...blankContent().deadline,responsibleUserId:'user-gsg'},requirements:[{...blankRequirement('proof','file'),label:'사진/리포트'},{...blankRequirement('url','link'),label:'게시 URL'},{...blankRequirement('other','number'),label:'다른 메뉴 수량'}]};
  taskId=(await tasks.create(admin,{category:'spot',content:c,targets:[{contextId:A,ownerId:'user-gsg',assigneeId:'user-luna',coAssigneeIds:['user-co'],productIds:['product-serum']}],idempotencyKey:randomUUID()})).ids[0];await tasks.command(admin,taskId,{command:'publish',expectedRevision:(await repo.get('task',taskId))!.revision,idempotencyKey:randomUUID()});
  const catalog=(await service.command(admin,{command:'save_catalog',contextId:A,catalogId:null,expectedRevision:0,idempotencyKey:randomUUID(),draft:{title:'합성 카탈로그',versionLabel:'2026 v1',source:source()}})).ids[1];
  const product=(await repo.get('product','product-serum'))!,relation=(await repo.list('contextProduct',A)).find(r=>r.data.productId===product.id)!;
  const prod={productId:product.id,productVersionId:product.data.currentVersionId!,contextProductVersionId:relation.data.currentVersionId!,productUseId:null,sampleVariant:'판매용'};
  const menu=(key:string):MenuDraft=>({identity:{catalogVersionId:catalog,menuKey:key,menuName:'외부 메뉴 '+key,menuNumber:'1'},sourceStatements:[{id:'price1',field:'price',rawValue:'10000円',source:source()},{id:'price2',field:'price',rawValue:'12000円',source:{...source(),sourceVersion:'email-v2'}}],conflicts:[{field:'price',statementIds:['price1','price2'],state:'needs_confirmation',resolution:''}],conditions:{state:'confirmed',sourceStatementIds:['price1','price2'],publicExplanation:'현행 비용 확인 필요',cost:{amount:null,currency:null,taxIncluded:'unknown'},discount:'할인 별도',points:'포인트 별도',cancellationTerms:'신청 후 협의',schedules:[]},templateVersionId:null,request:{...c,title:'선택 메뉴 '+key,internalOriginal:'PRIVATE_REQUEST',internalMemo:'PRIVATE_MEMO',requirements:key==='one'?c.requirements.slice(0,2):c.requirements.slice(2)},products:[prod,{...prod,sampleVariant:'배포용1mL'}],physical:key==='one'?[{key:'shoot',destination:'촬영 A',purpose:'촬영',product:prod,requestedQuantity:'1',unit:'개',plannedShip:c.deadline,plannedArrival:c.deadline},{key:'distribute',destination:'배포 B',purpose:'배포',product:{...prod,sampleVariant:'배포용1mL'},requestedQuantity:'100',unit:'개',plannedShip:c.deadline,plannedArrival:c.deadline}]:[],followups:key==='one'?[{key:'photo',kind:'execution_photo',requirementKey:'proof',deadline:c.deadline},{key:'url',kind:'publication_url',requirementKey:'url',deadline:c.deadline}]:[]});
  draft={title:'합성 행사',menus:['one','two','three'].map(menu)};campaignId=(await service.command(admin,{command:'save',contextId:A,taskId,campaignId:null,expectedRevision:0,idempotencyKey:randomUUID(),draft})).ids[0];
 }
 async function command(command:string,extra:Record<string,unknown>={},token=admin,svc=service){const d=await service.detail(token,campaignId);return svc.command(token,{command,contextId:A,taskId,campaignId,expectedRevision:d.revision,idempotencyKey:randomUUID(),...extra});}
 async function publish(){versionId=(await command('publish')).ids[1];return versionId;}
 async function select(response='participate',selected=[draft.menus[0].identity]){return command('participate',{campaignVersionId:versionId,response,selectedMenus:selected,providedBy:person,note:'브랜드 회신'},brand);}
 async function submitted(){const w=await sub.workspace(brand,taskId),u=(await new SubmissionFiles(identity,dir).upload(brand,taskId,w.request.id,[{clientItemId:randomUUID(),name:'합성.png',type:'image/png',bytes:png}])).items[0];if(u.state!=='ready')throw Error('upload fixture');const p=await new ProductService(identity).detail(brand,'product-serum',A);
  await sub.draft(brand,taskId,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:w.draft?.revision??0,content:{...blankDraft(),answers:[{requestId:w.request.id,requirementKey:'proof',productId:null,type:'file',input:{fileVersionIds:[u.file.id]}}],artifacts:[{fileVersionId:u.file.id,role:'evidence',answer:{requirementKey:'proof',productId:null}}],productSelections:[{productId:p.productId,expectedCommonRevision:p.commonRevision,expectedContextRevision:p.contextRevision,bindingIds:[],retailPriceVersionId:null,asOfDate:'2026-09-21'}]},idempotencyKey:randomUUID()});const next=await sub.workspace(brand,taskId);const id=(await sub.submit(brand,taskId,{baseRequestId:next.request.id,expectedDraftRevision:next.draft!.revision,expectedTaskRevision:next.taskRevision,mode:'partial',idempotencyKey:randomUUID()})).ids[0];const snapshot=await sub.snapshot(brand,id);const reference:SubmittedReference={taskId,requestId:snapshot.requestId,submissionId:id,contentHash:snapshot.contentHash,answer:{requirementKey:'proof',productId:null},fileVersionIds:[u.file.id],productUseIds:snapshot.products.map(p=>p.id)};return {snapshot,reference,fileId:u.file.id};
 }
 async function business(){return Promise.all((['campaignCatalog','campaignCatalogVersion','campaign','campaignVersion','campaignSelection','campaignExternalFact','campaignPhysicalFact','campaignFollowupFact','task','requestVersion','submissionDraft','submission','productUseSnapshot','audit','domainEvent','commandReceipt'] as RecordKind[]).map(k=>repo.list(k)));}
 afterEach(async()=>{repo?.close();if(dir)await rm(dir,{recursive:true,force:true});});
 it('AC-12-01 actual three menus selected1, decline/reselect and completed suppression keep immutable answers and inactive missing0',async()=>{await setup();await publish();await select();let d=await service.detail(brand,campaignId);expect(d.progress.map(x=>[x.active,x.missingRequired])).toEqual([[true,2],[false,0],[false,0]]);const actual=await submitted(),before=await repo.get('submission',actual.snapshot.id);expect((await service.detail(brand,campaignId)).progress[0].missingRequired).toBe(1);await select('decline');let summary=await service.remainder(brand,taskId);expect(summary.missingRequired).toBe(0);expect(summary.reminderEligible).toBe(false);expect(await repo.get('submission',actual.snapshot.id)).toEqual(before);await select();expect((await service.remainder(brand,taskId)).missingRequired).toBe(1);await repo.transaction(s=>{const t=s.get('task',taskId)!;s.update('task',t.id,t.revision,{...t.data,status:'completed'});});summary=await service.remainder(brand,taskId);expect(summary.reminderEligible).toBe(false);d=await service.detail(brand,campaignId);expect(d.progress[1].evaluation).toBeNull();});
 it('AC-12-02 per-menu axes independent, applied decline creates discussion and preserves external applicant/recorder history',async()=>{await setup();await publish();await select();const original=(await repo.get('task',taskId))!;const fact={axis:'application',value:'applied',requester:person,performedBy:external,occurredAt:null,source:source(),note:'공개 신청 기록'};await command('external',{campaignVersionId:versionId,menu:draft.menus[0].identity,fact});await command('external',{campaignVersionId:versionId,menu:draft.menus[1].identity,fact:{...fact,axis:'selection',value:'not_selected'}});await select('decline');const d=await service.detail(brand,campaignId);expect(d.progress[0].state).toMatchObject({response:'decline',application:'applied',cancellation:'discussion',execution:'not_started'});expect(d.progress[1].state).toMatchObject({application:'not_applied',selection:'not_selected',cancellation:'none'});expect(d.external[0].performedBy).toMatchObject({kind:'external_source',label:external.label});expect(d.external[0].recorderLabel).not.toBe(external.label);expect(d.external[0]).not.toHaveProperty('source');expect((await repo.get('task',taskId))!.data.draft).toEqual(original.data.draft);expect((await sub.workspace(brand,taskId)).request.source!.retainedRequirementKeys).toEqual(['proof','url']);expect((await sub.workspace(brand,taskId)).draftEvaluation).toMatchObject({required:0,missing:0,invalid:0});});
 it('AC-12-03/04 exact shooting1/distribution100 dispatch and receipt independent; tracking/file never receipt and zero stays explicit',async()=>{await setup();await publish();await select();const {reference,fileId}=await submitted();const base={performedBy:person,occurredAt:null,evidence:[reference],note:'합성 실물 사실'};const physical={campaignVersionId:versionId,menu:draft.menus[0].identity,physicalKey:'shoot'};await command('physical',{...physical,fact:{...base,kind:'tracking',carrier:'합성택배',trackingNumber:'000123',trackingUrl:'https://example.test/track'}},brand);let progress=(await service.detail(brand,campaignId)).progress[0];expect(progress.physical.map(x=>x.receipt)).toEqual(['unconfirmed','unconfirmed']);expect(progress.physical[0].dispatchFacts).toBe(0);const dispatch=(await command('physical',{...physical,fact:{...base,kind:'dispatch',quantity:'1',unit:'개',carrier:'합성택배',trackingNumber:'000123'}},brand)).ids[1];await command('physical',{...physical,fact:{...base,kind:'receipt',quantity:'0',unit:'개',dispatchFactIds:[dispatch]}},brand);progress=(await service.detail(brand,campaignId)).progress[0];expect(progress.physical[0]).toMatchObject({receiptFacts:1,dispatchFacts:1,fulfillment:'not_inferred'});expect(progress.physical[0].facts.at(-1)).toMatchObject({quantity:'0'});expect(progress.physical[1]).toMatchObject({receiptFacts:0,dispatchFacts:0,definition:{requestedQuantity:'100',destination:'배포 B'}});expect((await new CampaignFileService(identity,new FileService(identity,dir)).download(brand,fileId,versionId,reference.submissionId,'original')).bytes).toEqual(png);await expect(command('physical',{...physical,physicalKey:'distribute',fact:{...base,kind:'receipt',quantity:'1',unit:'개',dispatchFactIds:[dispatch]}},brand)).rejects.toMatchObject({status:404});});
 it('SA-49 actual compatible followup receipt uses exact answer/file and independent deadlines; arbitrary upload/reference mismatch writes0',async()=>{await setup();await publish();await select();const {reference}=await submitted();const followup={campaignVersionId:versionId,menu:draft.menus[0].identity,followupKey:'photo',source:reference,receivedBy:person,occurredAt:null,note:'사진 수신'};await command('followup',followup,brand);const d=await service.detail(brand,campaignId);expect(d.progress[0].followups.map(f=>f.status)).toEqual(['received','pending']);const before=await business();for(const invalid of [{...followup,followupKey:'url'},{...followup,source:{...reference,contentHash:'f'.repeat(64)}},{...followup,source:{...reference,answer:{requirementKey:'other',productId:null}}}])await expect(command('followup',invalid,brand)).rejects.toMatchObject({status:404});expect(await business()).toEqual(before);});
 it('AC-12-05 private conflicts remain exact and public confirmed null/zero/decimal conditions never inherit original quote; drafts invisible',async()=>{await setup();await expect(service.detail(brand,campaignId)).rejects.toMatchObject({status:404});expect((await service.list(brand,A)).total).toBe(0);await publish();const before=await service.detail(brand,campaignId),staff=await service.detail(admin,campaignId);expect(staff.staff!.publishedOriginal!.menus[0].sourceStatements.map(s=>s.rawValue)).toEqual(['10000円','12000円']);expect(before.selected!.menus[0].conditions.cost.amount).toBeNull();expect(before.selected!.menus[0].confirmationIssues).toEqual([{field:'price',state:'needs_confirmation'}]);expect(JSON.stringify(before)).not.toContain('PRIVATE_');const old=await repo.get('campaignVersion',versionId);draft.title='PRIVATE_EDIT_TITLE';draft.menus[0].conditions.cost={amount:'12345678901234567890.1234',currency:'JPY',taxIncluded:'no'};await command('save',{draft});expect(await service.detail(brand,campaignId)).toEqual(before);expect(await repo.get('campaignVersion',versionId)).toEqual(old);const second=await publish();expect((await service.detail(brand,campaignId)).selected!.menus[0].conditions.cost.amount).toBe('12345678901234567890.1234');expect((await service.detail(brand,campaignId,old!.id)).selected!.id).toBe(old!.id);expect(second).not.toBe(old!.id);});
 it('A19 role/current scope/provider forgery and replay revocation deny while existing fact history is preserved',async()=>{await setup();await publish();await expect(select('participate')).resolves.toBeDefined();const d=await service.detail(brand,campaignId),body={command:'participate',contextId:A,taskId,campaignId,campaignVersionId:versionId,expectedRevision:d.revision,idempotencyKey:randomUUID(),response:'participate',selectedMenus:[draft.menus[0].identity],providedBy:person,note:'stable'};await expect(service.command(team,body)).rejects.toMatchObject({status:403});await expect(service.detail(foreign,campaignId)).rejects.toMatchObject({status:404});await expect(service.command(brand,{...body,providedBy:{kind:'user',userId:'user-co'}})).rejects.toMatchObject({status:403});const saved=await service.command(brand,body);expect(await service.command(brand,body)).toEqual(saved);const facts=await repo.list('campaignSelection');await repo.transaction(s=>{const m=s.list('membership',A).find(m=>m.data.userId==='user-luna')!;s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});await expect(service.command(brand,body)).rejects.toMatchObject({status:404});await expect(service.detail(brand,campaignId)).rejects.toMatchObject({status:404});expect(await repo.list('campaignSelection')).toEqual(facts);});
 it('A20 all late stage failures rollback facts/root/audit/event/receipt, stale CAS and same intent remain atomic',async()=>{await setup();const fault=new CampaignService(identity,()=>{throw Error('late campaign fault');});let before=await business();await expect(command('publish',{},admin,fault)).rejects.toThrow('late campaign fault');expect(await business()).toEqual(before);await publish();await select();const actual=await submitted();const cases=[['save',{draft}],['participate',{campaignVersionId:versionId,response:'participate',selectedMenus:[draft.menus[0].identity],providedBy:person,note:''}],['external',{campaignVersionId:versionId,menu:draft.menus[0].identity,fact:{axis:'execution',value:'finished',requester:person,performedBy:external,occurredAt:null,source:source(),note:''}}],['physical',{campaignVersionId:versionId,menu:draft.menus[0].identity,physicalKey:'shoot',fact:{kind:'dispatch',quantity:'1',unit:'개',carrier:'',trackingNumber:'',performedBy:external,occurredAt:null,evidence:[actual.reference],note:''}}],['followup',{campaignVersionId:versionId,menu:draft.menus[0].identity,followupKey:'photo',source:actual.reference,receivedBy:external,occurredAt:null,note:''}]] as const;for(const [name,extra] of cases){before=await business();await expect(command(name,extra,admin,fault)).rejects.toThrow('late campaign fault');expect(await business()).toEqual(before);}const row=(await repo.get('campaign',campaignId))!,input={command:'publish',contextId:A,taskId,campaignId,expectedRevision:row.revision,idempotencyKey:randomUUID()};const results=await Promise.all([service.command(admin,input),service.command(admin,input)]);expect(results[0]).toEqual(results[1]);expect((await repo.list('domainEvent')).filter(e=>e.data.sourceVersionId===results[0].ids[1])).toHaveLength(1);await expect(service.command(admin,{...input,idempotencyKey:randomUUID()})).rejects.toMatchObject({status:409});await expect(repo.transaction(s=>s.update('campaignVersion',versionId,1,s.get('campaignVersion',versionId)!.data))).rejects.toBeDefined();});

 it('SA-44/46 two actual catalog versions sharing menu number remain distinct; selection changes preserve original productUse capture',async()=>{await setup();const first=draft.menus[0].identity.catalogVersionId,cat=(await repo.get('campaignCatalogVersion',first))!;const second=(await service.command(admin,{command:'save_catalog',contextId:A,catalogId:cat.data.catalogId,expectedRevision:(await repo.get('campaignCatalog',cat.data.catalogId))!.revision,idempotencyKey:randomUUID(),draft:{title:'카탈로그 개정',versionLabel:'2027 v2',source:{...source(),sourceVersion:'v2',originalText:'다른 원문 가격'}}})).ids[1];draft.menus[1].identity={...draft.menus[0].identity,catalogVersionId:second,menuName:'같은 번호 다른 메뉴'};await command('save',{draft});await publish();await select();const actual=await submitted();await select('participate',[draft.menus[1].identity]);expect((await service.detail(brand,campaignId)).progress.map(p=>p.active)).toEqual([false,true,false]);const use=(await repo.get('productUseSnapshot',actual.snapshot.products[0].id))!;draft.menus[0].products[0]={...draft.menus[0].products[0],productUseId:use.id,productVersionId:use.data.productVersionId,contextProductVersionId:use.data.contextProductVersionId};draft.menus[0].physical[0].product=draft.menus[0].products[0];await command('save',{draft});await publish();const p=await new ProductService(identity).detail(admin,'product-serum',A);await new ProductService(identity).command(admin,p.productId,{command:'save_common',contextId:A,expectedCommonRevision:p.commonRevision,common:{...p.common,name:'나중에 바뀐 상품명'},idempotencyKey:randomUUID()});const d=await service.detail(brand,campaignId);expect(d.selected!.menus[0].products[0].productVersionId).toBe(use.data.productVersionId);expect(await repo.get('productUseSnapshot',use.id)).toEqual(use);expect((await service.catalogs(admin,A)).items[0].versions.map(v=>v.id)).toEqual([second,first]);});
 it('D02 actual file bytes read then current membership revocation still prevents campaign download return',async()=>{await setup();await publish();await select();const {reference,fileId}=await submitted();await command('followup',{campaignVersionId:versionId,menu:draft.menus[0].identity,followupKey:'photo',source:reference,receivedBy:external,occurredAt:null,note:'외부 수령 담당'},brand);class RevokingFiles extends FileService{override async download(...args:Parameters<FileService['download']>){const result=await super.download(...args);await repo.transaction(s=>{const m=s.list('membership',A).find(m=>m.data.userId==='user-luna')!;s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});return result;}}await expect(new CampaignFileService(identity,new RevokingFiles(identity,dir)).download(brand,fileId,versionId,reference.submissionId,'download')).rejects.toMatchObject({status:404});expect(await repo.list('campaignFollowupFact')).toHaveLength(1);});
 it('A20 catalog late fault leaves no root/version/receipt; stale source relationships and actual G04 incompatible rules refuse publication',async()=>{await setup();const before=await business(),broken=new CampaignService(identity,()=>{throw Error('catalog rollback');});await expect(broken.command(admin,{command:'save_catalog',contextId:A,catalogId:null,expectedRevision:0,idempotencyKey:randomUUID(),draft:{title:'추가 원문',versionLabel:'v9',source:source()}})).rejects.toThrow('catalog rollback');expect(await business()).toEqual(before);draft.menus[0].request.requirements[0].type='short_text';draft.menus[0].followups=[];await command('save',{draft});await expect(command('publish')).rejects.toMatchObject({status:409,code:'REQUEST_MISMATCH'});expect(await repo.list('campaignVersion')).toHaveLength(0);});
 it('A19 valid nested unknown values are preserved in immutable storage but excluded from both DTOs; known malformed fails503',async()=>{await setup();await publish();const original=(await repo.get('campaignVersion',versionId))!;const expanded=structuredClone(original.data) as unknown as Record<string,unknown>;const menus=expanded.menus as Record<string,unknown>[];(menus[0].conditions as Record<string,unknown>).hidden='STORED_CANARY';(menus[0].products as Record<string,unknown>[])[0].hidden='PRODUCT_CANARY';const id=randomUUID();await repo.transaction(s=>{s.create('campaignVersion',{id,contextId:A,data:{...expanded,sequence:999} as unknown as typeof original.data});const root=s.get('campaign',campaignId)!;s.update('campaign',campaignId,root.revision,{...root.data,currentVersionId:id});});const before=createHash('sha256').update(JSON.stringify(await repo.get('campaignVersion',id))).digest('hex');expect(JSON.stringify(await service.detail(brand,campaignId))).not.toContain('CANARY');expect(createHash('sha256').update(JSON.stringify(await repo.get('campaignVersion',id))).digest('hex')).toBe(before);const broken=structuredClone(original.data);(broken.menus[0].conditions.cost as unknown as Record<string,unknown>).amount={secret:'KNOWN_CANARY'};await repo.transaction(s=>s.create('campaignVersion',{id:randomUUID(),contextId:A,data:{...broken,sequence:1000}}));await expect(service.detail(brand,campaignId)).rejects.toMatchObject({status:503});});
 it('G12-R01 AC-12-01 canonical G04 and G05 omit unselected requirements; selected partial then full uses real product capture',async()=>{
  await setup();const original=(await repo.get('task',taskId))!,originalRequest=(await repo.get('requestVersion',original.data.currentRequestId!))!;await publish();let w=await sub.workspace(brand,taskId);expect(w.request.source).toMatchObject({noMaterials:true,originalRequestId:originalRequest.id});expect(w.draftEvaluation).toMatchObject({required:0,missing:0,invalid:0,canSubmitFull:true});expect(w.products).toHaveLength(0);expect((await tasks.detail(brand,taskId)).requirementStatus).toHaveLength(0);
  await select();w=await sub.workspace(brand,taskId);expect(w.request.content.requirements.map(q=>q.key)).toEqual(['proof','url']);expect(w.request.source).toMatchObject({actorId:'user-luna',noMaterials:false});expect((await repo.get('requestVersion',w.request.id))!.data.publishedBy).toBe('user-luna');expect(w.draftEvaluation?.required).toBe(2);expect(w.products.map(p=>p.productId)).toEqual(['product-serum']);const actual=await submitted();w=await sub.workspace(brand,taskId);expect(w.submittedEvaluation?.evaluation.missing).toBe(1);await expect(sub.submit(brand,taskId,{baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,expectedTaskRevision:w.taskRevision,mode:'full',idempotencyKey:randomUUID()})).rejects.toMatchObject({status:409});
  await sub.draft(brand,taskId,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,content:{...w.draft!.content,answers:[...w.draft!.content.answers,{requestId:w.request.id,requirementKey:'url',productId:null,type:'link',input:{url:'https://example.test/published',description:'게시 자료',contentFixed:false,fixedReference:null}}]},idempotencyKey:randomUUID()});w=await sub.workspace(brand,taskId);const full=(await sub.submit(brand,taskId,{baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,expectedTaskRevision:w.taskRevision,mode:'full',idempotencyKey:randomUUID()})).ids[0];expect((await sub.snapshot(brand,full)).evaluation).toMatchObject({required:2,missing:0,canSubmitFull:true});expect((await sub.snapshot(brand,actual.snapshot.id)).contentHash).toBe(actual.snapshot.contentHash);expect(await repo.get('requestVersion',originalRequest.id)).toEqual(originalRequest);expect((await repo.get('task',taskId))!.data.draft).toEqual(original.data.draft);
 });
 it('G12-R02 AC-12-01/02 decline keeps applied facts and immutable draft, explicit zero-request rebase removes old product selections and can reselect',async()=>{
  await setup();await publish();await select();const actual=await submitted(),oldDraft=(await repo.list('submissionDraft'))[0],oldRequest=(await repo.get('requestVersion',actual.snapshot.requestId))!;
  await command('external',{campaignVersionId:versionId,menu:draft.menus[0].identity,fact:{axis:'application',value:'applied',requester:person,performedBy:external,occurredAt:null,source:source(),note:'실제 신청 관찰'}});const facts=await repo.list('campaignExternalFact');await select('participate',[draft.menus[1].identity]);expect((await service.detail(brand,campaignId)).progress[0]).toMatchObject({active:false,retainedForCancellationReview:true,state:{cancellation:'discussion'}});await select('decline');let w=await sub.workspace(brand,taskId);expect(w.request.source).toMatchObject({noMaterials:true,retainedRequirementKeys:['proof','url']});expect(w.requiresRebase).toBe(true);expect(w.draftEvaluation).toMatchObject({required:0,missing:0,invalid:0});expect(w.products).toHaveLength(0);expect((await service.detail(brand,campaignId)).progress[0]).toMatchObject({active:false,retainedForCancellationReview:true,reminderEligible:false,missingRequired:0});expect(await repo.get('submissionDraft',oldDraft.id)).toEqual(oldDraft);expect(await repo.get('requestVersion',oldRequest.id)).toEqual(oldRequest);expect(await repo.list('campaignExternalFact')).toEqual(facts);
  await expect(sub.draft(brand,taskId,{command:'save',baseRequestId:oldRequest.id,expectedDraftRevision:oldDraft.revision,content:oldDraft.data,idempotencyKey:randomUUID()})).rejects.toMatchObject({status:409,code:'REQUEST_CHANGED'});
  const rebase=await sub.rebasePreview(brand,taskId);expect(rebase.answers.every(a=>!a.compatible)).toBe(true);await sub.draft(brand,taskId,{command:'rebase_apply',baseRequestId:rebase.fromRequestId,targetRequestId:rebase.currentRequestId,expectedDraftRevision:rebase.draftRevision,carryAnswers:[],idempotencyKey:randomUUID()});w=await sub.workspace(brand,taskId);expect(w.draft!.content.answers).toEqual([]);expect(w.draft!.content.productSelections).toEqual([]);expect(w.draft!.content.artifacts).toEqual([]);expect((await sub.evaluate(brand,taskId,{baseRequestId:w.request.id,content:w.draft!.content})).missingProductIds).toEqual([]);
  await select();w=await sub.workspace(brand,taskId);expect(w.requiresRebase).toBe(true);expect(w.request.content.requirements.map(q=>q.key)).toEqual(['proof','url']);expect(w.products).toHaveLength(1);expect((await sub.snapshot(brand,actual.snapshot.id)).contentHash).toBe(actual.snapshot.contentHash);
 });
 it('G12-R03 general requirements survive; normal empty publish forbidden; independent request revision and competing campaign conflict rollback',async()=>{
  await setup();let t=(await repo.get('task',taskId))!;const c={...t.data.draft!,requirements:[...t.data.draft!.requirements,{...blankRequirement('general','short_text'),label:'일반 담당 연락'}]};await tasks.command(admin,taskId,{command:'save',expectedRevision:t.revision,content:c,idempotencyKey:randomUUID()});await tasks.command(admin,taskId,{command:'publish',expectedRevision:(await repo.get('task',taskId))!.revision,idempotencyKey:randomUUID()});await command('save',{draft});await publish();let w=await sub.workspace(brand,taskId);expect(w.request.content.requirements.map(q=>q.key)).toEqual(['general']);expect(w.draftEvaluation).toMatchObject({required:1,missing:1});await select();w=await sub.workspace(brand,taskId);expect(w.request.content.requirements.map(q=>q.key)).toEqual(['general','proof','url']);
  const other=(await service.command(admin,{command:'save',contextId:A,taskId,campaignId:null,expectedRevision:0,idempotencyKey:randomUUID(),draft})).ids[0];let before=await business();await expect(service.command(admin,{command:'publish',contextId:A,taskId,campaignId:other,expectedRevision:1,idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'CAMPAIGN_REQUEST_CONFLICT'});expect(await business()).toEqual(before);
  t=(await repo.get('task',taskId))!;await tasks.command(admin,taskId,{command:'publish',expectedRevision:t.revision,idempotencyKey:randomUUID()});before=await business();await expect(select('decline')).rejects.toMatchObject({code:'CAMPAIGN_REQUEST_CONFLICT'});expect(await business()).toEqual(before);
  t=(await repo.get('task',taskId))!;await tasks.command(admin,taskId,{command:'save',expectedRevision:t.revision,content:{...c,requirements:[]},idempotencyKey:randomUUID()});before=await business();await expect(tasks.command(admin,taskId,{command:'publish',expectedRevision:(await repo.get('task',taskId))!.revision,idempotencyKey:randomUUID()})).rejects.toMatchObject({status:422});expect(await business()).toEqual(before);
 });
 it('G12-R04 conditional parent removal rejects publication without touching original request or approved campaign',async()=>{
  await setup();const t=(await repo.get('task',taskId))!;const parent={...blankRequirement('menu-choice','choice'),label:'메뉴 답변',options:['yes','no']},general={...blankRequirement('general','short_text'),label:'일반 후속',condition:{key:parent.key,equals:'yes'}};const c={...t.data.draft!,requirements:[parent,general]};await tasks.command(admin,taskId,{command:'save',expectedRevision:t.revision,content:c,idempotencyKey:randomUUID()});await tasks.command(admin,taskId,{command:'publish',expectedRevision:(await repo.get('task',taskId))!.revision,idempotencyKey:randomUUID()});draft.menus=[{...draft.menus[0],request:{...draft.menus[0].request,requirements:[parent]},followups:[]}];await command('save',{draft});const before=await business();await expect(publish()).rejects.toMatchObject({code:'CAMPAIGN_REQUEST_CONFLICT'});expect(await business()).toEqual(before);
 });
 it('G12-PRE01 G07 global requirements apply only to active material products, including product list/detail counts',async()=>{
  await setup();const products=new ProductService(identity),p2=(await products.create(admin,{contextId:A,brandId:(await repo.get('context',A))!.data.brandId,common:{...blankCommon(),name:'미선택 메뉴 전용 상품',code:'G12-PRE01-P2'},fields:blankContext(),idempotencyKey:randomUUID()})).ids[0];await products.command(admin,p2,{command:'link_task',contextId:A,taskId,expectedTaskRevision:(await repo.get('task',taskId))!.revision,idempotencyKey:randomUUID()});const detail=await products.detail(admin,p2,A),target={productId:p2,productVersionId:detail.commonVersionId,contextProductVersionId:detail.contextVersionId,productUseId:null,sampleVariant:'미선택상품'};draft.menus[1].products=[target];draft.menus[2].products=[target];await command('save',{draft});await publish();await select();const w=await sub.workspace(brand,taskId);expect(w.products.map(p=>p.productId)).toEqual(['product-serum']);expect((await repo.get('task',taskId))!.data.productIds).toEqual(['product-serum',p2]);
  const table=await new EvidenceService(identity).table(brand,A),row=table.rows.find(r=>r.productId===p2)!,p2detail=await products.detail(brand,p2,A),list=await products.list(brand,{context:A}),p2list=list.items.find(p=>p.productId===p2)!;
  console.log('G12_PRE01_OBSERVED',JSON.stringify({mode,selectedProducts:w.products.map(p=>p.productId),p2,table:row.counts,detail:p2detail.materialCounts,list:p2list.materialCounts}));expect.soft(row.cells.filter(c=>c.taskId===taskId).every(c=>!c.applicable&&c.status==='not_applicable')).toBe(true);expect.soft(row.counts).toEqual({connected:true,requested:0,missing:0,unconfirmed:0});expect.soft(p2detail.materialCounts).toEqual({connected:true,requested:0,missing:0,unconfirmed:0});expect.soft(p2list.materialCounts).toEqual({connected:true,requested:0,missing:0,unconfirmed:0});await select('decline');expect((await new EvidenceService(identity).table(brand,A)).rows.filter(r=>['product-serum',p2].includes(r.productId)).flatMap(r=>r.cells.filter(c=>c.taskId===taskId))).toEqual([]);
 });
});
