import { afterEach,describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { RecordRepository,RecordKind } from '@/domain/records';
import { createMockRepository } from '@/server/repositories/mock';
import { createSqliteRepository } from '@/server/repositories/sqlite';
import { openDatabase,migrate } from '@/server/db/database';
import { policyFixture,tokenFor,NOW } from '../fixtures/policy';
import { IdentityService } from '@/server/auth/service';
import { TaskService } from '@/server/tasks/service';
import { ProductService } from '@/server/products/service';
import { SubmissionService } from '@/server/submissions/service';
import { SubmissionFiles } from '@/server/submissions/files';
import { FileService } from '@/server/files/service';
import { CorrectionService } from '@/server/corrections/service';
import { CorrectionFiles } from '@/server/corrections/files';
import { readCorrectionRemainder } from '@/server/corrections/summary';
import { blankContent,blankRequirement } from '@/domain/tasks/types';
import { blankDraft } from '@/domain/submissions/types';
import type { ReviewTarget,OpinionInput,BatchDraftInput } from '@/domain/corrections/types';
const A='ctx-jp-a-luna',admin=tokenFor('user-admin'),brand=tokenFor('user-luna'),co=tokenFor('user-co'),team=tokenFor('user-team');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS0cAAAAASUVORK5CYII=','base64');
const kinds:RecordKind[]=['correctionOpinion','correctionOpinionVersion','correctionDraft','correctionBatch','correctionItemState','correctionReflection','correctionResolution','correctionReview','audit','domainEvent','commandReceipt'];
for(const mode of ['mock','sqlite'] as const)describe(`${mode} G10 real submission correction producer`,()=>{
 let repo:RecordRepository,identity:IdentityService,service:CorrectionService,sub:SubmissionService,taskId:string,dir:string;
 async function setup(){repo=mode==='mock'?createMockRepository(()=>NOW):(()=>{const db=openDatabase(':memory:',true);migrate(db);return createSqliteRepository(db,()=>NOW);})();identity=await policyFixture(repo);service=new CorrectionService(identity);sub=new SubmissionService(identity);dir=await mkdtemp(path.join(os.tmpdir(),'g10-'));const tasks=new TaskService(identity),c={...blankContent(),title:'G10 actual fixture',description:'Public request',deadline:{...blankContent().deadline,responsibleUserId:'user-gsg'},requirements:[{...blankRequirement('answer'),label:'Answer'}]};taskId=(await tasks.create(admin,{targets:[{contextId:A,ownerId:'user-gsg',assigneeId:'user-luna',coAssigneeIds:['user-co'],productIds:['product-serum']}],content:c,category:'spot',idempotencyKey:randomUUID()})).ids[0];await tasks.command(admin,taskId,{command:'publish',expectedRevision:1,idempotencyKey:randomUUID()});}
 async function submitted(label='v1'):Promise<ReviewTarget>{let w=await sub.workspace(brand,taskId);const upload=await new SubmissionFiles(identity,dir).upload(brand,taskId,w.request.id,[{clientItemId:randomUUID(),name:label+'.png',type:'image/png',bytes:png}]);if(upload.items[0].state!=='ready')throw Error('fixture upload');const fileId=upload.items[0].file.id,p=await new ProductService(identity).detail(brand,'product-serum',A);await sub.draft(brand,taskId,{command:'save',baseRequestId:w.request.id,expectedDraftRevision:w.draft?.revision??0,content:{...blankDraft(),answers:[{requestId:w.request.id,requirementKey:'answer',productId:null,type:'long_text',input:{text:label}}],artifacts:[{fileVersionId:fileId,role:'review_copy',answer:null}],productSelections:[{productId:p.productId,expectedCommonRevision:p.commonRevision,expectedContextRevision:p.contextRevision,bindingIds:[],retailPriceVersionId:null,asOfDate:'2026-09-21'}]},idempotencyKey:randomUUID()});w=await sub.workspace(brand,taskId);const id=(await sub.submit(brand,taskId,{baseRequestId:w.request.id,expectedDraftRevision:w.draft!.revision,expectedTaskRevision:w.taskRevision,mode:'full',idempotencyKey:randomUUID()})).ids[0],row=(await repo.get('submission',id))!;return {taskId,submissionId:id,requestId:row.data.requestId,submissionContentHash:row.data.contentHash,answer:null,fileVersionIds:[fileId],productUseIds:row.data.productUseIds,location:{page:'2',locator:'bottom mark'}};}
 const opinion=(target:ReviewTarget):OpinionInput=>({target,source:{kind:'external_opinion',agency:'Synthetic agency',reviewer:'Reviewer',source:'Private mail'},originalText:'PRIVATE_G10_ORIGINAL',internalFileVersionIds:[],receivedOn:'2026-09-21',conflictingOpinionVersionIds:[]});
 async function opinionId(target:ReviewTarget){return (await service.command(admin,{command:'save_opinion',taskId,opinionId:null,expectedRevision:0,opinion:opinion(target),idempotencyKey:randomUUID()})).ids[1];}
 async function draft(target:ReviewTarget,previousBatchVersionId:string|null=null):Promise<BatchDraftInput>{return {title:'Public changes',summary:'Selected summary',items:await Promise.all(['one','two','three'].map(async key=>({key,target,internalOpinionVersionIds:[await opinionId(target)],publicSource:'Selected source',change:'Change '+key,reason:'Reason',publicDescription:'Public explanation '+key,priority:'normal' as const,issue:'correction' as const}))),mode:'normal',pendingScopes:[],previousBatchVersionId};}
 async function saved(d:BatchDraftInput){return (await service.command(admin,{command:'save_draft',taskId,draftId:null,expectedRevision:0,draft:d,idempotencyKey:randomUUID()})).ids[0];}
 async function publish(d:BatchDraftInput){const id=await saved(d);return (await service.command(admin,{command:'publish',taskId,draftId:id,expectedRevision:1,idempotencyKey:randomUUID()})).ids[0];}
 const snapshots=()=>Promise.all(kinds.map(k=>repo.list(k)));
 it('D02 correction file current authority is rechecked after actual asynchronous bytes read',async()=>{await setup();const v1=await submitted(),b=await publish(await draft(v1));let completed=0;const wrapped:RecordRepository={...repo,transaction:async op=>{const result=await repo.transaction(op);if(++completed===2)await repo.transaction(s=>{const m=s.list('membership',A).find(m=>m.data.userId==='user-luna')!;s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});return result;}};await expect(new CorrectionFiles(new IdentityService(wrapped,()=>NOW),dir).download(brand,v1.fileVersionIds[0],new URLSearchParams({batchVersionId:b,itemKey:'one'}))).rejects.toMatchObject({status:404});expect(completed).toBe(2);});
 afterEach(async()=>{repo?.close();if(dir)await rm(dir,{recursive:true,force:true});});
 it('AC-10-01 internal original immutable versions do not affect public preview/body/count/order/time; explicit publication only',async()=>{await setup();const target=await submitted(),d=await draft(target),id=await saved(d),before=await service.workspace(brand,taskId);expect(before.batches).toEqual([]);expect(before.staff).toBeNull();expect(await repo.list('domainEvent')).toHaveLength(2);const preview=await service.preview(admin,id);expect(JSON.stringify(preview)).not.toContain('PRIVATE_G10');expect(JSON.stringify(preview)).not.toContain('internalOpinion');await expect(service.preview(brand,id)).rejects.toMatchObject({status:403});const key=randomUUID(),cmd={command:'publish',taskId,draftId:id,expectedRevision:1,idempotencyKey:key},result=await service.command(admin,cmd);expect(await service.command(admin,cmd)).toEqual(result);const pub=await service.detail(brand,result.ids[0]);expect(pub.items).toHaveLength(3);expect(pub.items[0].publicDescription).toContain('Public');const original=await repo.list('correctionOpinionVersion'),root=(await repo.list('correctionOpinion'))[0];await service.command(admin,{command:'save_opinion',taskId,opinionId:root.id,expectedRevision:root.revision,opinion:{...opinion(target),originalText:'PRIVATE_LATE'},idempotencyKey:randomUUID()});expect(await service.detail(brand,result.ids[0])).toEqual(pub);expect((await repo.list('correctionOpinionVersion')).filter(v=>original.some(o=>o.id===v.id))).toEqual(original);expect(JSON.stringify(await service.workspace(brand,taskId))).not.toContain('PRIVATE_');expect(JSON.stringify(await service.workspace(brand,taskId))).not.toContain(root.id);});
 it('AC-10-02 actual v2 reflects two selected items; one resolved one wrong-file and third pending; upload/full submit does not resolve',async()=>{await setup();const v1=await submitted(),b=await publish(await draft(v1)),snapshot=await repo.get('correctionBatch',b),v2=await submitted('v2');expect((await service.detail(brand,b)).items.map(i=>i.state.status)).toEqual(['pending','pending','pending']);const cmd={command:'reflect',taskId,batchVersionId:b,items:['one','two'].map(itemKey=>({itemKey,expectedItemRevision:0,target:v2,note:'Explicit v2'})),idempotencyKey:randomUUID()};const ids=(await service.command(co,cmd)).ids;expect(await service.command(co,cmd)).toEqual({ids});await service.command(admin,{command:'resolve',taskId,batchVersionId:b,items:[{itemKey:'one',expectedItemRevision:1,reflectionId:ids[0],decision:'resolved',reason:''},{itemKey:'two',expectedItemRevision:1,reflectionId:ids[1],decision:'not_reflected',reason:'Wrong emblem file'}],idempotencyKey:randomUUID()});const latest=await service.detail(brand,b);expect(latest.items.map(i=>i.state.status)).toEqual(['resolved','not_reflected','pending']);expect(latest.items[0].state.resolution?.resolvedBy).toBe('user-admin');expect(await repo.get('correctionBatch',b)).toEqual(snapshot);expect((await repo.get('task',taskId))!.data.status).toBe('submitted');expect((await service.workspace(brand,taskId)).remainder.unresolved).toBe(2);await expect(service.command(team,{...cmd,idempotencyKey:randomUUID()})).rejects.toMatchObject({status:403});await expect(service.command(brand,{command:'resolve',taskId,batchVersionId:b,items:[{itemKey:'one',expectedItemRevision:2,reflectionId:ids[0],decision:'resolved',reason:''}],idempotencyKey:randomUUID()})).rejects.toMatchObject({status:403});expect((await service.detail(brand,b)).items[1].history.resolutions[0].reason).toBe('Wrong emblem file');});
 it('AC-10-03 explicit followup and conflicting sources retain immutable original and urgent null waiting date',async()=>{await setup();const v1=await submitted(),b=await publish(await draft(v1)),old=await repo.get('correctionBatch',b),d=await draft(v1,b);d.mode='urgent_partial';d.pendingScopes=[{agency:'Remaining agency',scope:'Package emblem',expectedOn:null}];d.items[0].issue='conflicting_opinions';d.items[0].internalOpinionVersionIds.push(await opinionId(v1));d.items[0].publicDescription='Conflicting instructions require confirmation';const next=await publish(d);expect((await service.detail(brand,next)).items[0].state.status).toBe('needs_confirmation');expect((await service.detail(brand,next)).pendingScopes[0].expectedOn).toBeNull();expect(await repo.get('correctionBatch',b)).toEqual(old);const orphan=await saved(await draft(v1));await expect(service.command(admin,{command:'publish',taskId,draftId:orphan,expectedRevision:1,idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'FOLLOWUP_REQUIRED'});const r=await repo.get('correctionDraft',old!.data.draftId);await expect(service.command(admin,{command:'save_draft',taskId,draftId:r!.id,expectedRevision:r!.revision,draft:d,idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'PUBLISHED_IMMUTABLE'});});
 it('AC-10-04 actual previous review remains reference only; changed version and scope get no inherited result; private review is invisible to brand summary',async()=>{await setup();const v1=await submitted(),before=(await sub.snapshot(brand,v1.submissionId)).review;const base={command:'record_review',taskId,target:v1,source:opinion(v1).source,scope:{medium:'Label',language:'ja',usePlace:'Retail A',productIds:['product-serum']},receivedOn:'2026-09-21',result:'no_changes_requested',rationale:'PRIVATE_REVIEW',evidenceFileVersionIds:v1.fileVersionIds,previousReviewId:null,idempotencyKey:randomUUID()};const old=(await service.command(admin,base)).ids[0];expect((await sub.snapshot(brand,v1.submissionId)).review).toEqual(before);expect((await sub.snapshot(admin,v1.submissionId)).review.reviews[0].result).toBe('no_changes_requested');const v2=await submitted('v2');expect((await sub.snapshot(admin,v2.submissionId)).review).toMatchObject({connected:true,status:'pending',reviews:[]});await service.command(admin,{...base,target:v2,scope:{...base.scope,language:'en'},result:'needs_confirmation',evidenceFileVersionIds:v2.fileVersionIds,previousReviewId:old,idempotencyKey:randomUUID()});const actual=(await service.workspace(admin,taskId)).staff!.reviews;expect(actual.find(r=>r.target.submissionId===v2.submissionId)).toMatchObject({result:'needs_confirmation',previousReviewId:old,previousReviewIsReferenceOnly:true});expect((await sub.snapshot(brand,v2.submissionId)).review.reviews).toEqual([]);await expect(service.command(admin,{...base,source:{kind:'ai_candidate',runId:'missing-run',findingId:'finding',source:'AI'},idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'NOT_FOUND'});});
 it('A19 exact hash/request/answer/files/productUse relation deny before writes; current role and context are required',async()=>{await setup();const v1=await submitted(),v2=await submitted('v2'),before=await snapshots();for(const bad of [{...v1,submissionContentHash:'a'.repeat(64)},{...v1,requestId:'not-request'},{...v1,answer:{requirementKey:'missing',productId:null}},{...v1,fileVersionIds:v2.fileVersionIds},{...v1,productUseIds:v2.productUseIds}])await expect(opinionId(bad)).rejects.toMatchObject({status:404});expect(await snapshots()).toEqual(before);await expect(service.workspace(tokenFor('user-wave'),taskId)).rejects.toMatchObject({status:404});await expect(opinionId({...v1,taskId:'task-wave'})).rejects.toMatchObject({status:422});const b=await publish(await draft(v1));await expect(service.command(brand,{command:'reflect',taskId,batchVersionId:b,items:[{itemKey:'one',expectedItemRevision:0,target:v1,note:''}],idempotencyKey:randomUUID()})).rejects.toMatchObject({code:'TARGET_MISMATCH'});});
 it('A20 every late fault rolls back opinion/draft/publication/reflection/resolution/review and all audit/event/receipt rows',async()=>{await setup();const v1=await submitted(),d=await draft(v1),draftId=await saved(d),failer=new CorrectionService(identity,()=>{throw Error('late correction fault');});async function fails(actor:string,cmd:unknown){const before=await snapshots();await expect(failer.command(actor,cmd)).rejects.toThrow('late correction fault');expect(await snapshots()).toEqual(before);}await fails(admin,{command:'save_opinion',taskId,opinionId:null,expectedRevision:0,opinion:opinion(v1),idempotencyKey:randomUUID()});await fails(admin,{command:'save_draft',taskId,draftId:null,expectedRevision:0,draft:d,idempotencyKey:randomUUID()});await fails(admin,{command:'publish',taskId,draftId,expectedRevision:1,idempotencyKey:randomUUID()});const b=(await service.command(admin,{command:'publish',taskId,draftId,expectedRevision:1,idempotencyKey:randomUUID()})).ids[0],v2=await submitted('v2'),reflect={command:'reflect',taskId,batchVersionId:b,items:[{itemKey:'one',expectedItemRevision:0,target:v2,note:''}],idempotencyKey:randomUUID()};await fails(brand,reflect);const reflectionId=(await service.command(brand,reflect)).ids[0];await fails(admin,{command:'resolve',taskId,batchVersionId:b,items:[{itemKey:'one',expectedItemRevision:1,reflectionId,decision:'resolved',reason:''}],idempotencyKey:randomUUID()});await fails(admin,{command:'record_review',taskId,target:v1,source:opinion(v1).source,scope:{medium:'label',language:'ja',usePlace:'retail',productIds:['product-serum']},receivedOn:'2026-09-21',result:'opinion_only',rationale:'Private evidence',evidenceFileVersionIds:v1.fileVersionIds,previousReviewId:null,idempotencyKey:randomUUID()});});
 it('A20 same intent and concurrent CAS publication creates one batch/outbox; current revocation defeats successful replay',async()=>{await setup();const v1=await submitted(),id=await saved(await draft(v1)),cmd={command:'publish',taskId,draftId:id,expectedRevision:1,idempotencyKey:randomUUID()};const results=await Promise.all([service.command(admin,cmd),service.command(admin,cmd)]);expect(results[0]).toEqual(results[1]);await expect(service.command(admin,{...cmd,idempotencyKey:randomUUID()})).rejects.toMatchObject({status:409});expect(await repo.list('correctionBatch')).toHaveLength(1);expect((await repo.list('domainEvent')).filter(e=>e.data.eventType==='CORRECTION_BATCH_PUBLISHED')).toHaveLength(1);await repo.transaction(s=>{const session=s.get('session','policy-session-user-admin')!;s.update('session',session.id,session.revision,{...session.data,revokedAt:NOW});});await expect(service.command(admin,cmd)).rejects.toMatchObject({status:401});});
 it('D02 exact public batch file current original/reference; internal opinion attachment never released and new source file cannot replace old bytes',async()=>{await setup();const v1=await submitted(),internal=(await new FileService(identity,dir).upload(admin,taskId,[{name:'PRIVATE_SOURCE.png',type:'image/png',bytes:png}],'internal')).files[0];const o=await service.command(admin,{command:'save_opinion',taskId,opinionId:null,expectedRevision:0,opinion:{...opinion(v1),internalFileVersionIds:[internal.id]},idempotencyKey:randomUUID()});const d=await draft(v1);d.items[0].internalOpinionVersionIds=[o.ids[1]];const b=await publish(d),files=new CorrectionFiles(identity,dir),q=new URLSearchParams({batchVersionId:b,itemKey:'one'});expect((await files.download(brand,v1.fileVersionIds[0],q)).bytes).toEqual(png);await expect(files.download(brand,internal.id,q)).rejects.toMatchObject({status:404});await expect(new FileService(identity,dir).download(brand,internal.id,taskId,'original')).rejects.toMatchObject({status:404});expect(JSON.stringify(await service.detail(brand,b))).not.toContain('PRIVATE_SOURCE');await repo.transaction(s=>{const m=s.list('membership',A).find(m=>m.data.userId==='user-luna')!;s.update('membership',m.id,m.revision,{...m.data,status:'suspended'});});await expect(files.download(brand,v1.fileVersionIds[0],q)).rejects.toMatchObject({status:404});});
 it('A19 valid stored unknown nested additions are retained but never projected; malformed known nested public fields fail503',async()=>{await setup();const v1=await submitted(),d=await draft(v1),id=await saved(d);await repo.transaction(s=>{const row=s.get('correctionDraft',id)!;const next={...row.data.draft,secret:'PRIVATE_EXT',items:row.data.draft.items.map(i=>({...i,extra:{canary:'PRIVATE_EXT'},target:{...i.target,location:{...i.target.location,secret:'PRIVATE_EXT'}}}))};s.update('correctionDraft',id,row.revision,{...row.data,draft:next});});const raw=await repo.get('correctionDraft',id),preview=await service.preview(admin,id);expect(JSON.stringify(preview)).not.toContain('PRIVATE_EXT');const b=(await service.command(admin,{command:'publish',taskId,draftId:id,expectedRevision:2,idempotencyKey:randomUUID()})).ids[0];expect(JSON.stringify(await service.detail(brand,b))).not.toContain('PRIVATE_EXT');expect((await repo.get('correctionDraft',id))!.data.draft).toEqual(raw!.data.draft);const bad=await saved(await draft(v1,b));await repo.transaction(s=>{const r=s.get('correctionDraft',bad)!;s.update('correctionDraft',bad,r.revision,{...r.data,draft:{...r.data.draft,items:r.data.draft.items.map(i=>({...i,publicDescription:{secret:'PRIVATE_BAD'}}))} as unknown as BatchDraftInput});});const before=await repo.get('correctionDraft',bad);await expect(service.preview(admin,bad)).rejects.toMatchObject({status:503});expect(await repo.get('correctionDraft',bad)).toEqual(before);await expect(repo.transaction(s=>{const r=s.get('correctionBatch',b)!;s.update('correctionBatch',b,r.revision,r.data);})).rejects.toMatchObject({code:'INVALID_RECORD'});const remainder=await repo.transaction(s=>readCorrectionRemainder(s,identity.principal(s,brand),taskId,()=>NOW));expect(remainder.connected).toBe(true);});
});
