import { TaskService } from '@/server/tasks/service';
import { SubmissionService } from '@/server/submissions/service';
import { SubmissionFiles } from '@/server/submissions/files';
import { blankContent, blankRequirement } from '@/domain/tasks/types';
import { blankDraft } from '@/domain/submissions/types';
import { afterEach, describe, it, expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { RecordRepository } from '@/domain/records';
import type { IdentityService } from '@/server/auth/service';
import { createMockRepository } from '@/server/repositories/mock';
import { createSqliteRepository } from '@/server/repositories/sqlite';
import { openDatabase, migrate } from '@/server/db/database';
import { policyFixture, tokenFor, NOW } from '../fixtures/policy';
import { EvidenceService } from '@/server/evidence/service';
import { ProductService } from '@/server/products/service';
import { FileService } from '@/server/files/service';
import { blankFileBinding } from '@/domain/products/types';
import { blankEvidenceMetadata } from '@/domain/evidence/types';
const A = 'ctx-jp-a-luna', brand = tokenFor('user-luna'), admin = tokenFor('user-admin');
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS0cAAAAASUVORK5CYII=', 'base64');
for (const mode of ['mock', 'sqlite'] as const)
    describe(`${mode} G07 immutable evidence`, () => {
        let repo: RecordRepository, identity: IdentityService, service: EvidenceService, products: ProductService, dir: string;
        async function setup() { repo = mode === 'mock' ? createMockRepository(() => NOW) : (() => { const db = openDatabase(':memory:', true); migrate(db); return createSqliteRepository(db, () => NOW); })(); identity = await policyFixture(repo); service = new EvidenceService(identity); products = new ProductService(identity); dir = await mkdtemp(path.join(os.tmpdir(), 'gs-hale-g07-evidence-')); }
        async function source() { const pid = 'product-serum', file = (await new FileService(identity, dir).upload(brand, { kind: 'product', productId: pid, contextId: A }, [{ name: 'invoice.png', type: 'image/png', bytes: png }], 'public')).files[0]; const p = await products.detail(brand, pid, A), binding = blankFileBinding(randomUUID(), file.id); await products.command(brand, pid, { command: 'save_files', contextId: A, expectedContextRevision: p.contextRevision, files: [binding], idempotencyKey: randomUUID() }); const d = await products.detail(brand, pid, A); return { kind: 'product_binding' as const, productId: pid, contextProductId: d.contextProductId, contextVersionId: d.contextVersionId, bindingId: binding.id, fileVersionId: file.id }; }
        afterEach(async () => { repo?.close(); if (dir)
            await rm(dir, { recursive: true, force: true }); });
        it('AC07-01/02 one exact file, two independent application histories; invoice never becomes certification', async () => {
            await setup();
            const src = await source(), second = (await products.create(brand, { contextId: A, brandId: 'brand-luna', common: { name: 'second', code: 'SECOND' }, idempotencyKey: randomUUID() })).ids[0];
            const result = await service.register(brand, { contextId: A, source: src, metadata: { ...blankEvidenceMetadata(), title: '갱신 청구서', documentType: 'renewal_invoice' }, productIds: ['product-serum', second], idempotencyKey: randomUUID() });
            let d = await service.detail(brand, result.ids[0]);
            expect(d.current.links).toHaveLength(2);
            const link = d.current.links[0];
            await service.command(admin, d.id, { command: 'assess', linkId: link.id, expectedLinkRevision: link.revision, status: 'application_confirmed', reason: '명시된 제품 목록 확인', idempotencyKey: randomUUID() });
            d = await service.detail(brand, d.id);
            expect(d.current.links[0].assessments[0].status).toBe('application_confirmed');
            expect(d.current.links[1].assessments).toHaveLength(0);
            expect(d.current.metadata.statedValidTo).toBeNull();
            expect(d.notice).toContain('인증 승인');
            expect(await repo.list('fileVersion')).toHaveLength(1);
            expect((await service.download(brand, d.id, d.current.id, link.id, 'download', dir)).bytes).toEqual(png);
            const old = await repo.get('evidenceVersion', d.current.id);
            await service.command(brand, d.id, { command: 'revise', expectedRevision: d.revision, source: src, metadata: { ...d.current.metadata, title: '새 자료 정보' }, productIds: ['product-serum', second], idempotencyKey: randomUUID() });
            const revised = await service.detail(brand, d.id);
            expect(revised.current.links.every(l => l.assessments.length === 0)).toBe(true);
            expect(await repo.get('evidenceVersion', old!.id)).toEqual(old);
            await expect(repo.transaction(s => s.update('evidenceVersion', old!.id, old!.revision, old!.data))).rejects.toMatchObject({ code: 'INVALID_RECORD' });
        });
        it('actual G05 producer drives canonical table/counts; standalone N/A never waives required response', async () => {
            await setup();
            const tasks = new TaskService(identity), sub = new SubmissionService(identity), uploads = new SubmissionFiles(identity, dir), content = { ...blankContent(), title: '자료 요청', description: '합성 자료 제출 요청', deadline: { ...blankContent().deadline, responsibleUserId: 'user-gsg' }, requirements: [{ ...blankRequirement('doc', 'file'), label: '문서', productIds: ['product-serum'], specifications: [{text:'서명 내용 확인',source:'합성 요청',version:'1',severity:'required' as const,check:'human' as const}] }, { ...blankRequirement('text', 'short_text'), label: '일반 답변' }] };
            const taskId = (await tasks.create(admin, { targets: [{ contextId: A, ownerId: 'user-gsg', assigneeId: 'user-luna', coAssigneeIds: [], productIds: ['product-serum'] }], content, category: 'spot', idempotencyKey: randomUUID() })).ids[0];
            await tasks.command(admin, taskId, { command: 'publish', expectedRevision: (await repo.get('task', taskId))!.revision, idempotencyKey: randomUUID() });
            let w = await sub.workspace(brand, taskId);
            const file = (await uploads.upload(brand, taskId, w.request.id, [{ clientItemId: randomUUID(), name: 'proof.png', type: 'image/png', bytes: png }])).items[0];
            if (file.state !== 'ready')
                throw new Error('fixture upload failed');
            const before = (await service.table(brand, A)).rows.find(r => r.productId === 'product-serum')!;
            expect(before.cells.filter(c => c.taskId === taskId && c.status === 'missing')).toHaveLength(2);
            expect((await service.sources(brand, A)).items.some(c => c.source.fileVersionId === file.file.id)).toBe(false);
            const pd = await products.detail(brand, 'product-serum', A);
            const draft = { ...blankDraft(), productSelections: [{ productId: pd.productId, expectedCommonRevision: pd.commonRevision, expectedContextRevision: pd.contextRevision, bindingIds: [], retailPriceVersionId: null, asOfDate: '2026-09-21' }], answers: [{ requestId: w.request.id, requirementKey: 'doc', productId: 'product-serum', type: 'file' as const, input: { fileVersionIds: [file.file.id] } }] };
            await sub.draft(brand, taskId, { command: 'save', baseRequestId: w.request.id, expectedDraftRevision: 0, content: draft, idempotencyKey: randomUUID() });
            w = await sub.workspace(brand, taskId);
            const submissionId = (await sub.submit(brand, taskId, { baseRequestId: w.request.id, expectedDraftRevision: w.draft!.revision, expectedTaskRevision: w.taskRevision, mode: 'partial', idempotencyKey: randomUUID() })).ids[0];
            const source = { kind: 'submission' as const, taskId, requestId: w.request.id, submissionId, requirementKey: 'doc', productId: 'product-serum', fileVersionId: file.file.id }, registered = await service.register(brand, { contextId: A, source, metadata: { ...blankEvidenceMetadata(), title: '질문지', documentType: 'questionnaire' }, productIds: ['product-serum'], idempotencyKey: randomUUID() }), d = await service.detail(brand, registered.ids[0]), link = d.current.links[0];
            await service.command(admin, d.id, { command: 'assess', linkId: link.id, expectedLinkRevision: link.revision, status: 'not_applicable', reason: '별도 상품 적용 미확인', idempotencyKey: randomUUID() });
            let row = (await service.table(brand, A)).rows.find(r => r.productId === 'product-serum')!;
            expect(row.cells.find(c => c.taskId === taskId && c.requirementKey === 'doc')!.status).toBe('content_confirmation');
            expect(row.cells.find(c => c.taskId === taskId && c.requirementKey === 'text')!.status).toBe('missing');
            expect((await products.detail(brand, 'product-serum', A)).materialCounts).toEqual(row.counts);
            expect(row.cells.find(c => c.taskId === taskId && c.requirementKey === 'doc')!.submissionUrl).toContain(submissionId);
            const emitted = row.cells.find(c => c.taskId === taskId && c.requirementKey === 'doc')!;
            expect([...new URL(emitted.requestUrl,'http://local').searchParams.keys()]).toEqual(['context']);
            const historical = new URL(emitted.submissionUrl!,'http://local').searchParams;
            expect(['context','requestId','submissionId','requirementKey','productId'].every(k=>historical.has(k))).toBe(true);
            const pendingCount = row.counts.unconfirmed;
            let currentLink = (await service.detail(admin, d.id)).current.links[0];
            await service.command(admin,d.id,{command:'assess',linkId:link.id,expectedLinkRevision:currentLink.revision,status:'application_confirmed',reason:'상품 관계만 확인',idempotencyKey:randomUUID()});
            row=(await service.table(brand,A)).rows.find(r=>r.productId==='product-serum')!;
            expect(row.cells.find(c=>c.taskId===taskId&&c.requirementKey==='doc')!.status).toBe('content_confirmation');
            expect(row.counts.unconfirmed).toBe(pendingCount);
            const missingBefore=row.counts.missing;
            currentLink=(await service.detail(admin,d.id)).current.links[0];
            await service.command(admin, d.id, { command: 'assess', linkId: link.id, expectedLinkRevision: currentLink.revision, status: 'correction_needed', reason: '서명 보완 필요', idempotencyKey: randomUUID() });
            row = (await service.table(brand, A)).rows.find(r => r.productId === 'product-serum')!;
            expect(row.cells.find(c => c.taskId === taskId && c.requirementKey === 'doc')!.status).toBe('correction_needed');
            expect(row.counts.unconfirmed).toBe(pendingCount-1);
            expect(row.counts.missing).toBe(missingBefore+1);
            expect((await sub.workspace(brand, taskId)).submittedEvaluation!.evaluation.missing).toBe(1);
        });
        it('fresh scope/current file authorization, assessment role, CAS, and late rollback enforced', async () => {
            await setup();
            const src = await source(), input = { contextId: A, source: src, metadata: { ...blankEvidenceMetadata(), title: '서명 질문지', documentType: 'signed_questionnaire' }, productIds: ['product-serum'], idempotencyKey: randomUUID() };
            await expect(new EvidenceService(identity, () => { throw new Error('fault'); }).register(brand, input)).rejects.toThrow('fault');
            expect(await repo.list('evidence')).toHaveLength(0);
            const result = await service.register(brand, input), d = await service.detail(brand, result.ids[0]), link = d.current.links[0];
            await expect(service.command(brand, d.id, { command: 'assess', linkId: link.id, expectedLinkRevision: link.revision, status: 'application_confirmed', reason: '확인', idempotencyKey: randomUUID() })).rejects.toMatchObject({ status: 403 });
            await expect(service.command(admin, d.id, { command: 'unlink', linkId: link.id, expectedLinkRevision: 999, idempotencyKey: randomUUID() })).rejects.toMatchObject({ status: 409 });
            await expect(service.detail(tokenFor('user-wave'), d.id)).rejects.toMatchObject({ status: 404 });
            await repo.transaction(s => { const m = s.list('membership', A).find(m => m.data.userId === 'user-luna')!; s.update('membership', m.id, m.revision, { ...m.data, status: 'suspended' }); });
            await expect(service.register(brand, input)).rejects.toMatchObject({ status: 404 });
            await expect(service.download(brand, d.id, d.current.id, link.id, 'download', dir)).rejects.toMatchObject({ status: 404 });
        });
    });
