import { afterEach, describe, it, expect } from "vitest";
import { createMockRepository } from "@/server/repositories/mock";
import { createSqliteRepository } from "@/server/repositories/sqlite";
import { openDatabase, migrate } from "@/server/db/database";
import { seed } from "@/server/db/seed";
import { IdentityService } from "@/server/auth/service";
import { DEMO_PASSWORD } from "@/domain/catalog";
import type { RecordRepository } from "@/domain/records";
const ctx = "ctx-jp-a-luna", ctx2 = "ctx-jp-b-luna";
for (const mode of ["mock", "sqlite"] as const)
    describe(`${mode} G01 identity contract`, () => {
        let repo: RecordRepository;
        let now = "2026-09-21T00:00:00.000Z";
        let service: IdentityService;
        async function setup(fault?: (operation: string) => void) { now = "2026-09-21T00:00:00.000Z"; if (mode === "mock")
            repo = createMockRepository(() => now);
        else {
            const db = openDatabase(":memory:", true);
            migrate(db);
            repo = createSqliteRepository(db, () => now);
        } await seed(repo); service = new IdentityService(repo, () => now, fault); return (await service.login(undefined, { email: "admin@example.test", password: DEMO_PASSWORD })).token; }
        const login = (email = "luna@example.test") => service.login(undefined, { email, password: DEMO_PASSWORD });
        afterEach(() => repo?.close());
        it("creates distinct combinations/events, rejects blank/unknown references and concurrent duplicates", async () => { const t = await setup(); const input = { type: "retail", countryId: "KR", retailerId: "retailer-a", brandId: "brand-luna" }; const result = await Promise.allSettled([service.createContext(t, input), service.createContext(t, input)]); expect(result.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(result.filter(r => r.status === "rejected")).toHaveLength(1); for (const field of ["countryId", "retailerId", "brandId"])
            await expect(service.createContext(t, { ...input, [field]: " " })).rejects.toMatchObject({ status: 422 }); await expect(service.createContext(t, { ...input, brandId: "unknown" })).rejects.toMatchObject({ status: 422 }); const event = await service.createContext(t, { type: "event", countryId: "KR", brandId: "brand-luna", eventName: "독립 행사" }); expect(event.data.retailerId).toBeNull(); expect(event.data.retailer).toBe("리테일러 미지정"); await expect(service.createContext(t, { type: "event", countryId: "JP", brandId: "brand-luna", eventName: " " })).rejects.toMatchObject({ status: 422 }); });
        it("creates country, retailer and brand variants as distinct contexts", async () => { const t = await setup(); const inputs = [{ countryId: "KR", retailerId: "retailer-c", brandId: "brand-new" }, { countryId: "SG", retailerId: "retailer-c", brandId: "brand-new" }, { countryId: "KR", retailerId: "retailer-b", brandId: "brand-new" }, { countryId: "KR", retailerId: "retailer-c", brandId: "brand-luna" }]; const created = []; for (const input of inputs)
            created.push(await service.createContext(t, { type: "retail", ...input })); expect(new Set(created.map(c => c.id)).size).toBe(4); expect(new Set(created.map(c => c.data.combinationKey)).size).toBe(4); for (const field of ["countryId", "retailerId", "brandId"])
            for (const value of [undefined, null, "", " "])
                await expect(service.createContext(t, { type: "retail", ...inputs[0], [field]: value })).rejects.toMatchObject({ status: 422 }); });
        it("requires actual credentials and explicit admin scope, never client role", async () => { await setup(); await expect(service.login(undefined, { email: "admin@example.test", password: "invalid-password-value" })).rejects.toMatchObject({ status: 401 }); const ops = await login("operator@example.test"); expect((await service.me(ops.token)).contexts.map(c => c.id)).toEqual([ctx]); await expect(service.createContext(ops.token, { type: "retail", countryId: "KR", retailerId: "retailer-a", brandId: "brand-luna" })).rejects.toMatchObject({ status: 403 }); const selected = await login("selected@example.test"); await expect(service.members(selected.token, ctx2)).rejects.toMatchObject({ status: 404 }); await expect(service.me("forged-cookie")).rejects.toMatchObject({ status: 401 }); await expect(login("suspended@example.test")).rejects.toMatchObject({ status: 401 }); });
        it("keeps one identity across memberships; existing account requires matching login and keeps credential", async () => { const t = await setup(); const before = await repo.list("credential"); const inv = await service.invite(t, "ctx-event-luna", { email: " LUNA@EXAMPLE.TEST ", name: "same", role: "brand" }); expect(inv.userId).toBe("user-luna"); await expect(service.accept(undefined, { token: inv.token })).rejects.toMatchObject({ status: 401 }); const other = await login("wave@example.test"); await expect(service.accept(other.token, { token: inv.token })).rejects.toMatchObject({ status: 403 }); const correct = await login(); await service.accept(correct.token, { token: inv.token }); expect((await repo.list("user")).filter(u => u.data.normalizedEmail === "luna@example.test")).toHaveLength(1); expect((await repo.list("membership")).filter(m => m.data.userId === "user-luna")).toHaveLength(3); expect(await repo.list("credential")).toEqual(before); });
        it("new invitation creates password and membership atomically; replay/race accepts once", async () => { const t = await setup(); const inv = await service.invite(t, ctx, { email: "new@example.test", name: "new", role: "brand" }); expect((await repo.get("user", inv.userId))?.data.status).toBe("invited"); const results = await Promise.allSettled([service.accept(undefined, { token: inv.token, password: DEMO_PASSWORD }), service.accept(undefined, { token: inv.token, password: DEMO_PASSWORD })]); expect(results.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(results.filter(r => r.status === "rejected")).toHaveLength(1); const logged = await login("new@example.test"); expect((await service.me(logged.token)).contexts.map(c => c.id)).toEqual([ctx]); expect((await repo.list("credential")).filter(c => c.data.userId === inv.userId)).toHaveLength(1); expect(JSON.stringify(await repo.list("audit"))).not.toContain(inv.token); expect(JSON.stringify(await repo.list("credential"))).not.toContain(DEMO_PASSWORD); });
        it("email normalization preserves plus/dot differences and duplicate pending invites have one identity", async () => { const t = await setup(); await service.invite(t, ctx, { email: " A+tag@example.test ", name: "tag", role: "brand" }); await service.invite(t, ctx, { email: "a@example.test", name: "base", role: "brand" }); const invitations = await Promise.allSettled([service.invite(t, ctx, { email: "dupe@example.test", name: "dupe", role: "brand" }), service.invite(t, ctx, { email: " DUPE@EXAMPLE.TEST ", name: "dupe", role: "brand" })]); expect(invitations.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(invitations.filter(r => r.status === "rejected")).toHaveLength(1); const first = invitations.find(r => r.status === "fulfilled")! as PromiseFulfilledResult<Awaited<ReturnType<IdentityService["invite"]>>>; await service.accept(undefined, { token: first.value.token, password: DEMO_PASSWORD }); expect((await repo.list("user")).filter(u => u.data.normalizedEmail === "dupe@example.test")).toHaveLength(1); expect((await repo.list("user")).filter(u => ["a+tag@example.test", "a@example.test"].includes(u.data.normalizedEmail ?? ""))).toHaveLength(2); });
        it("expiry boundary, reissue and cancelled token cannot activate a user", async () => { const t = await setup(); const inv = await service.invite(t, ctx, { email: "expiry@example.test", name: "expiry", role: "brand" }); const fresh = await service.reissue(t, inv.id, { expectedRevision: 1 }); await expect(service.reissue(t, inv.id, { expectedRevision: 2 })).rejects.toMatchObject({ status: 409 }); await expect(service.accept(undefined, { token: inv.token, password: DEMO_PASSWORD })).rejects.toMatchObject({ status: 410 }); now = fresh.expiresAt; await expect(service.accept(undefined, { token: fresh.token, password: DEMO_PASSWORD })).rejects.toMatchObject({ status: 410 }); expect((await repo.get("user", inv.userId))?.data.status).toBe("invited"); expect((await repo.list("credential")).some(c => c.data.userId === inv.userId)).toBe(false); });
        it("suspended accounts cannot be activated by invitations", async () => { const t = await setup(); await expect(service.invite(t, ctx2, { email: "suspended@example.test", name: "x", role: "brand" })).rejects.toMatchObject({ status: 409 }); await expect(service.invite(t, ctx, { email: "external@example.test", name: "x", role: "external" })).rejects.toMatchObject({ status: 422 }); });
        it("account suspension invalidates old sessions, retains author and flags assignments; reactivation does not restore sessions", async () => { const t = await setup(); const brand = await login(); const user = await repo.get("user", "user-luna"); const task = await repo.get("task", "task-onboarding"); await service.setUserStatus(t, "user-luna", { expectedRevision: user!.revision, status: "suspended" }); await expect(service.me(brand.token)).rejects.toMatchObject({ status: 401 }); expect((await repo.get("task", task!.id))?.data).toMatchObject({ authorId: "user-luna", assigneeId: "user-luna", assignmentNeedsAttention: true }); const stopped = await repo.get("user", "user-luna"); await service.setUserStatus(t, "user-luna", { expectedRevision: stopped!.revision, status: "active" }); await expect(service.me(brand.token)).rejects.toMatchObject({ status: 401 }); await expect(login()).resolves.toHaveProperty("token"); });
        it("membership suspension removes only one context and rejects old-session contextual access", async () => { const t = await setup(); const brand = await login(); const member = (await repo.list("membership", ctx)).find(m => m.data.userId === "user-luna")!; await service.setMembership(t, ctx, member.id, { expectedRevision: member.revision, status: "suspended" }); expect((await service.me(brand.token)).contexts.map(c => c.id)).toEqual([ctx2]); await expect(service.members(brand.token, ctx)).rejects.toMatchObject({ status: 404 }); expect((await repo.get("user", "user-luna"))?.data.status).toBe("active"); });
        it("reassignment enforces active context member, CAS, immutable author and audit", async () => { const t = await setup(); const task = (await repo.get("task", "task-onboarding"))!; for (const userId of ["user-wave", "user-suspended", "user-gsg"])
            await expect(service.reassign(t, ctx, { taskId: task.id, toUserId: userId, expectedRevision: task.revision })).rejects.toMatchObject({ status: 422 }); const changed = await service.reassign(t, ctx, { taskId: task.id, toUserId: "user-co", expectedRevision: task.revision }); expect(changed.data).toMatchObject({ assigneeId: "user-co", authorId: "user-luna" }); await expect(service.reassign(t, ctx, { taskId: task.id, toUserId: "user-team", expectedRevision: task.revision })).rejects.toMatchObject({ code: "CONFLICT" }); expect((await repo.list("audit")).filter(a => a.data.action === "task.reassigned")).toHaveLength(1); });
        it("invitation, activation, suspension and reassignment failures roll back writes and audit", async () => { const t = await setup(); const broken = new IdentityService(repo, () => now, () => { throw new Error("injected rollback"); }); const before = JSON.stringify(await repo.list("user")); await expect(broken.invite(t, ctx, { email: "rollback@example.test", name: "rollback", role: "brand" })).rejects.toThrow("injected"); expect(JSON.stringify(await repo.list("user"))).toBe(before); const inv = await service.invite(t, ctx, { email: "acceptfail@example.test", name: "acceptfail", role: "brand" }); await expect(broken.accept(undefined, { token: inv.token, password: DEMO_PASSWORD })).rejects.toThrow("injected"); expect((await repo.get("user", inv.userId))?.data.status).toBe("invited"); const brand = await login(); await expect(broken.setUserStatus(t, "user-luna", { expectedRevision: 1, status: "suspended" })).rejects.toThrow("injected"); await expect(service.me(brand.token)).resolves.toHaveProperty("user"); const task = (await repo.get("task", "task-onboarding"))!; await expect(broken.reassign(t, ctx, { taskId: task.id, toUserId: "user-co", expectedRevision: task.revision })).rejects.toThrow("injected"); expect(await repo.get("task", task.id)).toEqual(task); expect((await repo.list("audit")).filter(a => ["user.status", "task.reassigned"].includes(a.data.action))).toHaveLength(0); });
        it("rejects stopping an invited membership and reassigns stopped GSG ownership without rewriting author", async () => { const t = await setup(); const invited = (await repo.list("membership", ctx)).find(m => m.data.status === "invited")!; await expect(service.setMembership(t, ctx, invited.id, { status: "suspended", expectedRevision: invited.revision })).rejects.toMatchObject({ status: 409 }); expect((await repo.get("membership", invited.id))?.data.status).toBe("invited"); const ops = (await repo.get("user", "user-gsg"))!; await service.setUserStatus(t, ops.id, { status: "suspended", expectedRevision: ops.revision }); const task = (await repo.get("task", "task-onboarding"))!; expect(task.data.assignmentNeedsAttention).toBe(true); const changed = await service.reassign(t, ctx, { taskId: task.id, toUserId: "user-price", assignmentRole: "gsg", expectedRevision: task.revision }); expect(changed.data).toMatchObject({ ownerId: "user-price", assigneeId: "user-luna", authorId: "user-luna", assignmentNeedsAttention: false }); });
        it("enforces 15m pre-auth, 8h absolute session, CSRF and logout", async () => { await setup(); const pre = await service.csrf(); await service.checkCsrf(pre.token, pre.csrfToken); await expect(service.checkCsrf(pre.token, "wrong")).rejects.toMatchObject({ status: 403 }); now = new Date(Date.parse(now) + 15 * 60000).toISOString(); await expect(service.checkCsrf(pre.token, pre.csrfToken)).rejects.toMatchObject({ status: 403 }); const brand = await login(); now = brand.expiresAt; await expect(service.me(brand.token)).rejects.toMatchObject({ status: 401 }); const again = await login(); await service.logout(again.token); await expect(service.me(again.token)).rejects.toMatchObject({ status: 401 }); });
        it("never activates an unknown legacy account even when its ID collides with a new G01 fixture", async () => {
        if (mode === "mock") repo = createMockRepository(); else { const db = openDatabase(":memory:", true); migrate(db); repo = createSqliteRepository(db); }
        await repo.transaction(s => s.create("user", {id:"user-admin",contextId:null,data:{name:"legacy",email:"legacy@example.test",role:"gsg"}}));
        await seed(repo);
        const legacy = await repo.get("user", "user-admin");
        expect(legacy?.data.status).toBeUndefined(); expect(legacy?.data.adminGrant).toBeUndefined();
        await expect(new IdentityService(repo).login(undefined,{email:"legacy@example.test",password:DEMO_PASSWORD})).rejects.toMatchObject({status:401});
    });
    it("rate limiting and database relation checks fail closed", async () => { await setup(); for (let i = 0; i < 20; i++)
            expect(await service.throttle("test-key")).toBe(true); expect(await service.throttle("test-key")).toBe(false); await expect(repo.transaction(s => s.create("membership", { id: "invalid", contextId: "unknown", data: { userId: "user-luna", role: "brand", status: "active", scope: "", internalPriceAccess: false, activatedAt: now, suspendedAt: null } }))).rejects.toMatchObject({ code: "INVALID_RECORD" }); });
    });
