/* eslint-disable @next/next/no-img-element -- Private file endpoints need the browser authentication cookie. */
"use client";
import Link from "next/link";
import {useState} from "react";
import type {ProductDetail,ProductImpact} from "@/server/products/service";
import type {ProductCommon,ProductFileBinding} from "@/domain/products/types";
import {blankRetailPrice,blankInternalPrice} from "@/domain/products/types";
import {request,useCommand} from "@/features/tasks/client";
import {taskLabels} from "@/components/workspace";
import {CommonFields,ContextFields,PriceFields,InternalFields,Select} from "./fields";
import {CommonView,ContextView,PriceView,BindingView,PendingEvidence,Pairs,salesLabels,registrationLabels} from "./views";
import {Editor} from "./editor";
import {FileFields,bindingInput} from "./files";
import s from "@/features/tasks/ui.module.css";
import p from "./ui.module.css";
function Diff({changes}:{changes:ProductImpact['changes']}){return changes.length?<table className={p.table}><thead><tr><th>항목</th><th>변경 전</th><th>변경 후</th></tr></thead><tbody>{changes.map(c=><tr key={c.field}><td>{c.field}</td><td>{typeof c.before==='string'?c.before:JSON.stringify(c.before)}</td><td>{typeof c.after==='string'?c.after:JSON.stringify(c.after)}</td></tr>)}</tbody></table>:<p>변경된 공통 항목이 없습니다.</p>;}
function Impact({detail:d,common,revision}:{detail:ProductDetail;common:ProductCommon;revision:number}){const [result,setResult]=useState<ProductImpact|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function show(){setError('');setBusy(true);try{setResult(await request<ProductImpact>(`/api/products/${d.productId}/impact`,{contextId:d.context.id,common,expectedCommonRevision:revision}));}catch(e){setError(e instanceof Error?e.message:'변경 영향을 읽지 못했습니다.');}finally{setBusy(false);}}return <div><button className="button subtle" type="button" disabled={busy} onClick={()=>void show()}>공통 변경 영향 확인</button>{error&&<p role="alert" className={s.error}>{error}</p>}{result&&<section className={p.version}><h3>변경 영향 미리보기</h3><p>{result.sharedCommonNotice}</p><p>열람 가능한 적용 범위: {result.visibleContexts.map(c=>`${c.data.country} / ${c.data.retailer} / ${c.data.brand}`).join(' · ')}</p><Diff changes={result.changes}/><p className={s.hint}>이 미리보기는 저장하지 않습니다. 입력을 바꿨다면 다시 확인할 수 있습니다.</p></section>}</div>;}
function History({detail:d}:{detail:ProductDetail}){return <section id="history" className={s.panel}><h2>상품·자료 변경 이력</h2><h3>공통 상품 버전</h3>{d.commonHistory.map(v=><details className={p.version} key={v.id}><summary>공통 v{v.sequence} · {v.changedByLabel} · {v.changedAt}</summary><p>출처: {v.source} · {v.archived?'보관':'사용 중'}</p><p className={s.hint}>정확 상품 버전 {v.id}</p><Diff changes={v.changes}/><CommonView value={v.common}/></details>)}<h3>컨텍스트·파일 버전</h3>{d.contextHistory.map(v=><details className={p.version} key={v.id}><summary>컨텍스트 v{v.sequence} · {v.changedByLabel} · {v.changedAt}</summary><p>출처: {v.source}</p><p className={s.hint}>정확 컨텍스트 버전 {v.id}</p><ContextView value={v.fields}/>{v.files.map(b=><BindingView key={b.id} binding={b}/>)}</details>)}<h3>소비자가 이력</h3>{d.retail.history.length?d.retail.history.map(v=><details className={p.version} key={v.id}><summary>소비자가 v{v.sequence} · {v.changedByLabel} · {v.changedAt}</summary><PriceView value={v.fields}/><p className={s.hint}>가격 버전 {v.id} · 기록 출처 {v.source}</p></details>):<p>등록된 소비자가 이력이 없습니다.</p>}{d.internal&&<><h3>내부 가격 이력</h3>{d.internal.history.length?d.internal.history.map(v=><details className={p.version} key={v.id}><summary>내부 가격 v{v.sequence} · {v.changedByLabel} · {v.changedAt}</summary><PriceView value={v.fields}/><p className={s.hint}>가격 버전 {v.id} · 기록 출처 {v.source}</p></details>):<p>등록된 내부 가격 이력이 없습니다.</p>}</>}</section>;}
function Uses({detail:d}:{detail:ProductDetail}) {return <section className={s.panel}><h2>당시 사용된 상품 정보</h2><p className={s.notice}>{d.useConnection.message} 아래 계약 예시는 실제 제출 실적과 구별합니다.</p>{d.uses.length?d.uses.map(u=><details className={p.version} key={u.id}><summary>{u.producer==='prior_use_fixture'?'합성 사용본 계약 예시':u.producer} · {u.capturedAt}</summary><Pairs items={[["현재 상품과 별개인 사용본",u.id],["상품 버전",u.productVersionId],["컨텍스트 버전",u.contextProductVersionId],["소비자가 버전",u.retailPriceVersionId],["기준일",u.retailSelection.asOfDate],["내용 해시",u.contentHash],["파일 연결 해시",u.fileBindingHash]]}/><CommonView value={u.common}/><ContextView value={u.context}/>{u.retailPrice&&<PriceView value={u.retailPrice}/>}<h3>당시 파일 버전</h3>{u.files.map(f=><Pairs key={f.fileVersionId} items={[["파일 버전",f.fileVersionId],["해시",f.sha256],["제목",f.binding.title],["문서 유형",f.binding.documentType],["출처",f.binding.source]]}/>)}{u.taskId&&<Link className={s.link} href={`/tasks/${u.taskId}?context=${d.context.id}`}>관련 업무 보기 ↗</Link>}</details>):<p>연결된 사용본이 없습니다.</p>}</section>;}
export function ProductDetailScreen({initial}:{initial:ProductDetail}){
 const [d,setDetail]=useState(initial),[linkContext,setLinkContext]=useState(''),[taskId,setTaskId]=useState('');const action=useCommand(),url=`/api/products/${d.productId}`;
 const reload=async()=>{const next=await request<ProductDetail>(`${url}?context=${d.context.id}`);setDetail(next);};
 const commonArgs={detail:d,onData:setDetail};
 function filesRead(bindings:ProductFileBinding[]){return bindings.length?bindings.map(b=>{const file=[...d.files.map(f=>f.file),...d.reusableFiles].find(f=>f.id===b.fileVersionId);return file?<BindingView key={b.id} binding={{...b,file}}/>:<Pairs key={b.id} items={[["자료 제목",b.title],["파일 버전",b.fileVersionId]]}/>;}):<p>연결된 자료가 없습니다.</p>;}
 return <div className={s.stack}><Link className="back-link" href={`/products?context=${d.context.id}`}>← 상품 목록</Link><section className={p.context} aria-label="상품 컨텍스트"><strong>{d.context.data.country} / {d.context.data.retailer} / {d.context.data.brand}</strong><span>{d.archived?'보관':salesLabels[d.local.salesStatus]} · {registrationLabels[d.local.registrationStatus]}</span>{d.visibleContexts.map(c=><Link key={c.id} className={s.link} href={`/products/${d.productId}?context=${c.id}`}>{c.data.retailer} 보기 ↗</Link>)}</section><header className={s.heading}><div><p className="eyebrow">PRODUCT RECORD</p><h1>{d.common.name}</h1><p>{d.common.code} {d.common.temporaryCode?'· 임시 코드':''} · {d.context.data.brand}</p></div>{d.image&&<img className={p.media} src={d.image.originalUrl} alt={`${d.common.name} 상품 이미지`}/>}</header><nav className={p.tabs} aria-label="상품 상세 영역">{[['common','공통 정보'],['local','컨텍스트'],['retail','소비자가'],['files','자료'],['tasks','관련 업무'],['history','변경 이력'],['evidence','증빙·Excel']].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>
 <Editor {...commonArgs} id="common" title="브랜드 공통 정보" allowed={d.capabilities.editCommon} initial={initial.common} initialRevision={initial.commonRevision} command="save_common" field="common" revisionField="expectedCommonRevision" pick={x=>({value:x.common,revision:x.commonRevision})} read={v=><CommonView value={v}/>} notice={<><p className={s.notice}>{d.sharedCommonNotice}</p><p className={s.hint}>열람 가능한 적용 범위: {d.visibleContexts.map(c=>`${c.data.country}/${c.data.retailer}`).join(' · ')}</p></>} before={(v,r)=><Impact detail={d} common={v} revision={r}/>}>{(v,set)=><CommonFields value={v} onChange={set}/>}</Editor>
 <Editor {...commonArgs} id="local" title="컨텍스트 정보" allowed={d.capabilities.editContext} initial={initial.local} initialRevision={initial.contextRevision} command="save_context" field="fields" revisionField="expectedContextRevision" pick={x=>({value:x.local,revision:x.contextRevision})} read={v=><ContextView value={v}/>} notice={<p>현재 적용 범위: {d.context.data.country} / {d.context.data.retailer}. 판매 중단은 이 컨텍스트에만 반영됩니다.</p>}>{(v,set)=><ContextFields value={v} onChange={set} projects={d.projects}/>}</Editor>
 <Editor {...commonArgs} id="retail" title="소비자가" allowed={d.capabilities.editRetailPrice} initial={initial.retail.current?.fields??blankRetailPrice()} initialRevision={initial.retail.revision} command="save_retail" field="price" revisionField="expectedPriceRevision" pick={x=>({value:x.retail.current?.fields??blankRetailPrice(),revision:x.retail.revision})} read={v=><PriceView value={v}/>} notice={<p className={s.notice}>최근 기록한 가격입니다. 오늘 적용되는 가격을 자동으로 확정하지 않습니다. 적용 범위: {d.context.data.country} / {d.context.data.retailer}</p>}>{(v,set)=><PriceFields value={v} onChange={set}/>}</Editor>
 {d.internal&&d.capabilities.editInternalPrice&&<Editor {...commonArgs} id="internal" title="내부 공급 조건" allowed initial={initial.internal?.current?.fields??blankInternalPrice()} initialRevision={initial.internal?.revision??0} command="save_internal" field="price" revisionField="expectedPriceRevision" pick={x=>({value:x.internal?.current?.fields??blankInternalPrice(),revision:x.internal?.revision??0})} read={v=><PriceView value={v}/>} notice={<p>현재 컨텍스트에서 허용된 GSG만 볼 수 있습니다. 공개 행사 협찬비와 별도 항목입니다.</p>}>{(v,set)=><InternalFields value={v} onChange={set}/>}</Editor>}
 <Editor {...commonArgs} id="files" title="자료 연결" allowed={d.capabilities.editFiles} initial={initial.files.map(bindingInput)} initialRevision={initial.contextRevision} command="save_files" field="files" revisionField="expectedContextRevision" pick={x=>({value:x.files.map(bindingInput),revision:x.contextRevision})} read={filesRead} notice={<p className={s.notice}>{d.materialVerification.message} 원문에 없는 만료일이나 인증 승인을 만들지 않습니다.</p>}>{(v,set)=><FileFields detail={d} value={v} onChange={set}/>}</Editor>
 <section id="tasks" className={s.panel}><h2>관련 업무</h2>{d.linkedTasks.length?d.linkedTasks.map(t=><article className={p.version} key={t.id}><Link className={s.link} href={`/tasks/${t.id}?context=${d.context.id}`}>{t.data.title} ↗</Link><p>{taskLabels[t.data.status]} · {t.data.nextAction}</p></article>):<p>연결된 업무가 없습니다.</p>}{d.capabilities.linkTask&&!d.archived&&<><Link className="button" href={`/tasks/new?context=${d.context.id}&product=${d.productId}`}>이 상품으로 새 업무 만들기</Link><div className={s.actions}><Select label="연결할 기존 업무" value={taskId} onChange={setTaskId}><option value="">업무 선택</option>{d.taskChoices.map(t=><option value={t.id} key={t.id}>{t.title} · {taskLabels[t.status]}</option>)}</Select><button className="button subtle" disabled={action.busy||!taskId} onClick={()=>{const task=d.taskChoices.find(t=>t.id===taskId);if(task)void action.run(url,{contextId:d.context.id,command:'link_task',taskId,expectedTaskRevision:task.revision},async()=>{await reload();setTaskId('');},'기존 업무에 상품을 연결했습니다.');}}>기존 업무에 연결</button></div></>}{!d.capabilities.linkTask&&<p className={s.hint}>업무 생성·연결은 GSG 담당자가 진행합니다. 상품정보 편집과는 별도 권한입니다.</p>}</section>
 <History detail={d}/><Uses detail={d}/><section className={s.panel}><h2>적용 범위와 보관</h2>{d.linkedContextChoices.length>0&&!d.archived&&<div className={s.actions}><Select label="추가 연결 컨텍스트" value={linkContext} onChange={setLinkContext}><option value="">컨텍스트 선택</option>{d.linkedContextChoices.map(c=><option value={c.id} key={c.id}>{c.data.country} / {c.data.retailer} / {c.data.brand}</option>)}</Select><button className="button subtle" disabled={action.busy||!linkContext} onClick={()=>void action.run(url,{contextId:d.context.id,command:'link_context',targetContextId:linkContext,expectedCommonRevision:d.commonRevision},async()=>{await reload();setLinkContext('');},'컨텍스트를 연결했습니다. 파일·SKU·상태·가격은 별도로 등록하세요.')}>컨텍스트 연결</button></div>}<p>보관은 공통 상품의 논리 상태입니다. 기존 업무·자료·작성자·버전은 유지됩니다.</p>{d.capabilities.archive&&<button className="button subtle" disabled={action.busy} onClick={()=>void action.run(url,{contextId:d.context.id,command:d.archived?'restore':'archive',expectedCommonRevision:d.commonRevision},reload,d.archived?'상품을 복원했습니다.':'상품을 보관했습니다. 기존 이력은 유지됩니다.')}>{d.archived?'상품 복원':'상품 보관'}</button>}{action.error&&<p role="alert" className={s.error}>{action.error}</p>}{action.message&&<p role="status" className={s.success}>{action.message}</p>}</section><PendingEvidence/></div>;
}
