"use client";
import {useState,type ReactNode} from "react";
import type { ProductDetail } from "@/server/products/service";
import {request,useCommand} from "@/features/tasks/client";
import s from "@/features/tasks/ui.module.css";
import p from "./ui.module.css";
export type Refresh=(next:ProductDetail)=>void;
export function Editor<T>({id,title,detail,allowed,initial,initialRevision,command,field,revisionField,pick,onData,children,read,notice,before}: {id:string;title:string;detail:ProductDetail;allowed:boolean;initial:T;initialRevision:number;command:string;field:string;revisionField:string;pick:(d:ProductDetail)=>{value:T;revision:number};onData:Refresh;children:(value:T,set:(v:T)=>void)=>ReactNode;read:(value:T)=>ReactNode;notice?:ReactNode;before?:(v:T,revision:number)=>ReactNode}){
 const [value,setValue]=useState<T>(()=>structuredClone(initial)),[revision,setRevision]=useState(initialRevision),[baseValue,setBaseValue]=useState<T>(()=>structuredClone(initial)),[latest,setLatest]=useState<{value:T;revision:number}|null>(null),[loading,setLoading]=useState(false);const cmd=useCommand();const current=pick(detail);if(current.revision!==revision&&JSON.stringify(value)===JSON.stringify(baseValue)){setValue(structuredClone(current.value));setBaseValue(structuredClone(current.value));setRevision(current.revision);}const url=`/api/products/${detail.productId}`,get=()=>request<ProductDetail>(`${url}?context=${detail.context.id}`);
 async function compare(){setLoading(true);cmd.setError('');try{const next=await get();onData(next);setLatest(pick(next));}catch(e){cmd.setError(e instanceof Error?e.message:'최신 정보를 읽지 못했습니다. 입력은 유지됩니다.');}finally{setLoading(false);}}
 return <section id={id} className={`${s.panel} ${p.section}`}><h2>{title}</h2>{notice}{!allowed?read(initial):<form onSubmit={e=>{e.preventDefault();void cmd.run(url,{contextId:detail.context.id,command,[field]:value,[revisionField]:revision},async()=>{const next=await get(),saved=pick(next);onData(next);setValue(structuredClone(saved.value));setBaseValue(structuredClone(saved.value));setRevision(saved.revision);setLatest(null);},`${title}를 저장했습니다.`);}}><fieldset disabled={cmd.busy} className={p.fieldset}>{children(value,setValue)}{before?.(value,revision)}<div className={s.actions}><button className="button" type="submit">{cmd.busy?'저장 중…':`${title} 저장`}</button><button className="button subtle" type="button" disabled={loading} onClick={()=>void compare()}>{loading?'확인 중…':'최신 저장값 확인'}</button></div></fieldset>{cmd.error&&<p className={s.error} role="alert">{cmd.error} 작성한 입력은 유지됩니다.</p>}{cmd.message&&<p className={s.success} role="status">{cmd.message}</p>}{latest&&<div className={p.version}><h3>최신 저장값 · 비교 후 선택</h3><p>현재 입력은 바꾸지 않았습니다. 최신값과 비교한 뒤 적용 기준을 선택하세요.</p>{read(latest.value)}<div className={s.actions}><button className="button subtle" type="button" onClick={()=>{setRevision(latest.revision);setLatest(null);cmd.setMessage('입력은 유지했습니다. 검토한 내용을 저장 버튼으로 다시 적용하세요.');}}>입력 유지하고 최신 버전 기준 사용</button><button className="button subtle" type="button" onClick={()=>{setValue(structuredClone(latest.value));setBaseValue(structuredClone(latest.value));setRevision(latest.revision);setLatest(null);cmd.setMessage('입력을 최신 저장값으로 교체했습니다.');}}>입력을 최신 저장값으로 교체</button></div></div>}</form>}</section>;
}
