"use client";
import { useId, type ReactNode } from "react";
import type { ProductCommon, ProductContextFields, RetailPriceFields, InternalPriceFields } from "@/domain/products/types";
import s from "@/features/tasks/ui.module.css";
export function Field({label,value,onChange,area=false,type="text",required=false,hint}: {label:string;value:string|null;onChange:(v:string)=>void;area?:boolean;type?:string;required?:boolean;hint?:string}) {const id=useId();return <div className={s.field}><label htmlFor={id}>{label}{required?" *":""}</label>{area?<textarea id={id} value={value??""} onChange={e=>onChange(e.target.value)} required={required}/>:<input id={id} type={type} value={value??""} onChange={e=>onChange(e.target.value)} required={required}/>} {hint&&<span className={s.hint}>{hint}</span>}</div>;}
export function Select({label,value,onChange,children}: {label:string;value:string|null;onChange:(v:string)=>void;children:ReactNode}){const id=useId();return <div className={s.field}><label htmlFor={id}>{label}</label><select id={id} value={value??""} onChange={e=>onChange(e.target.value)}>{children}</select></div>;}
export const nullable=(v:string)=>v===""?null:v;
export function CommonFields({value:v,onChange:set,minimal=false}:{value:ProductCommon;onChange:(v:ProductCommon)=>void;minimal?:boolean}) {
 const top=(k:keyof ProductCommon,x:string)=>set({...v,[k]:x});
 return <div className={s.stack}><div className={s.grid}><Field label="상품명" value={v.name} onChange={x=>top("name",x)} required/><Field label="제품 코드" value={v.code} onChange={x=>top("code",x)} required hint="앞자리 0과 구분자를 유지합니다. 컨텍스트 안에서 중복을 검사합니다."/><label className={s.check}><input type="checkbox" checked={v.temporaryCode} onChange={e=>set({...v,temporaryCode:e.target.checked})}/>임시 제품 코드</label></div>{!minimal&&<>
 <fieldset className={s.sub}><legend>현지 표기</legend>{v.localNames.map((n,i)=><div className={s.grid} key={i}><Field label={`현지명 ${i+1} 언어`} value={n.language} onChange={x=>set({...v,localNames:v.localNames.map((a,j)=>i===j?{...a,language:x}:a)})}/><Field label={`현지명 ${i+1} 이름`} value={n.name} onChange={x=>set({...v,localNames:v.localNames.map((a,j)=>i===j?{...a,name:x}:a)})}/><button className="button subtle" type="button" onClick={()=>set({...v,localNames:v.localNames.filter((_,j)=>j!==i)})}>현지명 {i+1} 삭제</button></div>)}<button className="button subtle" type="button" onClick={()=>set({...v,localNames:[...v.localNames,{language:"",name:""}]})}>현지명 추가</button></fieldset>
 <div className={s.grid}><Field label="카테고리" value={v.category} onChange={x=>top("category",x)}/><Field label="용량값" value={v.capacity.amount} onChange={x=>set({...v,capacity:{...v.capacity,amount:nullable(x)}})} hint="미확인은 비워 두세요. 소수를 그대로 입력합니다."/><Field label="용량 단위" value={v.capacity.unit} onChange={x=>set({...v,capacity:{...v.capacity,unit:x}})}/><Field label="용량 원문" value={v.capacity.raw} onChange={x=>set({...v,capacity:{...v.capacity,raw:x}})}/>{([['color','색상'],['scent','향'],['other','기타 변형']] as const).map(([k,l])=><Field key={k} label={l} value={v.variants[k]} onChange={x=>set({...v,variants:{...v.variants,[k]:x}})}/>)}<Field label="제품 설명" area value={v.description} onChange={x=>top("description",x)}/><Field label="사용 방법" area value={v.usage} onChange={x=>top("usage",x)}/><Field label="원산지" value={v.originCountry} onChange={x=>top("originCountry",x)}/><Field label="제조사" value={v.manufacturer} onChange={x=>top("manufacturer",x)}/><Field label="제조 정보" area value={v.manufacturingDetails} onChange={x=>top("manufacturingDetails",x)}/></div>
 <fieldset className={s.sub}><legend>전성분</legend><div className={s.grid}><Field label="전성분 원문" area value={v.ingredients.text} onChange={x=>set({...v,ingredients:{...v.ingredients,text:x}})}/><Field label="성분 표기 언어" value={v.ingredients.language} onChange={x=>set({...v,ingredients:{...v.ingredients,language:x}})}/><Field label="성분 제출일" type="date" value={v.ingredients.submittedAt} onChange={x=>set({...v,ingredients:{...v.ingredients,submittedAt:nullable(x)}})}/><Field label="성분·제품 분류" value={v.ingredients.classification} onChange={x=>set({...v,ingredients:{...v.ingredients,classification:nullable(x)}})} hint="알 수 없으면 비워 둡니다. 상품명으로 분류를 추정하지 않습니다."/></div><p className={s.hint}>성분 파일은 자료 영역에서 정확한 파일 버전으로 연결합니다.</p></fieldset>
 <fieldset className={s.sub}><legend>포장·규격</legend><div className={s.grid}>{([['container','용기'],['packaging','패키지'],['label','라벨'],['box','박스'],['itf','ITF']] as const).map(([k,l])=><Field key={k} label={l} value={v.packaging[k]} onChange={x=>set({...v,packaging:{...v.packaging,[k]:x}})}/>)}</div></fieldset></>}</div>;
}
export function ContextFields({value:v,onChange:set,projects}:{value:ProductContextFields;onChange:(v:ProductContextFields)=>void;projects:{id:string;title:string}[]}){return <div className={s.grid}><Field label="컨텍스트 현지명" value={v.localName} onChange={x=>set({...v,localName:x})}/><Field label="현지 SKU" value={v.sku} onChange={x=>set({...v,sku:x})}/><Field label="JAN 바코드" value={v.jan} onChange={x=>set({...v,jan:x})}/><Select label="등록 상태" value={v.registrationStatus} onChange={x=>set({...v,registrationStatus:x as ProductContextFields['registrationStatus']})}>{Object.entries({unknown:'미확인',unregistered:'미등록',in_progress:'등록 진행',registered:'등록됨'}).map(([k,l])=><option value={k} key={k}>{l}</option>)}</Select><Select label="판매 상태" value={v.salesStatus} onChange={x=>set({...v,salesStatus:x as ProductContextFields['salesStatus']})}>{Object.entries({unknown:'미확인',planned:'출시 예정',selling:'판매 중',stopped:'판매 중단'}).map(([k,l])=><option value={k} key={k}>{l}</option>)}</Select><Select label="관련 입점 프로젝트" value={v.projectId} onChange={x=>set({...v,projectId:nullable(x)})}><option value="">연결 없음</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</Select><Select label="출시 날짜 정밀도" value={v.launchDate.precision} onChange={x=>set({...v,launchDate:{...v.launchDate,precision:x as 'date'|'datetime'}})}><option value="date">날짜</option><option value="datetime">날짜와 시각</option></Select><Field label="출시일" type={v.launchDate.precision==='date'?'date':'text'} value={v.launchDate.value} onChange={x=>set({...v,launchDate:{...v.launchDate,value:nullable(x)}})} hint={v.launchDate.precision==='datetime'?'예: 2026-10-01T09:00:00+09:00. 시각에는 오프셋과 시간대가 필요합니다.':'미정이면 비워 둡니다.'}/><Select label="출시일 확정 수준" value={v.launchDate.certainty} onChange={x=>set({...v,launchDate:{...v.launchDate,certainty:x as ProductContextFields['launchDate']['certainty']}})}><option value="unknown">미확인</option><option value="expected">예정</option><option value="confirmed">확정</option></Select><Field label="출시 시간대" value={v.launchDate.timezone} onChange={x=>set({...v,launchDate:{...v.launchDate,timezone:nullable(x)}})} hint="예: Asia/Tokyo"/><Field label="출시 정보 출처" value={v.launchDate.source} onChange={x=>set({...v,launchDate:{...v.launchDate,source:x}})}/><Field label="출시일 원문" value={v.launchDate.raw} onChange={x=>set({...v,launchDate:{...v.launchDate,raw:x}})}/></div>;}
export function PriceFields({value:v,onChange:set}:{value:RetailPriceFields;onChange:(v:RetailPriceFields)=>void}) {return <div className={s.grid}><Field label="소비자가" value={v.amount} onChange={x=>set({...v,amount:nullable(x)})} hint="0은 실제 금액입니다. 미확인은 비워 둡니다."/><PriceBasics value={v} onChange={set}/></div>;}
function PriceBasics<T extends RetailPriceFields|InternalPriceFields>({value:v,onChange:set}:{value:T;onChange:(v:T)=>void}){return <><Field label="통화" value={v.currency} onChange={x=>set({...v,currency:nullable(x)})} hint="예: JPY, KRW. 적용 국가·리테일러는 현재 컨텍스트입니다."/><Select label="세금 포함 여부" value={v.taxIncluded} onChange={x=>set({...v,taxIncluded:x as T['taxIncluded']})}><option value="unknown">미확인</option><option value="yes">포함</option><option value="no">별도</option></Select><Field label="가격 적용 시작일" type="date" value={v.effectiveFrom} onChange={x=>set({...v,effectiveFrom:nullable(x)})}/><Field label="가격 적용 종료일" type="date" value={v.effectiveTo} onChange={x=>set({...v,effectiveTo:nullable(x)})}/><Field label="가격 출처" value={v.source} onChange={x=>set({...v,source:x})}/></>;}
export function InternalFields({value:v,onChange:set}:{value:InternalPriceFields;onChange:(v:InternalPriceFields)=>void}){return <div className={s.grid}><Field label="내부 공급가" value={v.supplyAmount} onChange={x=>set({...v,supplyAmount:nullable(x)})}/><Field label="내부 공급률" value={v.supplyRate} onChange={x=>set({...v,supplyRate:nullable(x)})}/><Select label="공급률 단위" value={v.rateUnit} onChange={x=>set({...v,rateUnit:x===''?null:x as 'ratio'|'percent'})}><option value="">미확인</option><option value="ratio">비율 (예: 0.4)</option><option value="percent">퍼센트 (예: 40)</option></Select><Field label="공급률 기준" value={v.rateBasis} onChange={x=>set({...v,rateBasis:x})}/><PriceBasics value={v} onChange={set}/></div>;}
