import Link from "next/link";
import type { ProductList,ProductListQuery } from "@/server/products/service";
import { ProductGrid,PendingEvidence,salesLabels } from "./views";
import s from "@/features/tasks/ui.module.css";
import p from "./ui.module.css";
export function ProductListScreen({data:d,query:q}:{data:ProductList;query:ProductListQuery}) {
 const options=(key:'country'|'retailer'|'brand')=>Array.from(new Map(d.contexts.map(c=>[c.data[`${key}Id`],c.data[key]])).entries());
 const href=(page:number)=>{const params=new URLSearchParams(Object.entries(q).filter((entry):entry is [string,string]=>typeof entry[1]==='string'));params.set('page',String(page));return `/products?${params}`;};
 return <div className={s.stack}><header className={s.heading}><div><p className="eyebrow">PRODUCT LIBRARY</p><h1>상품정보</h1><p>브랜드 공통 정보와 컨텍스트별 유통·자료를 관리합니다.</p></div>{d.contexts.length>0&&<Link className="button" href={`/products/new${q.context?`?context=${q.context}`:''}`}>상품 등록</Link>}</header>
 <form method="get" className={s.panel}><div className={s.grid}><label className={s.field}>조회 컨텍스트<select name="context" defaultValue={q.context??''}><option value="">허용된 전체 컨텍스트</option>{d.contexts.map(c=><option key={c.id} value={c.id}>{c.data.country} / {c.data.retailer} / {c.data.brand}</option>)}</select></label>{(['country','retailer','brand'] as const).map(k=><label key={k} className={s.field}>{({country:'국가',retailer:'리테일러',brand:'브랜드'})[k]}<select name={k} defaultValue={q[k]??''}><option value="">전체</option>{options(k).map(([id,label])=>id?<option key={id} value={id}>{label}</option>:null)}</select></label>)}<label className={s.field}>상품명·제품 코드 검색<input name="q" defaultValue={q.q??''}/></label><label className={s.field}>SKU 검색<input name="sku" defaultValue={q.sku??''}/></label><label className={s.field}>카테고리<input name="category" defaultValue={q.category??''}/></label><label className={s.field}>상품 상태<select name="status" defaultValue={q.status??''}><option value="">전체</option>{Object.entries(salesLabels).map(([k,l])=><option value={k} key={k}>{l}</option>)}<option value="archived">보관</option></select></label></div><div className={s.actions}><button className="button">검색·필터 적용</button><Link className="button subtle" href="/products">필터 해제</Link></div></form>
 <p className={s.small}>조회 가능한 상품·컨텍스트 {d.total}건 · 상품명순 · {d.mode==='sqlite'?'영속 저장':'Mock · 재시작 시 초기화'}</p>{d.items.length?<ProductGrid items={d.items}/>:<section className={p.empty}><h2>{[q.q,q.country,q.retailer,q.brand,q.sku,q.category,q.status].some(Boolean)?'조건에 맞는 상품이 없습니다':'아직 등록된 상품이 없습니다'}</h2><p>{d.contexts.length?'필터를 바꾸거나 허용된 컨텍스트에 상품을 등록하세요.':'접근할 수 있는 컨텍스트가 없습니다.'}</p></section>}
 <nav className={s.actions} aria-label="상품 페이지">{d.page>1&&<Link className="button subtle" href={href(d.page-1)}>이전 페이지</Link>}<span>{d.page}페이지</span>{d.page*d.pageSize<d.total&&<Link className="button subtle" href={href(d.page+1)}>다음 페이지</Link>}</nav><PendingEvidence contextId={q.context}/></div>;
}
