/* eslint-disable @next/next/no-img-element -- Private file endpoints need the browser authentication cookie. */
import Link from "next/link";
import type { ProductCommon,ProductContextFields,RetailPriceFields,InternalPriceFields } from "@/domain/products/types";
import type { ProductDetail,ProductList } from "@/server/products/service";
import s from "@/features/tasks/ui.module.css";
import p from "./ui.module.css";
export const salesLabels={unknown:"판매 상태 미확인",planned:"출시 예정",selling:"판매 중",stopped:"판매 중단"};
export const registrationLabels={unknown:"등록 미확인",unregistered:"미등록",in_progress:"등록 진행",registered:"등록됨"};
export const purposeLabels={image:"상품 이미지",ingredients:"성분",packaging:"포장",document:"자료·증빙"};
export function Pairs({items}:{items:[string,unknown][]}) {return <dl className={p.pairs}>{items.map(([k,v],i)=><div key={`${k}-${i}`} style={{display:"contents"}}><dt>{k}</dt><dd>{v===null||v===undefined||v===""?"미확인":typeof v==="boolean"?v?"예":"아니요":String(v)}</dd></div>)}</dl>;}
export function CommonView({value:v}:{value:ProductCommon}){return <Pairs items={[["상품명",v.name],["제품 코드",v.code],["코드 유형",v.temporaryCode?"임시":"정식"],["현지 표기",v.localNames.map(n=>`${n.language}: ${n.name}`).join("\n")],["카테고리",v.category],["용량",[v.capacity.amount,v.capacity.unit].filter(Boolean).join(" ")],["용량 원문",v.capacity.raw],["색상",v.variants.color],["향",v.variants.scent],["기타 변형",v.variants.other],["설명",v.description],["사용법",v.usage],["원산지",v.originCountry],["제조사",v.manufacturer],["제조 정보",v.manufacturingDetails],["전성분",v.ingredients.text],["성분 언어",v.ingredients.language],["성분 제출일",v.ingredients.submittedAt],["성분·제품 분류",v.ingredients.classification],["용기",v.packaging.container],["패키지",v.packaging.packaging],["라벨",v.packaging.label],["박스",v.packaging.box],["ITF",v.packaging.itf]]}/>;}
export function ContextView({value:v}:{value:ProductContextFields}) {return <Pairs items={[["현지명",v.localName],["SKU",v.sku],["JAN",v.jan],["등록 상태",registrationLabels[v.registrationStatus]],["판매 상태",salesLabels[v.salesStatus]],["출시일",v.launchDate.value],["정밀도",v.launchDate.precision==='date'?'날짜':'일시'],["확정 수준",{unknown:'미확인',expected:'예정',confirmed:'확정'}[v.launchDate.certainty]],["시간대",v.launchDate.timezone],["출처",v.launchDate.source],["원문",v.launchDate.raw],["입점 프로젝트",v.projectId]]}/>;}
export function PriceView({value:v}:{value:RetailPriceFields|InternalPriceFields}){return <Pairs items={['amount'in v?["소비자가",v.amount]:["공급가",v.supplyAmount],...( 'supplyRate'in v?[["공급률",v.supplyRate],["공급률 단위",v.rateUnit],["공급률 기준",v.rateBasis]] as [string,unknown][]:[]),["통화",v.currency],["세금 포함",{unknown:'미확인',yes:'포함',no:'별도'}[v.taxIncluded]],["적용 시작",v.effectiveFrom],["적용 종료",v.effectiveTo],["출처",v.source]]}/>;}
export type ProductFile=ProductDetail['reusableFiles'][number];
export function FileLinks({file:f}:{file:ProductFile}){return <div className={s.actions}><a className={s.link} href={f.downloadUrl}>다운로드 · {f.name}</a><a className={s.link} href={f.originalUrl} target="_blank" rel="noreferrer">원본 ↗</a>{f.preview&&f.previewUrl&&<a className={s.link} href={f.previewUrl} target="_blank" rel="noreferrer">미리보기 ↗</a>}<span className={s.hint}>{f.mime} · {f.bytes.toLocaleString()} bytes · {f.visibility==='internal'?'GSG 내부':'공개 자료'}</span></div>;}
export function BindingView({binding:b}:{binding:ProductDetail['files'][number]}){return <article className={p.version}><h3>{b.title||b.file.name} · {purposeLabels[b.purpose]}</h3><Pairs items={[["문서 유형",b.documentType],["발행자",b.issuer],["발행일",b.issuedAt],["서명일",b.signedAt],["명시 유효 시작",b.statedValidFrom],["명시 유효 종료",b.statedValidTo],["유효기간 원문",b.validityRaw],["적용 상품 ID",b.productIds.join(", ")],["언어",b.language],["매체",b.media],["사용처",b.usePlace],["출처",b.source],["파일 버전",b.fileVersionId],["SHA256",b.file.sha256]]}/><FileLinks file={b.file}/></article>;}
export function ProductGrid({items}:{items:ProductList['items']}) {return <div className={p.cards}>{items.map(i=><article className={p.card} key={i.contextProductId}><div className={p.image}>{i.image?<img src={i.image.originalUrl} alt={`${i.common.name} 상품 이미지`}/>:<span>이 컨텍스트에 등록된 이미지 없음</span>}</div><div className={p.body}><span className={s.small}>{i.context.data.brand} · {i.context.data.country} / {i.context.data.retailer}</span><h2><Link href={`/products/${i.productId}?context=${i.context.id}`}>{i.common.name} ↗</Link></h2><p>{i.local.localName||i.common.localNames.map(n=>n.name).join(" · ")}</p><p>{i.common.code}{i.common.temporaryCode?" · 임시 코드":""} · SKU {i.local.sku||"미확인"}</p><p>{[i.common.capacity.amount,i.common.capacity.unit,i.common.capacity.raw].filter(Boolean).join(" ")} · {[i.common.variants.color,i.common.variants.scent,i.common.variants.other].filter(Boolean).join(" / ")||"변형 미확인"}</p><p>{i.common.category||"카테고리 미확인"}</p><div className={p.chips}><span className="badge">{i.archived?"보관":salesLabels[i.local.salesStatus]}</span><span className="badge">{registrationLabels[i.local.registrationStatus]}</span></div><p>{i.retailPrice?`${i.retailPrice.fields.amount??'금액 미확인'} ${i.retailPrice.fields.currency??''} · 최근 기록 소비자가`:'소비자가 미등록'}</p><p className={s.hint}>자료 집계 연결 예정 · 관련 업무 {i.relatedTaskCount}개</p></div></article>)}</div>;}
export function PendingEvidence(){return <section id="evidence" className={p.pending}><h2>증빙표·Excel</h2><p>자료별 적용·확인 상태와 요청·부족·미확인 자료 집계는 증빙 기능 연결 후 제공됩니다.</p><p>Excel 가져오기·내보내기는 G07 연결 예정입니다. 자료가 있다는 사실은 인증 승인이나 유효성 확인을 뜻하지 않습니다.</p></section>;}
